### ISSUE TITLE
New term request: Pyriform aperture stenosis

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#1002]
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3056623/

Superclass: abnormality of the nose? abnormality of the nasolabial region? hyperplasia of the maxilla?

**Comment by pnrobinson** [comment]
Def: narrowing of the anterior nasal aperture (piriform or pyriform aperture), which is a pear-shaped opening in the skull that is bounded above by the inferior borders of the nasal bones; laterally by the margins which separate the anterior from the nasal surfaces of the maxilla; and below by the same borders, where they curve medialward to join each other at the anterior nasal spine.

Add this as comment: Congenital nasal pyriform aperture stenosis (CNPAS) is a rare cause of nasal airway obstruction that clinically mimics choanal atresia, but needs to be differentiated from the latter because of the widely divergent modes of management [PMID:21423901].
