### ISSUE TITLE
Revise glomerulopathy(HP:0100820) hierarchy

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10030]
**HPO term**
glomerulopathy (HP:0100820), lobular glomerulopathy (HP_0008636), Glomerular sclerosis (HP_0000096), Glomerulonephritis (HP_0000099)

**Suggested revision and reasons**
Glomerulopathy should be parent term to all the other terms based on its definition of "Inflammatory or noninflammatory diseases affecting the glomeruli of the nephron."

Note: Lobular glomerulopathy does not have a text definition. Either suggest "Inflammatory or noninflammatory diseases affecting the glomeruli of the nephron with lobular deposits within the mesangial space" (PMID: 26064516) 
or possibly obsoleting as it is rarely used older term.

Suggested hierarchy here:
![Screenshot 2023-08-31 at 2 31 38 PM](https://github.com/obophenotype/human-phenotype-ontology/assets/26067008/ed720c82-197a-426c-a977-509bed2fe301)

This stemmed from a discussion aligning HP-MP @sbello

**Comment by LCCarmody** [comment]
Happy to make changes if you are okay with it.

**Comment by pnrobinson** [comment]
Lobular glomerulopathy is probably not a good term. It is used for one % entry in the HPO database. There are only 5 entries in all of PubMed that use the term, and none of them provide a precise definition, instead there was a biopsy that was said to look like a lobe.
The term "Glomerulopathy" itself is also not really a great HPO term because it is refering to a class of diseases with problems with the glomerulus, and is hard to distinguish from "Abnormal renal glomerulus morphology". 

We are planning to work with the nephrology group here to improve the representation of renal biopsies. I think for now the best thing is to obsolete the term "Lobular glomerulopathy" and leave the rest as is. If the MP team would like to join the HPO workshop for kidney terms let me know. I am hoping we will be able to hold it this year or 2025.
