### ISSUE TITLE
Composite term mixing sparse and thin eyebrows

### ISSUE THREAD

**Issue by FDNA1** [obophenotype/human-phenotype-ontology#1004]
Please separate the terms of spares and thin eyebrows. They should be two separate terms HP:0000535

**Comment by drseb** [comment]
Created two new classes:

HP_0045075 sparse eyebrows
HP_0045074 thin eyebrows

the composite class HP_0000535 is subclass of these two

**Comment by drseb** [comment]
HP_0000535 also got a new label

**Comment by FDNA1** [comment]
Thank you!

**Comment by pnrobinson** [comment]
Hi,
I think that the problem was that one of the synonym names was bundled. We do not want to have bundled terms like this: "Sparse and thin eyebrow". I am not sure I followed this exactly, but if this term was just created I would suggest obsoleting it. It the term has been around for a while, we need to reannotate the diseases with "sparse eyebrow" and "thin eyebrow" and then obsolete this term.

**Comment by drseb** [comment]
Please make a separate ticket for the obsoletion. The bundled term has the old ID and you we can then use

- HP_0045075 sparse eyebrows
- HP_0045074 thin eyebrows

for the annotations
