### ISSUE TITLE
Would like to add Anxiety term as Child of Negative Affectivity

### ISSUE THREAD

**Issue by akyocum** [obophenotype/human-phenotype-ontology#10164]
**HPO term**
Anxiety HP:0000739
**Suggested revision and reasons**
Child of Negative Affectivity HP:0031467

**Comment by pnrobinson** [comment]
I am not an expert, but it does not seem true that Anxiety is always a child of Negative affectivity
?

**Comment by pnrobinson** [comment]
Currently, Anxiety is a child of [Maladaptive fear-related cognitions](https://hpo.jax.org/app/browse/term/HP:5200230), which seems to be uncontroversial. According to Wikipedia, [Negative affectivity](https://en.wikipedia.org/wiki/Negative_affectivity) subsumes a variety of negative emotions, including anger, contempt, disgust, guilt, fear, and nervousness. This does not seem to be as good a match, or at least it is confusing.
@bcoleman96 
I would suggest let's leave the term where it is for now, this is too complicated to discuss by email/GitHub; we can revisit the entire hierarchy at a zoom or on-site meeting next year.

**Comment by bcoleman96** [comment]
I agree with Peter. We always want to move terms under broader terms whenever we can, but I think because of the exceptions, it's better to avoid it in this case.

@akyocum , If you think it is important to have a term related to anxiety under NA, we could create a new term like Tendency toward anxiety.
