### ISSUE TITLE
hydrophobia should not be listed under Maladaptive fear-related cognitions

### ISSUE THREAD

**Issue by akyocum** [obophenotype/human-phenotype-ontology#10174]
**HPO term**

HP:0032505

**Suggested revision and reasons**

Not really a phobia

**Comment by bcoleman96** [comment]
I think this term should be moved to be a child of Dysphagia or potentially Neuromuscular dysphagia. I'm unsure about the latter because there is no definition.

If we think fear of water is an important phenotype to include we could create a term for "Aquaphobia" which more literally means to be afraid of water.

**Comment by pnrobinson** [comment]
[Hydrophobia HP:0032505](https://hpo.jax.org/app/browse/term/HP:0032505) is defined as "Pharyngeal spasms that are provoked by an attempt to drink." Therefore it is not a phobia. I will place it under Dysphagia.

**Comment by pnrobinson** [comment]
I moved the term to Dysphagia and update the definition:

The word hydrophobia has been used to describe the avoidance of drinking in the presence of hydrophobic spasms that can be observed in human rabies (described as a blockage in the throat with worsening of dyspnea). However, rarely, the same word has been used to describe panic reactions observed in a patient when offered a glass of water. This term does not refer to the latter meaning.
