### ISSUE TITLE
Abnormality of the seventh cranial nerve (HP:0010827) 

### ISSUE THREAD

**Issue by sbello** [obophenotype/human-phenotype-ontology#10199]
**HPO term**
Abnormality of the seventh cranial nerve (HP:0010827) 

**Suggested revision and reasons**
Abnormality of the seventh cranial nerve (HP:0010827) the definition of this term does not imply morphology or physiology but the parent is morphology. The only child of this term is Facial palsy (HP:0010628) which is defined as a functional defect. The Facial palsy term also falls under the physiology branch (child of Cranial nerve paralysis HP:0006824).

I suggest that Facial palsy be removed as a child of Abnormality of the seventh cranial nerve to get this out of the morphology branch.

Consider also obsoleting the term Abnormality of the seventh cranial nerve (HP:0010827)  and replacing it with a term defined specifically for morphology.

**Comment by LCCarmody** [comment]
Looking at the Abnormal cranial nerve morphology branch, there are a few terms that are physiology and could be moved.

My suggestion is making new grouping terms under 'Abnormal cranial nerve physiology' and move the existing physiology terms there. Then clarifying or making new terms for morphology.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/carmol/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/carmol/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Status | Branch | parent | child |  
-- | -- | -- | -- | --
  | 'Abnormal cranial nerve physiology' |  
*new* |   | Abnormal seventh cranial nerve   physiology'
*moved* |   |   | 'Facial palsy'
*new* |   | Abnormal vestibulocochlear nerve   physiology
*moved* |   |   | 'Vestibular nystagmus'
*new* |   | Abnormal cranial nerve physiology   due to cranial nerve compression
*moved* |   |   | 'Facial paralysis'
  |   |   |   |  
  | 'Abnormal cranial nerve morphology' |  
  |   | 'Abnormal fifth cranial nerve   morphology'
  |   | 'Abnormal glossopharyngeal nerve   morphology'
  |   | 'Abnormal sixth cranial nerve   morphology'
  |   | 'Abnormality of inferior alveolar   nerve'
*new* |   | Abnormal eleventh cranial nerve   morphology'
*new* |   | Abnormal seventh cranial nerve   morphology'
*new* |   | Abnormal vestibulocochlear nerve   morphology'
  |   |   | 'Vestibular schwannoma'
  |   | 'Cranial nerve compression'
? |   |   | 'Optic atrophy from cranial nerve   compression'
  |   |   | 'Optic nerve compression'
  |   | 'Cranial nerve motor loss' |  



</body>

</html>
@pnrobinson  What do you think? If okay, I will add.

**Comment by pnrobinson** [comment]
@LCCarmody thanks!
Let's touch bases by zoom about moving forward. I am testing a new JavaFX app for working on the HPO that so far is much more efficient than Protege.
For now I have moved this term to abnormal physiology. I am not sure we have a use case for abnormal morphology of 7th CN yet, so let's wait until there is a need!
