### ISSUE TITLE
HP:0100814 Blue nevus definition and syn.

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#10299]
**HPO term**
HP:0100814 Blue nevus
**Suggested revision of textual definition**
No definition is provided, perhaps the NCI definition would be appropriate?
See http://purl.obolibrary.org/obo/NCIT_C3803

Also the synonym of "Mongolian spot" is a little confusing and potentially led to UMLS mapping this with Blue nevus HP:0100814; I have asked them to remap the blue nevus record to a different concept. I don't know if it would be reasonable to make a comment about Mongolian spot instead of leaving it as a synonym?

**Comment by kanems** [comment]
FYI this change should resolve the confusion for this pair of terms from #9626

**Comment by pnrobinson** [comment]
The terminology for these lesions is used inconsistenly in the literature. I think that Mongolian spot is actually not a synonsm of Blue nevus, but instead of Nevus of Ota:
https://dermnetnz.org/topics/blue-naevi-pathology
I am updating the synonyms.

I add this definition:
A solitary, bluish, smooth surfaced macule, papule or plaque tha is generally round or oval in shape. The histopathology of blue nevi varies by subtype, but general characteristics include a vertical wedge or bulbous shaped proliferation of spindle cells, dendritic melanocytes, and melanophages into a sclerotic dermis or subcutis.
PMID: [31747181](https://pubmed.ncbi.nlm.nih.gov/31747181)

**Comment by kanems** [comment]
Thanks for the clarification in HPO, I'll follow up with UMLS on this pair to try and get this captured in the next UMLS release.
Note I think there is a typo in the definition provided in your comment:
>A solitary, bluish, smooth surfaced macule, papule or plaque tha_t_ is generally round or oval in shape....
