### ISSUE TITLE
HP:5200137 - Reduced attempt to get or direct attention of peers

### ISSUE THREAD

**Issue by bcoleman96** [obophenotype/human-phenotype-ontology#10292]
**HPO term**
HP:5200137 - Reduced attempt to get or direct attention of peers

**Suggested revision and reasons**
Change parent from "Reduced social reciprocity with peers" (HP:5200136) to be "Reduced attempt to get or direct another's attention" (HP:5200027)

**Comment by pnrobinson** [comment]
@bcoleman96 
"Reduced attempt to get or direct attention of peers" is not an ideal label. "Reduced attempt" is not quite correct grammatically and would need to be "Reduced attempting" to indicate that we are talking about a tendency.
Also "get or direct" attention is redundant, since "get" implies "direct"
What about

"Infrequent attempting to engage others"
"Infrequent attempting to engage peers"

or something like that?

**Comment by pnrobinson** [comment]
@bcoleman96 
I made the following revision, please reopn if this still needs work

label:Infrequent social engagement with peers
id: HP:5200137
def: Social engagement refers to the interaction of an individual with others in a contextually appropriate manner. This term refers to a lower than typical number of attempts to engage peers in conversation, play, or other interactions.
