### ISSUE TITLE
rename HP:0009821 'Forearm undergrowth' and its subclasses

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10317]
The tree for `Forearm undergrowth` currently looks like this:
<img width="228" alt="Screenshot 2024-02-21 at 10 35 23 am" src="https://github.com/obophenotype/human-phenotype-ontology/assets/4812335/3dc39ae3-62a7-435f-ae8b-3052b2b6875c">
`short forearm` is a subclass of `forearm undergrowth` but also a synonym for `forearm undergrowth`.
`short forearm` seems to specifically refer to shortening of both radius and ulna, so would rename this term to `hypoplasia of both radius and ulna`. Would then rename `forearm undergrowth` to `short forearm` and make `forearm undergrowth` a synonym of `short forearm`.

Andreas Zankl, ORCID-ID 0000-0001-8612-1062
Lisanne Wit, ORCID-ID 0009-0007-1020-5412 (@lisannesw)

**Comment by pnrobinson** [comment]
This is not quite correct, because then if we annotate a patient to Hypoplasia of the radius the patient would be inferred to have all ancestor terms including hypoplasia of both radius and ulna; however, it is possible to have Hypoplasia of the radius without having Hypoplasia of the ulna. Maybe a better term label is "Forearm bone hypoplasia", def: Hypoplasia of radius and/or ulna etc etc.?

**Comment by pnrobinson** [comment]
Reviewing this today, and I think the hierarchy is accurate.  I am adding hypoplasia of both radius and ulna as a synonym to short forearm
