### ISSUE TITLE
Move HP_0008498 No permanent dentition

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#10428]
**HPO term**
HP_0008498 No permanent dentition is currently a child of HP_0000696 Delayed eruption of permanent teeth

Suggest to move to child of  HP_0006352 Failure of eruption of permanent teeth
![Screenshot 2024-03-29 at 11 47 58 AM](https://github.com/obophenotype/human-phenotype-ontology/assets/26067008/807b0eae-23da-48d3-ab2c-53e1857e077b)

**Suggested revision and reasons**
No permanent dentition is not delayed, but an absent phenotype.

**Comment by pnrobinson** [comment]
Failure of eruption of permanent teeth means the teeth are there but do not come out. 

 or not always, it is probably a synonym of
[Agenesis of permanent teeth HP:0006349](https://hpo.jax.org/app/browse/term/HP:0006349)

We use the term to annotate a legacy disease https://omim.org/entry/216300 that we should delete (omit list) because there is only one paper from 1971.

**Comment by LCCarmody** [comment]
Sorry, I missed that branch. Then, yes, probably merge these two.

**Comment by pnrobinson** [comment]
merged!
