### ISSUE TITLE
Neutrophilic dermatosis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1059]
Please consider new term for Neutrophilic dermatosis

**Comment by pnrobinson** [comment]
This is a disease. See for instance (http://www.dermnetnz.org/cme/emergencies/neutrophilic-dermatoses/),

 Dermatoses with dense dermal infiltrates of neutrophils include:

    Acute febrile neutrophilic dermatosis
    Pyoderma gangrenosum (PG)
    Overlap disorders

Neutrophilic dermatoses are probably mediated through helper T cell type 1 cytokines (IL-2, INF-γ) rather than helper T cell type 2 cytokines (IL-4). This results in the stimulation of a cytokine cascade, which might be responsible for the local and systemic activation of neutrophils and histiocytes. 

However, I think that the HPO could use terms like dermal and epidermal neutrophilic    
infiltrate:

Neutrophilic dermatosis= A    spectrum    of    diseases    based    on    histopathologic    finding    of    neutrophilic    infiltrate    without    evidence    of    infectious    agent,    historically    without    vasculitis. May    be    classified    as    epidermal(    superficial)    and    dermal    (neutrophilic    dermatoses    en    plaques,    deep)        with    and    without    vasculitis

**Comment by pnrobinson** [comment]
Adding terms for Neutrophilic infiltration of the skin as well as epidermal/dermal predominance.

**Comment by pnrobinson** [comment]
See HP_0031234
