### ISSUE TITLE
remove 'bone knee' synonym from Fractured knee HP:0041064

### ISSUE THREAD

**Issue by azankl** [obophenotype/human-phenotype-ontology#10684]
**HPO term**
Fractured knee HP:0041064

**Bug description**
has the synonym 'bone knee', not sure how that got in... ;-)
that synonym should be deleted

**Comment by azankl** [comment]
in fact, the whole term 'Fractured knee' is weird, the knee is a joint, not a bone, you normally dont fracture the knee, but the femur or tibia/fibula. There are also no diseases associated with that term, so maybe delete the whole term?

**Comment by pnrobinson** [comment]
@cmungall @matentzn @azankl at one point we autogenerated fracture terms, but this wound up leading to many errors.
I also do not really know what "fractured knee" means? Is this a think? I know what Fractured kneecap means, but wouldn't we also speak of the component bones rather than "fractured knee"?

**Comment by matentzn** [comment]
sounds right @pnrobinson - i dont think i have anything to add! i guess we should find a better name that expresses "fracture of any part of the knee"?

**Comment by azankl** [comment]
@pnrobinson You can fracture your tibia or fibula or femur, but not really your knee, I would just remove that term

**Comment by pnrobinson** [comment]
term obsoleted. Thanks @azankl
