### ISSUE TITLE
Add definition for Myelopathy

### ISSUE THREAD

**Issue by evanc1648** [obophenotype/human-phenotype-ontology#10734]
**HPO term**
HP:0002196

**Suggested revision of textual definition**
Disorder of the spinal canal causing the compression of the spinal cord.

**Comment by pnrobinson** [comment]
adding definition as

Myelopathy is an descriptive term, referring to pathology leading to a neurologic deficit related to the spinal cord. The clinical diagnosis of myelopathy requires a detailed history and physical examination to define the clinical syndrome. Neuroimaging is indicated in most instances of new-onset myelopathy. It is indicated also when the worsening of a myelopathy is unexplained.
PMID:27430455

Comment: This is a descriptive term that should not be used for new annotations. If possible, choose a more precise HPO term that describes the actual observed abnormality.The most frequent etiology of myelopathy is related to degenerative disease of the spine. This can be due to compression of the spinal cord by an osteophyte or extruded disc material in the cervical spine or, less often, in the thoracic spine. Subsequent to degenerative etiology, the next common etiologies are spinal cord compression due to extradural masses caused by metastatic disease to bone or blunt trauma. There are also primary neoplastic, infectious, inflammatory, neurodegenerative, vascular, nutritional, and idiopathic disorders that lead to myelopathy.

**Comment by pnrobinson** [comment]
added
