### ISSUE TITLE
Fix classes to exclude assay

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#1078]
e.g. Remove "by MRS" from class labels

**Comment by pnrobinson** [comment]
I do not think this can be done automatically, because there are some cases where the sign is related to the technology, e.g., molar tooth sign is just MRI. It would however be useful to flag up class labels with methods in their name and either remove them or document the reason for the names in the Wiki.

**Comment by drseb** [comment]
Yes agreed. I didn't intend to do this automatically. This was rather intended as a reminder-ticket.

**Comment by pnrobinson** [comment]
I am closing this, but I will add an item to the WIki about assays.
