### ISSUE TITLE
Update to Exposure to inhaled lipids

### ISSUE THREAD

**Issue by DnlRKorn** [obophenotype/human-phenotype-ontology#10789]
**HPO term**
Exposure to inhaled lipids/HP:6000005

**Suggested revision of textual definition**
"History of aspiration or inhalation of lipid-containing products."

This term is under the "Exposure History/HP:4000110" label.

It may also be helpful to put some kind of "related to other term" link from this to "Electronic cigarette exposure history/HP:0430032" since the text presents the phenomena as being connected.

**Comment by pnrobinson** [comment]
Thanks. I have updated the comment of History of aspiration or inhalation of lipid-containing products to read: 


Exogenous lipoid pneumonia is caused by aspiration or inhalation of lipid-containing products. In the past, the most common agents included mineral oil-based laxatives and nasal decongestants. Other causes include inhalation of petroleum jelly used as a lubricant, e.g., tracheostomy care. The incidence of exogenous lipoid pneumonia is growing exponentially in all age groups secondary to the phenomenon termed vaping. In the latter case, consider the term Electronic cigarette exposure histor (HP:0430032).
