### ISSUE TITLE
Thyroid dysgenesis

### ISSUE THREAD

**Issue by evanc1648** [obophenotype/human-phenotype-ontology#10889]
**HPO term**
HP:0008188

**Suggested revision of textual definition**
Abnormal development of the thyroid gland.

**Comment by pnrobinson** [comment]
@evanc1648 
Please have a look at https://hpo.jax.org/resources/contributing for suggestions about NTRs.
In this case, I would suggest the following definition:

def: Thyroid dysgenesis is a descriptive term that should be avoided if more precise information is available. However, the HPO keeps retains this term because it is commonly used in the medical literature. In humans, the process of thyroid morphogenesis occurs from the 3rd to 16th week of gestation. Alterations occurring during this period may result in a thyroid gland that is absent (thyroid agenesis or athyreosis), hypoplastic (thyroid hypoplasia), or located in an unusual position (thyroid ectopy). All these entities are grouped under the term thyroid dysgenesis. 
PMID:23698639

**Comment by evanc1648** [comment]
@pnrobinson
I will read through that page and learn how I can best contribute. Thank you for the information.

**Comment by pnrobinson** [comment]
thanks, added!
