### ISSUE TITLE
Gonadal dysgenesis

### ISSUE THREAD

**Issue by evanc1648** [obophenotype/human-phenotype-ontology#10884]
**HPO term**
HP:0000133

**Suggested revision of textual definition**
Abnormal development of the gonads.

**Comment by pnrobinson** [comment]
@evanc1648 This is something of a legacy term that is often used in the literature but it is very imprecise and should be avoided for new annotations. I am adding this definition:

Gonadal dysgenesis is the name given to any of a multitude of conditions that can cause impaired development of the gonads, i.e., the testes or ovaries, or to the related phenotypic features. The term is to be avoided if possible for new annotations, and more specific terms should be chosen.
PMID: [30969708](https://pubmed.ncbi.nlm.nih.gov/30969708)

Comment: Gonadal dysgenesis is a genetic condition due to errors in cell division and or alterations in genetic material, leading to complete or partial loss of gonadal development. The development of gonadal dysgenesis begins early either at fertilization or shortly after in the early stages of the embryo and fetus.
