### ISSUE TITLE
irrepressible vomiting 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1097]
Please consider new term for irrepressible vomiting

**Comment by pnrobinson** [comment]
Vomiting is not generally repressible, so adding the word irrepressible does not really describe a new phenotype. If you are looking to describe simply severe vomiting, then you could consider using the HPO modifier "severe". I have found some references to irrepressible vomiting of pregnancy that are from very old publications. If you are referring to this then possibly the correct term is "episodic vomiting" Please reopen this request if you disagree!

**Comment by LOURGHI** [comment]
This feature has been described in Ravine syndrome (PMID 22411793)when reading this article we could understand that vomitting is stubborn and persistent .

**Comment by pnrobinson** [comment]
I see what you mean. I have found this article which mentions some classifications, let's have a look at that. There are some other terms such as cyclic vomiting that we may also want to add to the HPO.

**Comment by pnrobinson** [comment]
Cyclic vomiting is defined as recurrent episodes of vomiting separated by symptom-free intervals or baseline health, so I think the current HPO term "Episodic vomiting" will suffice for that.

**Comment by pnrobinson** [comment]
I am seeing that the term "irrepressible vomiting" is used in several rather old articles to describe pregancy associated vomiting that is particularly severe. I think that probably it is best to just use the HPO term vomiting, and if you want to emphasize the severity, to add the modifier Severe. It is difficult to define exactly what is meant by "Irrepressible vomiting", because vomiting is not generally repressible. If anything, there should be a term volutary vomiting, but that is bulimia.
