### ISSUE TITLE
acute brainstem dysfunction

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1098]
please consider new term for acute brainstem dysfunction

**Comment by pnrobinson** [comment]
This is not a good HPO term because it is a physiological inference. Instead, it is better to annotate to the actual phenotypic observations, which can include coma or abnormalities of vital signs. There is no direct test that I know of that measures brainstem function directly, and an HPO term should be something that is directly observable (or that has a minimum of inference about pathophysiology).
