### ISSUE TITLE
Cutaneous bleeding.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1120]
Please consider a new term for Cutaneous bleeding.

**Comment by pnrobinson** [comment]
Could you define this more exactly? There is currently a term, "Excessive bleeding from superficial cuts" -- is that what you are thinking of? There is also a term petechiae, which is the result of bleeding into the skin -- please consider if this is a synonym.

**Comment by LOURGHI** [comment]
this feature is a criterion of  exculsion  of Congenital panfollicular nevus,it's  a multinodular  lesion which does not bleed.

**Comment by pnrobinson** [comment]
It is not a good idea to try and code every possible combination of features as an HPO term. If so we could basically create two children for each current HPO term X as "X that bleeds" and "X that does not bleed" etc. HPO terms should be describing the "atomic" (i.e., single and specific) abnormalities and can be combined as needed. Dermatology is admittedly a challenging discipline because a lot of the descriptions of lesions are actually pictures rather than English language definitions. In any case, "cutaneous bleeding" in the sense that a particular lesion does not have the term is not something that can be expressed using the current HPO structure. I am going to close this item, but we could reopen with a more detailed description of the skin lesion itself if that would be helpful.
