### ISSUE TITLE
areas of hyperpigmented, slightly atrophic, unilateral lesions following Blaschko lines on the trunk or limbs

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1124]
Please consider a new term for areas of hyperpigmented, slightly atrophic, unilateral lesions following Blaschko lines on the trunk or limbs.

**Comment by pnrobinson** [comment]
This is a so-called bundled term, since it contains multiple different phenotypes
1. hyperpigmentation on trunk
2. atrophy on trunk
3. hyperpigmentation on limbs
4. atrophy on limbs
following Blashko lines in some areas. 
I am adding an entry to the HPO WIki on "bundled terms" and how to avoid them -- please consult this. We would need to break down this description into individual terms to annotate the disease or patient being referred to.
