### ISSUE TITLE
dyshidrotic eczema

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1129]
Please consider a new term for dyshidrotic eczema.

**Comment by pnrobinson** [comment]
eczema is a disease rather than a phenotypic feature (the HPO does have a term for eczema, which is inconsistent, and probably will be removed as we improve the dermatology part of HPO). 
Dyshidrotic eczema, or dyshidrosis, is a skin condition in which blisters develop on the soles of your feet and/or the palms of your hands.
=> Could I suggest using terms for blistering etc to describe the individual phenotypic abnormalities of the patient you want to annotate?

**Comment by LOURGHI** [comment]
I think it's possible but we must clarify it on phenomizer guide because I think doctors have tendencies to introduce  clinical signs and not their descriptions.
