### ISSUE TITLE
grape-like globular structures on microscopy and radioimmunoassay

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1132]
Please consider a new term for grape-like globular structures grape-like globular structures on microscopy and radioimmunoassay .

This feature was found in patient with elastoderma.

**Comment by pnrobinson** [comment]
This description is too specific to be a good HPO term, however there are some features seen in elastoderma that I am adding now. I have used tables in https://www.ncbi.nlm.nih.gov/pubmed/25072684 to determine what features seem to be common to all or most patients. I have described each individual feature, because there may be other diseases that do not display all three of the following together.

1) Increased number of elastic fibers in the dermis (HP_0025164)
2) Clumping of elastic fibers in the dermis (HP_0025165)
3) Thickened elastic fibers inthe dermis (HP_0025166)
4) Fragmented elastic fibers in the dermis (HP_0025167)

I this that the "grape-like" term is probably best annotated with "Clumping..."
