### ISSUE TITLE
increased elastin synthesis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1134]
Please consider a new term for increased elastin synthesis.

**Comment by pnrobinson** [comment]
This is not a reliable term, since it is impossible to measure the synthesis of elastin in tissue directly. I suspect that this was a pathophysiologucal inference based on the presence of an increased amount of elastin fibers in elastoderma. The HPO should not be used to code pathophysiology, though, because that would be complicated and unreliable. Please use the term "Increased number of elastic fibers in the dermis" (HP_0025164).
