### ISSUE TITLE
irregular elastic tissue fibres

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1137]
Please consider a new term for irregular elastic tissue fibres.

**Comment by pnrobinson** [comment]
Hi! I am not sure that "irregular" is the best word for a term, since elastin fibers can have different appearances depending on the degree of stretch and prep of a histology sample anyway. I have added a term for "Abnormal cutaneous elastic fiber morphology" which I think is what you mean. I will add some child terms below that as per other requests. Please open a new request if you want to have a more specific term for irregularuty, but then please provide a definition and a PMID etc.
