### ISSUE TITLE
fibrinopurulent exudate

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1140]
Please consider a new term for fibrinopurulent exudate.

**Comment by pnrobinson** [comment]
Could you rpvode more conext? Fibrinopurulent means simply containing fibrin and pus, but exudate can occur at multiple locations in the body?

**Comment by LOURGHI** [comment]
The histology of these polyps reveals a “cap” of inflammatory granulation tissue with fibrinopurulent exudate that covers the polyps,PMID: 23416507.

**Comment by pnrobinson** [comment]
The issue is that if there is an HPO term called "fibrinopurulent exudate", then it will notbe possible for the computer to "know" that we are talking about a component of "Inflammatory cap polyposis", which is a disease characterized by the presence of multiple "Inflammatory cap polyps". I think it makes sense to add a term for "Inflammatory cap polyp".
