### ISSUE TITLE
upper aerodigestive  neoplasms

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1150]
Please consider a new term for upper aerodigestive  neoplasms.

**Comment by pnrobinson** [comment]
This is not a great HPO term because it is so mixed.
Cancers of the upper aerodigestive tract constitute approximately 4% of all malignancies. These include cancer of the lip, tongue, major salivary glands, gums and adjacent oral cavity tissues, floor of the mouth, tonsils, oropharynx, nasopharynx, hypopharynx and other oral regions, nasal cavity, accessory sinuses, middle ear, and larynx
I have also not been able to find an NCI thesaurus term corresponding to this concept. It is almost always better to annotate to a specific term, which in this case would be one of the cancers in the list above. Could you please reopen this request or create a new one with specific items?

**Comment by LOURGHI** [comment]
It's not specified in article please take a look at this entity:Bazex syndrome PMID: 24346922.
