### ISSUE TITLE
macular pucker -- new term

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#1152]

**Comment by psergouniotis** [comment]
Although it is still used clinically, my opinion would be not to include "macular pucker" as a term (I note that it is presently a synonym of HP:0100014 ("Epiretinal membrane"). There is a classification system on this type of conditions ( https://www.ncbi.nlm.nih.gov/pubmed/24053995 ).

I think "Vitreomacular adhesion", "Vitreomacular traction" should be added instead, possibly as subclasses of HP:0030498 ("Macular thickening")

**Comment by pnrobinson** [comment]
Would not Vitreomacular adhesion (defined in the article as a perifoveal vitreous detachment) be a subclass of "Posterior vitreous detachment" (Separation of the vitreous humor from the retina.)?
thanks

**Comment by psergouniotis** [comment]
'Posterior vitreous detachment' is different from 'Vitreomacular adhesion' and they should be two distinct terms. Notably, vitreomacular adhesion and vitreomacular traction are two of the many entities along the spectrum during the course of an incomplete posterior vitreous detachment (http://eyewiki.aao.org/Vitreomacular_Traction_Syndrome).

Posterior vitreous detachment (PVD) is defined as the separation of the posterior hyaloid face from the neurosensory retina (http://webeye.ophth.uiowa.edu/eyeforum/cases/196-pvd.htm).
 
'Vitreomacular adhesion'  & 'Vitreomacular traction' definitions can be found here https://www.ncbi.nlm.nih.gov/pubmed/24053995.

**Comment by pnrobinson** [comment]
It has been hypothesized that macular pucker results when vitreoschisis splits
the cortex anterior to hyalocytes leaving this cellular
membrane attached to the macula.

**Comment by psergouniotis** [comment]
As discussed above please consider adding the following terms:
* Vitreomacular adhesion
* Vitreomacular traction
* Full-thickness macular hole

1A. Preferred term label: Vitreomacular adhesion
2A. Synonyms: VMA
3A. Textual definition: Vitreomacular adhesion is defined as perifoveal vitreous separation with remaining vitreomacular attachment and unperturbed foveal morphologic features. It is an OCT finding that is almost always the result of normal vitreous aging, which may lead to pathologic conditions (PMID: 24053995)
4A. Suggested parent term: Macular thickening (HP:0030498)

1B. Preferred term label: Vitreomacular traction
2B. Synonyms: VMT
3B. Textual definition: Vitreomacular traction is characterized by anomalous posterior vitreous detachment accompanied by anatomic distortion of the fovea, which may include pseudocysts, macular schisis, cystoid macular edema, and subretinal fluid. Vitreomacular traction can be subclassified by the diameter of vitreous attachment to the macular surface as measured by OCT, with attachment of 1500 μm or less defined as focal and attachment of more than 1500 μm as broad (PMID: 24053995)
4B. Suggested parent term: Macular thickening (HP:0030498).

1C. Preferred term label: Full-thickness macular hole
2B. Synonyms: FTMH
3B. Textual definition: Full-thickness macular hole (FTMH) is defined as a foveal lesion with interruption of all retinal layers from the internal limiting membrane to the retinal pigment epithelium. Full-thickness macular hole is primary if caused by vitreous traction or secondary if directly the result of pathologic characteristics other than vitreomacular traction. Full-thickness macular hole is subclassified by size of the hole as determined by OCT and the presence or absence of vitreomacular traction (PMID: 24053995)
4B. Suggested parent term: Macular hole (HP:0011508).

**Comment by pnrobinson** [comment]
Closing this because it was dealt with in #2404
