### ISSUE TITLE
severe facial bone

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1156]
Please consider a new term for severe facial bone (Sagliker syndrome,PMID:24413727).

**Comment by drseb** [comment]
The article mentions 

>  **severe facial bone** and dental **deformities** 

So I guess you mean **severe facial bone deformities**. Severe is a modifier that we try to avoid to add to term labels. Given this wouldn't [Abnormality of facial skeleton](http://compbio.charite.de/hpoweb/showterm?id=HP:0011821) be sufficient?

BTW: What tool do you use to search for existing HPO terms?

**Comment by pnrobinson** [comment]
Looking at the description of Sagliker syndrome, it is characterized by hyperplasia of hte maxilla, frontal bossing, abnormality of the mandibula, and oral soft tissue hyperplasia (The HPO has gingival overgrowth, but I am adding this phrase as a synonym).The clinical descriptions on the papers are not really very good for the most part. 
Please use these terms rather than a general description of severe facial bone abnormality.
