### ISSUE TITLE
perinuclear inclusion bodies

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1159]
please consider a new term for perinuclear inclusion bodies.
(Infantile digital fibromatosis PMID: 27684985)

**Comment by pnrobinson** [comment]
In the article, it is the neoplastic cells that have inclusion bodies. I think it is best to annotate to a particular type of neoplasm and to define that neoplasm with these characteristics. In the HPO, there would be a term "Perinuclear inclusion bodies of XYZ" if otherwise normal cells in organ XYZ had these inclusion bodies.
