### ISSUE TITLE
fibrosis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1163]
Please consider a new term for fibrosis.
(Infantile digital fibromatosis PMID: 27684985).

**Comment by pnrobinson** [comment]
The HPO has a bunchof terms like "Renal fibrosis"; I do not think a term for Fibrosis alone is as good, since fibrosis is always localised or specified in some way. In many articles, the referent is left out. For instance, I think you are referring to this

Infantile digital fibromatosis is a benign asymptomatic nodular proliferation of fibrous tissue occurring almost exclusively on the dorsal and lateral aspects of the fingers or the toes,

http://emedicine.medscape.com/article/1057528-overview

?

**Comment by pnrobinson** [comment]
I think that this is a description of the tumor entity and should not be a separate HPO term.
