### ISSUE TITLE
Positif muscle-specific actin (MSA) 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1171]
Please consider a new term for Positif muscle-specific actin (MSA).
(Infantile digital fibromatosis PMID: 27684985).

**Comment by pnrobinson** [comment]
This in itself is not a good HPO term, because there are many normal tissues that stain positive for muscle-specific actin. I guess you are looking to describe Infantile Digital Fibroma. It might be best to submit a term request for that particular tumor and to describe the histology in the definition?
