### ISSUE TITLE
adjacent basal cell liquefaction

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1178]
Pleaes consider a new term for adjacent basal cell liquefaction
(Lichen planus pemphigoides,PMID : 23331194)

**Comment by pnrobinson** [comment]
This is not a good HPO term because it is too specific to this paper-- it refers to being "adjacent to some other finding". Please remember that the HPO intends to be used to annotate diseases in general, and any termthat is made should be valid also for future diseases. Please see the wiki for examples of how term requests should be constructued https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request
It is also not always possible to annotate everything in some paper of interest. Another good rule is that any finding should be mentioned in multiple articles -- that means it is something characteristic of the disease.
