### ISSUE TITLE
fetal distress

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1190]
Please consider a new term for fetal distress
(11q22.2q22.3 microdeletion syndrome,PMID : 25735893)

**Comment by pnrobinson** [comment]
I think that the HPO needs work in the area of intrapartum phenotypes. I am worried about using the term fetal distress even as a grouping term because it is so poorly defined. I wonder if the descriptions for this syndrome have any more specific abnormalities instead of fetal distress? 

Here is a typical statement about the phrase "fetal distress":

Fetal distress in itself is a non-specific term as the various
parameters to determine the type and degree of distress are
themselves  ill  defined.  The  simplistic  concept  that  fetal
dysfunction in labor can be considered as a single condition
and labelled as fetal distress is no longer tenable. The various
indicators  such  as  an  abnormal  intrapartum  FHR  pattern,
meconium staining of the amniotic fluid, and low apgar scores
should be evaluated in terms of their individual significance
not expecting that an abnormality in one will necessarily be
reflected  as  an  abnormality  in  the  other.

**Comment by pnrobinson** [comment]
After some thought I have added this term with def
An intrauterine state characterized by suboptimal values in the fetal heart rate, oxygenation of fetal blood, or other parameters indicative of compromise of the fetus. Signs of fetal distress include repetitive variable decelerations, fetal tachycardia or bradycardia, late decelerations, or low biophysical profile.
and comment
Fetal distress in itself is a non-specific term as the various parameters characterizing the type and degree of distress are themselves ill defined. Nonethless the term is in broad clinical use and thus is included as an HPO term. It is preferable to annotate with more precise terms if possible.

In the future we need to extend this part of the ontology.
