### ISSUE TITLE
deposition of lipofuscin-like substance in the retinal pigmented epithelium 

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1214]
Please consider a new term for deposition of lipofuscin-like substance in the retinal pigmented epithelium: diagnostic criteria in the Stargardt disease(PMID:27739528).superclasse:Abnormality of retinal pigmentation??

**Comment by pnrobinson** [comment]
According to the following comment, we should reconsider this (unless we are describing a histological abnormality, which would be very unusual)

(Comment by Dr. Panagiotis Sergouniotis) This is a tricky one. My feeling is that "Lipofuscin deposition in the retinal pigmented epithelium" would not be a great term as it suggests histological analysis of the abnormality. I do lots of HPO phenotyping for Stargardt disease (ABCA4-retinopathy) and the terms that I usually go for are:
* Retinal flecks [HP:0012045] or Macular flecks [HP:0011507]
* the superclasses of the above: Yellow/white lesions of the retina [HP:0030506] or  Yellow/white lesions of the macula [HP:0030500] 
* Hyperautofluorescent macular lesions [HP:0030631]: this refers to findings on fundus autofluorescence imaging which suggests lesions with increased lipofuscin content. Not everything that autofluoresces is lipofuscin though.

On a different note, perhaps "Hyperautofluorescent retinal lesions" and "Hypoautofluorescent retinal lesions" should be added as subclasses of HP:0030602

I think that the clinician should ideally record what he sees in the fundus or retinal imaging rather than what he presumes might be happening histologically (increased lipofuscin). I think it would be good if HPO reflects that but if you have different thoughts we could work on identifying further terms.
