### ISSUE TITLE
neonatal cholestasis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1225]
Please consider a new term for neonatal cholestasis.
PMID: 25647543,Isolated sedoheptulokinase deficiency.
Superclass:Cholestasis??

**Comment by pnrobinson** [comment]
Since this is only a single patient report, I would be cautious about adding this annotation, as many neonates have some degree of Neonatal hyperbilirubinemia (HP_0003265), which can result from multiple causes include cholestasis. In any case, the actual observation in this case was almost certainly  "Neonatal hyperbilirubinemia" and this could be used to annotate the patient.
Otherwise, one could use the HPO term "Cholestasis" and add the modifer Neonatal onset.
