### ISSUE TITLE
prominent columella

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1248]
Please consider a new term for prominent columella.
PMID:25195018.
Superclass:Abnormality of the columella.

**Comment by pnrobinson** [comment]
I think this is "Low hanging columella" (Columella extending inferior to the level of the nasal base, when viewed from the side.) (HP_0009765)  in Figure 1A,B of this manuscript. Potentially it is also "Wide columella, but the pictures are not entirely clear. I think that it is best to add prominent columella as a RELATED_SYNONYM to low hanging columella, because the adjective "prominent" is not very specific, and "low-hanging" is usually what would be promient.
