### ISSUE TITLE
multifocal choroidal lesions

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1315]
Please consider a new term for multifocal choroidal lesions.
Exclusion criteria for the diagnosis of Birdshot chorioretinopathy  were the presence of keratic precipitates and posterior synechiae and the presence of infectious, neoplastic, or other inflammatory diseases that can cause multifocal choroidal lesions .
PMID:26530345.
Superclass:Abnormality of the choroid??

**Comment by pnrobinson** [comment]
I do not think that the classification of choroidal lesions into multifocal and unifocal is commonly used in ophthalmology. Therefore, since this is an exclusion rather than a phenotypic feature that was observed and described in this way, I do not think we need to create an HPO term for it. I am closing this request now, but please reopen if you disagree.
