### ISSUE TITLE
diabetic proliferative retinopathy

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1325]
Please consider a new term for diabetic proliferative retinopathy.
In this study(The development and management of neovascular glaucoma),neovascular glaucoma followed diabetic proliferative retinopathy in 20% of cases.
neovascular glaucoma,PMID:1697175.

Superclass:Abnormality of the retinal vasculature???
                Retinopathy??

**Comment by pnrobinson** [comment]
I think that diabetic proliferative retinopathy is not a good HPO term, because it is a bundled phenotype. The neovascularization is the cause of the glaucoma and not a phenotypic feature resukting from it (in PMID 1697175). 
THere is an HPO term that can be used,  Retinal neovascularization, HP_0030666 -- this is the observed phenotype of the fundus (in addition to potentially retinal bleeding and scars).
