### ISSUE TITLE
synechial angle-closure glaucoma

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1342]
_**Please consider a new term for synechial angle-closure glaucoma.
  Invasion  of  the  anterior  chamber by a fibrovascular membrane ,in neovascular glaucoma ,initially obstructs aqueous outflow in an open-angle fashion and later contracts to  produce secondary  synechial  angle-closure  glaucoma  with  high  intraoccular pression .
PMID:27895936.
Superclass:Glaucoma??**_

**Comment by pnrobinson** [comment]
I think that this should be represented as
1) Synechiae of anterior chamber and
2) Angle-closue glaucoma.
Looking at the current HPO term, I see that it has the label "Primary closed angle glaucoma" -- this is a mistkae, because the HPO terms should not encode etiology. I also see the children terms of anterior chamber synechiae do not have definitions, and I think the "posterior" synechiae should be not in the anterior chamber. I am going to check the annotated diseases, write better definitions, and probably rearrange the structure slightly.

**Comment by psergouniotis** [comment]
I agree that "primary open angle glaucoma" and "primary closed angle glaucoma" should be replaced by "open angle glaucoma" (syn open-angle glaucoma) and "closed angle glaucoma" (syn closed-angle glaucoma). I also note that the textual definition for HP:0012108 is incorrect.

**Comment by pnrobinson** [comment]
Made changes to labels and definitions.
