### ISSUE TITLE
occular ischemic syndrome

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1343]
_**Please consider a new term for occular ischemic syndrome.
Which can be the cause of neovascular glaucoma (I'm discussing with my binome about annotating or not with syndromes that orientate to the disease) but I think it is an interesting syndrome and I will ask for its creation at Orphanet.
PMID:27895936
Superclass:Abnormal eye physiology??**_

**Comment by pnrobinson** [comment]
Ocular ischemic syndrome is a disease entity.
See http://eyewiki.aao.org/Ocular_Ischemic_Syndrome
EyeWiki claims it is rare, and thus it seems a good candidate to be in Orphanet. 
Since it is a disease, it is not a good HPO term.

**Comment by LOURGHI** [comment]
_**I will take into consideration the request,but I do not understand the existence of some diseases like the crohn desease???**_

**Comment by pnrobinson** [comment]
The HPO is not entirely consistent on this issue, and some of the HPO terms like Crohn disease have been included because they are used very often in typical data sources like OMIM. Geneticists who are deadline with genetic diseases that themselves are associated with secondary Crohn disease tend to phenotype their patients with "Crohn disease", rather than with the individual components. In the future, we need to try to improve on this, and thus hopefully at some point we can replace these HPO terms. For now, we would prefer not to create new terms like this unless it is really necessary for lots of annotations and diseases. So I think here it would be good to create an Orpha entry for the disease and then use HPO terms to annotate it....

**Comment by LOURGHI** [comment]
This is also the case for the annular pancreas..
