### ISSUE TITLE
Smooth muscle dysfunction

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1348]
_**Please consider a new term for Smooth muscle dysfunction .
Clinical manifestations of Paroxysmal nocturnal hemoglobinuria  include thromboembolic disease, chronic kidney injury, pulmonary hypertension, smooth muscle dysfunction, and chronic hemolysis.
PMID:27536121.
Superclass:Muscular abnormality??**_

**Comment by pnrobinson** [comment]
The phrase smooth muscle dysfunction is an inferrence about the pathophysiology and not an abserved phenotype. I think they are referring to dysphagia, which can be a dysfunction of the smooth muscle portion of the esophagus. I do not think that we should have a special term for "Smooth muscle dysfunction", though, because we do not want to encode assumptions about pathophysiology in a phenotype ontology.
