### ISSUE TITLE
INHERITANCE MODES

### ISSUE THREAD

**Issue by shaytzur** [obophenotype/human-phenotype-ontology#1353]
Hello,
I would like to suggest the following terms for more accurate definition of inheritance modes:

- Autosomal dominant, de-novo
- Autosomal dominant inheritance, partial penetrance
- Autosomal dominant inheritance, with imprinting
- X-linked recessive
- X-linked dominant
- Digenic
- Y-linked

Thank you,
Shay Tzur

**Comment by pnrobinson** [comment]
There are terms for autosomal dominant with maternal/paternal imprinting. As far as I am aware, there is no  disease in which these two are mixed.  The X and Y linked terms are already present under "gonosomal inheritance". Digenic inheritance is HP_0010984. 
 I think that the actual inheritance mode for a de novo mutation is simply "autosomal dominant" because once the mutation is there, it can be transmitted in a dominant fashion. I realise that it is useful to have the "de novo" category when filtering exome data etc., but this is not an inheritance mode. There is a term There is now a term HP_0001444, autosomal dominant somatic cell mutation that is close to AD, de novo, and I will explore what this has been used to annotate. We may need to revise this.

**Comment by shaytzur** [comment]
Thank you, most of the terms  are indeed already  there  (sorry , I missed the sub-classes).

Regarding de-novo, because of the different nature of the effects, it could be great if revising the AD  term will be considered:
1. "regular" autosomal dominant for partial penetrance gene-diseases , mainly in adults with a-symptomatic cases, and expected allele frequency in a control populations (_BRCA1/2, TTN , DSP_ etc.).
2. de-novo autosomal dominant for private alleles and severe pediatric gene-diseases (usually autosomal __CMT1A_ _, but there are de-novo also on X, _NONO_).

Regards, Shay

**Comment by pnrobinson** [comment]
I have added the term "Autosomal dominant germline de novo mutation" with the proposed definition
"Being related to a mutation that gamete that participates in fertilization. All cells of the emerging organism will be affected and the variant canl be passed on to the next generation.". There are a number of other terms under Autosomal dominant that should cover the other cases. If this does not cover what you are after,please reopenthis request or start a new one. thanks Peter
