### ISSUE TITLE
Pseudoptosis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1359]
_**Please consider a new term for Pseudoptosis.
Vernal keratoconjunctivitis presents with highly specific symptoms, such as photophobia ,tearing    and pseudoptosis.
PMID: 26278858.
Superclass:Ptosis??**_

**Comment by pnrobinson** [comment]
I have been looking around, and pseudoptosis is not really a good term. I haveseen it used with several differential meanings. The keratoconjunctivitis causes swelling of the lids, the lids cannot open fully, i.e., there is blepharophimosis. Ihavealso seen it used in the situation that there is proptosis of one eye and the other eye then seems to have ptosis (because relatively, the lid is lower than with the proptotic eye).
I would suggest it is better than you see if the term Blepharophimosis applies to keratoconjunctivitis.
