### ISSUE TITLE
brain hypoxia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1363]
_**Please consider a new term for brain hypoxia.
Observed in EAST syndrome,PMID:27500072.
The sign is not a diagnostic criterion but I think that it's an interesting term for other pathologies notably in intensive care units .
I try to keep this logic in demand for new terms (to have the maximum of interesting new terms)and I invite you to refine it if you see the necessity .
Superclass:Abnormality of nervous system physiology??**_

**Comment by pnrobinson** [comment]
Brain hypoxia is rarely observed as a phenotype directly. Instead, it is an inference about the pathophysiology of a disease.
In PMID:27500072, the authors write:
This is likely to be the result of brain hypoxia from the prolonged seizure and not directly due to the KCNJ10 mutation
The HPO reports observable phenotypes and not pathophysiology, so this is not a good term for the HPO. 
As far as I know, functional imaging of brain hypoxia is an experimental technique (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2949962/), but I do not think there is anything like this in clinical medicine.
