### ISSUE TITLE
hearing loss

### ISSUE THREAD

**Issue by tatsuomatsunaga** [obophenotype/human-phenotype-ontology#1372]
In the subclasses of "sensorineural hearing loss" and "hearing impairment" have common and distinct phenotypes. I recommend both have the same set of phenotypes in the same category.

In  "sensorineural hearing loss", Mid-frequency sensorineural hearing impairment, Unilateral sensorineural hearing impairment, Conductive hearing impairment, Sensorineural hearing impairment, which are all listed in  "hearing impairment" had better be listed.

In addition, I recommend the following phenotypes in  "sensorineural hearing loss". 
Mid and high-frequency sensorineural hearing loss, Mid and low-frequency sensorineural hearing loss, High and low-frequency sensorineural hearing loss, All-frequency sensorineural hearing impairment, Stable sensorineural hearing loss, Fluctuating sensorineural hearing loss, Symmetric sensorineural hearing loss, Asymmetric sensorineural hearing loss, Auditory Neuropathy.

In  "hearing impairment", Adult onset hearing impairment, Childhood onset  hearing impairment, Congenital hearing impairment, Old-aged hearing impairment, Mid and high-frequency hearing impairment, Mid and low-frequency hearing impairment, High and low-frequency hearing impairment, All-frequency hearing impairment, Bilateral hearing impairment, Stable hearing impairment, Fluctuating hearing impairment, Mixed hearing impairment, Symmetric hearing impairment, Asymmetric hearing impairment, Auditory neuropathy had better be listed.

**Comment by pnrobinson** [comment]
Thank you for this -- we will start to enter these terms shortly!

**Comment by pnrobinson** [comment]
Sorry for the long delay in this. We have been waiting because we thought that using modifiers was the best way to address these issues. The difficulty is that if we have too many subclasses then it will make the ontology difficult to use, and there are too many possible combinations to list them all (e.g., childhood onset fluctuating mid and low-frequency hearing impairment....etc). We have recently refactored the annotation format and our annotation software and have added a Clinical modifier section for the HPO. I will shortly ensure that all the necessary terms are there.

**Comment by pnrobinson** [comment]
I have added two new clinical modifiers, Fluctuating, and Stable.
I think that it will be better to hope to schedule a workshop about ear- and hearing related phenotypes, rather than trying to do this via issues. I have not been able to find good resources to find definitions and standards.
