### ISSUE TITLE
renal colic

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1386]
_**Please consider a new term for renal colic.
Observed in congenital megacalycosis.PMID:16293636.
Superclass:Abnormal renal physiology?? **_

**Comment by pnrobinson** [comment]
I think renal colic is better conceptualized as a disease. The actual symptom that is observed is described by the current HPO term "Abdominal colic" (read also the comments). Here is a describption of renal colic from https://www.ncbi.nlm.nih.gov/pubmed/25554119  that shows that it is a disease with an etiology, time course, treatment etc:
RC is triggered by partial or complete ureteral obstruction,
usually due to an impacted lithiasis that raises pressure
significantly. The classic clinical presentation of ureteral
lithiasis is intense, unilateral, sudden colic pain. It is ini-
tially located in the lumbar fossa usually irradiating toward
the inguinal and genital areas to later evolve when the cal-
culus descends in such a way that in the middle ureter it
can simulate appendicitis or diverticulitis, depending on its
location---right or left. As the calculus comes closer to the
bladder, the symptoms of vesical irritation predominate,
such as polakisuria and tenesmus. It is usually accompanied
by digestive symptoms such as nausea, vomiting or consti-
pation due to ileus reflux.

**Comment by LOURGHI** [comment]
_**Medical**_**_ history of this patient included  episodes of left renal colic ,
I think that renal colic is a pain, effectively which can be triggered by different causes:tumor,lithiasis or inflammation.It is a symptom often encountered in medical _**emergencies.**_
