### ISSUE TITLE
caliceal dilatation

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1391]
_**Please consider a new term for caliceal dilatation.
Observed in congenital megacalycosis.PMID: 16293636 .
Superclass:Abnormality of the renal collecting system??**_

**Comment by pnrobinson** [comment]
Currently, there is a term called megacalycosis (HP_0100581) that is used to annotate the Orphanet Entry for congenital megacalycosis. I believe that the term megacalycosis is more commonly used to describe the disease entity (e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4621186/) rather than the phenotypic finding. Therefore, I am changing the prefered label of this term to Dilatation of renal calices with Caliceal dilatation as a synonym and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4621186/ and megacalicosis as a related synonym
