### ISSUE TITLE
Retinal dystrophy [HP:0000556] subclasses

### ISSUE THREAD

**Issue by psergouniotis** [obophenotype/human-phenotype-ontology#1400]
Would it be possible to add:
* HP:0030637 (cone dysfunction, synonym cone dysfunction syndrome) and 
* HP:0007642 (congenital stationary night-blindness)
as subclasses of Retinal dystrophy [HP:0000556]?
The current connections should be maintained. 

Many thanks for considering this.

**Comment by psergouniotis** [comment]
I would be grateful if you would consider making the above amendment. Please let me know if you would like any additional information.

**Comment by pnrobinson** [comment]
Sorry for the late response. I am adding HP:0007642 as a subclass of Retinal dystrophy [HP:0000556].
We are in the process of separating out morphological and functional abnormalities and as a part of the cone dysfunction is classified as a functional abnormality so that it is not in the same hierarchy as retinal dystrophy. I am closing the issue for now but it would be great to get your insight on these topics.

**Comment by psergouniotis** [comment]
Many thanks Peter. Separating morphological from functional abnormalities sounds a reasonable step forward and it would be great to discuss this further at the ERN-EYE meeting in October.
