### ISSUE TITLE
acute respiratory failure

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1402]
_**Please consider a new term for acute respiratory failure.
Observed in Mercury Poisoning,PMID:26678598.
Superclass:Respiratory failure**_

**Comment by pnrobinson** [comment]
I think that it would be good to add the modifier "acute" (HP:0011009) to "Respiratory failure"
Respiratory failure should be extended to class I, II, and possibly III, IV (see comments on current term).

**Comment by pnrobinson** [comment]
After reviewing this, I think that the existing terms for hypoxemia and hypercapnia should be used in cases of type I and type II respiratory failure. Types III and IV describe clinical situations (preoperative, shock) rather than phenotypic features. Please use the modifier "acute" for annotations.
