### ISSUE TITLE
NTR/Layperson synonyms related to Allergies/Asthma

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1411]
Reviewing [WebMD discussion board on allergies](https://messageboards.webmd.com/health-conditions/f/allergies) and [asthma](https://messageboards.webmd.com/health-conditions/f/asthma#pi157388622=2)

Would we want terms or synonyms such as:

- [x] itching/progressive itching/itchiness
- [x] Itchy palms/itchy feet
- [x] stopped breathing - maybe syn for respiratory insufficiency?
- [x] swollen throat (maybe too granular?)
- [x] stuffy nose (child of Functional respiratory abnormality?)
- [x] gut rot (not sure what exactly is meant by this, need to research it further)
- [x] breaking out/broke out
- [x] chest tightness/tightness of chest (I've come across this more than once) - this is described in asthma as well (could be related syn for respiratory distress?)
- [x] wheat-sensitive (child of Immunologic hypersensitivity?)
- [x] chronic cough (as child of cough), persistent cough
- [x]  shortness of breath (syn for respiratory distress or episodic respiratory distress?)
- [x]  sore throat (there is recurrent sore throat but not sore throat on its own, maybe that is not a proper phenotype though?)
- [x] swelling of mouth
- [x] swelling of lips
- [x] puffy eyes
- [x] night gasping - related syn for episodic respiratory distress?

**Comment by pnrobinson** [comment]
@nicolevasilevsky 
1. Add itching as LP syn to pruritus
2. Itchy feet -> Pruritus on foot
3. Itchy palms -> We need a term Palmar pruritus, which would be a child of the current term Pruritus on hands
4. stopped breathing->this sounds even more serious that respiratory insufficiency, and I would not add it now because it is not a true synonym
5. Swollen throat I think this is a LP synonym for Pharyngitis (http://www.livestrong.com/article/153098-a-sore-and-swollen-throat/)
6. Stuffy nose: LP synonym for Nasal obstruction (HP_0001742). Also need to add nasal congestion (http://www.entnet.org/content/stuffy-nose)
7. gut rot according to urban dictionary ("Gut Rot. A particularily painful sharp, gastrous pain, caused by a night of heavy alcohol consumption, usually following the morning after consumption occurs.") This would thus be a disease according to our system, not a phenotype!
8. breaking out->this is used to describe getting pimples and thus is a BROAD_SYN for acne, I believe
9. chest tightness ->can we make a NTR for this?
10. wheat sensitive is an etiology, not a phenotype
11. Cough-> Let's make a NTR and extendthe current term
12. shortness of breath -> this is a LP syn for Dyspnea
13. Sore throat -> can we make a NTR 
14. swelling of mouth -> Might be related to tongue edema, but do you have more context?
15. Swelling of lips -> NTR
16 Puffy eyes. This is an LP synonym for Periorbital edema 
17. Night gasping ? Do you have more context?

**Comment by nicolevasilevsky** [comment]
Shortness of breath is currently a related synonym for HP_0002098 Respiratory distress. Should we remove it and make it an exact LP syn for Dyspnea instead?

**Comment by nicolevasilevsky** [comment]
Should sore throat be a syn for Pharyngitis?

Recurrent sore throat is a syn for Recurrent pharyngitis

**Comment by nicolevasilevsky** [comment]
Re: swelling of mouth, I can't find the message where someone wrote that, so let's ignore that one.

**Comment by nicolevasilevsky** [comment]
more context for night gasping: 
https://messageboards.webmd.com/search?q=Night%20gasping&group=4
"Things that point to asthma: - Short of breath - Tight chest - Night gasping - Had eczema and hayfever growing up. - Ventolin relieves symptoms immediately. Things that say it is not asthma: - Preventers not helping - Peak flow never drops and is very..."

I think it's when you wake up in the middle of the night and you are gasping for breath, could be a symptom of sleep apnea, or I think of it like when you wake up from a nightmare or something.

Maybe could be a child of Parasomnia?

**Comment by pnrobinson** [comment]
I am adding night gasping as HP_0031503.
I think we are now finished with the list.
