### ISSUE TITLE
NTR/Layperson synonyms related to Arthritis

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1412]
I'm reviewing the [message board on WebMD](https://messageboards.webmd.com/health-conditions/f/arthritis)

Should we add the following terms/synonyms:

- [x] NT: joint pain
- [ ] syn for cartilage destruction: 'no cartilage'? someone wrote "my doctor discovered I have virtually no cartilage in my entire wrist"
- [x] NT: groin pain
- [ ] shallow hips
- [x] Avascular Necrosis - there is 'Avascular necrosis of the capital femoral epiphysis', could we add this as a parent?
- [ ] trigger finger/trigger thumb - @pnrobinson should we add a new class? This could be similar to HP_0012276 Digital flexor tenosynovitis. [Mayo Clinic](http://www.mayoclinic.org/diseases-conditions/trigger-finger/basics/definition/con-20043819) says it is stenosing tenosynovitis. 
- [ ] add 'swollen tendon' as syn of 'tendonitis'?
- [x] add related syn to knee pain: burning pain under knee cap?
- [x] add related syn to Paresthesia: numbness
- [x]  add related syn to edema: water retention?
- [x] NT: knuckle (syn for finger joint maybe?), add term enlarged knuckle(s)

**Comment by pnrobinson** [comment]
1) Avascular necrosis is the layman synonym for  'Avascular necrosis of the capital femoral epiphysis', so to speak.
2) Pain under knee cap sounds like a synonym of knee pain. "Burning" is a particular type of pain, but perhaps it is better to think about haveing modifiers for pain rather than explicit pain subclasses?
3) Paresthesias is usually translated as tingling, even though the Wikipedia entry says numbness is one of the manifestations of paresthesia. We need to revisit these definitions.
4) Knuckle is a synonym for the metacarpal phalangeal joints I think
5) Water retention is a good layperson syn for edema
6) I am not sure what narrow hips means?
7) Swollen tendon is not quite the same thing as tendonitis -- tendonitis is a bundled term with swelling and pain. We need to revisit this.

**Comment by nicolevasilevsky** [comment]
Just to clarify, Avascular necrosis should be a synonym of ''Avascular necrosis of the capital femoral epiphysis'?

**Comment by nicolevasilevsky** [comment]
There is UBERON_0003695 metacarpophalangeal joint in UBERON - is this synonymous for knuckle? @cmungall @mellybelly (If yes, I will make a new synonym request in the Uberon tracker)

**Comment by pnrobinson** [comment]
@nicolevasilevsky Yes: The metacarpophalangeal joint (MP joint), or knuckle, is where the finger bones meet the hand bones.

**Comment by nicolevasilevsky** [comment]
added new syn

**Comment by nicolevasilevsky** [comment]
open questions are:

1. should we add a new term for groin pain?
2. trigger finger/trigger thumb - @pnrobinson should we add a new class? This could be similar to HP_0012276 Digital flexor tenosynovitis. Mayo Clinic says it is stenosing tenosynovitis.

**Comment by pnrobinson** [comment]
Added term for groin pain.

**Comment by pnrobinson** [comment]
I think that trigger finger and Digital flexor tenosynovitis are near synonyms, see
http://www.msdmanuals.com/professional/musculoskeletal-and-connective-tissue-disorders/hand-disorders/digital-flexor-tendinitis-and-tenosynovitis-trigger-finger
- [ ] Todo find out what the differentia are if any
