### ISSUE TITLE
Snoring

### ISSUE THREAD

**Issue by jasonli1717** [obophenotype/human-phenotype-ontology#1418]
Please consider adding snoring as a phenotype.

**Preferred label**: Snoring
**Synonyms**: snore, snores, snoring symptoms

**Definition**: noisy breathing during sleep. Vibration of respiratory structures resulting in sound due to obstructed air movement during breathing while sleeping.

**References**: UMLS C0037384, NCI thesaurus code C116315
[(https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0037384)]

**Suggested Parent term**: sleep phenotype, breathing dysregulation

**Comment by pnrobinson** [comment]
A term for Snoring already existed (HP:0025267). I have created a hybrid definition from your suggestion
Deep, noisy breathing during sleep accompanied by hoarse or harsh sounds caused by the vibration of respiratory structures (especially the soft palate) resulting in sound due to obstructed air movement during breathing while sleeping.
and added the synonyms. I also agree with 'breathing dysregulation' as a parent class.
