### ISSUE TITLE
create new annotation property for metabolomic-related phenotypes

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#1436]
apologies if duplicate ticket, i know we've discussed.

It would be great to create a flag for phenotypes that meet a certain IC or other specificity score and are associated with metabolic diseases. Then, if some threshold annotation sufficiency wrt these terms is met in a patient profile (e.g. they have two or more), it automatically indicates the need for sending for metabolic profiling. 

@cmungall @drseb @jpgourdine ideas welcome.

**Comment by jpgourdine** [comment]
I think we could use the change of Zscore range of some blood metabolites (example in table S3 in this supplemental in this  article
[PMID- 27225280-supplemental.docx](https://github.com/obophenotype/human-phenotype-ontology/files/887427/PMID-.27225280-supplemental.docx) )

We could integrate in HPO for instance for 3-methylcrotonyl CoA carboxylase 

'Phenotypic abnormality'
	 Abnormality of metabolism
	      'Abnormal homeostasis'
		'Abnormality of blood metabolites   
           		Increased Zscore of β-hydroxyisovalerate  

The issue is how to describe the range of Zscore (in this case, >3 is significant)

Also, we could use some of the UDN data with solved cases where metabolomics profiling was conducted to create molecular phenotypes.

JP

**Comment by pnrobinson** [comment]
I think that if we simply use "Increased β-hydroxyisovalerate" it is better than Increased Zscore of β-hydroxyisovalerate. We can state in the definition that this is usually determined by a Z score method. 
@mellybelly The IC is calculated using the annotations and will depend on the corpus of diseases being considered. It would not be a good idea to add this information to the term definitions, because the IC changes essentially everytime we update the annotation database.

**Comment by jpgourdine** [comment]
Hi all,
I am reopening this ticket as Tom Metz from the UDN metabolomics core asked me to get some metabolites associated with diseases to HPO. He used [polysearch](http://wishart.biology.ualberta.ca/polysearch/) but the metabolites/diseases association are weak (no indication of the increase/decrease of the metabolite, nor the evaluant, etc.)
There are more then 50% of the metabolites studied by the UDN in HPO, I am working on th rest.
I started this spreadsheet [ here](https://docs.google.com/spreadsheets/d/1IDh-8tNtGwBiwcGpElHiOjBruhaARDxTWp30rCfOC_I/edit?usp=sharing) . Let me know if I am missing something @drseb 
Thanks
JP

**Comment by pnrobinson** [comment]
Hi everybody,

it would be great to revisit this. We also need to add new HPO term annotations to diseases. JP, if there is some chance of getting a lot of data here that would be great. There are also some other resources on metabolic diseases we could consult.

-Peter


Peter Robinson

Professor and Donald A. Roux Chair, Genomics and Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________
