### ISSUE TITLE
NTR: Abnormality of cardiovascular system electrophysiology

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#1447]
From:  https://docs.google.com/document/d/10VcYh_qDSf9iPt40gBaOvrwUQTIUoMzxxR1fEtuqSuU/edit

now:
```
    is_a HP:0011025 ! Abnormality of cardiovascular system physiology *** 
     is_a HP:0000822 ! Hypertension
     is_a HP:0001279 ! Syncope
     is_a HP:0001635 ! Congestive heart failure
     is_a HP:0001693 ! Cardiac shunt
     is_a HP:0002615 ! Hypotension
     is_a HP:0003115 ! Abnormal EKG
     is_a HP:0003116 ! Abnormal echocardiogram
     is_a HP:0011028 ! Abnormality of blood circulation
     is_a HP:0011675 ! Arrhythmia
     is_a HP:0030148 ! Heart murmur
     is_a HP:0030149 ! Cardiogenic shock
     is_a HP:0030163 ! Abnormal vascular physiology
```

```
 is_a HP:0011025 ! Abnormality of cardiovascular system physiology
   is_a HP:NEW Abnormality of cardiovascular system electrophysiology; AKA Conduction system abnormalities
     is_a HP:0011675 ! Arrhythmia
        is_a HP:0005150 ! Abnormal atrioventricular conduction *** 
     ....
   is_a HP:NEW Abnormality of cardiovascular system physiology, non-electrical
     is_a HP:0030163 ! Abnormal vascular physiology
     ....

```

**Comment by pnrobinson** [comment]
As so often the MP team has done great work with the analogous portion of the MP, and there are multiple upper level terms. The HP has multiple upper level terms, but I think that we should try to make to overall granularity more consistent. I have added Abnormality of cardiovascular system electrophysiology, and we will work on the remaining non-electrical physiology terms as we go through the suggestions from the workshop. I do not think that there is a good case to be made, however, for having just these two terms at this level, and I do not like the "non-electrical" part of the definition -- it reminds me of NOT OTHERWISE SPECIFIED.

**Comment by pnrobinson** [comment]
I have rearranged the other "physiology" terms in this subhierarchy as far as seemed appropriate for now.
