### ISSUE TITLE
NTR/synonyms for Heart Health

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1456]
I am reviewing the [WebMD message board for heart health](https://messageboards.webmd.com/health-conditions/f/heart-health)

@pnrobinson and/or @drseb, can you review the terms below and check off ones I should add? And please comment on the others (or we can discuss whenever we get a call set up)

**NTR:**
- [ ] pressure in chest / chest pressure (maybe not a proper phenotype)

**New synonyms:**
- [ ] Skipped heartbeat- syn of Arrhythmia?
- [x] SVT as syn for Supraventricular tachycardia (abbreviation)
- [ ] chest discomfort as syn for chest pain?
- [x] add layperson tag to palpitations
- [ ] New synonym 'widowmaker' (and widow maker) for Myocardial infarction
- [x] abbrev MI for Myocardial infarction
- [x] New syn 'heart racing' and 'racing heart' for palpitations
- [ ] new syn 'crushing chest pain' and 'sharp chest pain' for chest pain
- [ ] 'difficulty catching breath' as syn for Breathing dysregulation?
- [ ] Extra heart beat as syn for hear murmur

**Comment by pnrobinson** [comment]
skipped heaqrt beat is one particular kind of arrhythmia.
chest discomfort is not as severe as chest pain
widowmaker is an eloquent phrase but I am not sure MI is the only disease to have this moniker
heart racing is a synonym of tachycardia, I think
crushing/sharp are probably best left as modifers rather than terms?
difficulty catching breath is extremely unspecific -- certainly it is not a good synonym for breathing dysregulation (which encompasses much more than recovery after being out of breath).
extra heart beat -- I think this is a good synonym for extrasystole

**Comment by nicolevasilevsky** [comment]
- Should we add skipped heart beat as a subclass of arrhythmia?
- Should we add chest discomfort as a new term? Perhaps as a child of 'Abnormality of the thorax'?
- I'll look into windowmaker further, I think it may refer to a certain type of heart attack
- Should I add extra heart beat as a synonym of 'Ventricular extrasystoles'?

**Comment by nicolevasilevsky** [comment]
Still reading the message board, additional (potential) synonyms are:

- [ ] missed heartbeat (syn for skipped heart beat (if we decide to add that term) 
- [ ] new term: Enlarged heart
- [ ] fluid retention as synonym for edema

**Comment by pnrobinson** [comment]
Enlarged heart is a LP synonym for Cardiomegaly
Let's think about an HP term for skipped heart beat -- can we make that a separate TR?

**Comment by pnrobinson** [comment]
@nicolevasilevsky  can this item be closed or are there still open questions?

**Comment by nicolevasilevsky** [comment]
we can close!
