### ISSUE TITLE
NTR/Layperson synonyms related to mental health

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#1458]
I am reviewing the [mental health message board on WebMD](https://messageboards.webmd.com/health-conditions/f/mental-health#pi157388622=2), I suggested we consider adding the following synonyms:

- [x] hearing sounds as a synonym for auditory hallucinations
- [x] mental impairment as synonym for cognitive impairment

NTR:
- [ ] germophobia, syn of [Mysophobia](https://en.wikipedia.org/wiki/Mysophobia). Other syns: germ phobia, germaphobia. Child of Abnormal fear/anxiety-related behavior

**Comment by drseb** [comment]
Haha:

> "Germophobia" redirects here. For **Germanophobia** (a fear of Germany), see [Anti-German sentiment](https://en.wikipedia.org/wiki/Anti-German_sentiment).

**Comment by nicolevasilevsky** [comment]
Oh no!

**Comment by pnrobinson** [comment]
I do not think that the term Mysophobia is in usage -- there is only one English language citation in pubmed from 1952, and then there are about ten others in various other languages.  I am also not so sure that we should add the term Germophobia right now, since it is not really used in PubMeb. We will need to revist the entire Behavior ontology, and I would suggest we do the Phobia terms systematically then. I am therefore closing this issue.
