### ISSUE TITLE
new term:Cornea verticillata?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1460]

**Comment by pnrobinson** [comment]
Def: Golden brown or gray deposits with a clockwise, whorl-like distribution in the inferior interpalpebal portion of the cornea.
synonym (exact): Vortex keratopathy
comment: Cornea verticillata may occur due to Fabry disease and as an adverse effect to medications including amiodarone.


synonym: Vortex keratopathy

**Comment by LCCarmody** [comment]
Duplicate of cornea verticillata #2183
