### ISSUE TITLE
new term:Iris flocculi?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1469]

**Comment by pnrobinson** [comment]
Definition:  Multiple cysts along the pupillary margin that appear as spherical or tear-drop-shaped pigmented lesions or wrinkled masses emerging from the pupillary border of the iris. PMID:27843899, 7575269
Parent term: http://compbio.charite.de/hpoweb/showterm?id=HP:0000525
Comment: Iris flocculi cause little, if any, visual impairment in most cases. However, they are occasionally associated with dissecting aortic aneurysm due to a shared mutation in smooth muscle that affects both the iris and the aorta [PMID:27843899].
