### ISSUE TITLE
new term:Soft tissue hyperplasia ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1472]

**Comment by pnrobinson** [comment]
@LOURGHI can you provide us with more detail about which soft tissue is hyper plastic or whether this is a generalized finding?

**Comment by LOURGHI** [comment]
I's noted Bone / soft tissue hyperplasia .
Observed very frenquently in Parkes Weber syndrome.

**Comment by pnrobinson** [comment]
see https://www.ncbi.nlm.nih.gov/pubmed/24038909

**Comment by pnrobinson** [comment]
This description is hard to place and I am left wondering if it wouldn’t be better to describe this lesion either as an arteriovenous malformation or as a dermal manifestation. I have not been able to find a definition of the lesion that would allow me to place it in the hierarchy. The problem is that there are lots of different kinds of soft tissue, if we defined this as an abnormality of soft tissue using the ontology, then it would logically be an abnormality of all of them, but this is not what the phenotype is.
