### ISSUE TITLE
new term:Dense scalp hair?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1571]

**Comment by pnrobinson** [comment]
@LOURGHI  is this a medically abnormal phenotype? Can you provide more details?

**Comment by LOURGHI** [comment]
This sign was observed very frequently in Arthrogryposis - epileptic seizures - migrational brain disorder,Edinburgh malformation syndrome,Facial dysmorphism - macrocephaly - myopia - Dandy-Walker malformation,Gingival fibromatosis-hypertrichosis syndrome,Jung-Wolff-Back-Stahl syndrome and occasionnally in Mullerian derivatives - lymphangiectasia - polydactyly.

**Comment by pnrobinson** [comment]
@LOURGHI  Can we use the term hypertrichosis? Here (https://www.omim.org/entry/129850),there is "forehead hairiness" but since there hasn't been any new article about this syndrome since the 1980s, I would doubt that it really exists. 
Also here https://www.omim.org/entry/235255, the term used is hypertrichosis.
Hypertrichosis (face, body) 

I think that hypertrichosis should be the preferred term. Dense scalp hair is not an abnormal phenotype in my opinion.
