### ISSUE TITLE
new term:frontoparietal porencephalic cyst?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1648]

**Comment by pnrobinson** [comment]
I think that the current HPO term porencephaly should have the preferred label porencephalic cyst, because that is the phenotypic feature, and porencephaly should be a related synonym as it is describing the disease. As so often, there is overlap in language for diseases and closely associated phenotypic features.

**Comment by pnrobinson** [comment]
I have made this change to HP_0002132. I would suggest that you use that term for the annotation. We should try to not to have one term for each possible anatomic location of a cyst, which would mean a combinatorial explosion. If there is evidence that a certain diseases is characterized by a specific location of porencephalic cyst and that we need the term for differential diagnosis,we could reconsider, but this is not the case to my knowledge.
