### ISSUE TITLE
new term:Meningism ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1652]

**Comment by pnrobinson** [comment]
The best term for this would be Nuchal rigidity (HP_0031179), which is defined as
Resistnace of the extensor muscles of the neck to being bent forwards (i.e., impaired neck flexion) as a result of muscle spasm of the extensor muscles of the neck. Nuchal rigidity is not a fixed rigidity. Nuchal rigidity has been used as a bedside test for meningism, although its sensitivity for this purpose has been debated.
I will add Meningism as a related synonym. It is not an exact synonym, because Meningism means the presence of nuchal rigidity in somebody without meningitis (i.e., is includes anotion of etiology and is not a pure phenotype feature).

**Comment by pnrobinson** [comment]
I have added this comment:
Meningism is resistance to neck flexion due to painful spasm of extensor muscles resulting from meningeal irritation. The diagnosis of meningism is made in someone whose symptoms simulate meningitis, but in which no actual inflammation of these membranes is present. Nuchal rigidity can thus be observed in individuals with meningitis or with meningism.

**Comment by LOURGHI** [comment]
but meningism is the **set of symptoms** that can evoke meningitis without inflammation .
