### ISSUE TITLE
new term:Cross gender role behavior?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1690]

**Comment by pnrobinson** [comment]
@LOURGHI can you provide more context? It is important to be very precise with terms like this in order to avoid encoding whatever prejudices we or society may have,and thus I would prefer to be extremely precise and provide definitions and references. If we cannot provide this at the current time,then we should consult with experts before constructing terms in this area.

**Comment by LOURGHI** [comment]
Sorry,I have no context.

**Comment by pnrobinson** [comment]
I think it is better to close this issue, since we should develop terms for this area ideally in a workshop setting with experts in the field.
