### ISSUE TITLE
new term:Arterial pulse abolition?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1713]

**Comment by pnrobinson** [comment]
This term needs more detail. Do we mean reduction of the arterial pulse of a specific artery? Obviously if the arterial pulse is completely abolished then this is not compatible with life. Please provide more details @LOURGHI

**Comment by LOURGHI** [comment]
It was observed ,occasionally in Ebstein malformation.

**Comment by pnrobinson** [comment]
I think that Ebstein individuals can have bradyarrhythmias or heart blocks. I think it is better to annotate with respect to the rhtym anomaly, since to me the phrase "Arterial pulse abolition" sounds like the hjeart completely stops beating causing sudden cardiac death -- in any case, it is not a clear description, and we should not use it for annotations, I think.

**Comment by LOURGHI** [comment]
This sign is widely used in cardiology especially in the ischemia of lower limbs without life-threatening.
It's a shame not to have it on HPO.

**Comment by LOURGHI** [comment]
What I find on the file I have is abolition or diminution of arteriel pulse  on the following diseases:Pseudoxanthoma elasticum,Ehlers-Danlos syndrome, vascular type,Antiphospholipid syndrome,Buerger disease,Takayasu arteritis,Giant cell arteritis,Werner syndrome.

Abnormal arterial physiology could be the super class of the two terms:
Pulse abolished=absence of pulse perception 
Decreased pulse.

**Comment by pnrobinson** [comment]
I am adding a term called Absent ankle pulse, with definition: The pulsation of the posterior tibial artery behind the internal malleolus, or of the dorsalis pedis artery,cannot be detected on physical examination. I think this is what is meant here. HP_0031271
