### ISSUE TITLE
new term:Squaring of scapulae?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1801]

**Comment by pnrobinson** [comment]
@LOURGHI  I cannot find anything on this. Can you provide more information?

**Comment by LOURGHI** [comment]
It was observed in Spondylometaphyseal dysplasia, Sedaghatian type,PMID: 24706940 .

**Comment by pnrobinson** [comment]
Figure 1 of that article shows "Squaring of inferior scapula", meaning a flat (horizontal) inferior edge of the scapula.

**Comment by pnrobinson** [comment]
I do not really like the term "squaring" because the scapula in the radiograph is not square-like, although it may resemble a rectangle. 

I am adding the term as  HP_0031233
name:Horizontal inferior border of scapula
def:A morphological abnor,mality of the scapula in which there is a flat (horizontal) inferior edge of the scapula. The entire scapula is said to resemble a square, leading to the designation sqaring of the scapula (in Figure 1 of PMID:24706940 the scapulae have a roughly rectangular shape).
