### ISSUE TITLE
new term:Double-layered patellae ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1802]

**Comment by pnrobinson** [comment]
@LOURGHI  Is this the same as Bipartite patella, HP_0010498 ?

**Comment by LOURGHI** [comment]
This sign was observed in Multiple epiphyseal dysplasia type 4 , 20301483[PMID]_12525546[PMID].
Could be related synonym???

**Comment by pnrobinson** [comment]
Actually, this is a separate feature.
Here is bipartite patella:


and here 
https://www.ncbi.nlm.nih.gov/pubmed/12966518
is "double layer patella" (See Figure 2A and 3B).

I would define this as
An anomaly of the patella characterized by two layers visible on lateral  knee  X-ray such that one layer is in front of the other in the sagittal orientation (See Figure 2A and 3B of PMID:12966518). This finding persists into adulthood (PMID:12525546).

Comment: This feature can be observed in Multiple epiphyseal dysplasia type 4. It is distinct from bipartite patella, which is characterized by an unfused accessory ossification center at the superolateral aspect of the patella. Double layer patella appears to be caused by the presence of several patellar ossification  centers.

Todo -- add to annotation file PMID     12525546 (Ballhausen), frequency 7/10

**Comment by LOURGHI** [comment]
thank you!
