### ISSUE TITLE
new term:Triangular-shaped tibiae?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1806]

**Comment by pnrobinson** [comment]
See https://www.ncbi.nlm.nih.gov/pubmed/18616733

**Comment by LOURGHI** [comment]
Observed in Mesomelic dysplasia, Savarirayan type,PMID:17702012.

**Comment by pnrobinson** [comment]
I am not sure if there is a need for a separate term or is hypoplastic tibia is correct. I have asked the last author Malte Spielmann (see http://jmg.bmj.com/content/52/7/476.long).

**Comment by pnrobinson** [comment]
This feature is characteristic of Nievergelt syndrome
https://www.ncbi.nlm.nih.gov/pubmed/18616733 (see especially Figure 2)

Label: Triangular tibia
Definition: A short, dysplastic tibia with a triangular shape. Instead of the normal shaft configuration of the tibia, the tibia forms a triangle with the longest side corresponding to the proximal-distal dimension, and the apex of the triangle diected laterally (See Figure 2 of PMID:18616733).
