### ISSUE TITLE
new term:Long bones metaphyseal  osteolysis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1815]

**Comment by pnrobinson** [comment]
@LOURGHI as far as I know, osteolysis in the metaphyseal region is not a characteristic feature that deserves its own HPO term,and thus it might be appropriate to annotate to an existing HPO term for Osteolysis. (Thus, I am wondering if in the patient being referred to, an osteolytic lesion occured because of some disease process such as osteomyelitis, and it just happened to occur in a metaphysis -- and doubting that there is a disease where multiple independent patients get osteolytic lesions that are localized in the metaphysis of long bones).
Thus, please annotate to a general ostelysis term.
If there is a characteristic metaphysis osteolysis term, please reopen and  provide  more information and reference, and please describe which long bones are affected?
