### ISSUE TITLE
new term:axial osteosclerosis ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1831]

**Comment by pnrobinson** [comment]
@LOURGHI  Do you mean this
http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=2527&Disease_Disease_Search_diseaseType=ORPHA&Disease_Disease_Search_diseaseGroup=2777&Disease(s)/group%20of%20diseases=Axial-osteosclerosis&title=Axial-osteosclerosis&search=Disease_Search_Simple
Andthus the osteosclerosis is the axial skeleton and not just the axis bone?

**Comment by LOURGHI** [comment]
in fact,we need this term for annotating Osteomesopyknosis.

**Comment by pnrobinson** [comment]
Then I think that axial sclerosis means osteosclerosis of the spine. We have annotated Osteomesopyknosis with HP_0100861,which is vertebral body osteosclerosis, which is a more precise term. In Orphanet, Axial osteosclerosis is used as a synonym for the disease Osteomesopyknosis (http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=2527&Disease_Disease_Search_diseaseType=ORPHA&Disease_Disease_Search_diseaseGroup=2777&Disease(s)/group%20of%20diseases=Axial-osteosclerosis&title=Axial-osteosclerosis&search=Disease_Search_Simple), so that I think it is best not to use the same words for the phenotype. I would advice annotating to HP_0100861, vertebral body osteosclerosis
