### ISSUE TITLE
new term:Septic shock ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1858]

**Comment by pnrobinson** [comment]
This is a disease (because "septic" is refering to the etiology of the shock). It is thus not in scope for HPO.

**Comment by LOURGHI** [comment]
What about the Cardiogenic shock??I think that the septic shock is rather a complication of the disease than a disease.

**Comment by pnrobinson** [comment]
There is a tension between the boundary between disease and phenotype. The problem with septic shock is that the term can only be used with patients that have sepsis -- and thus it is not describing something that was observed (reduced blood pressure etc etc with sepsis) but is also making an inference that the sepsis is causing the shock. Cardiogenic shock is perhaps better because it is closer to the actual clinical observation.
