### ISSUE TITLE
new term:Lymphomesenteric cysts ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1899]

**Comment by pnrobinson** [comment]
See this:
Mesenteric cysts are uncommon abdominal masses in children. They occur most frequently in the small bowel mesentery and often contain chylous fluid. These cysts may be multilocular, grow to huge proportions and are believed to be caused by obstructed, malformed, ectopic lymphatic tissue.
https://www.ncbi.nlm.nih.gov/pubmed/7997498
I think thus that mesenteric cyst HP_0030451 is the correct term here.
