### ISSUE TITLE
new term:SIADH the sydrome of  inappropriate secretion of antidiuretic hormone?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1966]

**Comment by pnrobinson** [comment]
SIADH is a disease. I am adding the term
ID: HP_0031218
Name: Inappropriate antidiuretic hormone secretion
Def: A state of increased circulating antidiuretic hormone despite hyponatremia and hypo-osmolality with normal or increased plasma volume.
Comment: Common etiologies of inappropriate antidiuretic hormone (ADH) secretion include nervous system disease, cancer, pulmonary disease, and as a side effect of a medication. This term is meant to refer to the inappropriately high level of ADH and not to the full syndrome of inappropriate antidiuretic hormone secretion (SIADH), which is considered a disease entity rather than a phenotypic feature.

I am adding the SIADH as a RELATED synonym.
