### ISSUE TITLE
new term:Visceral xanthomatosis?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#1968]

**Comment by pnrobinson** [comment]
@LOURGHI 
Xanthomatosis: A condition in which fatty deposits occur in various parts of the body.
Currently, the HPO has Xanthomatosis defined as fatty skin deposits.
I am not sure that "Visceral xanthomatosis" is much used anymore since a google search found the last article in 1966. Can you provide some more details? Maybe we should choose another preferred label?

**Comment by LOURGHI** [comment]
Sorry no context for this term.

**Comment by pnrobinson** [comment]
I think we should close this issue then, because the meaning of the phrase Visceral xanthomatosis is unclear. We can reopen the issue if more information becomes available.
