### ISSUE TITLE
new term:Abnormal glycemia after glucagon test?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2035]

**Comment by pnrobinson** [comment]
I am not sure if this is a great term because the glucagon test by design tends to reduce blood sugar and this is not necessarily a general abnormal response but may be better conceptualized as a kind of an adverse event of the test. I do not think that this event is used in the differential diagnosis of diseases. Please reopen with more details if otherwise.
