### ISSUE TITLE
new term:Abnormal plasma c-peptide?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2037]

**Comment by pnrobinson** [comment]
This is Abnormal C-peptide level HP:0030794

**Comment by drseb** [comment]
Why aren't you adding this as synonym then?

**Comment by drseb** [comment]
C-Peptide seem to be measured in blood as well as in urine. Why don't you aim to distinguish here?

https://www.urmc.rochester.edu/encyclopedia/content.aspx?contenttypeid=167&contentid=c_peptide_urine

**Comment by pnrobinson** [comment]
The C-peptide itself is not abnormal, it is only the level that is abnormal. Therefore, the label "Abnormal C-peptide" is not correct (although phrases like this are used as "abbreviations", they do not make sense in an ontology without context).

**Comment by pnrobinson** [comment]
I agree that urine C peptide terms would be good. Need to read up on this.

**Comment by pnrobinson** [comment]
This is a good ref for urine C peptide
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3748788/
It seems that the parameter of choice is urine C-peptide:creatinine ratio

**Comment by pnrobinson** [comment]
I think that it is difficult to make a term for urinary C peptide concentration, because the interpretation of the test result is very much dependent on the clinical situation. It can be used to differentiate between MODY and T2DM (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3024335/), but I do not think that the term would make much sense in isolation. I am closing this issue for now, but we can reconsider at some future workshop with endocrinologists.
