### ISSUE TITLE
new term:Phacomatosis cesioflammea?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2105]
observed in Phakomatosis pigmentovascularis

**Comment by pnrobinson** [comment]
Phacomatosis cesioflammea is a disease entity rather than a phenotypic feature. According to the following, it is defined by two phenotypic features, both of which have HPO terms. Therefore, Phacomatosis cesioflammea should possibly be a term in ORDO and it should be annotated to the two corresponding HPO terms. I am not very familiar with this disease though and it might be good to get input from a dermatologist.

Phacomatosis cesioflammea, earlier called as Phacomatosis pigmentovasularis (PPV) Type II is a rare condition characterized by the coexistence of dermal melanocytosis (Mongolion spot or Nevus of Ota) and nevus flammeus (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3752481/)
