### ISSUE TITLE
new term:Sexual activity ?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2122]
Term that could be classified in a group called triggering factors in clinical modifiers?

**Comment by pnrobinson** [comment]
Would the term triggered by exertion be sufficient or is there a phenotypic feature that is specifically triggered by sexual activity?

**Comment by LOURGHI** [comment]
this sign is observed in Paroxysmal extreme pain disorder with rectal pain as very frequent .

**Comment by pnrobinson** [comment]
I think that it is probably the exertion that is the trigger. HPO terms should not try to capture all of the nuances of a situation. Consider also that a heart attack can be triggered by sexual activity, but presumably it is the exertion that is the causative factor rather than anything specific to the sexual activity.
