### ISSUE TITLE
new term:Musty odor?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2140]

**Comment by LCCarmody** [comment]
There doesn't appear to be a body odor class in HPO?  Should we add this?

@pnrobinson

**Comment by pnrobinson** [comment]
Musty odor can be a manifestation of metabolic diseases like PKU (see https://en.wikipedia.org/wiki/Phenylketonuria). I think that we should create a small hierarchy of body odor classes under consitutional symptom

**Comment by LOURGHI** [comment]
This encourages me to apply for the term fish oder that I encountered in Dimethylglycine dehydrogenase deficiency PMID: 10102904.and I have annotated with Constitutional symptom as a parent of the sign.

**Comment by LCCarmody** [comment]
Suggested hierarchy: 
Parent Class: HP_0025142 Constitutional symptom
New Term: body odor 
def: An unpleasant smell produced after perspiration. Body odor occurs when sweat contacts bacteria that normally reside on the skin.  
Reference: PMID: 26507593

Synonyms: Body odour, BO, bromhidrosis (?-http://emedicine.medscape.com/article/1072342-overview), 

Subclass of Body odor:  Musty odor, Fishy odor, Fish odor

@pnrobinson Does this look okay?

**Comment by pnrobinson** [comment]
@LCCarmody I think the suggested hierarchy is good. The definition applies to "normal" body odor but not necessairy to that caused by metabolic disease. I think that we shoudl go with "A perceived unpleasant smell given off by the body", which I think is applicable to all categories of body odor. (In "normal" body odor, the smell  comes from the action of baceteria on sweat, which is initially nearly odorless; in some metabolic diseases, the distuirbance in metabolism produces a compound which has an unpleasant smell without the action of bacteria on sweat).
