### ISSUE TITLE
new term:visual gaze preference?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2144]

**Comment by LCCarmody** [comment]
@pnrobinson Is this a synonym for  (HP_0000549) Abnormal conjugate eye movement ?

**Comment by pnrobinson** [comment]
@LOURGHI  I think you are referring to a sign after an acute stroke, correct?

Visual gaze preference
Def: An abnormality of gaze that can be observed following an acute supranuclear cerebral lesion (e.g., stroke) that is characterized by an acute inability to  direct gaze contralateral to the side of the lesion and is accompanied by a tendency for tonic deviation of the eyes toward the side of the lesion. 
Comment: With visual gaze preference due to an acute supranuclear cerebral lesion, the oculocephalic reflex (which can be elicited by the so called Doll's head manoeuvre) is intact. The head is briskly turned from side to side with the head held briefly at the end of each turn. If the brainstem and infranuclear pathways are intact, then the eyes rotate to the opposite side to the direction of head rotation. Stroke is the most common etiology of this finding.
Parent term: HP:0000496 Abnormality of eye movement

Note we may later want to revise the hierarchy under HP:0000496 but it is not incorrect now.

**Comment by LOURGHI** [comment]
It was observed in Sturge-Weber syndrome,This is all I have as context.

**Comment by LCCarmody** [comment]
@pnrobinson In Sturge-Weber syndrome the visual gaze preference begins in the first 2 years of life, but the stroke (or stroke-like episodes "Neurological symptoms can continue to worsen gradually with time, or are often caused by a specific stroke-like episode. No consensus exists on what a stroke-like episode is, but these episodes can be functionally defined as a new neurological deficit, occurring with or without the context of seizures, which last longer than 24 hours. "PMCID: PMC4487908) can happen in later childhood or there is adult onset SWS (PMC4487908).

I need to do a little more digging, but should we alter the definition?  Keep looking for a more inclusive definition?

**Comment by pnrobinson** [comment]
@LCCarmody Not sure I understand but we should not include the stroke-like episodes in the definition of visual gaze preference; the HPO does not as a rule attempt to encode the cause of a phenotypic feature, and visual gaze preference can have other causes in other diseases. 
We should though try to figure out if we need a term for "Stroke-like episode"

**Comment by LCCarmody** [comment]
Sorry, I forgot to reply to this.  I only meant that maybe the definition you suggested might be narrow, but I think it could encompass this specific context too.

I did look into 'stroke-like episode' and found this: "Stroke-like episodes (SLEs) are phenotypic features predominantly of mitochondrial disorders (MIDs), most frequently mitochondrial encephalopathy, lactacidosis, SLE (MELAS)-syndrome, and mimic the clinical manifestations of ischemic stroke to some extent [2]. " PMCID: PMC3377871

I think it should be included as a term.

**Comment by pnrobinson** [comment]
I have added a new issue for stroke-like episode, which is a good suggestion.
