### ISSUE TITLE
new term:coloboma of the nostrils?

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2152]

**Comment by pnrobinson** [comment]
The term HP_0003191, Cleft ala nasi, is what is meant. 
In an underdeveloped ala the continuity of the tissue encircling the nostril is undisturbed while in a cleft it is disrupted. The term coloboma has been replaced because a coloboma is a remnant of a physiologically occurring discontinuity of tissue; the alae nasi do not have such a discontinuity.
I would suggest we add "Nostril coloboma" as a RELATED SYNONYM

**Comment by LCCarmody** [comment]
@pnrobinson I could work with Nicole to add this if you would like.

**Comment by pnrobinson** [comment]
@LCCarmody please do so!
