### ISSUE TITLE
Fuchs endothelial dystrophy is missing

### ISSUE THREAD

**Issue by daboe01** [obophenotype/human-phenotype-ontology#2162]
at least you briefly mention it in the comment: on HP:0012038

**Comment by pnrobinson** [comment]
The HPO strives to provide terms to describe the individual phenotypic features of disease. Fuchs endothelial dystrophy is a disease rather than an individual phenotypic observation. I have seen papers talking about corneal phenotypes in which the disease names are used to describe the appearance of the cornea, but in so doing it becomes impossible to describe differences in individual patients with the same disease. Could you please provide a description of the feature to be annotated?

**Comment by daboe01** [comment]
thickening of descemet's membrane together with guttae formation. both features progress and eventually induce corneal edema.
nicely summarized here: https://www.ncbi.nlm.nih.gov/pubmed/26937169

**Comment by daboe01** [comment]
got it. i need to code guttata+stromal edema for Fuchs.
Sorry for the inconvenience.
