### ISSUE TITLE
optokinetic nystagmus.

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2167]
_**Please consider a new term for optokinetic nystagmus.
Observed in Friedreich ataxia.
PMID:8149209.
Superclass:Nystagmus??**_

**Comment by pnrobinson** [comment]
Optokinetic nystagmus is a very normal phenomenon, see
https://en.wikipedia.org/wiki/Optokinetic_response
The article you refer to says: "[patients with FA have ]...relatively preserved optokinetic nystagmus (OKN) and smooth pursuit"
I do not think that it is worth annotating this because it is not a clear statement and this is an old article. I would check this with more recent literature if you want to annotate eye involvement in FA -- I think that patients do have "abnormal" Nystagmus and we should have an annotation to "Nystagmus" for Friedreich.
