### ISSUE TITLE
Mistake in definition of Sea-blue histiocytosis

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2186]
Current definition of HP_0001982 (Sea-blue histiocytosis): _An abnormality of macrophages, also known as histiocytes, in which the cells take on a sea blue appearance due to abnormally increased lipid content_

One of the translators (eheiden) notes:
> Histiocyte and macrophage are not synonyms. Hystiocytes are a type of macrophages. See: Das et. al. Monocyte and macrophage plasticity in tissue repair and regeneration. Am J Pathol. 2015 Oct;185(10):2596-606. doi: 10.1016/j.ajpath.2015.06.001. PMID:26118749

**Comment by pnrobinson** [comment]
Thanks!
New definition:
An abnormality of histiocytes, in which the cells take on a sea blue appearance due to abnormally increased lipid content. Histiocytes are a type of macrophage. Sea-blue histiocytes are typically large macrophages from 20 to 60 micrometers in diameter with a single eccentric nucleus whose cytoplasm if packed with sea-blue or blue-green granules when stained with Wright-Giemsa.
