### ISSUE TITLE
Primary Membranoproliferative Glomerulonephritis

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#2189]
In discussion with Danny Gale, and with reference to closed issues #925 and #1011, there are some concerns over some terms relevant to this disease.

For HP:0012576 “Glomerular C3 deposition” , “C3 Nephropathy” is given as a synonym but is not the same. Can it be a separate sub-class of HP:0000793 Membranoproliferative glomerulonephritis? The textual definition would be: "glomerular C3 deposition without comparable glomerular immunoglobulin deposition". "C3 glomerulopathy” should be the preferred name for the term, with “C3 nephropathy" as a synonym.

For HP:0004746 “Glomerular subendothelial electron-dense deposits”, “Dense deposit disease” is given as a synonym but it is not the same - Glomerular subendothelial electron-dense deposits are seen in a range of kidney diseases (including C3 glomerulonephritis) but, critically, NOT dense deposit disease. Can "Dense Deposit disease" be a separate sub-class of “C3 glomerulopathy”, the Textual definition would be: "dense intramembranous transformation of the basement membrane."

“C3 glomerulopathy” that is not Dense Deposit Disease is “C3 glomerulonephritis” (C3GN): i.e. C3GN is a sub-class of “C3 glomerulopathy”

**Comment by pnrobinson** [comment]
@cmungall  @andrewdevereau sorry to get back so late about this, we have had so many groups interacting with us in 2017/2018 that we are have some backlog. 
Please note that C3 nephropathy is not a phenotypic feature, it is a disease. We list it therefore as a RELATED_SYNONYM because we have seen that it is used like a phenotypic feature in some disease descriptions. 
Please note that to make the entire system of HPO and genomic diagnostics work in an ideal way it is important to be strict about the distinctions between phenotypic features and disease. The community has not always done this, and for instance, one finds items such as "Grave disease" as phenotypic features in the clinical synopsis of OMIM entries (and therefore of some HPO disease models). We are therefore undertaking a substantial extension of our system that will use MONDO disease terms to disambiguate items like this, and we will in the future link to the MONDO term for C3 glomerulopathy (the phenotypic features that are related to glomerulopathy will be put there, and the algorithms will work better in EHR systems etc). 
The issue is the same with “Glomerular subendothelial electron-dense deposits” -- “Dense deposit disease” is given as a RELATED SYNONYM to indicate that it is not the same. 
If you like we can skype about all of this .
