### ISSUE TITLE
NTR: Pseudo-aneurysm

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2271]
From Stanford cardiology workshop

NTR: Pseudo-aneurysm

**Comment by pnrobinson** [comment]
Def: A pseudoaneurysm (PSA) is a contained rupture; there is a disruption in all 3 layers of the arterial wall  PMID:    17515479
Comment: PSAs may occur under 4 circumstances: (1) after catheterization (Figure 2); (2) at the site of native artery and synthetic graft anastomosis (eg, aortofemoral bypass graft); (3) trauma; and (4) infection (eg, mycotic PSA)
Parent term: Abn or artery.

**Comment by nicolevasilevsky** [comment]
We have HP_0001724 Aortic dilatation and a subclass of this term is HP_0004942 Aortic aneurysm. Questions:
1) Should I rename HP_0001724 Aortic dilatation to 'Dilatation of the aorta'?
2) @mellybelly said we should use the term dilatation instead of aneurysm (according to the [notes from the cardiovascular mtg](https://docs.google.com/document/d/10VcYh_qDSf9iPt40gBaOvrwUQTIUoMzxxR1fEtuqSuU/edit)), but these terms would have the same label if I changed aneurysm to dilatation in both classes. I am not sure what the difference is between these two terms, HP_0004942  does not have a text or logical def.

**Comment by nicolevasilevsky** [comment]
Another question:
I did not relabel this term: HP_0007029 Cerebral berry aneurysm. @mellybelly do you agree it should not be relabeled?

**Comment by pnrobinson** [comment]
This is the wrong issue for cerebral berry aneurysm!
see here:
http://www.bafound.org/about-brain-aneurysms/brain-aneurysm-basics/
and here is a definition:
Berry aneurysm: A small aneurysm that looks like a berry and classically occurs at the point at which a cerebral artery departs from the circular artery (the circle of Willis) at the base of the brain. Berry aneurysms frequently rupture and bleed.
Thus, all berry aneurysms are cerebral, and the two terms are synonymous. Not sure which is the better preferred label.

**Comment by nicolevasilevsky** [comment]
Oh yes, I see there is a proper issue for cerebral berry aneurysm here: #2254

**Comment by mellybelly** [comment]
I think that HP_0001724 Aortic dilatation and  HP_0004942 Aortic aneurysm should be merged. @pnrobinson @drseb I'm not sure the process for this in HP right now ;-).

**Comment by nicolevasilevsky** [comment]
@pnrobinson is 'brain aneurysm' a proper synonym of HP_0004944 'Dilatation of the cerebral artery'? @mellybelly and I just reclassified it as a broad synonym.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  Hm, I had never heard the term brain aneurysm used but: http://www.mayoclinic.org/diseases-conditions/brain-aneurysm/basics/definition/con-20028457
I think it is probably best defined as a lay person synonym for cerebral aneurysm.
