### ISSUE TITLE
HP_0000575: visual acuity should not be used in the definition of scotoma

### ISSUE THREAD

**Issue by daboe01** [obophenotype/human-phenotype-ontology#2272]
the definition should rather refer to brightness higher than normal required for the detection of a light stimulus.

**Comment by pnrobinson** [comment]
Sorry for the late reply.I have looked in some of the ophthalmology textbooks we have (all in German) and also online,and it seems that acuity is the key element of most definitions
https://en.wikipedia.org/wiki/Scotoma
Could you provide more context/background?

**Comment by daboe01** [comment]
the definition of visual field defects is based on light intensity thresholds, the unit of mean defect (MD) is decibels.
visual acuity, by contrast,  is defined as spacial resolution.

**Comment by daboe01** [comment]
http://eyewiki.aao.org/Standard_Automated_Perimetry

**Comment by pnrobinson** [comment]
Could you possibly provide a suggested text for the definition? I have looked at lots of sources, mainly for nonophthalmologists, and I am always seeing something like this:
--a partial loss of vision or a blind spot in an otherwise normal visual field.
Perhaps it would be good to leave a definition like that for the primary text, but to explain how perimetry works in a comment?

**Comment by daboe01** [comment]
A pathological increase of the detection threshold for a light stimulus in any region of the visual field
