### ISSUE TITLE
Clean up created_by and DC:creator annotation properties

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#2289]
We are using both of these annotation properties, it would be nice to choose one and have a standardized reference to people using ORCID where possible. These could be fixed via script.

**Comment by drseb** [comment]
I will write a small java program to fix that

**Comment by drseb** [comment]
in HP and MP

**Comment by cmungall** [comment]
Protege now allows new classes to be auto-tagged with user and date

This is the GO setup
http://go-ontology.readthedocs.io/en/latest/Configs.html#configuring-new-entities-metadata

We use the oio vocab to facilitate conversion to the relevant obo tags.

I suggest HPO chooses either oio or dc, normalizes all existing properties (use @drseb's java or a hacky search-and-replace or sparql update...), and adds instructions to the editors guide so everyone's protege will tag in the same way.

It's probably best if the obo community agrees on a standard pair of properties, since many people shift between editing in different ontologies. This would point towards the oio vocab being used here.

**Comment by pnrobinson** [comment]
@drseb @cmungall  -- can we implement this and document the SOP here https://github.com/obophenotype/human-phenotype-ontology/wiki

**Comment by pnrobinson** [comment]
@drseb @cmungall @mellybelly  We have thousands of each option in the file. Which one do we want to keep actually?

**Comment by drseb** [comment]
Oh sorry. I forgot about this issue. I would hope that @cmungall can let us know what is OBO-guideline and what is most commonly used.

**Comment by cmungall** [comment]
I would use oio as this is standard for a lot of ontologies like GO: https://go-ontology.readthedocs.io/en/latest/Configs.html#configuring-new-entities-metadata

**Comment by pnrobinson** [comment]
@drseb bringing this to the top of your inbox.
