### ISSUE TITLE
Define attribution strategy for groups

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#2290]
It would be great if we could attribute groups such as the cardio-hackathon participants using an annotation property. GO does this, perhaps we should follow a similar pattern. We can have group pages on our github that can be referenced as doc. What annotation property should be used?

@cmungall @drseb @pnrobinson

**Comment by drseb** [comment]
we plan to keep the status quo, i.e. include contributors in NAR paper and do our best with nano-attributions

**Comment by pnrobinson** [comment]
@mellybelly @drseb @cmungall I would like to add a contributors page to the new HPO Website in which we will list the names of the people who have contributed to HPO terms.I think it would be good to have a database table in which we link ORCIDs etc, and then whenever we write something like an NAR paper, we can automatically come up with a list of people who we could invite to be coauthors in exchange for their contributions. In my experience though people contribute because they think it is useful and nobody has seemed to care that much about nanoattributions, so I do not think we need to create much more machinery than we have now--the NAR authorships seem to be the bestway of saying thanks.

**Comment by mellybelly** [comment]
@cmungall has a way of autogenerating some of this in the obo tooling I believe
