### ISSUE TITLE
critic

### ISSUE THREAD

**Issue by petkraw** [obophenotype/human-phenotype-ontology#2292]
The main description of HP:0001156 us brachydactyly syndrome. Brachydactyly is a synonyme. I find the description brachydactyly syndrome as a feature very confusing.

**Comment by pnrobinson** [comment]
The word brachydactyly just means "short finger" but one observes patterns of shortness encompassing multiple locations (these are the subclasses). These are of course bundled terms, but because they are used so often the literature we have kept them. Brachydactyly syndrome should never be used to annotate a patient, it is a grouping term. 
Do you perhaps have a better suggestion for the primary label?

**Comment by petkraw** [comment]
http://compbio.charite.de/hpoweb/showterm?id=HP:0001156
maybe just make "brachydactyly" the default and either delete "brachydactyly syndrome" or make it a synonyme?

**Comment by pnrobinson** [comment]
I agree and have made this change.
