### ISSUE TITLE
Fix cleft palate and lip hierarchy

### ISSUE THREAD

**Issue by mellybelly** [obophenotype/human-phenotype-ontology#2297]
For combined clefting of both lip and palate, we should have a superclass grouping term for 'Medial cleft lip and palate' HP_0008501 and 'Bilateral cleft lip and palate' HP_0002744. 

Suggest:
'Cleft lip and palate' with exact synonym 'labio-palatal cleft'

Definition: Clefting of the lip and the hard palate.

However, a few considerations. One can have clefting of the lip with the hard palate or the hard and the soft palate. One could also have unilateral clefting of the palate and the lip. These would also be new terms.

@markengelstad can you make recommendations for which combinations are clinically relevant and also help with adding clinical synonyms.

**Comment by nicolevasilevsky** [comment]
Should we create a superclass for HP_0000204 Cleft upper lip and HP_0010281 Cleft lower lip that is "Cleft lip"?

**Comment by pnrobinson** [comment]
The practical problem with this is that if MDs use the phrase "cleft lip" they "automatically"mean cleft upper lip, so there is a substantial possibility of people choosing the wrong term. @markengelstad  Can you advise as the the bast phraseology?

**Comment by markengelstad** [comment]
i'll supply a list of clinically relevant variants of cleft lip palate/ facial clefts (that we use in our log/ graph) in a bit... gotta drain a neck abcess -- I'll be back soon!

**Comment by pnrobinson** [comment]
We have an outstanding request  (the oldest openrequest)
New terms for facial clefts #609
with some conversation about the Tessier classification. It would be great to reopen this discussion

**Comment by markengelstad** [comment]
- Here's our the list of cleft related terms in the log.
- They are meant to be distinct enough to prevent overlap/ confusion.
- Also there are a couple of terms that are post-coordinated with multiple findings/ phenotypes, for convenience while logging (like "Bilateral complete cleft upper lip and palate and maxillary alveolus") 
- I supply both 'incomplete soft palate' and 'incomplete cleft palate' because its not always clear to a user where the cleft ends  (hard or soft palate) 
- I use 'mandibular cleft' to separate out lower clefting... which is very very rare of course.  But good options might be to include 'Cleft of lower lip'  and  'Central cleft of mandible'

The list:

Bilateral alveolar cleft of maxilla
Bilateral cleft palate
Bilateral cleft upper lip
Bilateral complete cleft upper lip and palate and maxillary alveolus
Bilateral incomplete alveolar cleft of maxilla
Bilateral incomplete cleft palate
Bilateral incomplete cleft upper lip
Central cleft upper lip
Cleft of face
Cleft of soft palate
Cleft of uvula
Cleft palate
Complete cleft of soft palate
Incomplete cleft of soft palate
Incomplete cleft palate
Mandibular cleft
Submucous cleft of hard palate
Submucous cleft of soft and hard palate
Submucous cleft of soft palate
Unilateral alveolar cleft of maxilla
Unilateral cleft palate
Unilateral cleft upper lip
Unilateral complete cleft upper lip and palate and maxillary alveolus
Unilateral incomplete alveolar cleft of maxilla
Unilateral incomplete cleft palate
Unilateral incomplete cleft upper lip

**Comment by markengelstad** [comment]
The tessier / facial clefts in the log: 

Tessier 0 cleft of face - midline facial cleft
Tessier 1 cleft of face - paramedian facial cleft
Tessier 10 cleft of face - supraorbital facial cleft
Tessier 11 cleft of face - supraorbital facial cleft
Tessier 12 cleft of face - supraorbital facial cleft
Tessier 13 cleft of face - supraorbital facial cleft
Tessier 14 cleft of face - midline facial cleft
Tessier 2 cleft of face - paramedian facial cleft
Tessier 3 cleft of face - paramedian facial cleft
Tessier 30 cleft of face - midline facial cleft
Tessier 4 cleft of face - infraorbital facial cleft
Tessier 5 cleft of face - infraorbital facial cleft
Tessier 6 cleft of face - infraorbital facial cleft
Tessier 7 cleft of face - infraorbital facial cleft
Tessier 8 cleft of face - supraorbital facial cleft
Tessier 9 cleft of face - supraorbital facial cleft
Cheilognathoprosoposchisis

**Comment by nicolevasilevsky** [comment]
I am going to add the following terms/hierarchy - I just discussed this with Mark

Facial cleft
- Mandibular cleft

Oral cleft
-Cleft palate (Ext Syn: Cleft of hard and soft palate)
--Submucous cleft of soft and hard palate
---Submucous cleft of hard palate
--Bilateral cleft palate
--Unilateral cleft palate
--Cleft of soft palate
---Submucous cleft of soft palate
---Cleft of uvula
-- Cleft of hard palate
---Cleft of alveolar ridge of maxilla 
----Unilateral alveolar cleft of maxilla
----Bilateral alveolar cleft of maxilla

-Cleft lip (NT)
--Cleft upper lip
---Bilateral cleft upper lip
--Central cleft upper lip
--Unilateral cleft upper lip

**Comment by nicolevasilevsky** [comment]
added HP_0410030 Cleft lip and added logical def:
'has part' some 
('closure incomplete' and ('inheres in' some lip) and ('has modifier' some abnormal))

This infers 'Abnormality of the digestive system morphology to be a parent, and I pasted the explanation below. Does this seem correct?

![image](https://user-images.githubusercontent.com/6722114/27358582-fd639c50-55dc-11e7-8d62-b7d7c2c2edff.png)

**Comment by nicolevasilevsky** [comment]
@markengelstad Should 'Unilateral cleft upper lip' be a synonym of  HP_0011340 Incomplete cleft of the upper lip?

**Comment by nicolevasilevsky** [comment]
Note to self 
Removed 'mandibular cleft' as synonym for 'Cleft mandible' because I accidentally added a new clas of the same name. Add it back after I obsolete HP_0410029 Mandibular cleft

I need help obsoleting HP_0410029 Mandibular cleft
@drseb or @cmungall, can either of you help?

**Comment by nicolevasilevsky** [comment]
@markengelstad We have two terms that are inferred to be equivalent:
HP_0000175 Cleft palate
HP_0410004 Cleft secondary palate

Should these be merged?

cc @drseb and @pnrobinson

**Comment by nicolevasilevsky** [comment]
Ok, done adding/rearranging the terms per @markengelstad's recommendations.

The only open question now is about the two classes that are inferred to be equiv, I moved this to another ticket #2431
