### ISSUE TITLE
expansion of the cortexes in the proximal and middle phalanges in digits 2-4 (musculoskeletal abnormalities)

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/human-phenotype-ontology#2330]
>This is a request for a new term

>1. Preferred term label (e.g., Asplenia)_
Expansion of the cortexes in the proximal and middle phalanges in digits 2-4

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

>4. Reference (PMID)
This reference relates this requested phenotype with the NGLY1-deficiency rare disease
https://www.ncbi.nlm.nih.gov/pubmed/27388694

>5. Suggested parent term 
http://compbio.charite.de/hpoweb/showterm?id=HP:0011001 

>6. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.
DO: DOID:0060728
ORPHANET: ORPHA:404454
OMIM:615273

>7. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)
http://orcid.org/0000-0003-0169-8159

**Comment by LCCarmody** [comment]
@pnrobinson Would this be 'Thickened cortex of bones' or a subclass thereof?  Or should this be defined as 'increased density'?

**Comment by pnrobinson** [comment]
It is really difficult to make a term for this, since there are many ways a cortex of a bone can become expanded and there are no other details in the publication. This was also a feature that only occurred in 1 of the 12 patients. I have looked in google and pubmed and not found very much that is similar to this, and for now I would suggest we close this term. If we can find a text book or something like that that classifies defects like this and associates them in general with diseases then we could reopen this issue.
