### ISSUE TITLE
Change label to delete 'due to immunodeficiency'

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#2417]
Change label from Hepatic abscesses due to immunodeficiency to Hepatic abscesses

**Comment by LCCarmody** [comment]
Also, change Cellulitis due to immunodeficiency to just cellulitus

**Comment by LCCarmody** [comment]
@pnrobinson 
The request from the hackathon was to remove 'due to immunodeficiency', but there are a number of items defined by this.  Also, if you remove 'cellulitis due to immunodeficiency', then there are two terms named 'cellulitis'.  Should we continue? Or is there a different way to describe this phenotype?

<img width="428" alt="screen shot 2017-07-07 at 3 11 59 pm" src="https://user-images.githubusercontent.com/26067008/27973064-aa22b678-6326-11e7-8eaf-a590b0328268.png">

**Comment by pnrobinson** [comment]
ToDo
-- there are two other "due to immunideficiency" terms that need reworking.

**Comment by pnrobinson** [comment]
Revised Osteomyelitis due to immunodeficiency

**Comment by pnrobinson** [comment]
Cellulitis due to immunodeficiency is used to annotate

- [ ] OMIM:233700 | GRANULOMATOUS DISEASE, CHRONIC, AUTOSOMAL RECESSIVE, CYTOCHROME B-POSITIVE,TYPE I | NCF1 (653361)
- [ ] OMIM:233690 | GRANULOMATOUS DISEASE, CHRONIC, AUTOSOMAL RECESSIVE, CYTOCHROME B-NEGATIVE | CYBA (1535)
- [ ] OMIM:233710 | GRANULOMATOUS DISEASE, CHRONIC, AUTOSOMAL RECESSIVE, CYTOCHROME B-POSITIVE,TYPE II | NCF2 (4688)
- [ ] OMIM:306400 | GRANULOMATOUS DISEASE, CHRONIC, X-LINKED

**Comment by pnrobinson** [comment]
done refactoring

**Comment by drseb** [comment]
This issue has not been resolved. Found 
`OMIM:233700	GRANULOMATOUS DISEASE, CHRONIC, AUTOSOMAL RECESSIVE, CYTOCHROME B-POSITIVE,TYPE I					HP:0002755	Osteomyelitis due to immunodeficiency			IEA	IEA							OMIM:233700	HPO	2009-02-17`
