### ISSUE TITLE
supraorbital hyperostosis

### ISSUE THREAD

**Issue by slaulederkind** [obophenotype/human-phenotype-ontology#2484]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label: supraorbital hyperostosis

>2. Synonym: hyperostosis of supraorbital bone

>3. Textual definition: Excessive growth or abnormal thickening of the supraorbital portion of the frontal bones. PMID:16835913

>4. Suggested parent term: Cranial hyperostosis HP:0004437

>5. Frontometaphyseal dysplasia - PS305620 (OMIM).

>6. RGD:gthayman

**Comment by pnrobinson** [comment]
I think that this is essentially the same thing as "Prominent supraorbital ridges" (HP:0000336), which is defined as Greater than average forward and/or lateral protrusion of the supraorbital portion of the frontal bones. Please let me know if you see any difference between this term and Hyperostosis and if so provide the differentia. Otherwise I would add this Supraorbital hyperostosis as a synonym.

**Comment by slaulederkind** [comment]
It is up to you. Hyperostosis seems to be the pathology responsible for the prominent ridges.  HP has both "Abnormality of the supraorbital ridges" and "Craniofacial hyperostosis", without a connection between the two. The proposed term/synonym would fit beneath either of those terms.

**Comment by pnrobinson** [comment]
I think this is probably best as a synonym, since the HPO does not have separate terms for pathophysiology. Sometimes medical terms are based on our assumptions of pathophysiology, but in this context, these seem really to be just a shorthand way of describing certain phenotypes.
