### ISSUE TITLE
Clarify meaning/classification of 'Somatic mutaiton'

### ISSUE THREAD

**Issue by mbrush** [obophenotype/human-phenotype-ontology#2514]
Can someone clarify the meaning of the currently definition-less HP_0001428 term ('Somatic mutation').  It is a child of 'Mode of Inheritance', but it is not clear how 'somatic mutation' fits here.  The child of this term is 'Somatic mosaicism' - but mosaic traits arise from de novo mutations in the soma of an individual, and therefore is not inherited or heritable.

I suspect that these 'somatic' terms included under 'Mode of inheritance' because, like the other terms here, they describe the origin of genetic traits.  But in these cases no inheritance is involved.  I suggest adding/clarifying definitions and labels to avoid confusion this may cause.

**Comment by pnrobinson** [comment]
I disagree since this is a particular mode of inheritance of disease that is limited to the involved cells so to speak. Does this definition make sense (just added):
def:This term applies to a disease whose etiology is related to an alteration in DNA that occurs after conception.
comment:Somatic mutations  occur in all body tissues throughout life and are not present in the germline from which the individual developed (The Greek word soma means body.) The majority of somatic mutations have no phenotypic effect. However, occasionally they may have functional consequences that confer a selective advantage on the cell owing to preferential growth or survival. These so-called driver mutations may ultimately lead to cancer or other diseases.

**Comment by mbrush** [comment]
I guess my point is that 'somatic mutation' being classified as a 'mode  of  inheritance' is potentially confusing given that in such cases  there is no trait/disorder inheritance happening (i.e. there is no "genetic trait or disorder passed from one generation to the next [HPO:probinson ]").  But I understand the idea behind putting it here is that _not being inherited_ can itself be considered a "mode" of inheritance (i.e. one in which no inheritance is actually involved in the etiology of a genetic trait).   
 
My larger concern was the lack of a definition for  the 'somatic mutation' term.  I think the text you suggest @pnrobinson is great, but I would make the definition read like a proper definition rather than an explanation of how the term is applied.  Something like the following would be consistent with the wording of other 'mode of inheritance' definitions: 
 
**def**:  "A mode of inheritance in which a trait or disorder results from a de novo mutation occurring after conception, rather than being inherited from a preceding generation.
 
**comment**: "This term applies to a disease whose etiology is related to an alteration in DNA that occurs after conception. Somatic mutations occur in all body tissues throughout life and are not present in the germline from which the individual developed (The Greek word soma means body.) The majority of somatic mutations have no phenotypic effect. However, occasionally they may have functional consequences that confer a selective advantage on the cell owing to preferential growth or survival. These so-called driver mutations may ultimately lead to cancer or other diseases."

**Comment by pnrobinson** [comment]
Thanks for the suggestion, I agree and have made the corresponding revisions.
