### ISSUE TITLE
Preferred term label/ HP:0011788

### ISSUE THREAD

**Issue by BrunOrpha** [obophenotype/human-phenotype-ontology#2525]
Increased serum free triiodothyronine (HP:0011788) can currently be more often searched, found and selected in HYPERthyroïdism than his current parent hypothyroidism(HP:0000821), although its place is correct in the rare field of thyroid hormone resistance (OMIM#188570).

Suggestion:  add to HP:0011788 increased serum FT3 "due to...(something)" ?

**Comment by pnrobinson** [comment]
I do not understand.
Increased serum free triiodothyronine (HP:0011788) is a child of Abnormality of thyroid physiology but not of Hyper- or Hypothyroidism. I think that in general we need to revise these thyroid terms,and I will do so soon. In general the HPO does not include "due to" terms, but instead the simple phenotype observations.

**Comment by BrunOrpha** [comment]
Thank you for those precisions
