### ISSUE TITLE
 New term request: Abnormal autopod morphology 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2543]
Label: Abnormal autopod morphology

Parent class ID: HP_0040064 

Parent label: Abnormality of limbs 

Suggested text def: Any structural anomaly of the distal elements of the limb of vertebrates including the pedal or prehensile appendages (e.g. hand, foot, phalanges and/or digits). 
_(I revised this def slightly, per Chris' comment below_

Logical def: 
has part' some(morphology and ('inheres in' some limb) and ('has modifier' some abnormal)) 

Text def xref: MP:0000572

**Comment by cmungall** [comment]
The logical def you gave is not correct, I think you meant [UBERON:0002470](http://purl.obolibrary.org/obo/UBERON_0002470) ! autopod region

I don't think the terminology is right for HPO, autopod is more of an evodevo term? 'hand or foot' may be better. We can add this as human-preferred label in Uberon

What's the reason for adding the class? It wouldn't be annotated directly. Note that adding it will increase the latticeyness of HPO, since you have a bifaceted classification (A/P vs segments on proximodistal axis). Is this bad? Not necessarily, but I have a sense that HPO generally tries to limit this and chooses not to subdivide across all possible facets.

**Comment by cmungall** [comment]
> Suggested text def: Any structural anomaly of the distal elements of the limb of vertebrates including the pedal or prehensile appendages (e.g. hand, foot, paw, phalanges and/or digits). |

we wouldn't use a vertebrate definition in HPO

**Comment by nicolevasilevsky** [comment]
This was one of the terms on this spreadsheet:
[MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
I would suggest we not add an autopod term right now, or whatever the equivalent should be. The skeletal system should be revised from top to bottom to make things more consistent, and that is not something we should be attempting to do piecemeal with issues.
