### ISSUE TITLE
New term request: Common truncal valve stenosis	

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2572]
Label: Common truncal valve stenosis	
Parent class ID: HP_0001654	
Parent label: Abnormality of the heart valves	

Suggested text def: Abnormal constriction or narrowing of the single outflow tract valve that opens into the truncus arteriosus that is frequently present in cases of truncus arteriosus septation defects.	
Text def xref: MP:0010590

See [MPO flyer spreadsheet](https://docs.google.com/spreadsheets/d/13sBAq55KesjYl32WHw0o_BBSEH1kPV082l_4cG04LGo/edit#gid=33920039)

**Comment by pnrobinson** [comment]
@cmungall  @nicolevasilevsky @mellybelly  This is tricky because it can only exist in the context of truncus arteriosus, and if we allow users to code this term alone, then it could lead to inconsistent data. On the other hand, we already have four subtypes of truncus arteriosus and this could start a combinatorial explosion.
Long term the only way to deal with this is probably the use of modular ontologies with different levels of detail fordifferent situations. I am not sure that we need to go into this level of detail now,and I would propose not adding this term unless there are objections.

**Comment by nicolevasilevsky** [comment]
no objections from me!

**Comment by pnrobinson** [comment]
OK, I will close this.
