### ISSUE TITLE
abnormality of radial ray

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#2613]
>1. Preferred term label (e.g., Asplenia)_

abnormality of radial ray

>2. Synonyms (e.g., Absent spleen)

deformity of radial ray
radial ray deformity
radial ray anomaly
radial ray abnormality

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

cc: @dnahotline

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

HP:0040064

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

Fanconi anemia  (hierarchy is a bit fraught at present, so not sure what correct ID would be)

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

orcid.org/0000-0002-9353-5498

cc: @dnahotline

**Comment by nicolevasilevsky** [comment]
this may be a related synonym for 'Abnormality of the radius' HP_0002818

see ref:
http://www.nature.com/gim/journal/v15/n3/full/gim2012120a.html

**Comment by nicolevasilevsky** [comment]
Expert response : Radial ray, I think, is the thumb,(2 bones) and 1st meta carpel. Radius would be it's own distinction. Radial in general is used for the thumb side of the hand and wrist

Adding new term above

**Comment by drseb** [comment]
I think this is a bundled term and is not optimal for adding to HPO. @pnrobinson , please comment

**Comment by pnrobinson** [comment]
Actually, I was condidering adding this term a while back but didnt for the reason that Seb mentions. Abn. of the radial ray is more of a disease category and it is not really a good phenotypic feature. I do not think that we should have it as a term.

**Comment by nicolevasilevsky** [comment]
@pnrobinson should I delete this term then?

cc @jmcmurry

**Comment by pnrobinson** [comment]
I would delete it!

**Comment by jmcmurry** [comment]
I'm not insistent, but could you explain why "abnormality of the digits" is ok but "abnormality of the radial ray" is not? I would like to understand the underlying principle.

**Comment by jmcmurry** [comment]
We have all kinds of things that are used disease categories and also phenotypes (like "cleft palate")

**Comment by nicolevasilevsky** [comment]
@pnrobinson I am holding off deleting this term, pending answers to Julie's questions :)

**Comment by drseb** [comment]
> We have all kinds of things that are used disease categories and also phenotypes (like "cleft palate")

But just because we have wrong things in there, doesn't mean we should add more questionable things. We are trying to fix and get disease-concepts out there.

> I would like to understand the underlying principle.

Me too. See for example the discussion we had [here](https://github.com/obophenotype/human-phenotype-ontology/issues/1873). Maybe @pnrobinson can write his thoughts on the reasoning into the wiki. 
For this specific issue, I think it is 1) a bundled term and 2) not used very often.  I guess this is the reasoning of @pnrobinson . But as you see in the linked issue, it is possible to convince him ;-)

**Comment by pnrobinson** [comment]
What was the use case -- was there an external request for radial ray abn? 
We have some diseases in HPO because disease A is characterized by disease B (e.g., Bardet Biedl syndrome -> Diabetes), and when we started the HPO in 2007/8, this was the data we had, i.e., there were very numberous existing annotations and publication that use this strategy of annotation. For radial ray anomaly, it seems it is just an imprecise way of describing phenotypes, and it is not being used nearly as often.

**Comment by jmcmurry** [comment]
It was a specific request of Maureen's

**Comment by jmcmurry** [comment]
I spoke to Peter at the Hackathon, and he explained the general principle that gave him pause about this term. Bundling terms like this can create problems with the hierarchy; it might end up rather high in the hierarchy as there is no logical parent nearby. He would prefer to decouple deformity of radius and deformity of thumb. I'm ok with that; slightly more verbose, but also not something that is likely to be used with tremendous frequency either.
