### ISSUE TITLE
new term request: Bacterial Upper Respiratory Tract Infection

### ISSUE THREAD

**Issue by pshultes** [obophenotype/human-phenotype-ontology#2623]
1. Preferred term label- Bacterial Upper Respiratory Tract Infection

2. Synonyms - N/A

3. Textual definition - upper respiratory tract infections contracted from bacteria instead of viruses; can include tonsillitis, sinusitis, otitis (ear infections), pharyngitis, etc. PMID: 28991170

4. Suggested parent term- HP:0011947 Respiratory Tract Infection

5. If you know of a disease that is characterized by this feature, please indicate it- N/A

6. nanoattribution- UCB:pshultes

**Comment by pnrobinson** [comment]
Currently, the HPO has some terms like "Recurrent Bacterial Upper Respiratory Tract Infections" that refer to a history of having numerous infections as is seen in immunodeficiencies, but does not cover a single episode of an infection, which is conceptualized as a disease. Have you seen the current HPO terms in this area? Do they work? If you are talking about the infection itself though, a Disease term should be used (e.g., MONDO!)

**Comment by pshultes** [comment]
Currently there is a HPO term for recurrent upper respiratory tract infections, HP:0002784. I was uncertain how specifically HPO terms should be used. Should there be distinct terms for viral and bacterial infections, especially considering how less frequent bacterial infections are? Right now there is no distinction.

**Comment by pnrobinson** [comment]
The issue is one of combinatorics -- if we include all permutations of recurrent infection X organ then there would be thousands of terms like this, which would make the entire system difficult to use. Our rule has been that if there is a type of recurrent infection that is characteristic of a disease (and not just of a single patient or case report), then we would add the term, otherwise, we recommend using a more upper level term. For instance, there are terms for recurrent bacterial and recurrent vairal infections.
If there is a disease with recurrent bacterial infections that is specific to the lung, say, then please provide pubmed references etc.

**Comment by pshultes** [comment]
Recurrent Bacterial Upper Respiratory Tract Infections/Bacterial Lung Infections are closely associated with autoimmune diseases such as Good's syndrome:

"Sinopulmonary Infections caused by encacpsulated bacteria"-
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4593265/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3585500/
