### ISSUE TITLE
New (parent) term request "Neonatal Complications"

### ISSUE THREAD

**Issue by brittneyj** [obophenotype/human-phenotype-ontology#2628]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Neonatal Complications

>2. Synonyms (e.g., Absent spleen)

possibly "perinatal complications" (not in the HPO) or "Abnormality of prenatal development or birth" (in the HPO already - HP:0001197)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

Complications occurring in the neonatal period) shortly after birth. This would be a nice parent term for "neonatal hypoglycaemia" - HP:0001998, "poor suck" - HP:0002033, and numerous other terms already in the HPO. 

>4. Suggested parent term (Please look in the hierarchy of the HPO using the [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or other browsers such as [OLS](http://www.ebi.ac.uk/ols/ontologies/hp) and find the place in the HPO where the new term best fits)

possibly "Abnormality of prenatal development or birth" HP:0001197 or "Phenotypic abnormality" - HP:0000118

>5. If you know of a disease that is characterized by this feature, please indicate it (e.g., by its Orphanet or OMIM id), and we will add the annotation to our database.

>6. If you would like a nanoattribution, please indicate your ORCID id or provide a label such as HPO:probinson (organization, first initial-last name)

**Comment by pnrobinson** [comment]
This is not possible without adding a lot of duplications to the HPO, essentially because of the logic of how ontologies work. If we put a term underneath "Neonatal complication", then that term is inferred to be ALWAYS neonatal. But there are lots of complications that MAY occur in the noenatal period, but ALSO can occur at other time points.
I think that this is something that should be solved at the data input level -- i.e., software such as Phenotips can be made to group together all of the HPO terms that in your center are observed in neonatal settings.
