### ISSUE TITLE
Accentuation of the pulmonic component of the second heart sound

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2635]
_**Please consider a new term for Accentuation of the pulmonic component of the second heart sound.
Observed in Idiopathic and/or familial pulmonary arterial hypertension.PMID:20301658.
I think that we need an intermediate super classe witch is abnormal heart sounds just below Abnormality of cardiovascular system physiology???**_

**Comment by pnrobinson** [comment]
Created as Abnormally loud pulmonic component of the second heart sound
added "accentuation.." as synonym.
Def: The pulmonic component is considered to be abnormally loud in a subject over age 20 if it is greater than the aortic component in the second left ICS or if it is audible at the cardiac apex. This may be due either to pulmonary artery hypertension or right ventricular dilatation, with part of the right ventricle assuming the position normally occupied by the left ventricle. A split second sound at the apex is, therefore, definitely abnormal. The loud P2 commonly heard at the apex in patients with atrial septal defect is probably due to a dilated right ventricle encroaching upon the cardiac apex [source-NCBI:NBK341].
