### ISSUE TITLE
Remove infancy onset modifiers from HPO-class labels

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#2647]
Merge them with more general class. Revise annotations to add onset modifier.

E.g. some candidates are:

- [ ] name: Failure to thrive in infancy
- [ ] name: Recurrent infantile hypoglycemia
- [ ] name: Transient hypogammaglobulinemia of infancy
- [ ] name: Recurrent infections in infancy and early childhood
- [ ] name: Calcific stippling of infantile cartilaginous skeleton
- [ ] name: Apneic episodes in infancy
- [ ] name: Fatal liver failure in infancy
- [ ] name: Infantile encephalopathy
- [ ] name: Acute infantile spinal muscular atrophy
- [ ] name: Redundant skin in infancy
- [ ] name: Infantile hypercalcemia
- [ ] name: Lumbar kyphosis in infancy
- [ ] name: Infantile sensorineural hearing impairment
- [ ] name: Infantile muscular hypotonia
- [ ] name: Infantile axial hypotonia
- [ ] name: Lethal infantile mitochondrial myopathy
- [ ] name: Infancy onset short-trunk short stature
- [ ] name: Infantile spasms

Can you comment @pnrobinson

**Comment by pnrobinson** [comment]
The policy that we have followed in the past is to provide precomposed terms like this for items that are really important for the differential diagnosis -- because most HPO software does not support adding modifiers. I think actually that we should keep these terms for now because they are all important diagnostic clues. 
As we move forward it would be good to develop software libraries and GUIs that make it easy to use all of our modifiers!

**Comment by drseb** [comment]
The problem is, that the annotations must be improved then. For example, for Prader-Willi-Syndrome, Hypotonia has always infantile onset. However, Prader-Willi-Syndrome is not listed when you look at "Infantile muscular hypotonia", but instead "Generalized hypotonia" is used. This is misleading for users, that expect Prader-Willi-Sydrome to show up for the infantile term. 

There are two ways forward here:
- go through all annotations and check if a more specific term should be used (very bad)
- replace all annotations that use modifiers in their labels with the more generic superclass and move the onset-information from the label to a meta-annotation (good)

Let me know what you think.

**Comment by pnrobinson** [comment]
I see your point but at the moment not even Phenomizer can be run with onset modifiers, and thus we would not really be making things easier for our users. If we made this change then we would also need to go back and add the modifier to Prader Willi, so we have to do manual annotation in any case. 
I also like the existence of separate terms because it means we can write in comments to better define them. I think these are things that will help users.
My suggestion is that we need to start to improve our software to make it easy to use modifiers like this, get the community to adopt this kind of solution, and then we can figure out how to evolve.

**Comment by drseb** [comment]
I see. I kind of agree. You got one thing wrong IMHO:

>  If we made this change then we would also need to go back and add the modifier to Prader Willi, so we have to do manual annotation in any case.

This could be done automatically, once we define that "Infantile muscular hypotonia" is equivalent to 
"Generalized hypotonia"+"Infantile onset". 

I will close for now, but this should be higher up in priority lists...
