### ISSUE TITLE
please add more HPO terms to primary angle closure glaucoma

### ISSUE THREAD

**Issue by PACGresearcher** [obophenotype/human-phenotype-ontology#2659]
Hello

Tn addition to HP:0012109 these additional HPO terms should be added to primary angle closure glaucoma to make it more comprehensive.

HP:0000593 Abnormality of the anterior segment of the globe
HP:0025311 Anterior chamber cyst
HP:0000594 Shallow anterior chamber
HP:0012630 Abnormality of the trabecular meshwork

Thank you

**Comment by drseb** [comment]
Is this request about extending the annotations of OMIM:137760 ?

**Comment by pnrobinson** [comment]
btw, is there a specific abnormalit of the trabecular meshwork that we should include? For instance,
The meshworks from patients with POAG have a lower cellularity than normals (https://www.ncbi.nlm.nih.gov/pubmed/6462622).
Also note that there are many forms of POAG including
https://omim.org/entry/137760  (see the section on genetic heterogeneity)
In general, we try to be specific about what findings are present in which form (although the above findings may be common to all). Any insight would be appreciated.

**Comment by pnrobinson** [comment]
I have investigated the Science article that found the gene for OMIM:137760, but unfortunately there is not much clinical data. Our rule is that our annotations be supported by published evidence. I realize that the phenotypes you mention are commonly found in POAG but since we are annotating specific Mendelian forms we need to rely on publications. Please reopen this issue if you know of publications that would support these annotations! Thanks
