### ISSUE TITLE
 patches of dense fibrosis

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#2672]
_**Please consider a new term for patches of dense fibrosis taking the form of collagen sheets, Diagnostic criteria of Idiopathic pulmonary fibrosis.PMID:21471066.
Superclass:Pulmonary fibrosis??**_

**Comment by pnrobinson** [comment]
I think that the "patches of dense fibrosis" are really describing the "Pulmonary fibrosis" rather than being something different. I do not think we should try to differentiate Pulmonary fibrosis in this way unless there is a clear differential diagnostic reason (I am not familiar with one). Please annotate simply to Pulmonary fibrosis for now.
