### ISSUE TITLE
ENR-EYE NTR: Axial myopia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2742]
[added] Added//Axial myopia//new term request (PS); parent- Myopia [level: 7]; term- Axial myopia [level: 8]

**Comment by pnrobinson** [comment]
@psergouniotis
is this a good definition
Axial myopia is defined as an axial length above the norm and too long for the refractive power of the whole optical system of the eye. 
https://www.nature.com/articles/eye2013223
How is this distinguished from other forms of myopia, like High myopia? Or can you be both axial myopia and high myopia? Would it then be better to annotate with increased axial length and high myopia?

**Comment by psergouniotis** [comment]
[I] The definition looks good.

[II] On a different note, please consider adding the following sentence to the definition of myopia:
(...) Myopia arises where light from a distance is brought to a focus in front of the retina either because the refracting power of the eye is too great (index myopia) or the anteroposterior diameter is too long (axial myopia).

[III] The following subclasses are proposed for myopia:
Myopia
  | Axial myopia
  | Mild myopia
  | Moderate myopia
  | Severe myopia (rename to High myopia)
  | Latent myopia

The AOA definitions for MYOPIA are: low (<–3D), moderate (–3 to –6D), or high (>–6D). 

[IV] Further to your question, axial relates to the kind of myopia while low/moderate/high relate to the degree of myopia. Indeed a myopia could be both high and axial.

Annotating this with increased axial length and high myopia may be inaccurate as, in rare occasions you may have myopia, increased axial length but not purely axial myopia.
