### ISSUE TITLE
ENR-EYE NTR: Increased tear production

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2752]
[added] Added//Increased tear production//new term request (PS); parent- Increased lacrimation [level: 7]; term- Increased tear production [level: 8]

**Comment by pnrobinson** [comment]
@psergouniotis
Is this different from increased lacrimation (defined as Abnormally increased lacrimation, that is, excessive tearing (watering eye).?

**Comment by psergouniotis** [comment]
Yes they are different.

Firstly, "Increased lacrimation" should be renamed to 'Epiphora" (with "Increased lacrimation" kept as a synonym). 

Secondly the following structure is proposed:
Epiphora 
  | Increased tear production
  |   | Increased basal tear production
  |   | Reflex tearing
  | Lacrimal pump failure
  | Decreased tear drainage

Further to your question, you can have "Increased lacrimation" (epiphora) roughly due to either too many tears being produced (Increased tear production) or to not enough tear being drained away (Decreased tear drainage). Therefore, "Increased tear production" should be a subclass and not a synonym of "Increased lacrimation" (Epiphora)

**Comment by pnrobinson** [comment]
Adding term for Increased tear production with definition: Increased lacrimation owing to overproduction of tears.

**Comment by pnrobinson** [comment]
@psergouniotis 
Can you provide definitions for
- [ ] Increased basal tear production
 - [ ] Reflex tearing

**Comment by pnrobinson** [comment]
@psergouniotis 
I am adding this definition for Lacrimal pump failure: Reduced tear outflow is due to tear pump dysfunction and associated with increased tearing. -- is it OK?

**Comment by pnrobinson** [comment]
@psergouniotis 
Can you provide a definition for Decreased tear drainage. Is it a synonym of Nasolacrimal duct obstruction (NLDO) ?

**Comment by pnrobinson** [comment]
@psergouniotis The definition for Lacrimal pump failure is OK and was added.

**Comment by psergouniotis** [comment]
Proposed definitions:
- Increased basal tear production: a form of watery eye associated with overproduction of tears due to an increased parasympathetic drive to the secretory component of the lacrimal system (lacrimal gland); this could be due to pro-secretory drug use (e.g. pilocarpine) or autonomic disturbance.

- Reflex tearing: a form of watery eye associated with overproduction of tears due to reflex tearing in response to a local irritant (e.g. trichiasis or foreign body), chronic ocular surface disease (e.g. blepharitis) or systemic disease (e.g. thyroid eye disease)

- Lacrimal pump failure (please consider modifying to): a form of watery eye associated with abnormal lid tone and/or lid position. The former is due to lid laxity (common involutional change in the elderly) or a weak orbicularis muscle (e.g. due to VII cranial nerve palsy). The latter is typically associated with ectropion causing punctal eversion.

- Decreased tear drainage: A form of watery eye associated with obstruction of the nasolacrimal system. This may arise at the level of the punctum, the canaliculi, the sac or the nasolacrimal duct.

"Decreased tear drainage" may be associated with Nasolacrimal sac obstruction &  Nasolacrimal duct obstruction. However, not all obstructions will cause decreased tear drainage and therefore I think it would be best not to have these associated (one could select both "Nasolacrimal sac obstruction" and "Decreased tear drainage")

**Comment by LCCarmody** [comment]
Added definitions to Increased basal tear production, Reflex tearing, and Updated lacrimal pump failure.  I left 'Decrease tear drainage' because I am not sure where it should be located.

**Comment by LCCarmody** [comment]
Going to close this issue since there is another issue open about this topic.
