### ISSUE TITLE
ENR-EYE NTR: Floppy eyelid syndrome

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2863]
[added] Added//Floppy eyelid syndrome//new term request (PS); parent- Upper eyelid entropion [level: 7]; term- Floppy eyelid syndrome [level: 6]

**Comment by pnrobinson** [comment]
@psergouniotis
I would say this is a disease and not a phenotype
https://www.ncbi.nlm.nih.gov/pubmed/17700238
@nicolevasilevsky @cmungall We should put this into MONDO if Panos (psergouniotis) agrees that this should be a disease and not a phenotype.

**Comment by psergouniotis** [comment]
In the spreadsheet I recommended introducing the term "Floppy eyelid" (and have "Floppy eyelid syndrome" as its synonym).

"Floppy eyelid syndrome" is an ill defined entity but I agree with you that it is not exactly a phenotype. It would be more relevant to MONDO and therefore please do not add this as a synonym of "Floppy eyelid".

**Comment by nicolevasilevsky** [comment]
@cmungall should I add 'floppy eyelid syndrome' to MONDO (as a PR)?

**Comment by LCCarmody** [comment]
Following up on this:  The hierarchy should be:
Upper eyelid entropion 
      Floppy eyelid
            Eyelid laxity (Issue #2864)  ?

Or could Floppy eyelid and eyelid laxity be synonyms?

**Comment by psergouniotis** [comment]
I would recommend to have "Floppy eyelid" as a subclass of "Eyelid laxity". 

On a different note, on HPO Workbench, "Abnormal eyelid morphology" seems to have replaced "Abnormality of the eyelid" as the primary term for HP:0000492. This is inaccurate and quite a few of the children terms are functional rather than morphological abnormalities. Pleas consider to keep HP:0000492 as "Abnormality of the eyelid".

**Comment by pnrobinson** [comment]
@psergouniotis we should move the physiology terms to the abn or eyelid physiology term then! The overall structure is that there is a top level Abnormality of X term (where X is eye in this case) and then everything goes to morphology or physiology.

**Comment by psergouniotis** [comment]
thanks Peter. The issue with these terms is that they are ocular adnexa, not eye. So it would be perhaps reasonable to have "abnormality of the eyelid" or "abnormality of nasolacrimal system" etc as top level terms and then everything goes to morphology or physiology. 

also, what do you usually do for symptoms which could be either due to a morphological or a physiological abnormality (e.g. epiphora or nyctalopia)?

**Comment by pnrobinson** [comment]
I would say that epiphora is clearly a physiological finding, and if it is due to a morphological abnormality then both items should be coded separately (same for nyctalopia). This strategy helps to keep the ontology more streamlined.

**Comment by psergouniotis** [comment]
thanks for the response. the issue is that in terms of hierarchy, there will be quite a few terms in which certain subclasses will be morphological abnormalities and certain subclasses physiological. 

in any case, back to the initial issue, I think it would be quite parsimonious to have:
* "Abnormality of the ocular adnexa" with the following subclasses:
- Abnormality of the nasolacrimal system
- Abnormality of the common tendinous ring
- Abnormality of the conjunctiva
- Abnormality of the eyelid
- Abnormality of the extraocular muscles
- Abnormality of the eyebrow

Then for each one of these there should be "Abnormal #### morphology" plus, where appropriate, "Abnormal #### physiology". 

The current HPO workbench version (where Abnormality of the eyelid is a synonym of Abnormal eyelid morphology) is inaccurate

**Comment by psergouniotis** [comment]
perhaps consider closing this - the discussion could be continued in 
#2864 and  #3408

**Comment by pnrobinson** [comment]
OK, I will close this. Please consider that the physiology does not always match 1 to 1 with the organs. For instance, abnormal tearing could be production or drainage, related to different organs. I will close this issue, and we could skype about the the strategy.
