### ISSUE TITLE
ENR-EYE NTR: Lymphangioma of the orbit

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2876]
[added] Added//Lymphangioma of the orbit//new term request (PS); parent- Hamartoma of the orbital region [level: 4]; term- Lymphangioma of the orbit [level: 5]

**Comment by psergouniotis** [comment]
please add "lymphagioma of the orbit" as a subclass of "Hamartoma of the orbital region" (HP:0030670).

proposed definition (as per Oxford Handbook of Ophthalmology 2014):  a hamartoma of lymph vessels that usually presents in childhood. It tends to increase in size with head-down posture and with the Valsalva manoeuvre. Superficial lesions are visible as transilluminable cystic spaces of the lid or
conjunctiva that may also contain blood. Deep lesions may cause gradual proptosis or present acutely with orbital pain and reduced vision due to haemorrhage.
