### ISSUE TITLE
ENR-EYE NTR: Cyclodeviation

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2930]
[added] Added//Cyclodeviation//new term request (PS); parent- Congenital exotropia [level: 10]; term- Cyclodeviation [level: 9]

**Comment by pnrobinson** [comment]
Adding term
Cyclodeviation is defined as the rotation of an eyeball along the anteroposterior axis and cyclotropia as a misalignment of cyclodeviation between the two eyes.


@psergouniotis. - please reopen item if the definition needs revision

**Comment by psergouniotis** [comment]
see also #3341

As per ERN-EYE document, I recommend adding "Cyclodeviation" as a subclass of "Strabismus". "Rotational strabismus" can be a synonym of "Cyclodeviation".
Definition: A form of strabismus in which one eye is wheel rotated so that the upper end of its vertical axis is nasal (incyclodeviation) or temporal (excyclodeviation).

"Cyclodeviation" should have two subclasses: "Cyclotropia" and "Cyclophoria".
Definition for "Cyclotroria": A form of manifest strabismus (heterotropia) in which the one eye is wheel rotated so that the upper end of its vertical axis is nasal (incyclotropia) or temporal (excyclotropia).
Definition for "Cyclophoria": A form of latent strabismus (heterophoria) in which the occluded eye wheel-rotates on dissociation.

"Cyclotropia" should have two subclasses: "Incyclotropia" and "Excyclotropia".
"Cyclophoria" should have two subclasses: "Incyclophoria" and "Excyclophoria"
