### ISSUE TITLE
ENR-EYE NTR: Incyclotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2931]
[added] Added//Incyclotropia//new term request; synonym: incyclodeviation (PS); parent- Cyclodeviation [level: 9]; term- Incyclotropia [level: 10]

**Comment by pnrobinson** [comment]
Adding term with definition:
A type of cyclotropia (torsion of one or both eye about the visual axis of the eyes) in which the upper poles of the globes are rotated inward (medially) to each other.
@psergouniotis please reopen issue if this definition needs revision

**Comment by psergouniotis** [comment]
see also #2930

"Incyclotropia" should be a subclass "Cyclotropia".

Definition of  "Incyclotropia":
A type of cyclotropia in which the one eye is wheel rotated so that the upper end of its vertical axis is nasal.  This misalignment around the anteroposterior axis is causing the optic disc to appear below the macula of fundoscopy. Incyclotropia is typically due to weakness of the excyclorotating muscles (inferior oblique; inferior rectus).
