### ISSUE TITLE
ENR-EYE NTR: Excyclotropia

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2932]
[added] Added//Excyclotropia//new term request; synonym: excyclodeviation (PS); parent- Incyclotropia [level: 10]; term- Excyclotropia [level: 10]

**Comment by pnrobinson** [comment]
Adding term with definition:A type of cyclotropia (torsion of one or both eye about the visual axis of the eyes) in which the upper poles of the globes are rotated outward (laterally) to each other.

@psergouniotis please reopen issue if this definition needs revision

**Comment by psergouniotis** [comment]
see also #2930

"Excyclotropia" should be a subclass "Cyclotropia".

Definition of  "Excyclotropia":
A type of cyclotropia in which the one eye is wheel rotated so that the upper end of its vertical axis is temporal.  This misalignment around the anteroposterior axis is causing the optic disc to appear above the macula of fundoscopy. Excyclotropia is typically due to weakness of the incyclorotating muscles (superior oblique, superior rectus).
