### ISSUE TITLE
ENR-EYE NTR: Unilateral strabismus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#2979]
[suppressed] HP:0010877//Strabismus//Suppressed//Unilateral strabismus//HP:0000486//Strabismus//unilateral could be added as a modifier (PS); parent- Cyclic exotropia [level: 11]; term- Unilateral strabismus [level: 9]

**Comment by pnrobinson** [comment]
@psergouniotis
Are we sure we want to remove this term?

This term is used in many places
https://www.aoa.org/patients-and-public/eye-and-vision-problems/glossary-of-eye-and-vision-conditions/strabismus
it is not currently being used to annotate a disease in our corpus

**Comment by psergouniotis** [comment]
Proposed definition for strabismus: A misalignment of the eyes so that the visual axes deviate from bifoveal fixation. The classification of strabismus may be based on a number of features including the relative position of the eyes, whether the deviation is latent or manifest, intermittent or constant, concomitant or otherwise and according to the age of onset and the relevance of any associated refractive error. 

I would still be keen to obsolete this term as I think it is inaccurate. Strabismus may be associated with pathology in one eye only but refers to the relative position of the eyes. Strictly speaking therefore it cannot be unilateral (but if anyone disagrees and wants to specify they can select the relevant modifier).

**Comment by psergouniotis** [comment]
Maybe we can meet in the middle:
If you want to keep this, perhaps rename it to "Monocular Strabismus" (syn monocular deviation & unilateral strabismus).
Definition: A unilateral ocular deviation in which fixation does not alternate.

**Comment by pnrobinson** [comment]
Thanks, I have updated the definition of strabismus.
I have changed the label to monocular strabismus, and I have updated its definition to A type of strabismus in which the fixating eye is always the same one, while the other eye is constantly deviated. Monocular strabismus is to be distinguished from alternating strabismus, in which either of the eyes 'squints' at different times.
