### ISSUE TITLE
ENR-EYE NTR: Peripheral traction retinal detachment

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3169]
[No action] HP:0007643//Tractional retinal detachment//Peripheral traction retinal detachment//HP:0007917//Tractional retinal detachment; parent- Tractional retinal detachment [level: 11]; term- Peripheral traction retinal detachment [level: 12]

**Comment by pnrobinson** [comment]
@psergouniotis  I added the definition
Tractional retinal detachment at the periphery of the retina.
Note that there is a substantial definition of the parent term "Tractional retinal detachment"
--please reopen issue of the definition is not good.

**Comment by psergouniotis** [comment]
Please add "Tractional retinal detachment at the periphery of the retina" or "Peripheral tractional retinal detachment" (one as primary term one as synonym) as subclass of "Tractional retinal detachment".

Current def of "Tractional retinal detachment" is OK but I quite like the one in Oxford Handbook of Ophthalmology (2014):
A type of retinal detachment arising due to a combination of contracting retinal membranes, abnormal vitreoretinal adhesions, and vitreous changes. It is usually seen in the context of diseases that induce a fibrovascular response, e.g. diabetes.

Also, for "Exudative retinal detachment" (HP:0012231)  I would favour the following definition:
A type of retinal detachment arising from damage to the outer blood–retinal barrier that allows fluid to access the subretinal space and separate the neurosensory retina from the retinal pigment epithelium.

**Comment by pnrobinson** [comment]
@psergouniotis  There is already a term called "Peripheral traction retinal detachment" that is a child of "Traction retinal detachment" I will add the above two as synonyms.

**Comment by psergouniotis** [comment]
Yes - I have not seen this initially. I think it would be best to have 
"Peripheral tractional retinal detachment" as the primary term with the following being synonyms: "Tractional retinal detachment at the periphery of the retina" & "Peripheral traction retinal detachment".

All these should be a subclass of "Tractional retinal detachment"

(I know it is not the main topic but please also consider adding the above recommended definition for "Exudative retinal detachment")

**Comment by pnrobinson** [comment]
done. Also added new definition for "Exudative retinal detachment".
