### ISSUE TITLE
ENR-EYE NTR: Cystic retinal degeneration

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3181]
[No action] HP:0007667//Retinal degeneration//Cystic retinal degeneration//HP:0000546//Retinal degeneration; parent- Peripheral retinal atrophy [level: 12]; term- Cystic retinal degeneration [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis 
Is this term related to microcystic degeneration (see http://bjo.bmj.com/content/bjophthalmol/51/10/714.full.pdf)
Can you help with a definition?

**Comment by psergouniotis** [comment]
Quite a vague term "Cystic retinal degeneration". I think people may use it in the context that you described, I would personally prefer the primary term to be "Peripheral cystoid retinal degeneration" (subclass of  "Peripheral retinal degeneration"). As synonym I would have "microcystic retinal degeneration", microcystoid retinal degeneration" & "cystic peripheral retinal degeneration" (but not the current "Cystic retinal degeneration").

Proposed definition: Degenerative changes of the peripheral retina consisting of close-packed tiny cystic spaces at the outer plexiform/inner nuclear retinal level. The degeneration is very common in adult eyes and starts adjacent to the ora serrata and extends circumferentially and posteriorly.

* NOTE: as discussed in a different thread, Lattice retinal degeneration & Reticular pigmentary degeneration should be subclasses of "Peripheral retinal degeneration" rather than just "Retinal degeneration".

**Comment by pnrobinson** [comment]
Added definition and modified primary label as suggested.
