### ISSUE TITLE
ENR-EYE NTR: Intraretinal hemorrhage

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3209]
[added] WG//Added//Intraretinal hemorrhage//new term request (WG); parent- Vireous hemorrhage [level: 12]; term- Intraretinal hemorrhage [level: 11]

**Comment by pnrobinson** [comment]
@psergouniotis  There is anow a term called Retinal hemorrhage -- isn’t that the same thing as Intraretinal hemorrhage? And why is the suggested parent term "Vitreous hemorrhage"? Please provide guidance!

**Comment by psergouniotis** [comment]
This is a difficult topic and there was no consensus at the Odile meeting.
I propose the following:

- Abnormal fundus morphology (HP:0001098) - please rename to "Abnormal fundal morphology" (keeping "Abnormal fundus morphology" as a synonym.
- Add "Fundus hemorrhage" as a subclass of "Abnormal fundal morphology".
- Make modifications so that the hierarchy looks as below:

Fundus hemorrhage
  | Retinal hemorrhage
  |  |  Macular hemorrhage
  |  |  Foveal hemorrhage
  |  |  Intraretinal hemorrhage
  |  |  |  Dot haemorrhage/microaneurysm of the retina
  |  |  |  Blot hemorrhage of the retina
  |  |  Subretinal hemorrhage
  |  |  |  Submacular hemorrhage
  |  |  Subinternal limiting membrane hemorrhage (synonym Sub-ILM hemorrhage)
  | Pre-retinal hemorrhage
  |   |  Subhyaloid hemorrhage
  |  Macular hemorrhage
  |  Foveal hemorrhage

The difficult one is what is a "Retinal hemorrhage". Is it just hemorrhage within the retinal layers (intraretinal)? Should sub-retinal hemorrhage and sub-ILM hemorrhage be considered types of retinal hemorrhage?

The proposed definition for "Sub-retinal hemorrhage" is "accumulation of blood between the neurosensory retina and the Retinal Pigment Epithelium (RPE) arising from the choroidal or retinal circulation"

RPE is one of the 12 layers of the retina so one could argue that "Sub-retinal hemorrhage" should be a subclass of "Retinal hemorrhage".  The same argument can be used for "Subinternal limiting membrane hemorrhage.

However,  "Subinternal limiting membrane hemorrhage" is often considered a form "Pre-retinal hemorrhage". I think this is not completely accurate so I have only included "Subhyaloid hemorrhage" as a subclass of "Pre-retinal hemorrhage". 

"Macular hemorrhage" & "Foveal hemorrhage": foveal and macular describe location. I have therefore not attempted to associate them with specific location. 

"Vitreous hemorrhage": although the origin ia the retinal blood vessels it would be confusing to have it as a subclass of retinal hemorrhage. I think it should stay as a subclass of "Abnormality of the vitreous humor". It can be argued that it should also be a subclass of "Abnormality of the fundus" but I think it would be best not to include it at this stage.

Any thoughts would be greatly appreciated

**Comment by pnrobinson** [comment]
@psergouniotis 
We currently have
Dot-and-blot retinal hemorrhage
Should this be split into the two terms as above?
Also, can you provide a definition for intraretinal hemorrhage?
I have put foveal hemorrhage under macular h. Is this correct?

**Comment by psergouniotis** [comment]
Dot-and-blot retinal hemorrhages is a commonly used term relating to a fundoscopic appearence where both dot haems and blot haems are present.

one could instead select two terms (blot haems AND dot haems) but given that this is a frequent, useful term consider keeping "Dot-and-blot retinal hemorrhages" as a subclass of "Intraretinal hemorrhage".  An issue here could be though that the superclass refers to "hemorrhage" while the subclass has "hemorrhages". This is not logical and any thoughts how we could accommodate the plural (e,g, intraretinal hemorrhages) would be appreciated.

Notably, I would still recommend introducing "Dot haemorrhage/microaneurysm of the retina" and "Blot hemorrhage of the retina" as proposed above.

>  I have put foveal hemorrhage under macular h. Is this correct?
yes this is correct - it should be a subclass.

> Also, can you provide a definition for intraretinal hemorrhage?
Possible def: A subtype of fundus hemorrhage occuring within the neurosensory retina. Intraretinal haemorrhages may be 'dot' or' blot' shaped or flame shaped depending upon their depth within the retina. 
Although the fundoscopic appearence of an intraretinal hemorrhage can exibit significant variability it can typically be distinguished from a subretinal hemorrhage (occuring between the neurosensory retina and the RPE) or a sub-ILM hemorrhage (occuring between the internal limiting membrane and the neurosensory retina).


(see also p55 & 56 of this classic guideline document https://www.rcophth.ac.uk/wp-content/uploads/2014/12/2013-SCI-301-FINAL-DR-GUIDELINES-DEC-2012-updated-July-2013.pdf)

**Comment by pnrobinson** [comment]
THanks, I have implemented and checked the hierarchy.
