### ISSUE TITLE
ENR-EYE NTR: Occult macular dystrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3240]
[No action] HP:0030636//Macular dystrophy//Occult macular dystrophy//HP:0007754//Macular dystrophy; parent- Macular dystrophy [level: 11]; term- Occult macular dystrophy [level: 12]

**Comment by psergouniotis** [comment]
Possible definition: "Occult macular dystrophy is a, typically hereditary, abnormality of the macula associated with progressive foveal cone dysfunction and no apparent fundoscopic, full-field electoretinogram (ERG), or fluorescein angiogram abnormalities.

**Comment by pnrobinson** [comment]
I obsoleted the term and improved the annotations for the disease "Occult macular dystrophy"

**Comment by psergouniotis** [comment]
I would not suggest obsoleting the term. Best to keep "Occult macular dystrophy" in HPO and just amend the definition.

**Comment by pnrobinson** [comment]
@psergouniotis I have unobsoleted this term for now.
However, this article really suggests that this is a disease and not a phenotype.
https://www.ncbi.nlm.nih.gov/pubmed/25665791
We do not currently have HPO terms for "Attenuated focal macular ERG". Perhaps it would be best to actually obsolete this term and then to create a new term for the latter? Otherwise please suggest a definition for Occult macular dystrophy

**Comment by pnrobinson** [comment]
I added your definition

**Comment by psergouniotis** [comment]
I have worked on this phenotype before and I think it is more a phenotype than a disease (https://www.ncbi.nlm.nih.gov/pubmed/23281133). The appearance can have genetic, environmental (laser or sun staring) or drug-related (nitrates) aetiology. 

I have previously proposed a definition: A, typically hereditary, abnormality of the macula associated with progressive foveal cone dysfunction and no apparent fundoscopic, full-field electoretinogram (ERG), or fluorescein angiogram abnormalities.

The ERG terms that could be used instead of the less accurate "Attenuated focal macular ERG" are
"Abnormal amplitude of pattern electroretinogram" and "Abnormal  central response of multifocal electroretinogram".

**Comment by psergouniotis** [comment]
@LCCarmody 
please consider finalising this:
* introduce term "Occult macular dystrophy" as a subclass of "Macular dystrophy" (HP:0007754)
* proposed definition:  A typically hereditary abnormality of the macula associated with progressive foveal cone dysfunction and no apparent fundoscopic, full-field electoretinogram (ERG), or fluorescein angiogram abnormalities.

**Comment by pnrobinson** [comment]
This is HP_0030636
