### ISSUE TITLE
ENR-EYE NTR: Rod-cone dystrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3275]
[No action] HP:0000510//Pigmentary retinopathy//Rod-cone dystrophy//HP:0000580//Pigmentary retinopathy//this should perhaps not be a subclass of Pigmentary retinopathy (PS); parent- Pigmentary retinopathy [level: 11]; term- Rod-cone dystrophy [level: 12]

**Comment by psergouniotis** [comment]
This should not be a subclass of "Pigmentary retinopathy" (but it should remain a subclass of "Retinal dystrophy")

Proposed definition (based on PMID: 20212494) 
"An inherited retinal disease subtype in which the rod photoreceptors appear to be more severely affected than the cone photoreceptors. Typical presentation is with nyctalopia (due to rod dysfunction) followed by loss of mid-peripheral field of vision, which gradually extends and leaves many patients with a small central island of vision due to the preservation of macular cones. "

**Comment by pnrobinson** [comment]
No longer subclass of pigmentary retinopathy!
