### ISSUE TITLE
ENR-EYE NTR: Pericentral retinitis pigmentosa

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3276]
[No action] HP:0007947//Rod-cone dystrophy//Pericentral retinitis pigmentosa//HP:0000510//Rod-cone dystrophy; parent- Rod-cone dystrophy [level: 12]; term- Pericentral retinitis pigmentosa [level: 13]

**Comment by psergouniotis** [comment]
This should remain a subclass of "Rod-cone dystrophy".
Possible definition (from PMID 28981474):
A subtype of retinitis pigmentosa in which, instead of the pathology starting in the mid-periphery like typical retinitis pigmentosa, the disease starts in the near periphery closer to the vascular arcades and tends to spare the far periphery.
