### ISSUE TITLE
ENR-EYE NTR: Hypopigmentation of the fundus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3286]
[No action] HP:0007894//Abnormality of retinal pigmentation//Hypopigmentation of the fundus//HP:0007703//Abnormality of retinal pigmentation; parent- Retinal pigment epithelial mottling [level: 11]; term- Hypopigmentation of the fundus [level: 11]

**Comment by psergouniotis** [comment]
Presently, hypopigmentation of the fundus is a subclass of "Abnormality of retinal pigmentation". 
It would be more correct if it was a subclass of "Abnormality of the fundus" (HP:0001098) > "Abnormality of fundal pigmentation" (proposed new term). 
Textual definition for "Hypopigmentation of the fundus": Reduced pigmentation of the fundus, typically generalised. Fundoscopy may reveal a low level pigment in both RPE and choroid with clear visibility of choroidal vessels (pale/albinoid) or low pigment level in the RPE with deep pigment in choroid so that visible choroidal vessels are separated by deeply pigmented zones (tesselated/tigroid).

"Hyperpigmentation of the fundus" should also be removed from "Abnormality of retinal pigmentation" and be included as a subclass of "Abnormality of the fundus" (HP:0001098) > "Abnormality of fundal pigmentation" (proposed new term).  
Textual definition of "Hyperpigmentation of the fundus" : Increased pigmentation of the fundus.

Rationale: alterations in pigmentation of the fundus are typically not a result of changes in the retina. The variable pigmentation within both RPE and choroid combine to change profoundly the appearance of the normal fundus between individuals. This is partly a racial characteristic and partly genetic.

**Comment by pnrobinson** [comment]
@psergouniotis  OK! One question -- are all pigment abnormalities of the retina actually fundus abnormalities?

**Comment by psergouniotis** [comment]
Yes. Maybe "Abnormality of retinal pigmentation" should also be a subclass of "Abnormality of fundal pigmentation"

**Comment by pnrobinson** [comment]
It seems clinicians use names like "pigmented retinal spots" but actually the spots are "shining through" the transparent retina from the fundus? Should we therefore make Abnormality of retinal pigmentation a SYNONYM of "Abnormality of fundal pigmentation"? Or is this an oversimplification?

**Comment by psergouniotis** [comment]
Essentially the question is if the RPE (which is pigmented) part of the retina. Most would consider it one of the 12 layers of the retina. Therefore, while most retinal layers are transparent, the RPE is not. 
Also, you can have intraretinal pigmentation as part of certain diseases (e.g. rod-cone dystrophy/RP). 

In general I would prefer not to make "Abnormality of retinal pigmentation" a SYNONYM of "Abnormality of fundal pigmentation". The latter refers to the fundoscopic impression which reflects both RPE and choroidal pigmentation while the former it reflects RPE defects.

**Comment by pnrobinson** [comment]
Adding new term Abnormality of fundus pigmentation (HP_0031605); added definitions and moved terms as suggested above.
