### ISSUE TITLE
Term Definition added to Soft, doughy skin

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#3297]
>If this is a request for a new term, please provide us with the folloing information (c.f., https://github.com/obophenotype/human-phenotype-ontology/wiki/How-to-make-a-good-term-request).

>1. Preferred term label (e.g., Asplenia)_

Soft,  doughy skin 

HP_0001027

>2. Synonyms (e.g., Absent spleen)

>3. Textual definition (the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term).

extremely  fragile; saggy, redundant skin, doughy texture.

https://rarediseases.info.nih.gov/diseases/2089/dermatosparaxis-ehlers-danlos-syndrome

**Comment by pnrobinson** [comment]
I think that the text is specifying a particular type of soft, doughy skin
Common symptoms include soft, doughy skin ** that is extremely fragile; saggy, redundant skin **
Therefore, this is not a definition of soft, doughy skin.
It is hard to define this term, because it seems "obvious"
The best I have been able to come up with is
A skin texture that is unusually soft (and may feel silky), and has a malleable consistency resembling that of dough.
Ideas?

**Comment by krageth** [comment]
I agree with you @pnrobinson . I saw this one and spent a bit of time looking around for a suitable definition in the literature, but I think it is fairly self defined by the term name - as you stated. I do like the "malleable consistency resembling that of dough" because that really sets it apart from its parent term definition.

**Comment by pnrobinson** [comment]
Added the definition.
