### ISSUE TITLE
Duplicate term

### ISSUE THREAD

**Issue by krageth** [obophenotype/human-phenotype-ontology#3303]
Arthralgia/arthritis appears twice in the ontology but under two different parent terms. This may be due to the fact that the second Arthralgia/arthritis occurs under the "Pain" class. -  I could be way off on this one, either way please educate me! Thanks!

Arthralgia/arthritis: HP_0005059 
Parent term: Arthritis HP_0001369 ('Abnormal joint morphology')

Arthralgia/arthritis: HP_0005059
Parent term: Arthralgia HP_0002829 (Under Pain)

**Comment by drseb** [comment]
Are you using a tree-browser to look at hpo?

**Comment by pnrobinson** [comment]
Arthralgia/arthritis has two parent terms. If you look at the "Description" window in Protege, you will see "subclass of", and in this case it shows both Arthralgia and Arthritis. Actually this is not a great term and when we return to the skeletal system we may want to revise or obsolete it (it is simply the combination of both arthritis and Arthralgia, and so if a patient has both then we can annotate with both of these terms).
In any case, since Protege can only display in two dimensions, terms that have two parents will appear in two different places.

**Comment by krageth** [comment]
@drseb Yep!
@pnrobinson - Makes sense! Thank you!
