### ISSUE TITLE
Subclasses of "Hyperintensity of cerebral white matter on MRI"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3305]
@sheridae suggests to add under "Hyperintensity of cerebral white matter on MRI"

- _Focal_ hyperintensity of cerebral white matter on MRI
- _Multifocal_ hyperintensity of cerebral white matter on MRI
- _Confluent_ hyperintensity of cerebral white matter on MRI

We probably have to merge with (or add synonyms to) existing terms "Diffuse white matter abnormalities", "Focal white matter lesions", and "Multifocal cerebral white matter abnormalities"

Can we add the same for "**Hypo**intensity of..."

This is important for classification of white matter disorders. See e.g. Figure 1 here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2677542/

@pnrobinson what do you think?

**Comment by pnrobinson** [comment]
I agree these are good suggestions. @Frank-Probst should we work on structuring this subsection?

**Comment by Frank-Probst** [comment]
Sure!  The algorithm that Sebastian linked to is very good, but you have to be cautious about MRI findings, because if you're going to say hyper- or hypointense, you really need to say if the finding is on the T1-weighted images versus the T2-weighted images, because they're not always "reverse images" of one another.  With or without contrast is important, too.  FLAIR adds another dimension to the whole thing, and I have to admit that I don't really know what FLAIR is/does to the images.  MRI technology has evolved quite a bit over the last 15 or so years, so the radiologists are doing all kinds of things that are replacing older techniques, like angiograms and even echocardiograms.

**Comment by sheridae** [comment]
Hi all,


I completely agree with the comments about MRI methodolgy, and certainly these comments would probably hold for other aspects of neuroradiology as well. The truth is that classifications based on pathology are possibly still gold standard, but that methodology is not a standard part of clinical investigation so addressing MRI findings probably is necessary, as this is the standard now.


The T1 images result in images which highlight fat tissue within the body, while T2 images highlight Fat and water, thus Fatty tissue is distinguished from water-based tissue by comparing with the T1 images – anything that is bright on the T2 images but dark on the T1 images is fluid-based tissue. So it is the use of the two methodolgies which is important. Since myelin is principally fatty the methodologies are particularly complementary. T2 is an image resolution technique that results in removing signal from the cerebrospinal fluid (CSF) from the final images. It isparticularly useful in the detection of subtle changes at the periphery of the hemispheres and in the periventricular region close to CSF. So again it is complementary. T2 hyperintensity is referred to in several subclasses already.


Eamonn


Best Wishes
Eamonn Sheridan
Section of Clinical Genetics
Leeds Institute for Molecular Medicine
St James's Hospital
Leeds LS9 7TF

++113 343 8504


________________________________

**Comment by drseb** [comment]
We made a first pass on the suggested structure. Please let us know what you think.

**Comment by pnrobinson** [comment]
Do you mean the terms emanating from HP_0030890 ?
Would this mean that all of the terms above Punctate periventricular T2 hyperintense foci are also T2?
I am not sure this is the case and would like to review it.
Here is a good review article
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4599520/
Are you working with a neuroradiologist in Berlin? Can we set up a skype?

**Comment by drseb** [comment]
> Do you mean the terms emanating from HP_0030890 ?

We worked on "Hyperintensity of cerebral white matter on MRI", "Hypointensity of cerebral white matter on MRI", "Diffuse white matter abnormalities", "Focal white matter lesions", "Multifocal cerebral white matter abnormalities". Look at the subclasses of these and these commits: https://github.com/obophenotype/human-phenotype-ontology/commit/26281a89561089c23ea708bc8b2d788722df1b54  https://github.com/obophenotype/human-phenotype-ontology/commit/9c8b51d0f5e4af4dabe3aee703dfe078b8c44950

> Would this mean that all of the terms above Punctate periventricular T2 hyperintense foci are also T2?

We did not work on "Punctate periventricular T2 hyperintense foci"

> Are you working with a neuroradiologist in Berlin?

I work with Eamonn from Leeds and he works with expert neuroradiologists.

>  Can we set up a skype?

Yes. January?

**Comment by Frank-Probst** [comment]
@pnrobinson If you haven't already had the Skype meeting for this, can you please add me to it?  I'm not sure how much (if anything) I can contribute, but I think this would be a good opportunity for me to learn more about how structures are created and annotated.

**Comment by pnrobinson** [comment]
@drseb, these classes look good, but please provide definitions for any new class! I will try to add some this week but if you have them handy please comment on this issue.

**Comment by drseb** [comment]
do you mean logical definitions, because I think we added a text-definition for all the new classes that we added.

**Comment by pnrobinson** [comment]
a bunch of text definitions are missing!

**Comment by pnrobinson** [comment]
Adding definitions

1. Confluent hyperintensity of cerebral white matter on MRI
Areas of brighter than expected MRI signal in the white matter of the brain whereby individual patches run together.
2.Focal hyperintensity of cerebral white matter on MRI
An abnormal area of increased brightness (hyperintensity) that is limited to one particular area.
3. Multifocal hyperintensity of cerebral white matter on MRI
An abnormal area of increased brightness (hyperintensity) that occurs in several distinct areas.

-- reopen if needed.
