### ISSUE TITLE
wrong synonym for Late onset atopic dermatitis [HP:0007573]?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3339]
The synonym for Late onset atopic dermatitis [HP:0007573] is Late onset baby eczema. I think this syn may be wrong, I think the late onset means adult onset.

Some references:
http://www.sciencedirect.com/science/article/pii/S0190962204038472
https://www.medscape.com/viewarticle/737072 

cc @LCCarmody

**Comment by pnrobinson** [comment]
There is a medgen CUI for 
 Late onset baby eczema.
https://www.ncbi.nlm.nih.gov/medgen/895153
However, I do not think the phrase is very enlightening for lay persons. I would suggest deleting unless people strongly want to keep it.

**Comment by pnrobinson** [comment]
I will remove this synonym.

**Comment by pnrobinson** [comment]
I am also thinking that this section needs to be refactored as adult onset atopic dermatitis is probably best conceptualized as a disease. Nonetheless, I will leave it for now since I do not think we want to do this piecemeal. My new definition is: A form of atopic dermatitis with onset in adulthood characterized by atopic red face, chronic lichenified eczema on the trunk, subacute or psoriasiform dermatitis.
