### ISSUE TITLE
Missing strabismus subclasses

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3341]
I think we are missing, either as new classes or as synonyms:

- divergent strabismus
- paralytic strabismus
- rotational strabismus

please check if they should/can be added.

**Comment by pnrobinson** [comment]
Please note that we have a number of open requests from the ERN EYE meeting for strabismus.
@psergouniotis please advise

**Comment by pnrobinson** [comment]
divergent strabismus is a synonym of exotropia; I am adding it as a syn.

**Comment by psergouniotis** [comment]
Divergent strabismus should be a synonym of exodeviation (new subclass of "Strabismus").
Convergent strabismus should be a synonym of esodeviation (new subclass of "Strabismus").

As per ERN-EYE document, I recommend adding "Neurogenic strabismus" as a subclass of "Stabismus". Paralytic strabismus can be a synonym of "Neurogenic strabismus".
Definition: An ocular deviation caused by a palsy to one or more of the extraocular muscles or nerves
supplying them.

As per ERN-EYE document, I recommend adding "Cyclodeviation" as a subclass of "Strabismus". "Rotational strabismus" can be a synonym of "Cyclodeviation". 
Definition: A form of strabismus in which the one eye is wheel rotated so that the upper end of its vertical axis is nasal (incyclodeviation) or temporal (excyclodeviation). 

"Cyclodeviation" should have two subclasses: "Cyclotropia" and "Cyclophoria". 
Definition for "Cyclotroria": A form of heterotropia in which the one eye is wheel rotated so that the upper end of its vertical axis is nasal (incyclotropian) or temporal (excyclotropia). 
Definition for "Cyclophoria": A form of heterophoria in which the occluded eye wheel-rotates on dissociation.

"Cyclotropia" should have two subclasses: "Incyclotropia"  and "Excyclotropia".
"Cyclophoria" should have two subclasses: "Incyclophoria"  and "Excyclophoria"

**Comment by pnrobinson** [comment]
- [ ] synonyms for exo/eso deviation
- [ ] Neurogenic strabismus
- [ ] Cyclodeviation
- [ ]  two subclasses: "Cyclotropia" and "Cyclophoria".

**Comment by pnrobinson** [comment]
Done
