### ISSUE TITLE
ENR-EYE NTR: Chronic cicatrizating conjunctivitis

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#3380]
While researching Conjunctival cicatrization #2725, I found the below term.  Is it separate and should I add it?   It seems like more of a collection of phenotypes.

Found this: "Chronic cicatrizing conjunctivitis (CCC) is a broad term encompassing a spectrum of clinical disorders that result in conjunctival fibrosis and scar tissue formation. The resultant structural and functional alterations of the ocular surface can lead to loss of corneal transparency and loss of vision. Some of the conditions causing CCC are systemic diseases and thus have further potential for morbidity and even death. Therefore, it is clearly essential to identify the exact etiology of CCC early in its course, and to treat appropriately." https://entokey.com/cicatrizing-conjunctivitis/

**Comment by LCCarmody** [comment]
Tagging @psergouniotis and @pnrobinson

**Comment by psergouniotis** [comment]
#2725
Cicatricial conjunctivitis should be added as a subclass of "Abnormality   of the conjunctiva". Conjunctival  cicatrization should be synonym to "Cicatricial conjunctivitis ".

If someone wants to add "chronic" they could add as a modifier. I would not recommend "Chronic cicatrizating conjunctivitis" as a separare term. 

Definition for: cicatrizing conjunctivitis: An abnormality of the conjuctiva and ocular surface caused by conjunctival inflammation and associated with scarring.

**Comment by LCCarmody** [comment]
Won't add term. Closing issue.

**Comment by psergouniotis** [comment]
many thanks. please add the definition to cicatrizing conjunctivitis (An abnormality of the conjuctiva and ocular surface caused by conjunctival inflammation and associated with scarring)

**Comment by LCCarmody** [comment]
Hi--I did previously add the term conjunctival cicatrization (#2725) (with exact synonym Cicatricial conjunctivitis) with the definition "Conjunctival inflammation with progressive scarring". (citation: Griffiths, C, et al. Rook's textbook of dermatology. Chichester, West Sussex Hoboken, NJ: John Wiley & Sons Inc, 2016. Print.)

So, would you like "cicatrizing conjunctivitis" to be the term label and the others as exact synonyms? And I am happy to add your definition, but how would you like to be nanoattributed?  Do you have an orcid ID or we sometimes use organization:name (i.e., HPO:probinson). 

Thanks

**Comment by psergouniotis** [comment]
thanks for the response and for highlighting this. 
primary term should be "conjunctival cicatrization"
exact synonyms should include: conjunctival cicatricial conjunctivitis, cicatrizating conjunctivitis (...)
definition should be: an abnormality of the conjuctiva and ocular surface caused by conjunctival inflammation and associated with scarring.

My orcid ID is https://orcid.org/0000-0003-0986-4123
I think Peter has used UManchester:psergouniotis in the past but it would be best if my orcid ID was used instead (not sure if you could also do this retrospectively).

**Comment by LCCarmody** [comment]
No problem.  I will likely make updates tomorrow.  As for changing to the orcid id, it is easy to update--depending on how many there are.  If it is just a handful, I can do it.  If it is many, then I will ask someone who could write a script to replace all of them.  I think there has been a discussion about updating several older attributions using scripts, but I think that has had low priority.  Thanks--I will update.

**Comment by drseb** [comment]
I think a simple search/replace with a text-editor will be sufficient.

**Comment by LCCarmody** [comment]
@drseb Thanks. That didn't occur to me, but it was easy.  @psergouniotis: all your nanoattributions have been changed to your orcid id.
