### ISSUE TITLE
Suggesting new child term of "Dysautonomia"

### ISSUE THREAD

**Issue by cgunter624** [obophenotype/human-phenotype-ontology#3381]
Suggest creating new child term of Dysautonomia [HP:0002459] 
New term label: Orthostatic intolerance
New term definition: Development of symptoms when standing that are otherwise relieved when reclining.
New term comment (if any):
New term synonyms(if any):
New term lay person synonyms (if any):
Reference (e.g., PubMed ID): PMC3639459
Your biocurator ID for nanoattribution (if desired):

**Comment by pnrobinson** [comment]
THere is a term, HP_0001278, Orthostatic hypotonia.  I think that Orthostatic intolerance is best conceptualized as a disease because it is defined as having a set of phenotypic abnormalities and can be assigend to etiologies:
@nicolevasilevsky we should add this to MONDO
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3639459/

**Comment by nicolevasilevsky** [comment]
We have Orthostatic intolerance in MONDO already (MONDO_0011479)
