### ISSUE TITLE
Correction to term Onset

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3384]
Suggestion about term Onset [HP:0003674]
Current definition: The age group in which disease manifestations appear.
Current comment: Adolescent is defined by WHO as a person between 10-19 years of age.
Current synonym list: Age of onset

My suggestion:  Move the onset subhierarchy outside of clinical modifier.

**Comment by pnrobinson** [comment]
I have created a new upper level term called Clinical course -- and put underneath it all of our modifiers that related to the temporal development of disease, including Onset, Mortality, Temporal pattern, and Pace of Progression. I think it makes a lot of sense to group these terms together, and the resulting "Aspect" will make more sense too.

**Comment by mellybelly** [comment]
@pnrobinson can any of these be Xref'd or aligned with PATO? i had put in quite a few of these terms a long time ago. They may not be exactly what we need but we need these for all organisms so would be good to try.

**Comment by pnrobinson** [comment]
@mellybelly I agree. Should we make an issue at the PATO tracker?

**Comment by mellybelly** [comment]
yes please. Can you review what is PATO? I thought long and hard about this at the time I implemented it - essentially when do developmental processes start/end early/late, and changes in rate. But this was a *very* long time ago, and I think there have actually been edits since then that I might not agree with.
