### ISSUE TITLE
New annotation file format proposal

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3393]
The HPO team is planning to modernize the format of the annotation file ("phenotype_annotation.tab"). 
Here is a link to documentation about the planned change.
http://hpo-annotation-qc.readthedocs.io/en/latest/annotationFormat.html
Comments/suggestions/criticisms would be very welcome -- please respond to this issue.

**Comment by wshayes** [comment]
I've had a lot of success with using JSON/YAML/JSONLines formats with JSONSchema defining the data schema.  My arguments for it are here:  https://towardsdatascience.com/my-love-affair-with-json-edaca39e8320   (examples are included for how I manage terminology files which would be similar to the annotation file format proposed here).

Having a format that is immediately loadable as a rich data structure in pretty much every programming language is fantastically useful.  The only downside is it's not trivial to view in Excel, but converters are really easy to write. I really like the flexibility of using JSONLines so that I can process a small chunk at a time. With compression, the data descriptive overhead is greatly reduced - obviously a C-store would significantly exceed this in compression strength, but the *.tab structure probably wouldn't be more than 10-20% more compressible.  You would also have a data structure that is pre-designed for API interfaces.

**Comment by pnrobinson** [comment]
@wshayes this is a good suggestion. Note that the HPO data are also available from the Monarch Initiative as a JSON based API
https://api.monarchinitiative.org/api/
It seems that for now most of the people who download our resources from the HPO Website want good ol TSV files, but we can extend this if there is demand for it.

**Comment by mellybelly** [comment]
@wshayes please also feel free to give feedback on the monarch/biolink api, as we are trying hard to standardize across many sources
https://github.com/biolink/biolink-api

you may also be interested in the api model: https://github.com/biolink/biolink-model

**Comment by pnrobinson** [comment]
I am closing this item now as the new format is in place.
