### ISSUE TITLE
Correction to term Constriction of peripheral visual field

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3468]
Suggestion about term Constriction of peripheral visual field [HP:0001133]
Current definition: no definition available
Current comment: no comment available
Current synonym list: Concentric narrowing of visual field;Constricted visual field;Constricted visual fields;Depressed visual field;Limited peripheral vision;Reduced visual fields;Visual field constriction

My suggestion: Definition: Loss of ability to perceive light at the edge (periphery) of the usual visual field (the visual field is the area that a person is able to see with the eyes fixed in one position).
@psergouniotis -- is this definition good?

**Comment by psergouniotis** [comment]
The definition is good with the only part that is not 100% being the first few words: it is rather the relative or absolute decrease of retinal sensitivity rather than the loss of ability to perceive light.

In a way there is constriction of peripheral field when there is absolute or relative decrease in retinal
sensitivity extending from edge of visual field.

In contrast, there is a scotoma when there is absolute or relative decrease in retinal sensitivity within the visual field, bounded by areas of normal retinal sensitivity.

I would propose the following:
absolute or relative decrease in retinal sensitivity extending from edge (periphery) of the visual field in a concentric pattern. The visual field is the area that is perceived simultaneously by a fixating eye.

Please let me know if you would like me to try to make this less technical. 

On a different note, the terms "Depressed visual field" and "Reduced visual fields" are ill defined and I would recommend removing them from the synonym list.

**Comment by psergouniotis** [comment]
please also see #3475
