### ISSUE TITLE
painful dyskinesias

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3478]
_**Please consider a new term for painful dyskinesias observed in Paroxysmal non-kinesigenic dyskinesia
PMID:22967746.
Super class:Dyskinesia.**_

**Comment by pnrobinson** [comment]
I do not think this is a good term because Dyskinesia is a very general description of a movement disorder. The actual phenotypic observations of the family in PMID:22967746 are reported in Table 1 (items such as choreoathetosis). It is also unclear from the description whether all of the dyskinesias in this family are painful or just a few. For instance, Trismus is often associated with pain, but choreoathetosis is not. I would advise avoiding the "painful" modifier when annotating this paper because in my opinion the descriptions are too imprecise.
