### ISSUE TITLE
Acromicria

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#3528]
various syndromes and diseases mention this e.g.

 Orphanet:2928 ! Polyneuropathy-intellectual disability-acromicria-premature menopause syndrome
 Orphanet:3041 ! Intellectual disability-balding-patella luxation-acromicria syndrome
 Orphanet:969 ! Acromicric dysplasia

Should this be a (non-EXACT?) synonym of  Micromelia HP:0002983?

**Comment by pnrobinson** [comment]
Acromicria is not a synonym of micromelia. It is very rarely used as far as I know. "Acro" means "tip" and megaly means "big", and so an excess of growth hormone can lead to acromegaly: https://endocrinecareplan.weebly.com/acromegaly-dwarfism--gigantism.html
"micro" is the opposite of "megalo" and so this is a definition of acromicria - abnormal smallness of the limbs, including hands and feet, and sometimes the nose and jaws, due to a deficiency in pituitary function after puberty.
I think we probably need a new term for this but I would like to do some more research to get the optimal definition.

**Comment by pnrobinson** [comment]
added as HP_0031878
