### ISSUE TITLE
Craniocervical dystonia

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3538]
_**Please consider a new term for Craniocervical dystonia observed in Atypical pantothenate kinase-associated neurodegeneration.
PMID:26828213.
Superclass:segmental dystonia which is a new  term requested .**_

**Comment by pnrobinson** [comment]
According to this article, craniocervical dystonia can be consider to be a grouping class for
Blepharospasm
oromandibular dystonia
lingual dystonia
laryngeal dystonia
cervical dystonia

Currently we have a related grouping under craniofacial dystonia 
https://hpo.jax.org/app/browse/term/HP:0012179

I am not sure which system is more appropriate, but we will want to choose one or the other. @LOURGHI I will try to research this, are you familiar with this area?

**Comment by LCCarmody** [comment]
PMID: 22297875 Defines it as "Craniocervical dystonia is defined as a group of neurological disorders characterized by involuntary muscle contractions that frequently cause twisting, repetitive movements or abnormal postures affecting the periocular, perioral and laryngeal musculature, as well as mastication muscles and cervical muscles."

**Comment by pnrobinson** [comment]
We should try to find out if there is some recognized relationship between Craniocervical and Craniofacial dystonia -- I think they might be mutually incompatible.

**Comment by LCCarmody** [comment]
A little more digging and I think that craniocervical dystonias are persons with both cranial and cervical dystonia (and I guess craniofacial is a subset of cranial dystonias?).  Here is what I found:
", Craniocervical Dystonia (a mixed population of cranial dystonia, cervical dystonia and both combined);" " Since then, multiple other studies have addressed cervical
dystonia,81 craniofacial dystonia,82 limb dystonia,83 and series with
mixed populations.84,"   PMID: 29123945  

Not entirely sure if researchers are lumping the two together or that there are persons with both types of dystonias, but I interpreted as persons with both dystonias.

**Comment by pnrobinson** [comment]
I think that for now it is best to stick with our current hierarchy, that divides things according to craniofacial, I think this is a little more common. It is a grouping term and to annotate patients we should use the precise descriptions.
https://hpo.jax.org/app/browse/term/HP:0012179
