### ISSUE TITLE
Abnormality of the oral cavity super class of Chewing difficulties

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3547]
I think Abnormality of the oral cavity is more appropriate superclass for chewing difficulty ???

**Comment by pnrobinson** [comment]
Chewiing difficulties is physiological, and we may need to re-arrange terms in this area.

**Comment by pnrobinson** [comment]
Looking at this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4206107/
we may want to rearrange chewing difficulties -- which is not necessarily  neurological.

**Comment by pnrobinson** [comment]
Chewing and swallowing are interrelated. The act of chewing plays a fundamental role in the process of
swallowing food. Mastication prepares food for swallowing by breaking it into small particles.
Accordingly,  loss  of  teeth  has  been  associated  with swallowing difficulties.
https://onlinelibrary.wiley.com/doi/pdf/10.1111/adj.12064

**Comment by pnrobinson** [comment]
I have added subcategories for oral physiology and morphology and added this term to the Abn oral physiology hierarchy, and also changed the primary label to Impaired mastication and added the other synonyms as lay person.
New definition: An abnormal reduction in the ability to masticate (chew), i.e., in the ability to crush and ground food in preparation for swallowing.
New comment: Chewing and swallowing are interrelated. The act of chewing plays a fundamental role in the process of swallowing food. Mastication prepares food for swallowing by breaking it into small particles. Accordingly, loss of teeth has been associated with swallowing difficulties. Chewing difficulties may be caused by loss of teeth, partial dentures, or by tooth pain. Swallowing difficulties, in contrast, are often characterized by difficulties swallowing liquids, reflux, throat spasms, choking on dry food, or dysphagia.
