### ISSUE TITLE
Loinc 1960-4:  "Bicarbonate [Moles/volume] in Arterial blood"

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#3567]
Suggest creating a new term for Loinc: 1960-4 [Bicarbonate [Moles/volume] in Arterial blood] 
New term label: Abnormal Bicarbonate in blood (along with two children)
New term comment (if any): There are terms for abnormal bicarbonate in urin
Your biocurator ID for loinc2hpo (if desired): JGM:azhang

**Comment by kingmanzhang** [comment]
Now I think this might be equivalent to CO2 in blood, which exist in HPO. @pnrobinson @LCCarmody @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@kingmanzhang I think it is different - the urinary biocarabonate class uses the chebi term CHEBI_17544 hydrogencarbonate

I think we want the new classes:
**parent:** HP_0001939 'Abnormality of metabolism/homeostasis'
**new term:**  'Abnormality of circulating bicarbonate concentration'
**new child term:**  increased circulating bicarbonate concentration
**new child term:**  decreased circulating bicarbonate concentration

**Comment by drseb** [comment]
Please use uppee case for increased/decreased

**Comment by pnrobinson** [comment]
There are subtle differences in arterial and venous bicarbonate measurements because of the CO2 that is dissolved in the blood. For now I do not think that it is a good idea to try to capture this in the ontology--there is no way to use this data clinically without having the numbers etc and so ontologies cannot help with this distinction. I am adding "general" abn serum bicarbonate terms, see adding these terms, see HP_0032067
