### ISSUE TITLE
HPO Medical Terms Translated to Plain Language

### ISSUE THREAD

**Issue by GARDInfoCenter** [obophenotype/human-phenotype-ontology#3582]
@nicolevasilevsky , we reviewed 134 HPO Medical Terms and translated 91 of them into plain language. The remaining terms were not translated because either: (1) the HPO medical term was too vague and the translation may not work for all instances of its use, or (2) because to make the medical term lay friendly it would require a definition and not just a translation. We are attaching an Excel spreadsheet with the details. We realize that some of the translations may be lengthier than you would like; however, we have included them as a way to gain a better understanding of character limit, criteria to use when translating the medical terms, etc. 

These terms appear on 25+ GARD disease webpages. 

Thanks,
Maria
[HPO Medical Terms 25+_1 to 134.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/1981041/HPO.Medical.Terms.25._1.to.134.xlsx)

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter I reviewed all the terms, I think the terms below look good. @pnrobinson would you mind looking at these and let me know if they are okay to add? I will add them once you give me the okay. 

HPO term | Suggested layperson synonym
-- | --
Adult onset | symptoms begin in adulthood
Aganglionic megacolon | enlarged colon lacking nerve cells
Anemia | low number of red blood cells or hemoglobin
Astigmatism | abnormal curving of the cornea or lens of the eye
Blue sclerae | whites of eyes are bluish-gray color
Brachydactyly | short fingers or toes
Bronchiectasis | permanent enlargement of the airways of the lungs
Cafe-au-lait spot | flat light-brown birthmarks
Camptodactyly | permanent flexion of the finger or toe
Camptodactyly of finger | permanent flexion of the finger
Cardiomyopathy | disease of the heart muscle
Cerebral calcification | abnormal deposits of calcium in the brain
Cerebral cortical atrophy | decrease in size of the outer layer of the brain due to loss   of nerve cells
Childhood onset | symptoms begin in childhood
Chorioretinal coloboma | birth defect that causes hole in part of the eye
Chronic otitis media | chronic infections of the middle ear
Cirrhosis | scar tissue replaces healthy tissue in the liver
Clinodactyly | permanent curving of the finger
Clinodactyly of the 5th finger | permanent curving of the pinkie finger
Clitoral hypertrophy | enlarged clitoris
Congenital cataract | clouding of the lens of the eye at birth
Congenital onset | symptoms present at birth
Conjunctivitis | pink eye
Craniofacial   hyperostosis | excessive bone growth of the skull and face
Dilated cardiomyopathy | stretched and thinned heart muscle
Erythema | redness of skin or mucous membrane
Foot dorsiflexor weakness | foot drop
Gynecomastia | enlarged male breast
Hydrocephalus | too much cerebrospinal fluid in the brain
Hypertrophic   cardiomyopathy | enlarged and thickened heart muscle
Nystagmus | involuntary, rapid, rhythmic eye movements
Pes cavus | high-arched foot
Postaxial foot polydactyly | extra toe attached near the little toe
Posteriorly rotated ears | ears rotated toward back of head
Spasticity | involuntary muscle stiffness, contraction, or spasm
Atrial septal defect | an opening in the wall separating the top two chambers of the heart
Bicuspid aortic valve | aortic valve has two leaflets rather than three

**There are a few terms where I had suggestion revisions:**

HPO term | Suggested layperson synonym | Suggested revision
-- | -- | --
Anal atresia | absent or misplaced anus | Absent anus
Proximal   placement of thumb | attachment of thumb is closer to the wrist than is typical | Attachment of thumb close to wrist
Distal sensory impairment | decreased sensation in the distant parts of the body (e.g., arms and legs) | decreased sensation in extremities
Pulmonary arterial hypertension | increased blood pressure in the blood vessels of the lungs | increased blood pressure in blood vessels of lungs
Aminoaciduria | abnormally high levels of amino acids in the urine | Increased levels of animo acids in urine
Dysmetria | lack of coordination of movement (e.g. undershoot or overshoot movement) | lack of coordination of movement
Coarctation of aorta | birth defect where part of the aorta is narrowed | Narrowing of the main heart artery
Brachycephaly | shorter and broader skull shape than typical | short and broad skull
Dolichocephaly | taller and narrower skull shape than typical | Tall and narrow skull

@GARDInfoCenter and @pnrobinson - will you let me know if the suggested revisions look okay?

Attached is the spreadsheet with additional notes, for the synonyms that may not be a good fit for HPO (and I had a question on a few of them as well).

[HPO.Medical.Terms.25._1.to.134_NV.xlsx](https://github.com/obophenotype/human-phenotype-ontology/files/1981821/HPO.Medical.Terms.25._1.to.134_NV.xlsx)

**Comment by pnrobinson** [comment]
Some items -- 
1. Cafe-au-lait spot | flat light-brown birthmarks -> Cafe-au-lait spots are not necessarily or even usually present at birth.
2. Cerebral cortical atrophy | decrease in size of the outer layer of the brain due to loss   of nerve cells
-> I would say "due to loss of brain cells" (the brain is not just nerve cells!)
3. Chorioretinal coloboma | birth defect that causes hole in part of the eye
-> It might be better to say "causes a hole in the innermost layer at the back of the eye"
4. I have never heard "heart artery" for aorta -- is this really a lay synonym?

**Comment by pnrobinson** [comment]
Other than the four comments about, all of the suggestions look great!
I could not find a synonym for aorta, and so I would think that anybody who knows what the aorta is also knows what it is called, and so I would guess that "heart artery" would confuse more people than it would enlighten. Maybe "Narrowing of the aorta (large blood vessel that emerges from the heart)" or simply "Narrowing of the aorta" would be better?

**Comment by nicolevasilevsky** [comment]
I added all the synonyms above (and added 'Narrowing of the aorta' for 'Coarctation of aorta').

@GARDInfoCenter do you want to review my other comments in the attached spreadsheet (above) and let me know if you'd like me to add more LP syns?

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky Yes, we plan to meet internally on Friday to review the comments. I hope to get back to you early next week.

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter Great, thanks!

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky We are fine with the proposed changes you and Peter have made. Here are references for the decreased fetal movement and IQ. 

Decreased fetal movement - See attached. (There does not appear to be a consensus, but the article provides some information)
[Decreased fetal movement_ Diagnosis evaluation and management - UpToDate.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/2009613/Decreased.fetal.movement_.Diagnosis.evaluation.and.management.-.UpToDate.pdf)


IQ - https://www.merckmanuals.com/home/children-s-health-issues/learning-and-developmental-disorders/intellectual-disability       
https://www.ncbi.nlm.nih.gov/books/NBK332877/table/tab_9-1/?report=objectonly
--

Maria

**Comment by pnrobinson** [comment]
I think this item is finished, so I am closing the issue. Thanks everybody!
