### ISSUE TITLE
Loinc 33219-7:  "Epithelial cells.squamous [#/area] in Urine sediment by Automated count"

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3607]
Suggest creating a new term for Loinc: 33219-7 [Epithelial cells.squamous [#/area] in Urine sediment by Automated count] 
New term label: Presence of epithelial squamous cells in urine
New term comment (if any):
Your biocurator ID for loinc2hpo (if desired): HPO:nvasilevsky

**Comment by pnrobinson** [comment]
This should not be "Presence of" because a small number of epithelial squamous cells in urine is a normal finding. 
Here is a review that is good on this.
https://watermark.silverchair.com/labmed32-0153.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAlIwggJOBgkqhkiG9w0BBwagggI_MIICOwIBADCCAjQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZ9730W4n0p9oo1QaAgEQgIICBSDrZHm_tFXgWN3UW3hFL3lO2uqCqxzMPi_ITS6mtx48NLBhKTqriC3BggV1c7XTM-bXkc9yxsZVIBWFHMaV7SRscsY-T4vNTopEYrg-Vzv4AS-z9zdHvXE5GNyhCsSsHZN4gfFNCVB-POC1DUoo6965WR31rUZo4fOSyYY9dZrFwSe0rVaP-ePM9HMc0Qo14U0Ju_-o3aMKa1shW8tlkn4rXZnIFl7ceLCNBhUDbJAuKpjd0WHg3LJAV8G1eHY_iAel7rHXVoqGWhvyY5lPZqQAswjvUOcpHuWMCexQmckIFTD9JWiKMIR3cdNS53k5bsz5XUt1C0zjol4VwItCmoftalA8jK_HBqFArriLh99sCIbhYvWg0KHjmvmUnMWLEJEGvqmzYMqbPaYO-lLadYCPruGLkepw0c_DVK26nx6qU3udpCjc_-l61aQ25GA3cxTJCORVewQRRidpcKQpDK4TmxriUAZgXTMfbV5dkQYeWOaWrlicDFN8jAwCvyHiE6XXDMCtmZCn6Te-hHpoOJzsKg7vxF-P6xDsvwitaWXWMUFABIo0RtNoWqie9Y-uZfUzx59ZOKtFQvARyFAm7aiiJFAP6OHqjMjUEXwy3GyLXns2b1GUNaFupazbaXVY1hBDo-B4oOZMK5514xFmBIcfjiv4viCSq9704rR9JpY8GOvCgR4

**Comment by pnrobinson** [comment]
added as HP_0032212
