### ISSUE TITLE
Add subclasses for "autosomal recessive inheritance"?

### ISSUE THREAD

**Issue by oleraj** [obophenotype/human-phenotype-ontology#3687]
We just noticed today that ["autosomal recessive inheritance"](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118#id=HP:0000007) is not broken down into subclasses for compound heterozygous and homozygous recessive, though it lists them both in the description.  Can we add these two as subclasses? If this been considered previously and rejected, I'd be curious about the reason.  (I didn't see any issues related to this topic in the repo.)

**Comment by pnrobinson** [comment]
The inheritance terms are intended to describe a disease entity -- and any given AR disease may be inherited with homozygous or compound het mutations depending on the genotypes of the parents. I think that it is cleaner to describe the homozygous/compound het distinction as part of the genotype rather than of the phenotype (See for instance the definition in the Oxford Handbook of Genetics (https://www.amazon.com/Oxford-Handbook-Genetics-Medical-Handbooks/dp/0199545367), which is a great book.)
I have updated the definition of the term slightly as follows:
A mode of inheritance that is observed for traits related to a gene encoded on one of the autosomes (i.e., the human chromosomes 1-22) in which a trait manifests in individuals with two pathogenic alleles, either homozygotes (two copies of the same mutant allele) or compound heterozygotes (whereby each copy of a gene has a distinct mutant allele).

**Comment by oleraj** [comment]
Okay, thanks for the explanation, sounds good to me.
