### ISSUE TITLE
catecholaminergic ventricular tachycardia

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#3695]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
catecholaminergic ventricular tachycardia

### 2. Synonyms
biventricular tachycardia

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))

polymorphic ventricular tachycardia HP_0031677

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
CPVT OMIM:604772

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0002-1655-8012 Elisa Mastantuono
These disorders have a clear genotype-phenotype correlations and use the specific ECG terms is helpful to select the disease associated genes.
If the exact terms exist that the cardiologists use, then there are fewer genes to consider. OMIM term is more general however supporting papers are clearer and more specific.

**Comment by pnrobinson** [comment]
@jmcmurry according to my reading of this article, 
http://circep.ahajournals.org/content/5/5/1044
there is no PHENOTYPIC difference to "polymorphic ventricular tachycardia" -- the modifer "catecholaminergic" refers to the etiology and thus is more of a description of a disease than of the phenotype. Thus, if you do not know the diagnosis already, this will not help. Could you please ask Elisa if my interpretation is correct. Otherwise, could she please provide a description of what differentiates "catecholaminergic ventricular tachycardia" (aka "catecholaminergic polymorphic ventricular tachycardia") from garden variety "polymorphic ventricular tachycardia"?

**Comment by pnrobinson** [comment]
I think that we should not create a new term here. Closing this issue, reopen if needed.
