### ISSUE TITLE
merge HP:0009071 and HP:0100614?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#3700]
This ticket was added to the MONDO tracker: https://github.com/monarch-initiative/mondo/issues/236 

Please review these records and consider a merge.
https://www.mda.org/sites/default/files/publications/Facts_Inflamm_Myopathies_P-199.pdf states
'Another word for inflammatory myopathy is myositis.' and I have not seen any distinction made between these terms in general usage.
If a distinction is retained, please provide definitions that clarify each term.

cc @maglott

**Comment by pnrobinson** [comment]
Inflammatory myopathy is here: https://hpo.jax.org/app/browse/term/HP:0009071
it is not currently connected to 
Myositis https://hpo.jax.org/app/browse/term/HP:0100614
They are not synonymous, since "Inflammatory myopathy " refers to a more chronic state. However, we do need to provide definitions and revise the structure of this part of the HPO.

**Comment by pnrobinson** [comment]
Inflammatory myopathy is not the greatest term, because it is bundled and it does not provide a precise description, but since it is used to describe this as a feature we can keep it for now. The definition is
Chronic muscle inflammation accompanied by muscle weakness.
