### ISSUE TITLE
Unexplained fleeting jaundice

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3733]
_**Please consider a new term for Unexplained fleeting jaundice observed in Wilson disease PMID:24209444.
Superclass:jaundice.**_

**Comment by pnrobinson** [comment]
Wilson disease can be characterized by liver disease leading to jaundice. It is not specifically fleeting. The fact that it is associated with Wilson disease in this cause means that it does have an explanation, so I would not include that in the term name. If you want to annotate "fleeting" (which I would not advice), consider using the existing HPO term Intermittent jaundice. Otherwise I think that annotating the Jaundice would be correct.
