### ISSUE TITLE
Brisk distal reflexes

### ISSUE THREAD

**Issue by LOURGHI** [obophenotype/human-phenotype-ontology#3736]
_**Please consider a new term for Brisk distal reflexes observed in Spastic paraplegia-optic atrophy-neuropathy syndrome.PMID:15852396.
Superclass:brisk reflexe. **_

**Comment by pnrobinson** [comment]
I think that the authors of this paper are misusing the word "brisk" (which is not the same as hyperreflexia, see https://www.ncbi.nlm.nih.gov/books/NBK396/). I am saying this because they are describing severely affected patients in a disease that is normally characterized by hyperreflexia and they state only "brisk". I would say that for now it is enough to have one term for brisk reflexes and I think that these patients have Distal and proximal hyperreflexia (probably the best thing is to annotate to just Hyperreflexia, https://hpo.jax.org/app/browse/term/HP:0001347).
