### ISSUE TITLE
Term Request: Bone fracture

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3889]
New term request: Bone fracture. Definition: \
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
adding as HP_0020110

**Comment by callahantiff** [comment]
Thanks for adding this @pnrobinson! Would this term be used to cover open fractures and closed fractures? If it's not obvious as to whether the fracture is the result of traumatic injury or a disease process, do you have recommendations for applying this term? Or, are the intentions to use it more generally?

**Comment by pnrobinson** [comment]
We can add subterms for specific fracture types if needed, .e., open fracture. At present though this is a grouping term but it can be used to describe a single fracture event.

**Comment by callahantiff** [comment]
OK, great! I am working on annotating this portion of our EHR now. I am happy to help suggest terms or provide a list of the fracture types observed in our patient population (or both).

**Comment by pnrobinson** [comment]
please provide suggestions as new terms. We can add them to the latest release before Friday

**Comment by callahantiff** [comment]
OK, no problem 😃. I will get started on the new term requests tomorrow.

**Comment by callahantiff** [comment]
@pnrobinson, I'm sorry for the delay and for this long message. I figured it would be best to continue this conversation here before opening additional issues.
______
**Existing Terms** 
There currently are 15 "fracture" classes that are primarily organized under two different ancestor classes, listed below.
 
**Abnormality of skeletal morphology**
- Pseudo-fractures
- Multiple rib fractures
- Vertebral compression fractures
- Corner fracture of metaphysis
- Femur fracture

**Abnormality of skeletal physiology**
- Bone fracture
- Increased susceptibility to fractures
  - Bowing of limbs due to multiple fractures
  - Multiple prenatal fractures
  - Painless fractures due to injury
  - Pathologic fracture
  - Recurrent fractures
    - Fractures of the long bones
      - Fractured ulna
      - Fracturer radius
 
- [ ] **Bone fracture** was added as a new term and that it currently has no children. I’m curious if you plan to connect the fracture terms to the Bone fracture class?
______
**Adding New Terms** 
-  [ ] With respect to adding new terms, I wanted to ask how specific or detailed you would like HPO's representation of fractures to be? I think there is great potential to create a really rich representation and I could make a good first attempt using the patient data I have.

I spent sometime thinking through and researching this and propose that we could use the [AO/OTA Fracture Classification](https://www.aofoundation.org/Structure/resource/AO-OTA-Fracture-Dislocation-Classification/Pages/fracture-classification.aspx) system (download [here](https://classification.aoeducation.org/files/download/AOOTA_Classification_2018_Compendium.pdf))  as this seems to be the primary gold standard for fracture classification. I also think this system would work well with how the HPO is structured.

The classification system organizes fractures by localization and morphology (pgs. S4-S9; screenshot below).

![image](https://user-images.githubusercontent.com/8030363/56979721-b379fb80-6b37-11e9-87b4-3f1b9b13daa1.png)
 
For example, "closed fracture of anatomical neck of proximal right humerus" would be represented as:

Classification | Term
:--: | --
Bone | Humerus
Location | Proximal end segment
Type | Extraarticular, unifocal, 2-part fracture
Group | Surgical neck fracture
Subgroup | Simple fracture
 
If we go down that path, I have plenty of examples from my data to create a solid representation: **1,465 unique fracture-related diagnoses spanning >140 different bone/fracture locations**. I already started mapping the bones and locations to the HPO, which is fairly painless. If you don’t like this approach a much simpler one could be applied using the primary fracture patterns (e.g. closed, open, commented, compression, etc…).
______
Before I went any further down the rabbit hole, I wanted to run this by you and see what you thought. If you like this idea I am happy to work through the details of how it could be mapped to the HPO.

Bringing in @nicolevasilevsky

**Comment by callahantiff** [comment]
Here is the [spreadsheet](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit?usp=sharing) where I have been working on mapping these terms.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I just talked to Tiffany about these terms, seems like she has a good plan to add about 140 new HPO terms that she could use to annotate over 1400 data points from EHR data.

I think we could possibly come up with DOSDP patterns for these terms, and add them more quickly than manually adding them in Protege (if this plan sounds okay to you.)

**Comment by pnrobinson** [comment]
Sorry for the delay in answering. I think that the DOSDP idea sounds great; can we try this for a few examples and see where we are?

**Comment by callahantiff** [comment]
> Sorry for the delay in answering. I think that the DOSDP idea sounds great; can we try this for a few examples and see where we are?

@pnrobinson - Absolutely! I will work up a few specific examples this weekend. Do you prefer that I post them here or submit each one as separate NTRs?

**Comment by nicolevasilevsky** [comment]
@callahantiff let me know if you would like any help

**Comment by callahantiff** [comment]
> @callahantiff let me know if you would like any help

@nicolevasilevsky - that would actually be great!

This classification system is awesome, but a bit complicated to do correctly (at first). I'd like to think through some heuristics that help with _consistency_. Perhaps we could talk through a few DOSDPs together?

**Comment by nicolevasilevsky** [comment]
@callahantiff and are talking now: here is an example of a DOSDP to create bone fracture terms for various bones:
https://github.com/obophenotype/upheno/pull/498

For the other terms, they may be too complex to add logical definitions, but we could create patterns to create the label, synonyms and definitions, such as this pattern for closed fractures:

**pattern_name: abnormalClosedFractureOfAnatomicalEntity**
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalClosedFractureOfAnatomicalEntity.yaml
description: "An abnormal closed fracture in an anatomical entity, like a closed distal femur fracture."

contributors:
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0002-8169-9049

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "closed %s fracture"
  vars:
   - anatomical_entity

annotations:
  - annotationProperty: exact_synonym
    text: "closed frature of %s"
    vars:
     - anatomical_entity     

def:
  text: "A closed fracture of the %s."
  vars:
    - anatomical_entity

**Comment by callahantiff** [comment]
@pnrobinson - here are the high-level sub-categories that @nicolevasilevsky and I discussed including bone fracture DOSDPs for:

Fracture Pattern | Soft-tissue involvement | Displacement | Fragments | Mechanism
-- | -- | -- | -- | --
Linear fracture | Closed | Non-Displaced | Incomplete | Pathological
Transverse fracture | Open | Displaced | Complete | Stress
Oblique fracture |   | Malunion | Comminuted | Traumatic
Spiral fracture |   | Nonunion |   | Periprosthetic
Compression fracture/wedge fracture |   |   |   |  
Impacted fracture |   |   |   |  
Avulsion fracture |   |   |   |

**Comment by pnrobinson** [comment]
Thanks! How are we thinking of handling these combinatorics? That would be 7*2*4*3*4*n_bones terms...

**Comment by callahantiff** [comment]
> Thanks! How are we thinking of handling these combinatorics? That would be 7_2_4_3_4*n_bones terms...

That's a very fair question. One thought was to treat these particular terms as clinical modifiers. I could see that being useful for the Mechanisms, as those could also generalize to things besides bone fractures (e.g. sprains). That said, I don't think the other categories could easily generalize outside of fractures.

**Comment by pnrobinson** [comment]
So the terms would involve the fracture patterns or should that also be a modifier? Can we do this for one bone and the decide where to go?

**Comment by dosumis** [comment]
Wondering on how we could get moving on this.

Expanding on Nicole's suggestion, we might include fracture types in  PATO:  

fractured
   .  fractured, transverse
   .  fractured, impacted

(Might be more hierarchy here e.g. a grouping of simple fracture types?)

Bones and locations within them: Uberon.  It looks like Uberon  has pretty good coverage of [zones/regions for bones](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http://purl.obolibrary.org/obo/UBERON_0005913) and I'm sure could be extended to add any missing (or we may be  able  to refer  to some compositionally).

=> 
Avulsion fracture of medial epicondyle of humerus
Q:fractured, avulsion
E: epicondyle of humerus (UBERON:0016497)

It looks like this would cover most in @callahantiff's [spreadsheet](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=815709866).

I guess  if we just made the ones in the table we don't have to worry about combinatorial explosion?

Supporting the greater detail in some of the tables above would require more discussion. 

Would the following be sufficient for now?

 - Add major fracture types to PATO
 - make basic set of DOSDPs
 - convert spreadsheet into DOSDP tsv table (with appropriate mappings to Uberon & PATO)
 - generate terms

**Comment by nicolevasilevsky** [comment]
Per a discussion with @pnrobinson and @LCCarmody yesterday, we agree with your suggestion above @dosumis, thanks!

We thought we could create a pattern for fractures in various bones. @pnrobinson said he could  make new terms in HPO under clinical modifier:
-fracture modifier
  -Soft-tissue involvement, etc
  -Displacement, etc
  -Fragments, etc
  -Mechanism, etc

As a next step, I'll create a ticket and do a PR in PATO for the fracture terms that David mentioned above:
fractured
. fractured, transverse
. fractured, impacted
. etc

**Comment by nicolevasilevsky** [comment]
I created a PR for a 'fractured' pattern in uPheno: https://github.com/obophenotype/upheno/pull/695

**Comment by nicolevasilevsky** [comment]
@callahantiff we are moving forward with adding the fracture classes to HPO.
I created a tab in your spreadsheet [here](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=510110305) with the PATO fracture terms and the corresponding Uberon terms. 

It's probably easiest to discuss this on a call - could we meet sometime soon?

Just so I remember what I did, I will write it here:
- I looked at all the concepts in [fracture concepts tab](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=0), and then created a new tab, to sort these
- In [Fracture Concepts_NV_Sorted](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=1472378467), I sorted on Uberon ID (column C) and Fracture Pattern (Column E) and added those to the [DOSDP tab](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=510110305)
- Nico is going to test adding these to HPO

My question for @callahantiff- there are only 8 terms that are specific types of fractures (using 2 PATO terms that are children of fractured), but above you had 7 different subtypes of 'fractured'. Did you not see any data in the EHRs with other fracture types, like spiral fracture, etc.?

Are these the only terms we need (for now)?

**Comment by callahantiff** [comment]
@nicolevasilevsky - Sounds great for moving forward.

There should be more fracture types than 2 in our data, I have not yet finished mapping the fracture pattern type to each code. Maybe we can talk about this during our meeting too, some of the codes were not super straightforward to map to fracture patterns (at least that's what I remember when doing this a few months ago).

**Comment by matentzn** [comment]
For those interested, @nicolevasilevsky and I made a first stab at the fractured classes here:

https://ci.monarchinitiative.org/view/pipelines/job/hpo-pipeline-dev2/41/

For a classified view, download the file `hp-full.owl` (not: hp.owl).

The actual basis (source table) for the fracture hierarchy can be found here:
https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=510110305

Note that by convention, upheno patterns generate lower case names, so this will have to be corrected for the final version.

You can search for, say, `fractured epiphysis` and browse a bit up and down the hierarchy to get a sense:

![image](https://user-images.githubusercontent.com/7070631/81419563-1fce0880-9157-11ea-84a7-fb01c0bcd508.png)

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @callahantiff on the spreadsheet there was an example of a fractured tibia and femur. Do we want to create an HPO term that uses both bones? Or someone could use the two individual terms in annotations. (Because a person could have all kinds of fractured bones at the same time, right? So we don't want to create combinations of all the possible fractures, I assume. But maybe this is relatively common, so maybe we do want to add this example?)
Thanks!

**Comment by pnrobinson** [comment]
@nicolevasilevsky  I would say one bone at a time, and annotators would use multiple
 terms if a patient was unlikely enough to break multiple bones!

**Comment by nicolevasilevsky** [comment]
sounds good! 

Unlikely, or unlucky!

**Comment by callahantiff** [comment]
> @nicolevasilevsky I would say one bone at a time, and annotators would use multiple
> terms if a patient was unlikely enough to break multiple bones!

This approach makes sense to me!

**Comment by nicolevasilevsky** [comment]
Thanks @matentzn, this is a great first pass!

there are some existing fracture terms in HPO, so we'll need to update these with the new pattern.

I spotted one minor issue:
We have the term HP_0100168 'Fragmented epiphyses' which is defined as Fragmented appearance of the epiphyses and has the logical def:
'has part' some 
    (broken
     and ('inheres in' some epiphysis)
     and ('has modifier' some abnormal))

I think this logical def is wrong. @pnrobinson do you mind if I remove it?

Thanks!

**Comment by pnrobinson** [comment]
Let's revise this term and provide a better definition. The log def looks wrong!

**Comment by nicolevasilevsky** [comment]
It looks like there are a bunch of 'fragmented' terms that are children. Maybe the best approach is to request a 'fragmented' quality from PATO, and then we can update these.

**Comment by nicolevasilevsky** [comment]
Actually, looks like 'fragmented' is a synonym for shattered, which is in PATO (PATO_0002081):
https://www.merriam-webster.com/dictionary/fragmented

I'll add fragmented as a synonym to shattered.

@pnrobinson are you okay with using 'shattered' in the logical def for HP_0100168 'Fragmented epiphyses' and its children?

**Comment by pnrobinson** [comment]
I know that according to the dictionary they can be synonymous, but in this context we do not mean shattered (the result of violence), instead we mean "existing or functioning as though broken into separate parts; disorganized; disunified:" 
So I think for medical use PATO needs to be modified!

**Comment by nicolevasilevsky** [comment]
Sounds good! It should probably be a new term request to PATO then, I'll work on this.

**Comment by pnrobinson** [comment]
terms added!

**Comment by callahantiff** [comment]
Thank you all so much for adding these! I am incorporating them into OMOP2OBO today!
