### ISSUE TITLE
NTR: Infective Exacerbation of bronchiectasis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#3908]
New term request: Infective Exacerbation of bronchiectasis. Definition: \
Source: \
Parent: \
Disease association:

**Comment by pnrobinson** [comment]
@cmungall @nicolevasilevsky @LCCarmody @mellybelly @kingmanzhang 

This is probably best categorized as a disease. It also raises an important modelling question of how to represent a disease that can only occur in the presence of a phenotypic abnormality (bronchiectasis) -- that could also be regarded as a disease (it is a feature of many other diseases and is a valid HPO term though). 
Basically, bronchiectasis (https://www.verywellhealth.com/definition-of-bronchiectasis-2249062) can be colonized by some infectious agent. We will also need a strategy for how to categorize according to infectious agent using some sort of a slot.

Do we have a google doc for open items in MONDO?
In any case, I am closing this here, it should not be an HPO term.

**Comment by nicolevasilevsky** [comment]
@pnrobinson we just track all the open issues for MONDO on the tracker.

In case others don't know what this term means (like me) - I think it means it is a flare up of bronchiectasis due to an infection.

Here is a paper: https://www.ncbi.nlm.nih.gov/pubmed/28236369

@cmungall would we want to add this to MONDO as a child of MONDO_0005550 'infectious disease'

bronchiectasis is a disease in MONDO too (MONDO_0004822)
