### ISSUE TITLE
Painful sensory neuropathy

### ISSUE THREAD

**Issue by andrewdevereau** [obophenotype/human-phenotype-ontology#3989]
submitted on behalf of David Bennett, Professor of neurology and neurobiology, Nuffield department of clinical neurosciences, Uni. of Oxford

_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Painful sensory neuropathy

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Chronic neuropathic pain that is caused by a sensory neuropathy. Sensory neuropathy is defined as peripheral neuropathy (general term for any disorder of the peripheral nervous system) affecting the sensory nerves.

### 4. Parent term (use [HPO Browser](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) or [OLS](http://www.ebi.ac.uk/ols/ontologies/hp))
Sensory neuropathy HP:0000763

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Closest terms on Orphanet : Hereditary sensory and autonomic neuropathy Types 1-8

### 6. Your nano-attribution (ORCID-id or label, e.g. _HPO:probinson_ (organization:name))
https://orcid.org/0000-0002-1089-1543

**Comment by pnrobinson** [comment]
I think that this is more of an inference than a phenotypic observation. See " identification of neuropathic pain is hard. Few, if any, objective signs are present. Examiners have to decipher and interpret a collection of words that patients use to describe their pain. Patients may describe their symptoms as sharp, dull, hot, cold, sensitive, itchy, deep, stinging, burning, or some other descriptor. Additionally, some patients may feel pain with a light touch or pressure." from https://www.medicinenet.com/neuropathic_pain_nerve_pain/article.htm#what_are_the_signs_and_symptoms_of_neuropathic_pain. 
The problem is that if we bake this into the HPO, that is all we can get out. So we should try to code the actual observations and then let clinicians (and possibly algorithms) work on the inferences. 

The peripheral neuropathy section of the HPO needs some work in general.
