### ISSUE TITLE
Reduced erythrocyte adenosine deaminase activity 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#400]
Need new term
http://omim.org/clinicalSynopsis/102700?search=adenosine%20deaminase&highlight=deaminase%20adenosine

Reported by: pnrobinson

Original Ticket: [obo/human-phenotype-requests/400](https://sourceforge.net/p/obo/human-phenotype-requests/400)

**Comment by callahantiff** [comment]
The linked OMIM term includes SCID as a result of reduced erythrocyte adenosine deaminase activity, but looking into HP_0030273 (which I think is the term that was created for this), I see no mention of SCID in the term description/synonyms. 

Does this term only represent reduced red cell adenosine deaminase activity? Or, does it also include the **Alternative titles; symbols**(i.e., SCID DUE TO ADA DEFICIENCY; ADA-SCID; SCID DUE TO ADA DEFICIENCY, EARLY-ONSET) and **Other entities represented in this entry** (i.e., SCID DUE TO ADA DEFICIENCY, DELAYED ONSET, INCLUDED; SCID DUE TO ADA DEFICIENCY, LATE-ONSET, INCLUDED; ADENOSINE DEAMINASE DEFICIENCY, PARTIAL, INCLUDED; PARTIAL ADA DEFICIENCY, INCLUDED) included in the OMIM entry?
