### ISSUE TITLE
Why obsoleted?

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4030]
Why is "Short curly eyelashes (HP:0007691)" obsoleted? 

Now a user has to create two annotations instead of one. What have we gained by making this obsoletion? From a practical point of view this is no good decision.

**Comment by pnrobinson** [comment]
This is considered a bundled term -- we are avoiding these!

**Comment by drseb** [comment]
Yes I know, but why? What is the reason for this decision?

**Comment by pnrobinson** [comment]
Some patients may have just curly, and others may have just short eyelashes, and bundling like this is something that should be avoided. See e.g. Elements of Morphology introduction.

**Comment by drseb** [comment]
_Note: This is just for brainstorming._ 

I don't see any logical reasons at the moment to not include such a term other than the fear to blow up the number of classes in HPO (which I doubt)

There are patients that have both and it seems that this happens multiple times. Disadvantages of current solution are:

- Users have annotate their data with two terms instead of just one
- You can't easily (!) query for all patients/diseases that have both abnormalities

The previous solution looked like this:

```
Abnormal eyelashes
 |_ Curly eyelashes
     |_ Short & curly eyelashes
 |_ Short eyelashes
     |_ Short & curly eyelashes

```

Advantage is, that the negative things mentioned above are not existing anymore. What are the disadvantages from your point of view. I mean there must be a better reasoning behind this than saying "_something that should be avoided_". 

As said before - I just want to get a better understanding and brainstorm a bit. Thanks, Seb

**Comment by pnrobinson** [comment]
We decided to remove bundled terms many years ago according to this recommendation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2774524/
```
Bundling is a word we have used to describe a term that represents two or more component findings. 
The term “large nose” can serve as an example of a bundled term as the term comprises several 
distinct features: prominent nose; wide nasal ridge; prominent nasal tip; and broad nasal base. We 
have eliminated most bundled terms as they often include presumptions of pathogenesis or 
association, which may or may not be correct. Bundling is also problematic because it can obscure 
component abnormalities and if individuals are described using both the single bundled term and the 
component terms, it can lead to confusion. A number of terms have remained bundled, as we felt that 
the utility of the bundled term outweighed the potential pitfalls of bundling. 
If a term is considered to be bundled, this is mentioned in the definition and the individual components are indicated in the description.
```

We have kept some bundled terms such as Arachnodactyly since they are in such common clinical use.
In this case, there is no reason to believe that there is any particular connection between short and curly eyelashes, and there is no reason that we should offer this combination and not others such as
curly & prominent
Short & white
curly & trichiasis
sparse & curly 
multiple rows and short and curly ....

and so on. 


In terms of querying, the main problem is that some patients and diseases will be annotated to "Curly eyelashes" and "Short eyelashes" while others will be annotated to "Short & curly eyelashes", meaning that two queries (a simple one and a more complicated one) would be necessary to be sure you had found all patients or diseases with this combination.

**Comment by drseb** [comment]
Ok. I don't think this is the best decision, but the explanation makes sense. Thanks
