### ISSUE TITLE
are 'Joint hypermobility' and 'Joint hyperflexibility' distinct classes?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4035]
@GARDinfocenter requested adding the synonym 'joints move beyond expected range of motion' to HP_0005692 Joint hyperflexibility.

HP_0005692 Joint hyperflexibility. does not have a text definition, and when I googled it, it brings up results for joint hypermobility as well.

Are these terms maybe synonyms?

**Comment by GARDInfoCenter** [comment]
I consulted two of the medical geneticists with GARD and was told that although the two terms are often used interchangeably, "joint hyperflexibility" and "joint hypermobility" are not synonyms. Joint  hypermobility refers to joint mobility due to the tension in ligaments, whereas joint hyperflexibility refers to not only the joints but also the other tissues that can provide tension like the muscle. 

Hope this helps.
Maria

**Comment by nicolevasilevsky** [comment]
Thanks @GARDInfoCenter! I added a def to Joint hyperflexibility:
Increased mobility and flexibility in the joint due to the tension in tissues such as ligaments and muscles.
