### ISSUE TITLE
NTR: s/p transplant?

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4041]
_For new term requests, please provide us with the following information:_
@pnrobinson might it be appropriate to include a history of transplant (lung, liver, bone marrow) in a phenotypic description or do you have another recommendation on how to do that?

**Comment by pnrobinson** [comment]
@cmungall @drseb @mellybelly @matentzn @dosumis 
There are some general items in the past medical history like this that are used as phenotypic observations in the differential diagnosis. For instance if you are status post transplant you are on immunosuppresives and this can lead to secondary diseases. I am wondering if we should add this somewhere, either under "Constitutional symptom" or under "All" as a new subhierarchy. In the future we will use MONDO terms for the specifics of the PMH, but there are probably 100 items that we want to know about many of which are not MONDO-able.

**Comment by matentzn** [comment]
I have no answer, but it might be important. Is there no ontology out there with a serious attempt to cover those?

**Comment by pnrobinson** [comment]
Probably many individual terms are available in a variety of sources, but there is no way of computationally analyzing specifically the PMH  right now.

**Comment by pnrobinson** [comment]
I am adding the term as HP_0032443. I am also moving the Family History term to be a child of this new term.
@drseb @cmungall @mellybelly this will be important for precision medicine endeavours!
def:In a medical encounter, the physician generally will interview the patient about his or her current problem, and may perform additional testing. The past medical history (PMH) in contrast records information about the patient's medical, personal and family history that might be relevant to the presenting illness or to provide optimal clinical management. The PMH generally includes (if relevant) other major illnesses, hospitalizations, surgeries, injuries, allergies, gynecologic and obstetric history, family history, personal history including occupational history, alcohol and drug use, etc.
comment: This subontology of the HPO is not intended to provide all needed terms to describe the past medical history, but rather to be combined with other ontologies such as MONDO in order to capture information that is often needed to properly assess phenotypic findings related to a presenting medical problem.

**Comment by pnrobinson** [comment]
added s/p transplant as Status post organ transplantation
HP_0032444

**Comment by callahantiff** [comment]
Sorry, I know you closed this, but I had something I was hoping to run by you. I have several types of organ transplants in my database as well as associated issues transplantation. Would all of those terms then mapped to this term? Or, would it be worth further discussion?

**Comment by pnrobinson** [comment]
It is never a problem to reopen an issue. In this case, we are planning on a relatively small ontology for the past medical history but could probably have terms for the major transplants, heart, lung, liver, kidney etc.

**Comment by callahantiff** [comment]
OK, wonderful! Would it be helpful/useful if I compiled a list of terms that I have (with at least 1 patient)?
