### ISSUE TITLE
NTR: Granuloma

### ISSUE THREAD

**Issue by MorganSimiluk** [obophenotype/human-phenotype-ontology#4045]
_For new term requests, please provide us with the following information:_
### 1. Preferred term label
Granuloma

### 2. Synonyms
Granulomatous lesion.

### 3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
a mass of granulation tissue, typically produced in response to infection, inflammation, or the presence of a foreign substance.

### 5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
Chronic granulomatous disease

**Comment by pnrobinson** [comment]
It is not obvious where to place this on our current hierarchy because a granuloma can occur nearly anywhere in the body. It is also not "abnormal" immune system physiology (as is the term granulomatous inflammation in MP, which indicates "too much" granuloma formation). I imagine we should probably put this as an abnormal immune morphology. Children, such as liver granuloma can go there and also in their respective organ systems. Because a granuloma needs to be distinguished from an execessive granulomatous response, I would put granuloma under morphology and excessive granuloma formation under physiology. @mellybelly @drseb @cmungall  does this make sense?

**Comment by pnrobinson** [comment]
added. I think this is an Abn immune system morphology -- even if it can be a normal response to an infection we can consider it as abnormal for the time it is present.
