### ISSUE TITLE
Questions about CD marker phenotypes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4112]
- [ ] How should I annotate CD30 Ag presence? According to this [article](https://www.ncbi.nlm.nih.gov/pubmed/12826883), this marker is used to characterize lymphomatoid papulosis and anaplastic large cell lymphoma but can also be found in nonneoplastic skin disorders. 
- [ ] CD15 is a marker for Hodkin lymphoma, should I annotate this code as "hodgkin lymphoma? _add as specific cell surface marker_
- [ ] CD16 is a marker for NK cells and macrophages (see http://www.pathologyoutlines.com/topic/cdmarkerscd16.html). Should we create a new term that includes both those cell types? I don't think we can annotate a LOINC code with more than one term.

**Comment by nicolevasilevsky** [comment]
- [ ] CD56 is a marker for NK cells, we have 'Abnormal natural killer subset distribution', can I add increased natural killer subset distribution?

**Comment by pnrobinson** [comment]
I do not think we can use terms such as CD30 Ag presence, because this only makes sense in a certain context, and so we would need to specify the affected tissue or cell etc. And thus in some situations it is a normal finding and in other situations it is an abnormal finding. At least for the various WBCs, we should soon have abnormal proportion of X terms that will partially reflect the CD status, and so I would say that for now this is sufficient. For something like a tumor that is characterized by some CD, we should probably just note that in the comment section!
