### ISSUE TITLE
NTR: Abnormal and increased dendritic cell count

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4113]
## label:
Abnormal dendritic cell count
- increased dendritic cell count

## parent:
HP_0012310 'Abnormal monocyte count'

## def:
An abnormal number of dendritic cells in the blood or tissue.
An increased number of dendritic cells in the blood or tissue.

## synonym:
Abnormal DC count
- increased DC count

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/15795906

**Comment by pnrobinson** [comment]
Note that there are multiple classes of dendritic cell and not all of them develop from monocytes. Also, we should not use a subclass related just because one cell develops from another. I think we need to figure out what kinds of dendritic cell (follicular, sentinel and subtypes) we want to include here, and also note that we usually cannot or do not measure tissue counts.

**Comment by pnrobinson** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/28781372
https://www.ncbi.nlm.nih.gov/pubmed/18502722

**Comment by pnrobinson** [comment]
@MorganSimuluk sorry, still having difficult with this term. Do we mean the kind of circulating DCs as in this publication? What is the best definition?
http://www.jimmunol.org/content/early/2019/03/29/jimmunol.1900046

**Comment by pnrobinson** [comment]
Adding as HP_0020178
