### ISSUE TITLE
HP:0045013 *Decreased urinary glucose concentration*

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#4209]
Is it really a medical abnormality ?

**Comment by drseb** [comment]
Hmm. Strange... obsolete?

**Comment by sbello** [comment]
MGI has 3 annotations to the related term in the MP http://www.informatics.jax.org/mp/annotations/MP:0003870 so there may be some medical or at least physiological relevance.

**Comment by kingmanzhang** [comment]
@drseb It is not obsolete. @sbello That's interesting to know.

**Comment by drseb** [comment]
@kingmanzhang : I meant to ask if we should obsolete it. 

I haven't found any human data where this class is used. So I was suggesting to obsolete it. But with Sue's comment I am not sure.

**Comment by kingmanzhang** [comment]
@drseb Got you. I am not sure either. Maybe leave it as is.

**Comment by pnrobinson** [comment]
I suspect that the MP annotations are incorrect -- normally, the urine has no glucose (the kidneys do their best to reabsorb it because glucose is energy!). In any case, I think that this is not a correct phenotype in humans, see also this: https://en.wikipedia.org/wiki/Glycosuria
So I would vote to obsolete this term and I would think that MP should check whether it is also the case that the mouse kidney completely reabsorbs glucose under normal conditions (I would be surprised if this is not true). @sbello

**Comment by drseb** [comment]
agree. let's obsolete.
