### ISSUE TITLE
GJB2 and OMIM:304400

### ISSUE THREAD

**Issue by rfvqwas** [obophenotype/human-phenotype-ontology#4227]
I want to ask about the evidence of relation between the gene GJB2 and OMIM:304400.

GJB2 is on chr13, but the disease OMIM:304400 is X-linked recessive inheritance. This makes me very confused. And there is no such evidence on omim.

**Comment by drseb** [comment]
This stems from medgen and looks indeed suspicious. We will investigate.

@pnrobinson

**Comment by rfvqwas** [comment]
Thanks

**Comment by drseb** [comment]
This is the source: https://www.ncbi.nlm.nih.gov/medgen/336750

Will contact them and ask for the reason for that association. Thanks!

**Comment by pnrobinson** [comment]
The medgen entry appears to be a mistake.

**Comment by drseb** [comment]
I wrote their support team and will let you know their reply here.

**Comment by drseb** [comment]
@rfvqwas thanks for bringing this up. This will be fixed by clinvar and be visible in their files later this week. It will take a while until this is fixed on our side. First I have to do a new release and then the website has to be updated as well. I expect this to be visible during November. 

Thanks so much for reporting this!
