### ISSUE TITLE
Add lay synonym "tired all the time" to Episodic fatigue (HP:0012431)

### ISSUE THREAD

**Issue by kshefchek** [obophenotype/human-phenotype-ontology#4244]
Possibly also for fatigue and subclasses:
- no energy
- exhausted
- drained
- worn out
- wiped out

**Comment by pnrobinson** [comment]
all the time is different from episodic!
I think that the above words might be used in many different contexts that have nothing to do with fatigue, e.g., I am completely wiped out after having worked out for two hours at the gym. I am completely exhausted after taking the SATs. I think that a lay person would understand episodic fatigue, so for now I would not add these synonyms.

**Comment by pnrobinson** [comment]
This is a difficult topic, but I would suggest that we need to balance false positive and false negative rates with everything we do. Currently the HPO itself is way over on the side of avoiding false positive inferences, and I think this is appropriate for medical usage. I think we should have more conversations about this, but I think it is a bad idea to incorporate uncertainty into the HPO resources by design!
