### ISSUE TITLE
Terminology for increased antibody levels

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4262]
We  have the suggestion Increased IgG -- monoclonal and oligoclonal/polyclonal.
Is monoclonal synonymous with "Monoclonal gammopathy" Can we review the terminology please?

**Comment by mh11** [comment]
I think we need increased IgG polycloncal
IgG oligoclonal (2 or more bands but not polycloncal)
Increased IgG monoclonal (in adults this is usually caused by myeloma or  considered MGUS (monoclonal gammapathy of uncertain significance) but in children is not so my concern with using monoclonal gammapathy for this is that people will think MGUS/mylemoa which may not be true for either he adult or paediatric patients
(Posted on behalf of Kimberly)

**Comment by pnrobinson** [comment]
reply from Kimberly Gilmour (GOSH)
    I think we need increased IgG polycloncal
    IgG oligoclonal (2 or more bands but not polycloncal)
    Increased IgG monoclonal (in adults this is usually caused by myeloma or  considered MGUS (monoclonal gammapathy of uncertain significance) but in children is not so my concern with using monoclonal gammapathy for this is that people will think MGUS/mylemoa which may not be true for either he adult or paediatric patients

**Comment by pnrobinson** [comment]
@mh11 
Thanks!
One more question:
In cases of monoclonal gammopathy, the abnormal cell(s) may produce an intact immunoglobulin, free light chains without heavy chains (often both intact and free), and rarely only heavy chains. 
Do we want to have something like this?
```
Monoclonal elevation of IgG
-Monoclonal elevation of intact IgG
-Monoclonal elevation of IgG light chain
---Monoclonal elevation of IgG kappa chain
---Monoclonal elevation of IgG lambda chain
-Monoclonal elevation of IgG heavy chain
```
I will also add ``Oligoclonal elevation of IgG`` and ``Polyclonal elevation of IgG``

**Comment by pnrobinson** [comment]
@mh11 any update on this?

**Comment by mh11** [comment]
Apologies for the delay @pnrobinson 
The answer is - yes, the described tree makes sense.

**Comment by pnrobinson** [comment]
done
