### ISSUE TITLE
HP:0031988 ‘muscle spasm’ - typo in def and possible term duplication

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/human-phenotype-ontology#4267]
Hi,

While working on https://github.com/EBISPOT/efo/issues/291, I noticed that 
- [x] HP:0031988 ‘muscle spasm’ has a typo in its definition (http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0031988); 
- [ ] Also, in HP there’s a term NBO:0000588 ‘spasm’, but I believe all spasms are muscle spasms, so you might want to consider merging HP:0031988 and NBO:0000588 if they are the same, or revising one of the two terms if they are indeed different?

Thanks,

Paola Roncaglia (EFO editor)
ORCID iD: https://orcid.org/0000-0002-2825-0621

**Comment by pnrobinson** [comment]
The definition indeed has a typo
A sudden **involutanry** contraction of a muscle or group of muscles.
The NBO term is from one of the ontologies used for the logical definitions of HPO terms and thus is not a duplicate. One can have spasms in skeletal muscle but also in smoth musculature, e.g., Esophageal spasm. THe HPO term definition should state that we are talking about skeletal muscle. I will try to find a more precise definition.

**Comment by pnrobinson** [comment]
A more important issue is that muscle spasm and muscle cramp are probably best viewed as synonyms, even though muscle cramp is often used in a vague way in everyday parlance:
http://www.healthofchildren.com/M/Muscle-Spasms-and-Cramps.html

**Comment by pnrobinson** [comment]
The NBO term 'spasm' (NBO_0000588) is not being used to define anything in the HPO, and so it is just present in the hpo-edit.owl file and does not get exported to the obo file. I do not think it is causing any downstream problems, and in general I do not think that NBO is very useful for what we want to do, although I believe it is being used as a 1-1 bridge between some HP and MB terms, which is something akin to abuse of notation. @drseb @cmungall is there any chance we can get rid of the NBO import any time soon?

I will leave this issue open for a bit, but if nobody shouts I will merge muscle cramp and muscle spasm and try to explain the vague usage of the word cramp (which would be listed as a RELATED Lay Person synonym) in the comment.

**Comment by drseb** [comment]
@pnrobinson was the topic of behaviour discussed in the POTATO workshop? If all the other organisms are using NBO, it would not be in favour of removing NBO from HPO. 

@matentzn @dosumis

**Comment by matentzn** [comment]
@dosumis is putting together a taskforce to deal with this issue involving all the mods and HP to determine how to best deal with behavioral phenotypes. According to our current model, behaviours and behavioural phenotypes are NOT conceptually the same. I don't like that NBO, which is conceptually a species-neutral ontology of behaviours, ventures into the phenotype space: NBO:'behavioral phenotype' (the branch under which spasms and so on life) is conceptually overlapping with Upheno and HP and phenotypes should NOT be references as entities in EQ definitions (which they are right now, see [HP_0010529](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0010529) and many others). My feeling is that we will have to ditch references to NBO phenotypes altogether, and instead refer to the actual NBO behavioral processes in our EQ definitions (if they exist). Hopefully, there are not too many of those (less than 71 after a quick grep of HP). I agree with Sebastian that simply ditching NBO wont do if we want cross-species integration; But I also agree with Peter that NBO needs work. @dosumis has plans to renovate NBO over the next half year or so. 

We also need to revise the HP import mechanism soon, because you are now importing quite a lot of superfluous stuff from Upheno (which HP all by itself does not need). 

We will have species neutral classes for everything in Upheno; but this wont help if we want to infer the classifications across species from the EQ. Anyways, lots of rambling, solution:

I propose to 
1) Create a preliminary pattern for behavioural phenotypes with Leigh (we could start doing that this week if we get the go-ahead). 
2) Extract the 71 or so EQs from HP that mention NBO terms, see whether they conform to the same pattern, and create instances for those.
3) Replace uses of NBO phenotypes with NBO processes where available, where not, continue to use the NBO phenotype **pretending it is a behaviour rather than a behavioural phenotype** (or, alternatively, drop the EQ, which I am not much in favour of) <- maybe this is bad, not sure @dosumis.
4) Get rid of some of the NBO overhead by adding ODK dynamic imports to the HP release cycle (Sebastian and I will do that in the next one or two weeks).

After this, HP should only ever have references to NBO when they refer to a behaviour (that is, a behavioural process, not a behavioral phenotype) inside of an EQ. Which is as it, IMHO, should be.

**Comment by pnrobinson** [comment]
@matentzn +1 this sounds like a very reasonable plan. Please note that we are probably going to have a workshop on behavior phenotypes in Cambridge (England) next year and it would be great if you could attend. There is no date yet, however.

**Comment by drseb** [comment]
Please include me in said workshop @pnrobinson

**Comment by pnrobinson** [comment]
sure!

**Comment by dosumis** [comment]
Me too.  We should see if it's possible to coordinate this with other
behaviour phenotype work.

**Comment by pnrobinson** [comment]
I will keep everybody updated on the behaviour workshop (I have not heard anything new). 
Another issue is that I think we need to merge muscle spasms and muscle cramps. @drseb will this create any issues for you. Please see above, this is a mistake.

**Comment by pnrobinson** [comment]
done
