### ISSUE TITLE
Broken xrefs in HP

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4276]
@cmungall ODK complaints about malformed xrefs in HP (probably imports?) and spits out this:
```
_:b0,PMID: 26295364
_:b1,""
_:b2, ISBN:0-7216-0179-0
_:b3,DOI: 10.1530/endoabs.44.EP82
_:b4,PMID: 3243933
```

How can we debug/interpret this?

**Comment by LCCarmody** [comment]
The PMIDs look like they have inappropriate spaces.  Not sure about the others.

**Comment by LCCarmody** [comment]
@matentzn 
I fixed the issues I could find, but I don't know what the issue is for ISBN:0-7216-0179-0 or "".  The command you gave me returned "hp-edit.owl:AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "ISBN:0-7216-0179-0") <http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/HP_0100607> "Pain during menstruation that interferes with daily activities.")

I don't see any leading/trailing spaces. I deleted it and added it back.

**Comment by pnrobinson** [comment]
In general, it will be easier for our users if we find XREFs to pubmed (or bettter PMC) articles rather than books. For Dysmenorrhea, we could cite this article:
https://www.ncbi.nlm.nih.gov/pubmed/15686299

**Comment by LCCarmody** [comment]
Okay. Swapped the ISBN reference for PMID.  The only one I did not fix was _:b1,""  as I don't know a way to identify that.

**Comment by matentzn** [comment]
Now there is only one broken xref left.

```
_:b1,""
```

**Comment by pnrobinson** [comment]
What term does this correspond to? @matentzn

**Comment by matentzn** [comment]
I have enlisted the help of someone at ROBOT to help us find that out; unfortunately I have no idea yet..

**Comment by drseb** [comment]
@matentzn 

`AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "") <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <http://purl.obolibrary.org/obo/HP_0004488> "Congenital macrocephaly")`

???

**Comment by matentzn** [comment]
Oh wow, yes, could be! Can you fix this? How did you find it?

**Comment by drseb** [comment]
`grep hasDbXref hp-edit.owl | grep \"\"`
