### ISSUE TITLE
HP_0011146 obsoleted but axioms still present

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4280]
@matentzn and I found HP_0011146 term. It is obsoleted, but still in the class hierarchy.

**Comment by drseb** [comment]
I can't confirm this. It is listed as alt_id, but there is no class with this ID anywhere else as in obsolete-list. Can you give more details?

**Comment by matentzn** [comment]
also, there are two id annotations and two labels.

**Comment by matentzn** [comment]
Oh, was this obsoleted in the last week? We havent merged back from master.

**Comment by drseb** [comment]
I don't know who obsoleted and when. It would be great if protege would store a obsoletion-history, i.e. add the user and the timestamp. Can we request this at Protege-repo?

**Comment by balhoff** [comment]
I don't think there is any need for HP to import DOID. See this open issue: https://github.com/obophenotype/human-phenotype-ontology/issues/3540

**Comment by drseb** [comment]
I don't see any imports in https://raw.githubusercontent.com/obophenotype/upheno/master/imports/doid_import.owl

Am I looking in the wrong place?

**Comment by matentzn** [comment]
Wait guys.. I will send you the hole analysis later :P The new release pipeline creates fresh versions of the imports each time. This import you are referring to seb is very very old; DOID has changed a lot since then. Unfortunately, it is not as easy as jim suggests though: while there are only 4 definitions with DOID references, we seem to get at the moment our NCIt content from DOID as well. Let me work on that for a bit. No actions required at the moment! I will create a new better ticket later today.

**Comment by pnrobinson** [comment]
We should definitely not have DO for HP definitions --
