### ISSUE TITLE
Abnormality of ganglioside metabolism

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4315]
I think the main abnormality is accumulation of gangliosides in tissue. We should therefore rename this term and provide a more precise definition of exactly what is observed.

**Comment by LCCarmody** [comment]
Possible new label: Abnormal ganglioside metabolism and signaling?
Possible definition: The abnormal regulation, synthesis, and degradation of gangliosides. Defects in the lysosomal glycosidases or specific co-activators, result in accumulation of the substrates, such as glycosphingolipids, including gangliosides in GM1 gangliosidosis (Tay-Sachs disease) and GM2 gangliosidosis (Sandhoff disease).  Moreover, it has been proposed that Alzheimer’s disease is initiated by aggregation of amyloid-beta peptide caused by gangliosides. 

PMID: 21937853

**Comment by pnrobinson** [comment]
I think that the relevant phenotype is always ganglioside accumulation. I will change the name (which now fits into the new hierarchy) and adapt the above definition - thanks!
