### ISSUE TITLE
Current issues in odk-hp branch

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4326]
by "root class" I mean classes under owl:thing

- [ ] root class `amino acid chain` (PR) shall go somewhere else
- [ ] root class `disease` must go
- [ ] root PR classes floating around: PR_000003809, PR_000003918, PR_000003964, ...
- [ ] `trichofolliculoma` (MPATH) shall go under MPATH branch
- [ ] root class `subatomic particle` (CHEBI) shall go under CHEBI-branch
- [ ] UPHENO shall go if https://github.com/obophenotype/human-phenotype-ontology/issues/4325 is closed
- [ ] obsolete class references: CHEBI_48505, CHEBI_7805, GO_0033057, GO_0044702, GO_0044765

**Comment by matentzn** [comment]
by "root class" I mean classes under owl:thing

- [ ] root class `amino acid chain` (PR) shall go somewhere else
- [ ] root class `disease` must go
- [ ] root PR classes floating around: PR_000003809, PR_000003918, PR_000003964, ...
- [ ] `trichofolliculoma` (MPATH) shall go under MPATH branch
- [ ] root class `subatomic particle` (CHEBI) shall go under CHEBI-branch
  - subatomic particle is one of three root classes in CHEBI. Cant go away.
- [ ] UPHENO shall go if https://github.com/obophenotype/human-phenotype-ontology/issues/4325 is closed
- [ ] obsolete class references: CHEBI_48505, CHEBI_7805, GO_0033057, GO_0044702, GO_0044765
  - This will take a while to fix, too long to wait for it: All of these are embedded in some of our dependencies, in particular, NBO and CL. It will take a few months, but we have already started initiation the cleanup. They will eventually disappear.

**Comment by matentzn** [comment]
@drseb I committed new versions of imports. Can you check them again? Let me know what you think. If they are good enough, we can merge the imports alone into master (nothing else will be affected for now, just the imports).

**Comment by drseb** [comment]
looks good. I see a few GO classes floating around:

<img width="321" alt="screenshot 2019-02-01 at 12 06 52" src="https://user-images.githubusercontent.com/5172897/52119625-ea647200-2619-11e9-89f2-55a2eb9a5f3a.png">

**Comment by pnrobinson** [comment]
@drseb @matentzn How are we doing on this issue? Is it closeable?

**Comment by matentzn** [comment]
I have had some major [discussions](https://github.com/ontodev/robot/issues/456) about the remaining one issue, but I seem to have failed to make myself understood. The remaining issue that we have are obsolete class references of obsolete classes from other ontologies; it appears they are being pulled in whenever we use a their replacements (ex: chebi1 is obsolete, and replaced by chebi2. HP needs chebi2, chebi1 is pulled in as well). HP.obo is entirely unaffected by this. 

@drseb If this issue is important to you, shall we add a post-processing step that simply deletes all obsolete classes from other ontologies? Something like: make remove_obsoletes? The alternative is to simply ignore this issue, because it 1) it does not affect hp.obo and 2) there is some (very weak) sense to having them in. Let me know!

**Comment by drseb** [comment]
+1 to post-processing step

**Comment by drseb** [comment]
I think this is not an urgent matter and I don't really see a lot of obsolete classes anymore in protege. I will ask @matentzn if we see to many of these again.
