### ISSUE TITLE
NTR: Increased circulating alpha linolenate level

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4349]
NTR: Increased circulating alpha linolenate level
and decreased, abnormal

Parent: HP_0045016	Elevated Serum Long-Chain Fatty Acids

For LOINC code:
35164-3 Alpha linolenate (C18:3w3) [Moles/volume] in Serum or Plasma

**Comment by pnrobinson** [comment]
@nicolevasilevsky I think that this is not an endogenous metabolite. Does it really have a too high value? Or does its presence reflect ingestion of particular foods? i.e., is it bad to have an "increased amount"? I think that we may need to punt on many of the NTRs for LOINCs with the metabolic data, because we are not dealing with increased/decreased (abnormal), we are dealing with present/absent (reflective of diet)? Perhaps we need to make a new branch of HPO for these terms -- let's discuss the potential use cases. @nicolevasilevsky

**Comment by pnrobinson** [comment]
this is a trait (response to ingestion) and not an abnormality, we cannot annotate this in HPO currently.
