### ISSUE TITLE
NTR: Increased blood lead level

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4364]
**NTR:** Increased blood lead level

**Parent:**
HP_0410172 Blood xenobiotic

**For LOINC code:**
10368-9 Lead [Mass/volume] in Capillary blood

**Biocurator ID for loinc2hpo:**  UCDenver:tjcallahan

**Comment by pnrobinson** [comment]
This is not really a xenobiotic -- lead is not a "biotic". How should we categorise this? @cmungall @nicolevasilevsky @LCCarmody

**Comment by nicolevasilevsky** [comment]
The definition of xenobiotic from Chebi is:
A xenobiotic (Greek, xenos "foreign"; bios "life") is a compound that is foreign to a living organism. Principal xenobiotics include: drugs, carcinogens and various compounds that have been introduced into the environment by artificial means.

So seems like lead would fit under this def?

**Comment by pnrobinson** [comment]
Thanks, Nicole, I agree! I do not think I previously appreciated the full definition of xenobiotic, but I think this is 100% correct.

**Comment by nicolevasilevsky** [comment]
Cool - I can add this term :)

**Comment by cmungall** [comment]
Be careful using the role hierarchy in chebi - first, chebi don't model these as physical entities so this will cause issues where we use them in patterns where a physical entity is expected

also the role hierarchy is a bit odd and many structure-role associations are contextual rather than all-some
