### ISSUE TITLE
NTR: 3-Methylhistidinuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#4473]
**NTR:** 3-Methylhistidinuria

**Parent:**
NTR Abnormal urinary methylhistidine concentration (Issue #4470)

**For LOINC Code:**
28594-0 3-Methylhistidine/Creatinine [Ratio] in Urine

**Biocurator ID for loinc2hpo:** UCDenver:tjcallahan

**SOURCE:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1504145/

**Comment by nicolevasilevsky** [comment]
added
HP_0410317 'Increased urinary 3-methylhistidine'
HP_0410316 'Abnormal urinary 3-methylhistidine concentration'

(note, I added Abn urinary 1-methylhistidine and Abn urinary 3-methylhistidine as separate classes because CHEBI did not have a general methylhistidine class).

@callahantiff do we need Decreased urinary 3-methylhistidine too?

@drseb could you please MIREOT CHEBI:70959 - 3-methylhistidine

**Comment by callahantiff** [comment]
Yes, actually that would be good. Sorry I missed that, but it does seem that low levels of 3-methylhistidine in urine are clinically meaningful ([source])(https://www.sciencedirect.com/science/article/pii/0026049581900226).

**Comment by nicolevasilevsky** [comment]
Sounds good, I added HP_0410318 'Decreased urinary 3-methylhistidine'
