### ISSUE TITLE
Add loinc as xrefs

### ISSUE THREAD

**Issue by diatomsRcool** [obophenotype/human-phenotype-ontology#4580]
Can you please add the loinc mappings as xrefs in the hpo release pipeline? That way it will be easy to access via API. I would like to do this for my work with the NHLBI dataSTAGE project.
Thanks!

**Comment by pnrobinson** [comment]
Does this resource work for you?
https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation
I am not convinced that we should use xrefs, since the LOINC and HPO concepts are not referring to the same thing.

**Comment by diatomsRcool** [comment]
probably - can it be access via API?

**Comment by pnrobinson** [comment]
We could consider offering this as an API if there is a broad need, but perhaps it would be better to include it in biolink @cmungall . We are currently planning on adding this information to the HPO website as a tab called "tests" for individual HPO terms. There are probably many different ways of implementing an API, however, I am not sure that we want to offer a service that would translate FHIR messages into HPO codes because we do not want the general public using our website for data that might be considered PHI and we do not currently intend to set up a website with user validation etc. May I ask what your intended use case is?

**Comment by diatomsRcool** [comment]
This is for DataSTAGE. The use case is that someone is searching TOPMed data for studies that are relevant to diabetes (let's say). In addition to returning data tagged with diabetes, we also need to return data tagged with a measurement that is important for diabetes, such as blood glucose. The user may not search on blood glucose directly. Does that make sense?

**Comment by pnrobinson** [comment]
Sure. In this case I wonder if the best strategy would be to put these mappings into biolink so they can be used via API. @cmungall  if this is not a good idea please ping me. @diatomsRcool we can discuss how best to do this with our existing annotation files if it would be helpful, please ping me via email.
In any case I would like to not do this via the main ontology file, it is easier from a software engineering perspective to keep this data in a separate place. I hope this is ok!

**Comment by cmungall** [comment]
We can do the dipper route instead
