### ISSUE TITLE
Review Editor Docs

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4627]
- [X] Embedding images in GitHub Wiki
- [X] Add classes from external ontologies
- [X] Layperson synonym annotation: Best practices
- [X] Abbreviation synonym annotation
- [x] Term Obsoletion
- [x] Numerical synonyms
- [x] Release pipeline
- [x] Annotations
- [x] Keeping the OWL Top Level Clean
- [x] Running the Makefile
- [x] Design Patterns
- [ ] General-rules-for-design-patterns
- [ ] Design Patterns for Lab Values
- [ ] Movement
- [ ] Spectra and subclasses
- [ ] Restrictions for phenotype logical definitions
- [ ] Terms with identical logical definitions

**Comment by pnrobinson** [comment]
@drseb can you please review the Term Obsoletion page? I made a few minor changes to the text, but please check if you agree with the policy.

**Comment by pnrobinson** [comment]
- [ ] I do not understand the advice about Keeping the OWL Top Level Clean @matentzn could you check? What are the action items for curators?

**Comment by pnrobinson** [comment]
- [ ] @drseb @matentzn The Design Patterns might be partially obsolete now? I think it would be good to have recommended templates for English language definitions and comments that are more verbose than what we have in the yaml files. So that we define atrophy in a consistent way and provide more details for whatever the affected organ is. We should probably restrict this wiki to that and refer to the POTATO pages (?) for the design patterns?

**Comment by pnrobinson** [comment]
@drseb is the document about the release pipeline accurate? Does it belong here? If so can we add more details?

**Comment by matentzn** [comment]
'Keeping the top level clean' should probably be done by @drseb or me. Basically, we want to make sure that even when people open the full HP in Protege, they don't see 100 unrelated classes on the first level of the hierarchy, having to search for the HP phenotype branch. Note that if everything is normal, this should not happen; You will have a few branches say from GO and UBERON with classes that HP logical definitions refer to.

Another item that is missing on your list is 'Keep hp-edit.owl free of foreign axioms', where a foreign axiom is an axiom unrelated to HP (i.e. an axiom where no HP term is mentioned). This sometimes happens accidentally with Protege, but sometimes people do this kind of stuff intentionally, and it absolutely needs to be prohibited. For example, let's say you think that PATO morphology should be a subclass of PATO shape. Since the PATO maintainers don't agree with that 'worldview', you decide to just make it so in your ontology and add PATO morphology subclass of PATO shape to HP. This will break everything for all other ontologies. But as I said, this is mostly accidental. We started working on QC to identify such axioms.

A big change is coming on how logical definitions are curated across ontologies, using spreadsheets instead of Protege. We are in the process of rolling this out, but it will take a while. Once the process is established properly, I will edit the 'Maintain logical definitions' wiki page.

Regarding design patterns: I think it is still good to have a page on those, even though most of the stuff will be properly documented on uPheno! Maybe you will want to add things using patterns that are unrelated to EQ patterns for logical definitions; then you will have some patterns of your own!

**Comment by matentzn** [comment]
(I will help fleshing out the pages for the release pipeline as well, @LCCarmody just keep giving me nudges)

**Comment by drseb** [comment]
aren't the editor docs relatively clean now? can we close?

**Comment by LCCarmody** [comment]
No, but it is possible that some of the pages just need to be deleted. Specifically these pages:

  General-rules-for-design-patterns
  Design Patterns for Lab Values
  Movement
  Spectra and subclasses
  Restrictions for phenotype logical definitions
  Terms with identical logical definitions

And maybe @matentzn should just check this page to make sure it is okay?  THen I think we are done.
[Add new logical definitions to HPO using DOSDPs](https://github.com/obophenotype/human-phenotype-ontology/wiki/Add-new-logical-definitions-to-HPO-using-DOSDPs)

**Comment by matentzn** [comment]
@LCCarmody Looks exactly right! I guess we will clarify stuff incrementally while people are using these instructions.

**Comment by pnrobinson** [comment]
@LCCarmody  I am not sure if we can close this? The documentation probably still needs work but I am not sure if this issue has become stale?

**Comment by pnrobinson** [comment]
@LCCarmody  I would suggest we close this issue and if needed make individual issues for individual pages? Or are the open action items?
