### ISSUE TITLE
Check our current immune-related terms to annotate this disease

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4633]
https://omim.org/entry/245480

Can we annotate these features?

**Comment by nicolevasilevsky** [comment]
The terms we need are:

**Absent neutrophil lactoferrin**
**Parent:** 'Absent neutrophil specific granules'
**Text def:** The absence of lactoferrin in neutrophil granules, which could be caused by either an isolated failure of synthesis of this protein (or the production of an antigenically
unrecognizable form of lactoferrin) or a complete deficiency of specific granule production.
**Source:** PMID:6155073

 **Neutrophil nuclear clefts**
**Parent:** 'Abnormality of neutrophil morphology'
**Text def:**  An abnormality of the nucleus of neutrophils, which presents as either a type I nuclear cleft, where the nuclear cleft may show a transition into a round/oval shape. The second type nuclear cleft, which runs perpendicular to the nuclear surface, and this type of cleft might be related to nuclear lobe formation.
**Source:** PMID:3460353

**Low neutrophil alkaline phosphatase**
**Parent:** 'Low alkaline phosphatase'
**Text def:** An abnormally reduced level of alkaline phosphatase in neutrophils, which could be due to absence of enzyme or the production of defective enzyme.
**Source:** PMID:46759

 **Increased neutrophil mitochondria and ribosomes**
**Parent:** 'Abnormality of neutrophil morphology'
**Text def:** An increased numbers of ribosomes and mitochondria detected in neutrophils.
**Source:** PMID:6155073

@pnrobinson I can add these if this looks okay.

**Comment by pnrobinson** [comment]
@nicole -- these look great but the last term is bundled and we should have separate terms for mitochondria and for ribosomes. Also please add an etry to the annotation list that we do not forget to add these annotations after the next release! Thanks!

**Comment by nicolevasilevsky** [comment]
I added these terms. I don't know how to add entries to the annotation list though - where is that list?

**Comment by pnrobinson** [comment]
Thanks!
I usually make an issue like this:
https://github.com/monarch-initiative/hpo-annotation-data/issues/383
after adding terms to annotate a disease.
