### ISSUE TITLE
Conjunctival avascular cysts (filtering blebs)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#4746]
simulconsult

**Comment by pnrobinson** [comment]
@MIckeySegal -- do you mean the bleb that is created by glaucoma surgery? Current the HPO does not have surgical phenotypes but perhaps it is a good idea.
@matentzn @drseb @kingmanzhang @mellybelly @cmungall  -- should we had an annotation/tag to terms that are related to surgery (see the next to last picture here https://eyewiki.aao.org/Trabeculectomy for a related kind of conjunctival bleb). We might also introduce logical definitions that relate to surgery codes?

**Comment by MickeySegal** [comment]
What we have is from https://omim.org/entry/601552
"Some affected individuals develop highly unusual nontraumatic conjunctival cysts (filtering blebs), presumably caused by abnormal thinning of the sclera (Patel et al., 2014)."

https://omim.org/clinicalSynopsis/601552 refers to them as:
"Avascular conjunctival cystic elevations (filtering blebs)"

This doesn't sound surgical.

**Comment by pnrobinson** [comment]
Interesting -- I did not know about this. I will add this term, but we should still think about surgical phenotypes in the future!

**Comment by pnrobinson** [comment]
@MickeySegal adding as HP_0020125
