### ISSUE TITLE
congenital heart defect

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4835]
In a Kids First dataset, there is a description of 'congenital heart defect'. This is currently annotated this to Abnormal heart morphology.

Would we be willing to add congenital heart defect?

**Comment by pnrobinson** [comment]
I would say we should use the specific type of defect if available. We should use the age of onset (congenital) as a separate modifier. It does not make any sense to have a term called CHD in the HPO because there are hundreds of subtypes. We could consider rearranging the hierarchy of the HPO to reflect congenital developmental defects and the rest, this would require a concerted effort.
