### ISSUE TITLE
new cell terms for LOINC2HPO

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4843]
There are a lot of cell types detected in the blood in LOINC, do we want to create new terms for these?
- 42869-8 [CD138 cells/100 cells in Blood]
- Loinc: 14017-8 [CD22 cells/100 cells in Blood] 
- Loinc: 8126-5 [CD38 cells/100 cells in Blood] 
- Loinc: 8115-8 [CD16 cells/100 cells in Blood] 
- Loinc: 17177-7 [CD59 cells/100 cells in Blood]
- Loinc: 17175-1 [CD55 cells/100 cells in Blood] 
- Loinc: 18267-5 [CD16+CD56+ cells/100 cells in Blood] 
- Loinc: 17221-3 [CD235a cells/100 cells in Blood] 
- Loinc: 8136-4 [CD71 cells/100 cells in Blood]
- Loinc: 17183-5 [CD64 cells/100 cells in Blood] 
- Loinc: 17148-8 [CD41 cells/100 cells in Blood]
- Loinc: 17107-4 [CD117 cells/100 cells in Blood]
- Loinc: 17117-3 [CD15 cells/100 cells in Blood] 
- Loinc: 8109-1 [CD11c cells/100 cells in Blood]
- Loinc: 8111-7 [CD14 cells/100 cells in Blood] 
- Loinc: 8102-6 [CD33 cells/100 cells in Blood] 
- Loinc: 8110-9 [CD13 cells/100 cells in Blood] 
- Loinc: 8125-7 [CD34 cells/100 cells in Blood] 
- Loinc: 8133-1 [CD56 cells/100 cells in Blood]
- Loinc: 801-1 [Sickle cells [Presence] in Blood by Light microscopy]
- Loinc: 14018-6 [CD23 cells/100 cells in Blood]
- Loinc: 8118-2 [CD2 cells/100 cells in Blood] 
- Loinc: 8135-6 [CD7 cells/100 cells in Blood]
- Loinc: 8107-5 [CD10 cells/100 cells in Blood] 
- Loinc: 8132-3 [CD5 cells/100 cells in Blood] 
- Loinc: 8130-7 [CD45 (Lymphs) cells/100 cells in Blood]

**Comment by nicolevasilevsky** [comment]
@pnrobinson do you think we should add all these cell phenotypes to HPO or mark these unable to annotate in LOINIC2HPO?

**Comment by pnrobinson** [comment]
I think that for now we should not annotate these terms. These markers do not unambiguously determine a cell type, rather, it is the combination of markers that does, and the HPO has items such as "Increase Natrual Killer cell count" rather than these low level annotations.
If in the future we continue to work more with LOINC data, then we could expand the LOINC2HPO code in oder to combine cell types according to markers, but I am not sure this is really reliable or up to date, and expect that modern flow cytometry results would give us the combinations.
