### ISSUE TITLE
Term label obsoletion? Abnormal fucosylation of O-linked protein glycosylation (HP_0012359)

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#4866]
**HPO term**
 Abnormal fucosylation of O-linked protein glycosylation (HP_0012359)

**Suggested revision of label definition**
 "Abnormal O-linked protein fucose glycosylation' or Abnormal O-linked  protein fucosylation' 

This is not my area, but this term label is odd.  

Definition from X is "O-Linked fucose is an unusual form of glycosylation recently shown to modify the hydroxyls of serine or threonine residues at a strict consensus site within epidermal growth factor-like domains of several serum proteins." PMID: 9228088 

Is this the correct label?
@jpgourdine

**Comment by jpgourdine** [comment]
Hi lee,
Yes the definition is correct for O-fucosylation.
The hierarchy and labels will need to be discussed because it can lead to confusion between O-fucose and O-GalNA (majority of O-linked glycoproteins on which fucose residue may be added after). Beside, there are other O-linked glycoprotein (such as O-glucose, O-GlcNAc, and O-mannose)
JP

**Comment by LCCarmody** [comment]
Should we close this ticket and wait for an overall restructuring of these term labels?
