### ISSUE TITLE
Missing inference !!

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/human-phenotype-ontology#487]
Investigate why "Abnormality of depressor anguli oris muscle" is not inferred to be a subclass of "Abnormality of facial musculature"

Reported by: drseb

Original Ticket: [obo/human-phenotype-requests/487](https://sourceforge.net/p/obo/human-phenotype-requests/487)

**Comment by markengelstad** [comment]
I think i know.

A: Several new classes of "Abnormality of [facial muscle]" were added. 
B: Some of them were classified under a new class of "Abn of muscle of facial expression".  "Abnormality of depressor anguli oris muscle" was one of these. 
C: But the class "Abn of muscle of facial expression" was not given a logical definition, preventing the right inferencing. 

I think it was a mistake to classify these several muscles under the intervening class of "Abn of muscle of facial expression" rather than under "Abnormality of facial musculature", where they more appropriately belong for single asserted inheritance.     
Remedy: 
We should reclassify these as subclasses of "Abn of facial musculature". 

If we are interested in muscles of facial expression, it would be better to identify which abnormalities involve facial expression by use of inferernce/logical definition instead of asserted/ direct classification.

If you agree, i can do this. 

By the way, this is the same classification problem as for head and neck arteries.  We were classifying branches of arteries as subclasses of their arterial trunks.  For instance, "Abn of facial artery" subclass of "Abn of external carotid artery".  

This practice was also wrong.  "Abn of facial artery" should be direct subclass of "Abn of carotid arteries", which include all branches of the entire carotid arterial tree.  

This also needs to be changed back/ reverted. (only a few classes were affected) .

**Comment by drseb** [comment]
>A: Several new classes of "Abnormality of [facial muscle]" were added. 
>B: Some of them were classified under a new class of "Abn of muscle of facial expression". "Abnormality of depressor anguli oris muscle" was one of these. 
>C: But the class "Abn of muscle of facial expression" was not given a logical definition, preventing the right inferencing.

No this is a different issue. Protege is not inferring that *Abnormality of depressor anguli oris muscle* is a subclass of *Abnormality of facial musculature*. This is very mysterious, as UBERON correctly defines *depressor anguli oris muscle* as a subclass of *facial muscle* 

This can be a Protege-problem, an OWL-API-problem, or an ELK-problem. I will check later.

**Comment by cmungall** [comment]
I know what the problem is. I am going to blame this on Protege, because if I don't the blame falls on me.

I can see the problem easily because i have Protege configured to render 'obo foundry unique label' with precedence over 'rdfs:label':

```
'has part' some 
    ('quality (PATO)'
     and ('inheres in' some 'depressor anguli oris muscle')
     and ('has modifier' some abnormal))
```

```
'has part' some 
    (quality
     and ('inheres in part of' some 'facial muscle')
     and ('has modifier' some abnormal))
```

Yes, that's right. We have:

 * BFO:0000019 quality
 * PATO:0000001 quality -- obo foundry unique label: 'quality (PATO)'

We should always use the PATO one. I can look into removing the BFO class from the import chain (but may not be easy, as these things leak in easily from other ontologies)

**Comment by drseb** [comment]
Ah right. I am currently developing software for this. (I just forgot that I have stumbled upon this problem before).

Thanks Chris. That solves the problem.

**Comment by cmungall** [comment]
```
$ grep BFO_0000019 hp-edit.owl  | wc
      19     151    9192
```

here is the fix, if you date:
```
perl -pi -ne 's@BFO_0000019@PATO_0000001@' hp-edit.owl
```
