### ISSUE TITLE
revise label: 'Elevated alkaline phosphatase'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4909]
**HPO term**
'Elevated alkaline phosphatase'
'Low alkaline phosphatase'

**Suggested change**
these terms are children of 'Abnormality of alkaline phosphatase activity', so I think they should be revised to:
'Elevated alkaline phosphatase activity'
'Low alkaline phosphatase activity'

(the labels for the children should be revised as well)

**Comment by pnrobinson** [comment]
In this particular case, there are simply different methods of measuring the overall alk phos level. The biological/medical meaning is the same (i.e., there is less activity because there is less concentration). I believe that there are different ways of measuing alk phos, and one typically uses activity for the overall test and concentration of isozymes for the subtypes. I think it would be unnecessarily complicated to model this in detail and would likely just confuse users and have no big advantage, so I would close this for now?

**Comment by nicolevasilevsky** [comment]
Ok, let's close!
