### ISSUE TITLE
Disable sourceforge tracker

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#491]
Is there a way to disable the old [sourceforge tracker](https://sourceforge.net/p/obo/human-phenotype-requests/)? Or at least put a note there somewhere?
 
@cmungall  any ideas?

**Comment by cmungall** [comment]
It can be destroyed entirely, but nothing in between. No way to add a note AFAICT

**Comment by drseb** [comment]
Then I would suggest to delete it. Can you do that?

**Comment by cmungall** [comment]
Want to run them side by side a bit longer just to be paranoid?

How many distinct regular submitters do you have for sf? Have you already emailed them? It may be better to inform some after they post to sf rather than having some people go to the sf url and getting an error message and leaving confused...

**Comment by drseb** [comment]
Ok. You have a point.

I informed users on twitter and updated the links on the HPO website. But sure, waiting isn't a big problem. Should we then copy issues posted in future on sf to gh?

**Comment by cmungall** [comment]
the gosf2github.pl script can be run on arbitrary issues, so we could do 
that (but it may be fine to ask the person to manually redo the ticket, 
that way we properly track the submitter and can observe if there any 
obstacles to them using the new system)
