### ISSUE TITLE
Merge "Widening of the sacrosciatic notch"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#4935]
**HPO term**

"Widening of the sacrosciatic notch" and "Widened sacrosciatic notch"

related question: is there a difference between "sacrosciatic notch" and "greater sacrosciatic notch" ? 

**Reason for deprecation**

equivalent?

**Suggested replacement or term to consider**

**Comment by pnrobinson** [comment]
There is a greater and a lesser sacrosciatic notch.

Let me take a look at the annotations and try to figure out what is meant.
https://hpo.jax.org/app/browse/term/HP:0010456
https://hpo.jax.org/app/browse/term/HP:0008798

@drseb Can this be done after the release?

**Comment by pnrobinson** [comment]
Widened sacrosciatic notch is used for https://omim.org/entry/250220 only. 
This is not precise because there is a greater and a lesser notch. The OMIM entry does not go into detail. I think the annotation comes from https://www.ncbi.nlm.nih.gov/pubmed/15316973, and this also does not go into detail. I think they are referring to the greater notch. I am also unsure about the 'sacroilias notch' terms, this does not seem standard nomenclature. I will continue to investigate.
