### ISSUE TITLE
NTR: drug response terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#4968]
**Preferred term label:**
MONDO_0007348 Colchicine resistance
MONDO_0008697 'acetophenetidin sensitivity'
MONDO_0008906 Carbimazole sensitivity
MONDO_0012294 CYP2C19-related poor drug metabolism
MONDO_0012148 'drug metabolism, poor, CYP2D6-related'
MONDO_0014330 'eculizumab, poor response to'

See https://github.com/monarch-initiative/mondo/issues/860

I am going to obsolete these terms from Mondo. 
@pnrobinson do we want to add these terms to HPO? If yes, I can add them (or write up some definitions on this ticket).

(cc @cmungall )

**Comment by nicolevasilevsky** [comment]
@pnrobinson just checking in on this
these terms have been obsoleted from Mondo

**Comment by pnrobinson** [comment]
These are all not diseases. At least according to my definition of disease. I think these are more in scope of HPO. They would match with our new grant proposal actually. I tihnk we need to thhink harder about modelling though, because we (probably) do not want one term for X resistance (where X is one of 40,000 medications).  We need to decide if we want to allow postcomposition, if we want to annotate to just a high level, or something else. @cmungall @mellybelly

**Comment by pnrobinson** [comment]
I have been thinking about this area. There are some terms above that are probably inaccurate.
MONDO_0007348 Colchicine resistance
-- "Low adherence to colchicine treatment is a key component of resistance."(https://ojrd.biomedcentral.com/articles/10.1186/s13023-017-0609-1)
acetophenetidin sensitivity
--- This appears to relate to a single case report about 50 years ago (https://www.omim.org/entry/200300)

**Comment by pnrobinson** [comment]
eculizumab, poor response to
I would argue that this is actually a disease
https://omim.org/entry/615749

**Comment by pnrobinson** [comment]
The cytochrome related defects are definitely in scope, e.g., https://omim.org/entry/609535
This is a topic that we will address in the new NHGRI grant. I think it requires a workshop and a general plan before we start to address individual terms in these issues. I am going to close this now since the cytochrome related defects are obvious (i.e., will not be forgotten) and I am not convinced that the other items are valid.
