### ISSUE TITLE
Is it possible to get the new CPIC PGx Phenotype terms in HPO?

### ISSUE THREAD

**Issue by larrybabb** [obophenotype/human-phenotype-ontology#507]
Recently, the [CPIC Term Standardization for Clinical Pharmacogenetic Test Results Project](https://www.pharmgkb.org/page/cpicTermProject) finalized with a list of standard phenotype terms which can be found [here](https://www.pharmgkb.org/download.do?objCls=Attachment&objId=CPIC_Term_Standardization_Project_final_terms.pdf).  The recommendation mentions that the following "Drug Metabolizing Enzymes" (CYP enzymes, UGT1A1, TPMT, DPYD) phenotype terms:
Ultra-rapid Metabolizer
Rapid Metabolizer
Normal Metabolizer
Intermediate Metabolizer
Poor Metabolizer
should be preceded with the related gene.  
It would be useful to the ClinGen/ClinVar and DIGITizE AC projects if these phenotype where defined with formal concept ids in HPO (and eventually in SNOMED).  However, it is unclear to me that if you were to create these concepts, would you incorporate the specific gene into the definition of the phenotype?  
I believe that the terms listed as-is above should be defined as phenotypes in HPO so that the relationship to the specific enzyme producing genes can be established using the same curation and validation processes being defined by the community (i.e. ClinGen).

Any feedback on the likelihood and plan for incorporating these terms into HPO would be greatly appreciated.

Thank You.

**Comment by drseb** [comment]
In general, I am positive about adding these. 

I don't think *Normal Metabolizer*, *Intermediate Metabolizer*, and *Normal Function* will be included, as HPO is an ontology of *abnormalities*. Also, we would probably consider *Decreased Function* and *Poor Function* as equivalent. Can you explain, why these aren't synonyms in CPIC?

I will discuss with @pnrobinson 

Is this a complete list of the genes or is *CYP enzymes* referring to [every instance of CYP genes](http://ghr.nlm.nih.gov/geneFamily/cyp)? This would bloat the list of requested phenotype classes...

**Comment by larrybabb** [comment]
In regards to your final statement above...
The very reason I made this request is to try to determine whether phenotypes like these (ones that have an association to genes) will be defined to include the gene association.  I agree this is a slippery slope due to the fact that you can end up with a very large number of permutations and thus begin to diminish the value of the vocabulary.  It seems like HPO is using OMIM (for example) to generate associations between phenotypes and genes and I would think that these PGx phenotypes would be perfect candidates to have a set of terms that would permit the community to create direct relationships (with strength of evidence and such) to the genes that produce the function.  I do think the normal function is important/critical to allowing computational support for precision medicine, clinical decision support and improvements in physician care of patients in general.  Why wouldn't HPO include phenotypes that are "normal"?

In regards to your first point above...
I am more on the technical side of things, but I will see if I can get a representative from CPIC that would be willing to clarify the reasoning behind the two sets of terms "function" v "metabolism".  On the page [CPIC Term Standardization for Clinical Pharmacogenetic Test Results Project](https://www.pharmgkb.org/page/cpicTermProject) you might be able to discern their reasoning behind the need separate terms based on the various "Survey" documents (1 thru 4).  As you read those survey questions and their responses, you may start to understand why the stakeholders involved separated the two terms.  In the meantime, I will find someone with greater understanding and authority to help answer your questions and coordinate a set of final terms that will help promote the standard that this group has worked very hard at defining.

Thanks for the quick response.

**Comment by drseb** [comment]
>I agree this is a slippery slope due to the fact that you can end up with a very large number of permutations and thus begin to diminish the value of the vocabulary.

I would love to have more phenotypes in HPO, and I think this will increase the value of HPO.

>Why wouldn't HPO include phenotypes that are "normal"?

Because HPO is designed to represent classes of *abnormalities*. This is why the root of this part of HPO is labelled **Phenotypic abnormality**. You can still use negation to represent normal phenotypes (i.e. a patient does NOT have an abnormality of X ; this is exactly what we are already doing in our annotation files)

**Comment by mellybelly** [comment]
Normal phenotypes are being represented in OBA, and are interoperable with HPO MP and other abnormal ontologies

**Comment by larrybabb** [comment]
I did not understand that HPO was only meant to contain abnormalities. Definitely my ignorance. From my naive perspective I was thinking that the concept ids from a single phenotypic feature set like HPO could be used to provide a standard for ranking the clinical significance of phenotypes (like the pharma ones) with genes that may or may not be proven to cause those phenotypes, normal or abnormal.  

> You can still use negation to represent normal phenotypes (i.e. a patient does NOT have an abnormality of X ; this is exactly what we are already doing in our annotation files)

If there are several "abnormal" phenotypes for something like gene metabolic activity: ultra-rapid, rapid, (not normal), intermediate/decreased, & poor.  Then how can a negation on one phenotype represent "normal"?

I am definitely out of my league in understanding this area. As it must show by my line of questioning. I am basically trying to see if there's an opportunity to define standard phenotypes from the CPIC expert work in HPO that have a generalized definition as well as gene-specific definitions.  Maybe the ontology would provide for a concept parent phenotype like "poor metabolizer" that had subclasses for the more specific TPMT poor metabolizer, CYP2C9 poor metabolizer, etc..?

**Comment by drseb** [comment]
>Then how can a negation on one phenotype represent "normal"?

there would exist a general *abnormal XYZ metabolizer*

**Comment by larrybabb** [comment]
I see. The phenotype is inherently based on the gene. ok. 
It seems like there's going to be millions of phenotypes if we need to generate all the gene-specific ones.
Thank you for walking me through this.

**Comment by larrybabb** [comment]
one more thing.  a phenotype like HCM or DCM can be specifically related to one or more genes.  Will there eventually be MYH7 Dilated Cardiomypathy and MYH7 Hypertrophic Cardiomyopathy, etc..?

**Comment by pnrobinson** [comment]
I think the main issue is that one should decide on resources to describe these phenotypes that will enable certain types of analysis. If your primary aim is to have a database about the metablism of these compounds, then it might make sense to actually store the numeric data and normal ranges. The HPO is designed to allow analysis across the entire spectrum of human phenotype and is particularly useful when one wants to combine information from multiple fields of medicine or different organs or wants to do a differential diagnosis across thousands of diseases. It does not currently contain “normal” human phenotypes, although there is no reason one could not integrate normal phenotypes in the future. Could you explain exactly what you are trying to do?



If there are several "abnormal" phenotypes for something like gene metabolic activity: ultra-rapid, rapid, (not normal), intermediate/decreased, & poor. Then how can a negation on one phenotype represent "normal"?

=> You would use NOT of the parent term!



-Peter

**Comment by mellybelly** [comment]
A few comments:
1. HPO should never associate a phenotype with a gene directly - these would be in the annotations. This is fundamentally different than defining a disease or condition aka OMIM. The heart of the algorithms and of our approach to discovery requires these to be separate.

2. HPO is an ontology of abnormal phenotypes, but is being made interoperable with other types of traits in the Ontology of Biological Attributes (OBA). For example, abnormal eye color in HPO might be a subclass of an "eye color" trait in OBA. OBA is intended to be cross-species, whereas HPO is human. 

3. We do add things like "decreased X activity" (for example, "Reduced prothrombin activity"), which while these could be the result of some assay or absence of a gene product, they are defined in terms of the particular protein or chemical. So I guess its not fully devoid of a gene association, but this is tricky...

**Comment by drseb** [comment]
So I think this discussion has come to end for now, right?! Please re-open or file a new ticket if there are further questions.

**Comment by doughnuted** [comment]
Hi all, I'm resurrecting this thread. There are a number of academic and commercial projects emerging that are utilising this information and it would be good to update HPO rather then create other standards. I am currently looking at a production project where we are using the normalised phenotypes for decision support and having to use a non-standard ontology makes me nervous in terms of having to re-engineer things down the line.

You'll see that some of the terms appear in SNOMED CT, however they are incomplete and don't use the standardised nomenclature.

Dr Seb, historically "normal" wasn't a term used with reference to pharmacogenomics and indeed normal (e.g. 100% enzyme activity) may well be "abnormal" in the sense that it may be associated with rapid or ultrarapid metabolism. As I read that sentence I realise how confusing it is but the point I'm making is that when we are talking about PGx, I don't think we should use the term normal. In PGx we are usually working backwords- i.e. we genotype to predict phenotype, rather than phenotype to help identify genotype. Therefore we need to be able to annotate an individual with whatever phenotypes we predict, rather than annotate them as "not having abnormal drug metabolism". I think it's best to think that no phenotype is normal, the nomenclature is not static (i.e. what CPIC are now calling "normal" used to be called "extensive" for the very reason I'm mentioning; it changed back to normal because people find the "extensive" term confusing) and may well undergo another change in the future- if we think of them as levels 1-5, that currently have the aforementioned labels attributed to them.

mellybelly, I appreciate what you're saying about not having genes in the HPO term, however with PGx we are predicting enzyme/transporter function and the "intermediate XYZ metabolism" relates to the protein, not the gene.

My suggestion is that we start with the CPIC terms- https://cpicpgx.org/wp-content/uploads/2016/01/CPIC_term_standardization_project_final_terms.pdf, restricting to the CPIC level A genes/enzymes.
