### ISSUE TITLE
Age of Onset revision of hierarchy request

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#511]
Reported by Louise C Daugherty [at sourceforge](https://sourceforge.net/p/obo/human-phenotype-requests/492/):

>I wonder if you are planning on revisiting and revising the hierarchy of the Clinical Modifier Age of Onset (HP:0003674)? 
I am asking because increasingly more specific and significant age ranges associated to onset of a particular disorder is required for mapping patient data eg: >50 years, <16 years, as age data supplied is generally specific and not general. The current hierarchy does not fit this sort of data set, so mapping to the current ‘Age of onset’ hierarchy would only dilute what could be significant data set for patient records associated to a particular disease.
I realise there this is a somewhat tricky area, as there no community standard per se, and HPO have chosen to adopt, in the main, the Oxford Clinical Genetics handbook definitions, which is fine up to a point, but the problem lies in the more specific age ranges that lie within, and intersect these top level terms.
Are there plans for HPO to revisit the Age of Onset? If the top level terms definitions were revised, and then were broken down into more identifiable (even though ‘unofficial’ ranges) then it could address most, if not all of the community needs.

**Comment by drseb** [comment]
Reply by @pnrobinson :

>I think there is a case to be made for making the terms more granular, and a very simple way would be to make the terms for each year of life, i.e., childhood onset would have as children oset at age 3 years, onset at age 4 years etc.
I know there is an ontology out there that has one class for each year but it is not really that useful to map to it (maximally as equivalence axioms, but it is not worth the mireot trouble I think).
Louise, would that address your issues? Are there any other comments?

**Comment by drseb** [comment]
We have discussed this with @mellybelly before about adopting [stages ontologies approach](http://ohsu.pure.elsevier.com/en/publications/the-zebrafish-anatomy-and-stage-ontologies(e680b1fa-6bb9-4b71-b5f3-a0745429563f).html). Are there any news in this regard @pnrobinson @mellybelly ??

**Comment by cmungall** [comment]
We have already adopted [HsapDv](https://github.com/obophenotype/developmental-stage-ontologies/wiki/HsapDv)

See screenshot:

<img width="1289" alt="screen shot 2015-10-01 at 9 21 53 am" src="https://cloud.githubusercontent.com/assets/50745/10226703/ed3ca97e-681d-11e5-8a4c-54f2dcc1ad5b.png">

This ontology is already used for gene expression curation

Not all of the bins may match. But we just pick something and standardize. cc @fbastian

**Comment by lcdaugherty** [comment]
@cmungall, the adopted particlar system is a great start, but I am concerned that it does not cover community requirements.

The Age of onset hierarchy, should enable users to capture data for any disorder, but the current adopted system is somewhat restricted for some, if not most communities. For example, Late onset for Parkinson’s Disease is 70 years or older, but for Pulmonary arterial hypertension, late onset is 50 years or older. The current system does not support this top level data, let alone anything more granular. 

Age of onset is increasingly becoming important, as it associated with specific disease symptoms and rate of progression. Improving the terms for Age of onset will not only help narrow down possible diagnoses, but also help identify variants contributing to a particular pathogenesis.

I understand this is a difficult area to standardise,  but if  it could be broken down into specific granular ages, as suggested by @pnrobinson, then I think that would be really helpful.

**Comment by cmungall** [comment]
For disease-specific onsets, there is a way in OWL called "Generic Class Inclusions" that let us do this. Essentially this amounts to rules of the form:

    IF disease is 'Parkinsons' THEN age of onset is 70 or older
    IF disease is PAH THEN age of onset is 50 or older

(each one has to be independent, there is no way to say 'otherwise')

We can use bins, or we can use actual numbers.

Currently the onset hierarchy is used in combination with phenotypes. How should we interpret the onset value then? Is it always in reference to a disease?

**Comment by drseb** [comment]
>Currently the onset hierarchy is used in combination with phenotypes. How should we interpret the onset value then? Is it always in reference to a disease?

No, we use the Onset-classes for both, annotating diseases and as meta-annotation for phenotype-annotations.

**Comment by cmungall** [comment]
On 2 Oct 2015, at 12:58, Sebastian Köhler wrote:

>> Currently the onset hierarchy is used in combination with phenotypes. 
>> How should we interpret the onset value then? Is it always in 
>> reference to a disease?
>
> No, we use the Onset-classes for both, annotating diseases and as 
> meta-annotation for phenotype-annotations.

So if onset is context-dependent, which context do we use, P or D? What 
if one context is not stated (e.g. undiagnosed disease), what does O 
mean?. I'm sure this is all obvious to a clinician but as an ontologist 
I need all this stated in a formal unambiguous way… (or if it is 
inherently fuzzy good to state that explicitly too)

**Comment by drseb** [comment]
The onset is IMHO **independent of which event** you refer to. It just measures some point in the life of a human being. So IMHO it is valid to state the outbreak of disease D had onset O , and it is also valid to state the patient developed symptom P at onset O. 
What is wrong in my assumption?

**Comment by mellybelly** [comment]
I agree with you @drseb. While the "late" onset of one disease may be later than another disease's or symptom's "late" onset, the onset classes should be treated as standardized time intervals that break up the organism's lifespan. I would say that there should be an onset property rather than having this built into the stages, then you could apply onset time to any disease, phenotype, or treatment and use whatever degree of granularity you need for the interval reasoning.

**Comment by pnrobinson** [comment]
Assuming that an individal is annotated to a certain onset category, and a disease model in a database is annotated to the typical onset, then it should be possible to infer whether the onset in the individual is “late” or not. It does not make sense to me to have an additional ontology term to capture this subjective impression…

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651

Von: Melissa Haendel [mailto:notifications@github.com]
Gesendet: Freitag, 16. Oktober 2015 15:02
An: obophenotype/human-phenotype-ontology
Cc: Robinson, Peter
Betreff: Re: [human-phenotype-ontology] Age of Onset revision of hierarchy request (#511)


I agree with you @drseb<https://github.com/drseb>. While the "late" onset of one disease may be later than another disease's or symptom's "late" onset, the onset classes should be treated as standardized time intervals that break up the organism's lifespan. I would say that there should be an onset property rather than having this built into the stages, then you could apply onset time to any disease, phenotype, or treatment and use whatever degree of granularity you need for the interval reasoning.

**Comment by cmungall** [comment]
In that case the axiomatization for the children of adult onset should be removed, as they are incorrect

**Comment by pnrobinson** [comment]
I agree with Chris the axioms are a little dodgy. I think that there is a case to be made to have HPO onset terms that are human specific and to relate them to other ontologies as needed. I think the onset terms should be absolute and not relative. Note that the current term "late onset" is meant to mean "late adult onset" and perhaps we should change the prefered name, even though it is always used with this meaning unless there is special context.

**Comment by mellybelly** [comment]
see also #273 for relevant discussion

**Comment by markengelstad** [comment]
Also, we should keep in mind that onset is usually practically used as
'point in lifespan (age) at which D or P is first noticed clinically',
which is different than onset. For instance, a disease may be diagnosed at
age 55, but present since age 40.

So, we don't really know onset, much of the time...  we just know when it
was noticed.   So, should we think of it as onset?

So isn't onset just a proxy for age at which D or P was diagnosed/ charted/
classified?

**Comment by cmungall** [comment]
Agreed, we're talking about human-specificity here, mice don't come into it for this discussion

Sorry if I'm being dense. I'm not sure what everyone is agreeing to or not agreeing to. Pretend I'm a reasoner.

 1. Late onset for Parkinson’s Disease is 70 years or older
 2. Late onset for Pulmonary arterial hypertension is 50 years or older.
 3. All instances of late onset are 60 years or older
 4. All instances of late onset are 50 years or older

1 and 2 are asserted above. 3 is asserted in the text definition for the HP class. Clearly {2,3} form an inconsistent set, so what is the resolution here?

More generally, are we saying that we are abandoning ranges entirely for generic late/early onset definitions?

**Comment by pnrobinson** [comment]
There is no HPO term that describes the subjective "late"-ness of onset, they all refer to age ranges!

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Chris Mungall [notifications@github.com]
Gesendet: Dienstag, 20. Oktober 2015 20:38
An: obophenotype/human-phenotype-ontology
Cc: Robinson, Peter
Betreff: Re: [human-phenotype-ontology] Age of Onset revision of hierarchy request (#511)


Agreed, we're talking about human-specificity here, mice don't come into it for this discussion

Sorry if I'm being dense. I'm not sure what everyone is agreeing to or not agreeing to. Pretend I'm a reasoner.

  1.  Late onset for Parkinson’s Disease is 70 years or older
  2.  Late onset for Pulmonary arterial hypertension is 50 years or older.
  3.  All instances of late onset are 60 years or older
  4.  All instances of late onset are 50 years or older

1 and 2 are asserted above. 3 is asserted in the text definition for the HP class. Clearly {2,3} form an inconsistent set, so what is the resolution here?

More generally, are we saying that we are abandoning ranges entirely for generic late/early onset definitions?

**Comment by mellybelly** [comment]
Agreed, we should not define lateness of onset for any particular disease in the stage classes, these should simply refer to the ages of the patient. In my opinion these are not onset classes, they are age/stage classes. 

If we need to discuss the lateness of onset for a particular disease, we can use the correct "stage" class (making them as granular in time as needed), and then describe further refinements in the definition of the disease. For example, we could have a disease term:
"Late onset Parkinson's Disease" that would have the stage axiom to 'Late onset' => meaning any time after 60yrs. This would then be qualified in the definition of this disease to mean 70yrs or older. If/when a new age term was implemented, we could change this to 70yrs or older. 

I think that the onset terms should be age/stage terms, and we should have an onset property to relate them to diseases and phenotypes. This allows a lot more flexibility for other uses, such as the beginning of treatments, and when diseases end, either due to it being a childhood disease or due to treatment. 

This also would facilitate interoperability with GO and many other ontologies that treat stage/time/age all as temporal intervals without the built in assumptions about their relationships to other entities.

See also #273
