### ISSUE TITLE
Missing phenotypic gender for use as a clinical modifier

### ISSUE THREAD

**Issue by krttrr** [obophenotype/human-phenotype-ontology#5118]
Label: New Term Request

In annotating diseases with HPO, we would like to be able to use phenotypic gender as a clinical modifier (e.g. to note specific disease phenotypes that may only be present or more frequent in one gender). That idea is alluded to in the documentation of the new annotation format, but the terms are missing from the Clinical Modifier subontology. Can you add these terms?

https://hpo-annotation-qc.readthedocs.io/en/latest/annotationFormat.html#new-and-old-big-file-formats
> 9. Sex: This field contains the strings MALE or FEMALE if the annotation in question is limited to males or females. This field refers to the phenotypic (and not the chromosomal) sex, and does not intend to capture the further complexities of sex determination. If a phenotype is limited to one or the other sex, **then the corresponding term for the “Clinical modifier” subontology should also be used in the Modifier field.**

**Comment by pnrobinson** [comment]
The idea is that to annotate a disease you can use the MALE/FEMALE modifiers if you have sex-specific data (we use this now for a small minority of our annotations). In order to annotate individual patients, we are currently transitioning to the Phenopackets format (https://phenopackets-schema.readthedocs.io/en/latest/), which has other means for recording the phenotypic and chromosomal sex of individuals. So we would recommend doing this not with HPO terms but outside of the HPO annotations. Does this work for you?

**Comment by krttrr** [comment]
Yes, we want to use this to annotate disease, not describe patients. We've implemented an annotation schema where phenotypes are joined to disease entities and then modifiers are attached to the phenotypes. It would be nice to have gender clinical modifier terms available to fit within this schema in the same way as onset, frequency, etc. Otherwise we end up needing to either create non-HPO modifiers or create an extra almost-always-empty column for storing gender as a modifier (which is what you've done in the text annotation format described in the link above).

Do you see any advantage to keeping gender as a special non-term modifier concept?

**Comment by pnrobinson** [comment]
@krttrr  Not sure I understand you use case. Why doesn't the existing HPO annotation format work for you? It is nice not to have more than one option for doing things -- this is usually confusing, and if it does the same thing it should not be an issue.
Also note that if you are doing a lot of work with disease annotations and would like to contribute them to HPO please get in touch. We are about to start work on a Web-based collaboration portal for this.

**Comment by krttrr** [comment]
The schema we are using is simple and flexible. Diseases and phenotypes each exist in a table. There is then a join table between them to associate phenotypes to diseases. Additionally, there is a join between disease_phenotypes and phenotypes, which allows unlimited modifications to a phenotype-disease relationship. We then have a disease_phenotypes_modifiers_groups table, which lets you group modifiers. For instance, you could have a disease_phenotype that was “mild in a wet, warm climate” and "severe in a dry, cold climate" or "frequently severe in males" and "rarely severe in females". Having modifiers (e.g. gender) that exist outside of HPO terms breaks this. If there won't be official HPO terms, we'll create our own, but we would, of course, rather use the canonical terms.

You can do this with the HPOA flat format, but it's inefficient for storage and places some hard limits on the way modifiers can be combined.

Related to your last point, we're working on a manuscript that, amongst other things, will include aggregated disease-phenotype annotations extracted from molecularly diagnosed cases. It may make sense to incorporate this into HPO, perhaps as another annotation source? Happy to discuss offline!

**Comment by pnrobinson** [comment]
@krttrr  Should we find a time to zoom/skype? My email can be found under author information here https://www.ncbi.nlm.nih.gov/pubmed/32019583

**Comment by pnrobinson** [comment]
@krttrr 
coming back to this, I still am not sure I understand the term request. If you are denoting the sex of a proband in a database, probably the easiest thing is to  use a constant. Of course it is relatively difficult to model concepts of sex and gender comprehensively, but I do not think this was what you were asking for. Terms such as "Frequently severe in males" are not good ontology terms because they would lead to a combinatorial explosion if we made a term for each possible combination. 
As to your second question, we would be interesting in adding your annotation information to the HPOAs. I will close this request for now, but please contact me at the above named email address about this if there are still open issues.

**Comment by krttrr** [comment]
@pnrobinson I would agree that "frequently severe in males" is not a good ontology term. What we were doing at the time we asked about this was describing disease phenotypes with collections of modifiers (i.e. modifying/grouping modifiers). Anyways, we ultimately decided the entire modifier branch of HPO doesn't really make sense as an ontology -- it's more like a controlled vocabulary -- and have shifted our approach there.

A slight tangent: from the perspective of HPO's structure, which describes phenotypic _ab_normality only, I see why you would not want to include normal phenotypes (e.g. gender, normal cognitive function, normal vision, etc.). In the context of describing the phenotype of a person or a disease, however, asserting normality (or negating abnormality) can be quite useful. Something to think about...
