### ISSUE TITLE
Aligning HPO and HsapDv

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/human-phenotype-ontology#5119]
Hello HPO team, we are currently aligning HsapDv and HPO.

Inconsistencies requiring changes in HPO (in our opinion):
* Infant in HPO starts from 1 yo, in HsapDv it starts from 2 yo. For us, it's related to age of weaning, we think it makes sense to define infant based on this criteria. See for instance https://www.sciencedirect.com/science/article/pii/S1084952109002286. Or also http://genomics.senescence.info/species/entry.php?species=Homo_sapiens . Estimates vary a lot between methods and sources, but points to weaning not happening before 2yo.
* What are your criteria for distinguishing childhood and juvenile? For us it's pretty much the same. Couldn't we merge them?
* Juvenile is defined until 15yo. Sexual maturity appears before that age in human, see for instance http://genomics.senescence.info/species/entry.php?species=Homo_sapiens. We're happy to discuss what age we could use for sexual maturity, but apparently 13yo on average is generally accepted, and 15yo definitely seems late.

Changes that we could make to HsapDv:
* Neonatal in HPO is until 28 days, in HsapDv it's one month (31 days). I guess in HPO it was defined as 4 weeks rather than one month? No strong opinion on that, can update HsapDv.
* Child in HPO is until 5yo not included, in HsapDv it includes 5yo (until 6). No strong opinion on that, we can update HsapDv.

**Comment by pnrobinson** [comment]
Hi, HsapDv team,
our definitions are based on this book, which is standard in the fields of genetics:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3284726/

All of these stages are of course arbitrary to a lesser or greater extent. We cannot make any radical changes without going back and checking all of the diseases that have been annotated using these terms though, and so unless there is a true mistake I would hesitate to make changes.

As to infant, the word literally means "not speaking", and since most children speak their first words at at age of roughly 12 months (+/- 2 months or so),  there is a good etymologicall reason to define infant the way we do! (by the way, of course ending at 1 yo not "starting"!).

Possibly it is easier to skype/zoom/phone about this?

**Comment by mellybelly** [comment]
So we have had other tickets about this issue. We never quite finished the alignment, but they are not mutually exclusive, just need more granular times and to finish the alignment.

Please see these other tickets: 
https://github.com/obophenotype/uberon/issues/1485
https://github.com/obophenotype/human-phenotype-ontology/issues/4206

And some older ones:
https://github.com/obophenotype/developmental-stage-ontologies/issues/10
https://github.com/obophenotype/developmental-stage-ontologies/issues/17
https://github.com/obophenotype/developmental-stage-ontologies/issues/39

**Comment by fbastian** [comment]
Thanks for the explanations @pnrobinson (I jump in, since I wrote the first message with @ANiknejad). So, the context of HsapDv is to have an ontology that can be aligned with other species, in Uberon. Of course it's very different to a clinical context. See my comments below. Happy to discuss it on skype/zoom.

* I think having stages that align with model organisms such as mouse can also be very useful in a clinical context
* Infant/weaning: I didn't know about the etymology of infant, interesting! Our problem is that we need a term capturing weaning. We have many gene expression data in various species related to this state of weaning.
* Juvenile: we need a term related to sexual maturity, again this is a criteria that aligns well between species. I see in [this comment](https://github.com/obophenotype/human-phenotype-ontology/issues/4206#issuecomment-433262954) that pediatric cancer is considered until 14yo. This 15yo limit seems odd. I don't have access to the book you mentioned
* Making changes will be annoying for anybody of course. But we can manage that gracefully by obsoletion of terms, so that it is not necessary to review all annotations right away (because we will also need on our side to revise annotations, and other projects use HsapDv, such as the human cell atlas)

Considering these "hard" needs of materializing weaning and sexual maturity for us, it would require:
* add a term, parent of infant, that goes until time of weaning. That would require no change in annotations on your side for infant annotations.
* We would have a sibling term of infant, that would be "talking but no weaning". That would require change for some annotations to childhood.
* An updated childhood term would then start after weaning.
* Could you comment about merging chilhood and juvenile? What the difference between the two?
* Juvenile ending at 15yo is the most problematic I think. Does this age come from the book you refered to? I don't understand where this comes from, even in a clinical context.
* We would change neonatal and child in HsapDv

What do you think?

> (by the way, of course ending at 1 yo not "starting"!)

Woops, yes

**Comment by pnrobinson** [comment]
It is not easy to discuss this on the tracker, can we set up a time to call? firstname dot lastname at jax dot organisation

**Comment by fbastian** [comment]
We decided to completely align HsapDV to HPO, as we understand that medical pediatric terms take precedence in human. We'll update you once it's done.

**Comment by pnrobinson** [comment]
Sounds good! You may wish also to consult with this great book, which was the basis for our choices:
https://oxfordmedicine.com/view/10.1093/med/9780199545360.001.1/med-9780199545360

**Comment by pnrobinson** [comment]
We are also going to be working with the prenatal community on prenatal time ranges. This is also not entirely trivial but let us know if you are interested in collaborating on this.

**Comment by fbastian** [comment]
Thanks for the link to the book, sadly we don't have access to it at our university.

Definitely interested for coordinating prenatal stages! We have done quite some work on that already, you can have a look at the hierarchy under HsapDv:0000045 "prenatal stage".

**Comment by fbastian** [comment]
I share the raw notes of our discussion with @ANiknejad to make the alignment. We now have to capture it properly in the ontology

```
HsapDv:0000045 prenatal stage
    |
    |-po human embryo/fetus to align with HPO

HsapDv:0010000 postnatal stage => should correspond to UBERON:0000092 post-embryonic stage? to check, there is no xref in current HsapDv
    |
    - po HsapDv:0000257 immature stage => 0 to 15 yo => to obsolete to update age range
    |   |
    |   |- po HsapDv:0000262 newborn: from birth to 28 days => xref HPO neonatal onset
    |   |
    |   |- po NEW TERM pediatric, xref HPO pediatric onset: 28 days - 15yo
    |   |   |
    |   |   |- po HsapDv:0000261 infant stage: from 28 days to 2yo/weaning => to change to 1yo to align with HPO
    |   |   |
    |   |   |- po HsapDv:0000084 2-5 year-old child stage => to change to 1-5 yo, xref of HPO Childhood onset
    |   |   |   |
    |   |   |   |- po NEW term not infant but not weaning = 1yo-2yo
    |   |   |   |
    |   |   |   |- po NEW term 2-5yo: less than 5yo but weaning
    |   |   |
    |   |   |- po NEW term, xref HPO juvenile onset, 5-15yo
    |   |
    |- po adult 16-death, xref HPO adult => check HsapDv:0000204 mature, to obsolete or update or remove, should start at 16
    |    |
    |    |- po UBERON:0018241 prime adult stage: refine definition to say that it starts at sexual maturity, not at end of development
    |    |    |
    |    |    |- po young adult 16-40, xref HPO young adult
    |    |    |    |
    |    |    |    |-po NEW TERM 16-20
    |    |    |    |
    |    |    |    |-po HsapDv:0000237 third decade
    |    |    |    |
    |    |    |    |-po HsapDv:0000238 fourth decade
    |    |    |
    |    |    |- po middle aged 40-60, xref HPO middle aged onset
    |    |    |    |
    |    |    |    |-po HsapDv:0000239 fifth decade
    |    |    |    |
    |    |    |    |-po HsapDv:0000240 sixth decade
    |    |
    |    |- po HsapDv:0000093 human aged stage: to obsolete and replace to make it start at 60yo; xref UBERON:0007222 late adult stage; 60yo-death; xref HPO late onset
    |    |    |
    |    |    |- po HsapDv:0000094 65-79 year-old human stage => to obsolete/replace to make it start at 60yo
    |    |    |    |
    |    |    |    |- po HsapDv:0000241 seventh decade
    |    |    |    |
    |    |    |    |- po HsapDv:0000242 eighth decade
    |    |    |
    |    |    |- po HsapDv:0000095 80 year-old and over human stage 
    |    |    |    |
    |    |    |    |- po the appropriate decades
    |    |    |    |
    |    |    |    |- po HsapDv:0000247 centenarian human stage
    |    |    |    |    |
    |    |    |    |    |- po the appropriate decades
```

**Comment by pnrobinson** [comment]
I am not sure we ever came to closure for this. The HPO will be adding a bunch of prenatal terms this year, it might be good to coordinate? I am going to close this issue now since it seems we have reached consensus? Please reopen or email me if needed!
