### ISSUE TITLE
New terms: 'motor impersistence' and 'simultanapraxia'

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#514]
Definition of motor impersistence: the inability to maintain postures or positions (such as keeping eyes closed, protruding the tongue, maintaining conjugate gaze steadily in a fixed direction, or making a prolonged “ah” sound) without repeated prompts

Synonym of motor impersistence: negative chorea
Superclass of motor impersistence: abnormality of central motor function; abnormality of coordination

Definition of simultanapraxia: a subset of motor impersistence, defined as the inability to perform more than two of the simple voluntary acts simultaneously, such as closing the eyes and protruding the tongue. 

Reference: http://link.springer.com/referenceworkentry/10.1007%2F978-0-387-79948-3_2046

**Comment by pnrobinson** [comment]
@drseb  These terms look good to me.
We should add as a comment to "Motor impersistence": Damage to premotor and prefrontal regions results in motor-intentional disorders that disrupt initiation, maintenance, and termination of volitional movements. Motor impersistence (i.e., failure to maintain movement) more frequently develops following right than left hemisphere lesions. (xref pmid:17353476)
