### ISSUE TITLE
Abnormal apoptosis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5143]
http://www.ncbi.nlm.nih.gov/pubmed/26305041

**Comment by pnrobinson** [comment]
@Marwaabdelhakim

**Comment by pnrobinson** [comment]
The paper you are referring to is a mouse study. I am not sure that abnormal(ly increased) apoptosis is something that is measured in human medicine. I would therefore not add this as a term, but please get beack to me if you have references to human medicine & apoptosis!

**Comment by Marwaabdelhakim** [comment]
Thank you very much, Peter!

I am not sure if you would consider the term here as mentioned in human medicine, since the paper has used a murine animal model to investigate the phenomena experimentally .
16249245<https://www.ncbi.nlm.nih.gov/pubmed/16249245>

Best Regards,

Marwa

On 9 Feb 2020, at 4:31 PM, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:


The paper you are referring to is a mouse study. I am not sure that abnormal(ly increased) apoptosis is something that is measured in human medicine. I would therefore not add this as a term, but please get beack to me if you have references to human medicine & apoptosis!
