### ISSUE TITLE
NTR: Oculoclonic status status epilepticus

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5214]
"-Focal motor status epilepticus
---Status epilepticus with ictal paresis
---Repeated focal motor seizures
---Epilepsia partialis continua
---Adversive status epilepticus
---NTR: Oculoclonic status status epilepticus
label: Oculoclonic status status epilepticus
def: A type of focal motor status epilepticus characterized by repetitive and rapid saccades, in association with epileptic discharges.
source: PMID: 26336950, PMID: 2912713, PMID: 11967176
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE 2015
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney


Is the repetition of the word "status" in the label intentional?

**Comment by DLewisSmith** [comment]
No. Sorry, this was an error and should read:

'Oculoclonic status epilepticus'

Sent from my phone

On 22 Feb 2020, at 16:32, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

﻿

@DLewisSmith<https://github.com/DLewisSmith>
@galerp<https://github.com/galerp>
@shiva-g<https://github.com/shiva-g>
@ihelbig<https://github.com/ihelbig>
@GBalagura<https://github.com/GBalagura>
@hughkearney<https://github.com/hughkearney>

Is the repetition of the word "status" in the label intentional?
