### ISSUE TITLE
Make clear the distinction between short digit and brachydactyly

### ISSUE THREAD

**Issue by cmungall** [obophenotype/human-phenotype-ontology#522]
Note the reason currently infers short digit == brachydactly

Discovered while investigating
https://github.com/monarch-initiative/monarch-app/issues/1011
though I do not think related

The reason here is simply sharing the same equiv axiom, equivalent to:
```
'has part' some 
    ('decreased length'
     and ('inheres in' some digit)
     and ('has modifier' some abnormal))
```

In general we should never have shared equivalence axioms in the same ontology.

The 'short digit' axiom is I think trivially correct. I think that either brachydactyly refers to some difference that is hard to axiomatize; see the comment for short finger:
*Note that the term brachydactyly is reserved for specific patterns of short digits, see HP:0001156.*

Or they should be merged. Expert opinion sought.

This is the def for brachydactyly:

```
Digits that appear disproportionately short compared to the hand/foot. The word brachydactyly is used to describe a series of Mendelian diseases characterized by distinct patterns of shortened digits (brachydactyly types A-E). This is the sense used here, however, it is preferable to described the observed phenotypic abnormalities precisely.
```

and for short digit:

```
One or more digit that appears disproportionately short compared to the hand/foot, whereby either the entire digit or a specific phalanx is shortened.
```

Note that the core part of the text def (before '.') is indistinguishable to my eyes.

**Comment by pnrobinson** [comment]
Brachydactyly refers to bundled terms of abnormalities who compound occurence is the phenotype, since they not only occur in the eponymous diseases but also as features of other diseases!

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Chris Mungall [notifications@github.com]
Gesendet: Freitag, 16. Oktober 2015 02:40
An: obophenotype/human-phenotype-ontology
Betreff: [human-phenotype-ontology] Make clear the distinction between short digit and brachydactyly (#522)


Note the reason currently infers short digit == brachydactly

Discovered while investigating
monarch-initiative/monarch-app#1011<https://github.com/monarch-initiative/monarch-app/issues/1011>
though I do not think related

The reason here is simply sharing the same equiv axiom, equivalent to:

'has part' some
    ('decreased length'
     and ('inheres in' some digit)
     and ('has modifier' some abnormal))


In general we should never have shared equivalence axioms in the same ontology.

The 'short digit' axiom is I think trivially correct. I think that either brachydactyly refers to some difference that is hard to axiomatize; see the comment for short finger:
Note that the term brachydactyly is reserved for specific patterns of short digits, see HP:0001156.

Or they should be merged. Expert opinion sought.

This is the def for brachydactyly:

Digits that appear disproportionately short compared to the hand/foot. The word brachydactyly is used to describe a series of Mendelian diseases characterized by distinct patterns of shortened digits (brachydactyly types A-E). This is the sense used here, however, it is preferable to described the observed phenotypic abnormalities precisely.


and for short digit:

One or more digit that appears disproportionately short compared to the hand/foot, whereby either the entire digit or a specific phalanx is shortened.


Note that the core part of the text def (before '.') is indistinguishable to my eyes.

**Comment by drseb** [comment]
Ok. I will remove the eq-axiom from *Brachydactyly*.
