### ISSUE TITLE
NTR: Status epilepticus with ictal paresis

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5309]
"-Focal motor status epilepticus
---Oculoclonic status status epilepticus
---Repeated focal motor seizures
---Epilepsia partialis continua
---Adversive status epilepticus
---NTR: Status epilepticus with ictal paresis
label: Status epilepticus with ictal paresis
def: A type of focal motor status epilepticus characterized by prolonged ictal paresis or inhibitory motor seizures.
comment: Ictal paresis or inhibitory motor seizures are a relatively rare type of seizure characterized by an inability to initiate or continue movements despite retained awareness, which could last for many hours or even days. These manifest with paresis/paralysis of 1 side of the body (hemiplegia with or without facial involvement) or 1 extremity (upper or lower monoplegia) and are often preceded by other objective or subjective ictal symptoms, which may also occur concomitantly with the paresis or independently.
source: PMID: 26336950, PMID: 25667883, PMID: 17116038
seeAlso: Focal inhibitory status epilepticus
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE 2015
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

Just a question -- if you have ictal paresis, after status epilepticus, does this ALWAYS imply that the status was focal motor? If not, should this be explained a bit more for the non-specialist?

**Comment by DLewisSmith** [comment]
May be our definition below is not clear enough.

"A focal motor seizure characterized by weakness or complete paralysis of a muscle or group of muscles as the initial semiological manifestation."

This does not refer to post-ictal (after the seizure) paresis (eponymously known as a Todd’s paresis: a common phenomenon that can be due to a focal seizure or generalised seizure decompensating a focal abnormality of the brain) but rather that the ictal (actual) manifestation of the seizure is weakness of a localised part of the body. This is rare in the general population but common in mitochondrial disease.

Maybe change the definition to:

"A focal motor seizure characterized by weakness or complete paralysis of a muscle or group of muscles as the initial semiological manifestation of the seizure itself rather than as a post-ictal (Todd’s) phenomenon."
