### ISSUE TITLE
NTR: Generalized atonic seizure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5319]
"-Generalized-onset motor seizure
-Atonic seizure
---Generalized myoclonic seizure
---Generalized tonic seizure
---Generalized myoclonic-tonic-clonic seizure
---Generalized myoclonic-atonic seizure
---Bilateral tonic-clonic seizure with generalized onset
---Generalized-onset epileptic spasm
---Generalized clonic seizure
---Focal atonic seizure
---NTR: Generalized atonic seizure
label: Generalized atonic seizure
def: Generalized atonic seizure is a type of generalized motor seizure characterized by a sudden loss or diminution of muscle tone without apparent preceding myoclonic or tonic event lasting ~1-2 s, involving head, trunk, jaw, or limb musculature.
comment: Atonic means without tone. When leg tone is lost during a generalized atonic seizure, the patient falls on the buttocks or sometimes forward onto the knees and face. Recovery is usually within seconds.
seeAlso: Generalised atonic seizure
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE 2017
http://purl.org/dc/elements/1.1/source: PMID: 28276064, PMID: 28276060
http://www.w3.org/2000/01/rdf-schema#current_hpo: HP:0010819
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

The suggestion appears to be to replace the existing term HP:0010819 (Atonic seizure) with Generalized atonic seizure. However, therer are focal atonic seizures, (e.g., https://www.sciencedirect.com/science/article/pii/S1059131112001501), and so wouldn't it be better to just make this new term a chikd of Atonic seizure
Atonic seizure
-- Generalize atonic seizure
-- Focal atonic seizure

**Comment by DLewisSmith** [comment]
Hi Peter,

On reading the HPO definition of HP:0010819 I agree. We had misinterpreted HP:0010819 to mean 'generalized atonic seizure' when in fact it does not specify that it is generalized (and in fact it includes ‘focal...' as a child). This because in the old ILAE world ‘atonic’ not otherwise specified was usually interpreted to be ‘generalized’ in onset. It is a good example of why the HPO seizure subontology needed updating.

Our DAG is correct here (and consistent with your suggestion), it is the suggested replacement of terms that is wrong. I suggest that HP:0010819 is replaced by our new term 

RCgMMu8AeTeB1Qki0ZvxO6z	Atonic seizure

This has child terms:

RBKGb7FhVTEkThHamSpflIb	Focal atonic seizure

HPO_00000007	Generalized atonic seizure

**Comment by pnrobinson** [comment]
OK, thanks!
