### ISSUE TITLE
NTR: Music-induced seizure

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5404]
"-Reflex seizure
---Proprioceptive-induced seizure
---Somatosensory-induced seizure
---Reading-induced seizure
---Visually-induced seizure
---Startle-induced seizure
---Thinking-induced seizure
---Hot water-induced seizure
---Eating-induced seizure
---Praxis-induced seizure
---NTR: Music-induced seizure
label: Music-induced seizure
comment: Seizures induced by acoustic stimulation.
source: PMID: 11422340
seeAlso: Auditory-provoked seizure
http://webprotege.stanford.edu/RiCnLhdRh6VgSt0KNJ92ib: ILAE 2001
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

 Seizures induced by acoustic stimulation. => This definition is not specific to music. The article cited does not provide details. Should the definition instead be: 
"Seizure provoked by hearing music"
?

**Comment by DLewisSmith** [comment]
I agree Peter. The evidence for reflex seizure classification is limited and whilst these entities have been well described, the evidence for organising the DAG in this way is relatively weak (and these are not ILAE 2017 terms as the ILAE 2017 classification focused on semiology rather than precipitants). However, it is useful to have the concept represented and its position is based on sensible assumptions. I think Engel’s suggestion of a concept of a 'music-induced seizure’ should be interpreted as a seizure precipitated by listening to complex auditory stimulation (i.e. it is the cognitive processing of the auditory stimulus that triggers the seizure) rather than a sudden loud sound/noise which would be encompassed by a ’startle-induced seizure’.

Thus, I suggest changing the definition to ’Seizure precipitated by listening to music or other complex sounds’.

**Comment by pnrobinson** [comment]
Thanks, I added the term with your revised definition!
