### ISSUE TITLE
NTR: Focal impaired awareness cognitive seizure with impaired attention

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5414]
"-Focal impaired awareness cognitive seizure
---Focal impaired awareness cognitive seizure with hallucination
---Focal impaired awareness cognitive seizure with expressive dysphasia / aphasia
---Focal impaired awareness cognitive seizure with deja vu / jamais vu
---Focal impaired awareness seizure with dissociation at onset
---Focal impaired awareness cognitive seizure with conduction dysphasia / aphasia
---Focal impaired awareness cognitive seizure with receptive dysphasia / aphasia
---Focal impaired awareness cognitive seizure with anomia
---Focal impaired awareness cognitive seizure with impaired responsiveness
---Focal impaired awareness cognitive seizure with left-right confusion
---Focal impaired awareness cognitive seizure with forced thinking
---Focal impaired awareness cognitive seizure with auditory agnosia
---Focal impaired awareness cognitive seizure with neglect
---Focal impaired awareness cognitive seizure with illusion
---Focal impaired awareness cognitive seizure with dysgraphia / agraphia
---Focal impaired awareness cognitive seizure with dyscalculia / acalculia
---Focal impaired awareness cognitive seizure with  memory impairment
---Focal impaired awareness cognitive seizure with dyslexia / alexia
---NTR: Focal impaired awareness cognitive seizure with impaired attention
label: Focal impaired awareness cognitive seizure with impaired attention
def: A focal cognitive seizure with impaired attention characterized by impairment of awareness at some point during the seizure.
http://purl.org/dc/elements/1.1/source: www.epilepsydiagnosis.org
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney"
PMID:28276060: https://www.ncbi.nlm.nih.gov/pubmed/PMID:28276060

**Comment by pnrobinson** [comment]
@DLewisSmith
@galerp
@shiva-g
@ihelbig
@GBalagura
@hughkearney

This definition is not so obvious to me. If the seizure is characterized by impaired awareness isn't attention ALWAYS impaired? What exactly is different about this subtype?

**Comment by DLewisSmith** [comment]
Good catch Peter. The cognitive seizure subtypes, which are characterised by a specific cognitive deficit, are complex, clinically hard to classify at this level of detail, and extrapolated from descriptors in the ILAE 2017 Manual (rather than classification itself) and their (less critically appraised) extension on epilepsydiagnosis.org. Some of them may only be discernible in a research environment (if at all), particularly once the different states of awareness are considered.

Reviewing our ontology, none of the following 4 terms has been given dual parentage to the ’semiology independent of awareness’ path we used for other focal seizure subtypes:
Focal aware cognitive seizure with impaired attention
Focal aware cognitive seizure with impaired responsiveness
Focal impaired awareness cognitive seizure with impaired responsiveness
Focal impaired awareness cognitive seizure with impaired attention

Specifically there are no terms for these 2 seizure types without explicitly commenting on awareness: i.e.
Focal cognitive seizure with impaired attention
Focal cognitive seizure with impaired responsiveness

If it is acceptable to Peter from an HPO perspective I think that we should consider adding the following terms:
Term

Definition

Comment

Child of

Patent of

Focal cognitive seizure with impaired responsiveness

A type of cognitive seizure predominantly characterized by a reduced ability to respond to a stimulus at seizure onset.

Impaired responsiveness does not necessarily imply impaired awareness or behavioral arrest. A seizure dominantly characterized by behavioral arrest throughout the seizure without other features then it is considered separately to focal cognitive seizures (see 'Focal behavior arrest seizure').

Focal cognitive seizure

Focal aware cognitive seizure with impaired responsiveness

 

Focal impaired awareness cognitive seizure with impaired responsiveness

Focal cognitive seizure with impaired attention

A type of cognitive seizure characterized specifically by a reduced ability to attend to, or concentrate on something at seizure onset.

Depending on the definitions used it is debatable whether impaired attention always implies impaired awareness. In instances in which awareness is clinically determined to be retained throughout one of these seizures or impaired at some point during the seizure then the more specific terms Focal aware cognitive seizure with impaired attention or Focal impaired awareness cognitive seizure with impaired attention should be used accordingly.

Focal cognitive seizure

Focal aware cognitive seizure with impaired attention

 

Focal impaired awareness cognitive seizure with impaired attention

There may be debate as to whether 'impaired attention’ can have an ‘aware’ subtype (is attention purely a form of focused active awareness), depending on the definition used - I don’t think the epileptologists have thought about this in great detail (we are into the realms of cognitive neuroscience, if not philosophy), or intended it for use in an ontology. Including ‘impaired attention’ with child terms for ‘aware’ and ‘impaired awareness’ allows wiggle room for users to handle the phenomenological uncertainty at their own discretion and whilst this may result in some redundancy of terms, I would rather this than make assumptions that result in general disagreement.


What do you think?

D

**Comment by pnrobinson** [comment]
I think we have all of these terms except the combination. If you could provide a definition of 

Focal impaired awareness cognitive seizure with impaired attention

then I think we are all done!

**Comment by DLewisSmith** [comment]
Label: Focal impaired awareness cognitive seizure with impaired attention

Definition: A focal cognitive seizure with impaired attention characterized by impairment of awareness at some point during the seizure. (Unchanged from the original.)


The definition is just a refinement of Focal cognitive seizure with impaired attention (Like most of the focal seizures with specified awareness or impaired awareness).

**Comment by pnrobinson** [comment]
OK, thanks, adding term!
