### ISSUE TITLE
Revise logical def for HP_0001762 'Talipes equinovarus'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#5542]
In the [HP-MP mapping spreadsheet](https://docs.google.com/spreadsheets/d/1RMVorUO092l4CNnieazkgVT4U14u5ptlAQqQ2DLHbIU/edit#gid=1315360953), MP_0000576 clubfoot is equivalent to HP_0001883 Talipes, based on equiv logical definitions.

I think the logical definition should be removed from HP_0001883 Talipes and added to HP_0001762 'Talipes equinovarus'

'has part' some 
    (clavate
     and ('inheres in' some pes)
     and ('has modifier' some abnormal))

**Comment by drseb** [comment]
Why is the def of talipes wrong and better suited for talipes eq.?

**Comment by pnrobinson** [comment]
what does 'clavate' mean?

**Comment by sbello** [comment]
Hi Peter,
clavate in PATO means club-shaped ( http://purl.obolibrary.org/obo/PATO_0001883  for the more technical description) Based on the xrefs for the PATO term it looks like it was created to be used in the MP eq for clubfoot.
@drseb this came up because the MP term for clubfoot (MP:00005760) has the same eq as that of Talipes but based on the text definitions Anna and I thought it should map to talipes eq. so we asked Nicole to look into this on slack.
Sue

**Comment by pnrobinson** [comment]
prob OK to move the def to Talipes. We should revisit our definitions, there is a typo.

**Comment by nicolevasilevsky** [comment]
The text def for Talipes is:
A deformity of foot and ankle that has different subtypes that are talipes equinovarus, talipes equinovalgus, talipes calcaneovarus and talipes calcaneovalgus.

@pnrobinson Do you mean it is okay to move the logical def to HP_0001762 'Talipes equinovarus'?

The text def is:
Talipes equinovarus (also called clubfoot) typically has four main components: inversion and adduction of the forefoot; inversion of the heel and hindfoot; equinus (limitation of extension) of the ankle and subtalar joint; and internal rotation of the leg.

**Comment by pnrobinson** [comment]
The def should live at Talipes
the "equinovarus" is an additional specification!

**Comment by nicolevasilevsky** [comment]
Ok, thanks @pnrobinson.

**Comment by nicolevasilevsky** [comment]
I think this can be closed, as no action is needed.

**Comment by drseb** [comment]
I think we need to move some of the layperson synonyms to the parent class.

**Comment by sbello** [comment]
Some questions I'm left with:
Do all Talipes have the 'club' shape and the additional feature is the rotational position? Looking at the children of Talipes it seems like this is not the case? Looking at HP:0001884 the definition talks about flexibility. Basically my question is would all types of Talipes be considered club/clavate and the equinovarus is one specific type of clubfoot? 
Nicole asked about creating a new parent term in MP and moving the MP eq to this but I'm not certain what the MP parent would be. Looking at the annotations to the MP term. I think we have been using this as equivalent to Talipes. So possibly the eq match is good but the MP term should be relabeled or we need a new parent that is just talipes and the annotations need review. I'll add an MP ticket to look at this. Ticket is https://github.com/obophenotype/mammalian-phenotype-ontology/issues/3178

**Comment by pnrobinson** [comment]
@sbello Talipes is a general grouping term, see the definition here
https://hpo.jax.org/app/browse/term/HP:0001883

The logical definitions are both wrong, in my opinion, since these are complex malformations (actually bundled terms), that are nonetheless clinically useful and used a lot. I do not think it makes any sense to try to make logical defs for these terms at this time.
