### ISSUE TITLE
11q22.2q22.3 Microdeletion Syndrome

### ISSUE THREAD

**Issue by EZapataAldana** [obophenotype/human-phenotype-ontology#5592]
**HPO term**
Muscular Hypotonia

**Bug description**
11q22.2q22.3 microdeletion syndrome is a rare chromosomal anomaly characterized by mild intellectual disability, developmental delay, short stature, hypotonia and dysmorphic facial features. Anxiety and short attention span have also been reported.
There is no Muscular affection per se, thus it should be classified under Central Hypotonia HP:0011398
[2015. Yelavarthi. Partial monosomy of 11q22.2q22.3.pdf](https://github.com/obophenotype/human-phenotype-ontology/files/4530411/2015.Yelavarthi.Partial.monosomy.of.11q22.2q22.3.pdf)

**Comment by pnrobinson** [comment]
This is also an Orphanet entry, see https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=23473&Disease_Disease_Search_diseaseGroup=11q22-2q22-3&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=11q22-2q22-3-microdeletion-syndrome&title=11q22.2q22.3%20microdeletion%20syndrome&search=Disease_Search_Simple

**Comment by pnrobinson** [comment]
Looking at the current HPO structure, I am wondering if it would be better to obsolete the term called Central hypotonia, because as far as I know the phenotype is not distinguisable between central and peripheral hypotonia? This would mean also renaming the current term "Muscular hypotonia" (https://hpo.jax.org/app/browse/term/HP:0001252) to simply Hypotonia. @EZapataAldana  comments?

**Comment by EZapataAldana** [comment]
Hello Peter,
Thanks for taking the time to tackle this; I do not agree with eliminating the term “central hypotonia” and mesh peripheral and central hypotonia in just “hypotonia”. The reasoning is that: 1) We can clinically distinguish the etiology of the hypotonia (if it is due to a lower or upper motor neuron lesion) and 2) There are disorders that just affect the peripheral nervous system or the central nervous system, but most important, there are few disorders that affect both.
HPO is a great tool that helps us clinicians to reach a diagnosis, and if we eliminate well stablished terms and make them more ambiguous, it could complicate process.
ez

**Comment by pnrobinson** [comment]
@EZapataAldana  Sorry for my very delayed follow up.
As mentioned in our email discussion, the HPO does not attempt to encode etiology, instead the terms are meant to describe the actual clinical (phenotypic) observations. 

Therefore, it does seem better to merge the terms Central hypotonia and Muscular hypotonia and to rename the term simply to Hypotonia. 
We can add the terms
-- Central hypotonia
-- Peripheral hypotonia/Muscular hypotonia as narrow synonyms.

Here is the proposed definition. If you have any suggestions I would love to hear them


definition: Hypotonia is an abnormally low muscle tone (the amount of tension or resistance to movement in a muscle). Even when relaxed, muscles have a continuous and passive partial contraction which provides some resistance to passive stretching. Hypotonia thus manifests as diminished resistance to passive stretching. Hypotonia is not the same as muscle weakness, although the two conditions can co-exist. PMID: 21418198

Comment: Hypotonia can be caused by abnormalities of the central nervous system, any element of the lower motoneuron, or both. Hypotonia is not a specific diagnosis, but can be obsereved in hundreds of genetic and other diseases. The first distinction to make when assessing a child with hypotonia is whether decreased muscle tone is a result of an abnormality of the central nervous system (CNS), peripheral neuromuscular system, or a combined abnormality involving both. Clinical findings suggestive of an abnormality of the CNS may include hyperreflexia, cognitive developmental delay, and seizures. In contrast, physical findings pointing towards a neuromuscular origin may include weakness, lack of antigravity movements, muscle atrophy, fasciculations, and/or diminished reflexes, most often in the context of normal cognitive function. The HPO term does not distinguish between these etiologies. Additional HPO terms should be used as required to describe associated features.

**Comment by EZapataAldana** [comment]
Hello @Peter Robinson<mailto:Peter.Robinson@jax.org>
Thank you very much for having the chance to continue with my inquiry regarding the HPO definition for hypotonia.
I completely agree with your suggestion of merging both types of hypotonia and consider to divide in the two terms.
Regarding the "comment" section I just have one suggestion: "... Hypotonia can be caused by abnormalities of the central nervous system, any element of the lower motoneuron motor unit,  or both..." (Change "lower motorneuron" to "motor unit" because the definition is broader).
I would like to continue helping to improve the neuromuscular side of HPO.

Cheers,

Eugenio.

**Comment by pnrobinson** [comment]
@EZapataAldana  -- please note, I was suggesting adding 
Central hypotonia and Peripheral hypotonia as synonyms not as child terms because the phenotype itself is not different (it as associated with many different other phenotypic features in central and peripheral diseases, but HPO codes one thing at a time).
We'd be happy to have your future input for the HPO either via the tracker or feel free to contact me by email (which can be found here https://pubmed.ncbi.nlm.nih.gov/33264411/)

**Comment by EZapataAldana** [comment]
Ok, agreed. In terms of a phenotype they are not different, but the etiology is. As a clinician I have a hard time to wrap that in my mind. Thank you for letting me continue having future input for the HPO!
Best,
Eugenio.
