### ISSUE TITLE
Confirm cell type for Abnormal/Elevated/Reduced proportion of CD4+CD25+ regulatory T cells

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#5688]
**HPO term**
HP_0020111|HP_0020112|HP_0020113
Abnormal/Elevated/Reduced proportion of CD4+CD25+ regulatory T cells

**Bug description**

1.  Trying to confirm cell type and match with CL.  Is this [CL:0000792 | A CD4-positive, CD25-positive, alpha-beta regulatory T cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000792)?  The text definition also says 'Natural Treg' which is different ([CL_0000903|Natural T-regulatory cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000903)), which is defined as "CD4-positive alpha-beta T cell with the phenotype FoxP3-positive, CD25-positive, CD62L-positive, and CTLA-4 positive with regulatory function."

1. There is no mention in the HP textual definition with what it is proportional towards.  I assume T cells, but it isn't clear.

1. These are listed as 'Abnormal', 'Elevated', 'Reduced' for the various terms, but the majority of these term use 'Abnormal', Increased', 'Decreased'.  Could we change the labels to match the others?

This is related to #4289

**Comment by pnrobinson** [comment]
I think by default all of the current cells are alpha/beta unless specifically called gamma/delta. But we should specify that. I think that CD4+CD25+ regulatory T cells is the superclass (https://pubmed.ncbi.nlm.nih.gov/15036232/) and that the cells can be further specified by additional markers. Prob the definition is wrong.

**Comment by nicolevasilevsky** [comment]
I agree that T cells are by default are alpha/beta.

1. I think these HPO terms should use CL:0000792 CD4-positive, CD25-positive, alpha-beta regulatory T cell
2. The logical def will say the abnormal (or increased or decreased) proportion of Tregs is abnormal relative to just generic cells, so I think we specify that it is relative to any cell population. That provides some more flexibility for using this term.

How about this as a revised text def:
A deviation from the normal proportion of CD4-positive, CD25-positive, alpha-beta regulatory T cells in the blood, relative to another population of cells. 

There is a comment on this term explaining some of the difficulty with identifying Tregs, which I think is helpful, and with this comment, I think it's sufficient to leave our text def a little more vague and flexible.

Comment:
Identification of Treg cells remains problematic, because accumulating evidence suggests that all the presently-used Treg markers (CD25, CTLA-4, GITR, LAG-3, CD127 and Foxp3) represent general T-cell activation markers, rather than being truly Treg-specific.

3. Yes, I think we should make the labels consistent.

**Comment by nicolevasilevsky** [comment]
I added this to the appropriate spreadsheets. In spreadsheets, I used the new label (with increased instead of elevated, etc). @matentzn will the tsv spreadsheet override the existing label? (That is the desire. If not, I can fix it in Protege.)

I will update the text def in Protege.

Then I think this ticket can be closed? @LCCarmody

**Comment by matentzn** [comment]
@nicolevasilevsky The spreadsheet wont overwrite existing labels - that stuff needs to be handled manually!

**Comment by nicolevasilevsky** [comment]
got it - I just relabled the terms on a PR
