### ISSUE TITLE
Question about synonym HP_0000964 (Eczema)

### ISSUE THREAD

**Issue by edfoster10** [obophenotype/human-phenotype-ontology#574]
Nicole and I see that Dermatitis is an exact synonym for Eczema, but aren't these separate terms/conditions?

**Comment by markengelstad** [comment]
yes, they are different classes.

eczema is a synonym for 'atopic dermatitis'
'atopic dermatitis' is a subtype of dermatitis

**Comment by pnrobinson** [comment]
According to the national eczema association (https://nationaleczema.org/eczema/types-of-eczema/), Eczema is a general term for any type of dermatitis or “itchy rash”. This is a difficult area to model because much of the literature mixes up diseases and phenotypic features. Eczema is best conceptualized as a disease, and we need to include the phenotypic features of the disease here. 
However, I think for now it would be good to put "dermatitis" as a related_synonym of the term "Inflammatory abnormality of the skin". We are hoping to work together with the UK dermatologists on making this entire section more robust, stay tuned!
