### ISSUE TITLE
Term-gene relation missing

### ISSUE THREAD

**Issue by marc-sturm** [obophenotype/human-phenotype-ontology#5783]
Hi,

I'm not sure this is the right place to request this, but I wanted to report a missing term-gene relation.

The term "HP:0001022 - Albinism" should be associated to the gene HPS3, but is missing.

Evidence for this can be found e.g. here:
https://ghr.nlm.nih.gov/condition/hermansky-pudlak-syndrome#genes
https://de.wikipedia.org/wiki/Hermansky-Pudlak-Syndrom

Best,
  Marc

**Comment by pnrobinson** [comment]
This is Hermansky-Pudlak syndrome 3.
Actually, this syndrome is not characterized by classic albino hypopigmentation, see the original publication. Note that there are multiple types of Hermansky-Pudlak syndrome and they do have phenotypic differences.

Hair, skin and
eye pigmentation (top panels), iris transillumination (mid-
dle panels) and wet-mount electron microscopy of platelets
(bottom panels) in a non-HPS albino (left) and a member of
the central Puerto Rican HPS population (patient E-II-1,
patient #2 of ref. 14). Note the mild degree of skin and hair
hypopigmentation in the HPS patient and her minimal iris
transillumination compared with the classical albino
patient. (Iris transillumination is the appearance of light,
shone through the pupil, in the iris because there is insuffi-
cient iris pigment to block transmission.) https://pubmed.ncbi.nlm.nih.gov/11455388/


I have added terms for Mild hypopigmentation that will be available in the next release in August. 
If you have evidence about HPS3 specifically (article published in PubMed), please reopen this issue.

Thanks!
