### ISSUE TITLE
Chilblains additional parent classes

### ISSUE THREAD

**Issue by cmrn-rhi** [obophenotype/human-phenotype-ontology#5822]
**Chilblains** (HP:0009710)

**Suggested revision and reasons**
Definition states it presents "...on the dorsal aspect of the **fingers**, **toes**, **ears**, and **nose**."
Is currently only a subclass of **Abnormality of finger** (HP:0001167).

Recommend adding the following parent classes:
* **Abnormality of toe** (HP:0001780)
* **Abnormality of the nose** (HP:0000366)
* **Abnormality of the nose** (HP:0000366)

**Comment by pnrobinson** [comment]
Chillblains are usually on the hands or feet. We should revise the definition. I am not sure we need to have separate terms for each of the localizations.
Note that if we add these superclasses, this would mean for OWL that if a patient had a chillblain on a finger, it would (wrongly) be classified as an abnormality of the nose. The only solution would be to create separate terms such as Finger chillblain, Toe chillblain, Node chillblain etc. 
To my knowledge, there is no medical utility of this for the differential diagnosis, and so it would add complexity with little benefit. However, this is not my area of expertise, let me know otherwise!

**Comment by cmrn-rhi** [comment]
> Note that if we add these superclasses, this would mean for OWL that if a patient had a chilblains on a finger, it would (wrongly) be classified as an abnormality of the nose.

Currently the same could be said about the current structure; e.g. if a patient had chilblains on a toe or the nose, it is wrongly classified as an abnormality of the finger. However, perhaps a definition revision is in order since it can occur on other parts of the body (e.g. ears and legs), it just usually occurs on the hands, feet (toes, heels, etc), and/or face.

I feel like benefit would be derived from having the terms separated by anatomical part (like HP does with 'swelling' and various other terms). The reason this entry came to my attention is I was looking for something along the lines of "pseudo/infection induced chilblains" for contextual data collection on "COVID toes" and "COVID fingers". However, since those aren't true chilblains, and consequently I wouldn't be using the term under these circumstances, and perhaps it's wrong to assume medical utility for creating narrower 'chilblains' terms just because I would find value in the existence of narrow 'pseudo-chilblains' terms.

**Comment by pnrobinson** [comment]
After some thought, it seems better to place chilblains as a child of Inflammatory abnormality of the skin (https://hpo.jax.org/app/browse/term/HP:0011123). Thanks for pointing out the inconsistency, the fix should be visible with the August release.
