### ISSUE TITLE
Milky appearance of BAL fluid

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#5879]
@mgriese, @katrinknoflach

Do we need a term like this?

See

https://ojrd.biomedcentral.com/articles/10.1186/s13023-014-0171-z

**Comment by mgriese** [comment]
yes, is commonly used.
Return of lavage fluid characteristically has a milky apperance in pulmonary alveolar proteinosis. This is due to admixture of pulmonary surfactant, which is a lipoprotein complex.

**Another (new) term may be 
Bloody appearance of BAL fluid 
Return of lavage fluid characteristically has a bloody apperance in pulmonary alveolar hemorrhage. This is due to admixture of blood, which typically increases with each consecutive lavage portion. Microscopically erythrocytes can be seen. After 24 to 48 h macrophages contain phagocytosed erythrocytes, indicating previous bleeding.

**Comment by pnrobinson** [comment]
added terms
