### ISSUE TITLE
NTR: Emotional insecurity

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#6056]
**Preferred term label:**
Emotional insecurity

**Synonyms**
Insecure
Insecurity

**Definition (free text, please give PubMed ID)**
A feeling of general unease or nervousness that may be triggered by perceiving of oneself to be vulnerable or inferior in some way, or a sense of vulnerability or instability which threatens one's self-image or ego.
https://en.wikipedia.org/wiki/Emotional_security

**Parent term (use hpo.jax.org/app)**
Impairment in personality functioning

**Comment by nicolevasilevsky** [comment]
@pnrobinson I can add this term if it looks okay to you

**Comment by pnrobinson** [comment]
I do not think the definition is accurate. Here is another try:

Reduced emotional security, which can be defined as deficits in emotional reactivity (inability to develop an attitute of resistenace or vigiliance in the presence of potentially threatening situations), behavior regulation (inappropriate behavioral response to threatening situations characterized by either overinvolvement in the situation or by the avoidance of it) and inappropriate internal representations (exaggerated conscious or unconscious schemas of potential danger).
Sources https://pubmed.ncbi.nlm.nih.gov/7809306/
@bcoleman96 thoughts?

**Comment by bcoleman96** [comment]
Because psychology is so focused on patient communication, I think it's reasonable to use a definition consistent with the laymen's understanding. @pnrobinson I think your definition might be limited for the framework of Emotional Stability Theory and thus not general enough. I think the Wikipedia definition does a good job of capturing what a patient would mean when self-reporting this phenotype and what I would guess a psychiatrist would mean when including it in a clinical note because it emphasizes an unstable self-image which would lead to "emotional reactivity" and poor "behavior regulation". I also think it is relevant for pertinent pathologies (avoidant and borderline personality disorders).

**Comment by pnrobinson** [comment]
@bcoleman96 @nicolevasilevsky 
Should this be the parent
https://hpo.jax.org/app/browse/term/HP:0100851
instead of or in addition to the proposed parent Impairment in personality functioning

**Comment by pnrobinson** [comment]
added
