### ISSUE TITLE
Missing HP_0003614 (Trimethylaminuria) - MONDO_0011182 ("trimethylaminuria (disease)") xref 

### ISSUE THREAD

**Issue by AsierGonzalez** [obophenotype/human-phenotype-ontology#6166]
Hello, posting this under Typos/Bugs/Errors as I could not find a better category for a missing xref.

**HPO term**
[Trimethylaminuria - HP_0003614](http://purl.obolibrary.org/obo/HP_0003614)

**Bug description**
HP_0003614 seems to be equivalent to the MONDO term [MONDO_0011182- "trimethylaminuria (disease)"](http://purl.obolibrary.org/obo/MONDO_0011182). In fact the MONDO term has a xref to HP_0003614. We use HPO as part of EFO and one of our algorithms would benefit from HP_0003614 having a xref to MONDO_0011182.

I understand that you may have reservations about linking phenotypes to disease, so I wonder if you agree that the two terms are equivalent? And, if so, could the xref to MONDO be added?

**Comment by pnrobinson** [comment]
The term is not equivalent to the MONDO term. The disease entity Trimethylaminuria "is characterized by an unpleasant body odor reminiscent of rotting fish. The condition is due to the excretion of abnormally high levels of the volatile tertiary aliphatic amine trimethylamine (TMA) in the urine, sweat and breath...In adulthood, affected individuals often face relationship problems and suffer from low self-esteem; in turn, this may lead to social isolation, alcoholism, depression and even suicidal tendencies. In childhood, affected individuals tend to be shunned, ridiculed, or bullied at school, leading to aggressive or disruptive behavior and poor educational performance. ." (https://ojrd.biomedcentral.com/articles/10.1186/s13023-019-1174-6)

The HPO term refers to the biochemical finding in the urine. This is the computational model of the disease:
https://hpo.jax.org/app/browse/disease/OMIM:602079

For better or worse, the same English word is used to refer to disease entities and the most important phenotypic feature of the disease, and there are many cases of this in HPO/MONDO. You can always assume that the HPO term is talking about the phenotypic feature. @cmungall @nicolevasilevsky MONDO should use a different relation (not 'equivalent'), perhaps something like 'characteristic phenotypic feature' in cases like this.

**Comment by pnrobinson** [comment]
Note also "Trimethylamine metabolism may also be impaired in patients with chronic liver disease. A case of congenital intrahepatic portal–systemic shunt associated with trimethylaminuria has been reported.". The HPO website needs to be extended to better show the triggered-by annotations btw.

**Comment by AsierGonzalez** [comment]
Thank you for the response @pnrobinson. I have to clarify that the statement about  HP_0003614 being "equivalent" to MONDO_0011182 is how I interpret the xref in MONDO as there is no more information.

It is interesting that you say that I "can always assume that the HPO term is talking about the phenotypic feature". Does this mean that HPO don't represent diseases? Or are they combinations of phenotypes? It's interesting that the computational model of trimethylaminuria is identified using an OMIM id, as OMIM is not an ontology. Is this standard in HPO?

**Comment by pnrobinson** [comment]
Well, OMIM is the standard in genetics (one of the most valuable resources out there!) and so most users will expect to see OMIM terms. Under the hood we also map to MONDO which is our disease ontology, and we will start to link to this on the website in the future. There is some documentation about the scope of the HPO on the website, e.g. https://hpo.jax.org/app/help/introduction, please let me know if this is a good introduction or if we need to improve it!

**Comment by AsierGonzalez** [comment]
Thanks for pointing me to the documentation, it was very useful. I was not aware that HPO started building an ontology on top of OMIM descriptions, I know understand why you use those ids. Also good to know that you will start linking to MONDO in the future. Will HP_0003614 be linked to any MONDO term or is this yet to be decided?
