### ISSUE TITLE
Add Synonym: Dysuria

### ISSUE THREAD

**Issue by callahantiff** [obophenotype/human-phenotype-ontology#6223]
**HPO term**
Dysuria (`HP:0100518`)  

**Synonym to be added**
Painful urging to urinate

**broad/exact/narrow/plural/abbreviation ?**
Exact

**Comment by pnrobinson** [comment]
I think dysuria refers to pain while urinating, and not to a painful urge to urinate. Probably this concept is closer to https://hpo.jax.org/app/browse/term/HP:0000012. Let's see if we need to add a child term.

**Comment by pnrobinson** [comment]
I think this is probably two different features -- dysuria (pain while urinating) and urgency. Often these features go together, and so I am guessing that this description is combining two features rather than defining actual painful urgency (pain before actually urinating). Please reopen this with more information if needed.
