### ISSUE TITLE
NTR: Thickened basement membrane with dense deposits (level 5)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#6289]
Thickened basement membrane with dense deposits (level 5)
parent:Thickened glomerular basement membrane (NEW TERM)
def:Prominent GBM reflecting an diffuse and relativly uniform increase in thickness (subjective estimate) with elongated or ribbon-like intramembranous electron-dense deposit, replacing all or part of the width of the lamina densa @avizrosenberg @yongqunh

**Comment by avizrosenberg** [comment]
What is outstanding here?

**Comment by pnrobinson** [comment]
@avizrosenberg  -- I am wondering if we can label this term 

Glomerular basement membrane dense deposits

Otherwise, the term label sounds like it is describing a combination of two things (thick GBM and dense deposits).
My understanding is that dense deposits pretty much always go along with thickening of the GBM but that there are other causes of a thick GBM.
If this is OK, then I can add all of the terms underneath this hierarchy in an analogous fashion.

**Comment by yongqunh** [comment]
I searched and found some references:
https://pubmed.ncbi.nlm.nih.gov/368430/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2615696/ 
https://en.wikipedia.org/wiki/Membranoproliferative_glomerulonephritis 

based on the above wiki page, "Membranoproliferative glomerulonephritis (MPGN) is a type of glomerulonephritis caused by deposits in the kidney glomerular mesangium and basement membrane (GBM) thickening, activating complement and damaging the glomeruli."
Then there are three types of MPGN based on what are deposited:
Type I, the most common by far, is caused by immune complexes depositing in the kidney.
Type II: deposition of complement C3 
Type III is very rare, it is characterized by a mixture of subepithelial and subendothelial immune and/or complement deposits. 

Not sure if we need to includes the three types of deposits as subclasses.

**Comment by pnrobinson** [comment]
@avizrosenberg @yongqunh 
My main question with these terms is that they are "bundled" -- the have (1) thickend GBM AND (2) something else (dense deposits...).
I would prefer to code the two parts of each of these terms separately. -- Is this reasonable?

**Comment by yongqunh** [comment]
Separating them is reasonable.

**Comment by pnrobinson** [comment]
@yongqunh @avizrosenberg Thanks, I will implement the terms like this. We will be releasing a new version in about ten days that should then have essentially all of the requested KPMP terms for your inspection.
This term was added as 
HP:0033499
name: Glomerular basement membrane electron dense deposits
definition:Electron-dense deposits in the lamina densa with a ribbon or a sausage structure.
comment:See Figure 1 of PMID:33329990 for an example.
