### ISSUE TITLE
Immunohistochemistry findings relevant to various cancers should be added to HPOs

### ISSUE THREAD

**Issue by ykurtzke** [obophenotype/human-phenotype-ontology#6450]
[20201116 HPO Suggestions Immunohistochemistry.docx](https://github.com/obophenotype/human-phenotype-ontology/files/5548385/20201116.HPO.Suggestions.Immunohistochemistry.docx)

**Comment by pnrobinson** [comment]
@ykurtzke  Thanks for these suggestions. We are currently brainstorming some overall structures for this part of the HPO and hope to start work on this section shortly, sorry for the delay.

**Comment by pnrobinson** [comment]
@ykurtzke 
Sorry for the very late delay. In the meantime, we have figured out the design pattern and done a pilot study with lymphoma phenotypes. I think we would want to rework the suggestions from 2020 to fit into this new design pattern. I am going to close this for now because we will be working on the entire section. If you are interested please contact me by email.
