### ISSUE TITLE
Structure around "Abnormality of the orbital region"

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#653]
Previous comments were #581 and #587 

We need a longer session for this. We have to clearly separate morphology from general abnormalities. Let's meet for an hour @pnrobinson

**Comment by pnrobinson** [comment]
All of the terms in "Abnormality of the orbital region" refer to morphology. This is a general issue with HPO term names, that do not always reflect the morphology/function divide. Need to come up with a general plan here, but I am closing this issue for now.

**Comment by drseb** [comment]
I disagree. As written before there are subclasses that are clearly not **abnormal morphology**, such as *Weak extraocular muscles*

see also https://github.com/obophenotype/human-phenotype-ontology/issues/581

**Comment by pnrobinson** [comment]
I have removed the explicit link of Weak extraocular muscles to this part of the hierarchy, and renamed the parent class with morphology. The reasoner still infers that weakness is a morphological abnormality because we are using E/Q with the Pato "decreased strength".I do not see any way to define this otherwise in GO (there is a GO term for motor behavior, but not much underneath that). 
I am going to add this to the HPO wiki -- how do we logically define weakness? The same issue will affect numerous terms.

**Comment by drseb** [comment]
I don't think this was the best way to solve this and rather improves the chaos in that region of HPO. The weakness was just one example of several of such cases
