### ISSUE TITLE
Neoplasm of the stomach HP:0006753

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#6553]
**HPO term**
Neoplasm of the stomach HP:0006753

**Bug description**

Suggest removing the synonym "Increased gastric cancer" from this term. 
The term "cancer" carries a connotation of malignancy that is not inherent to the term "neoplasm" or even "tumor." There is already a child term (Stomach cancer HP:0012126) that includes "gastric cancer" as synonym, so the concept of gastric cancer seems to already be appropriately captured within HPO.

**Comment by nicolevasilevsky** [comment]
This synonym was a related synonym, but I agree it should be removed, as it sounds very awkward. I removed this on PR #6556.

I also changed the scope of the synonym 'Cancer of the pancreas' to broad for HP_0002894 'Neoplasm of the pancreas'

cc @pnrobinson

**Comment by drseb** [comment]
Wouldn’t it be better to move the synonym instead of removing it?

**Comment by pnrobinson** [comment]
I think the issue is that "increased gastric cancer" refers to a cohort -- an overall increased risk. However, the way HPO is structured, the phenotypes are supposed to refer to an individual patient (who either has gastric cancer or not). We express increased frequencies at least indirectly in the annotation files. 
We actually do not have a great way of saying that for some disease the overall risk of a phenotypic feature such as cancer is increased. I do not think this would be easy to do without some major biocuration and software engineering.
Therefore, for now I would vote for deleting the synonym "increased gastric cancer"

**Comment by drseb** [comment]
But there must be a reason it was included in the first place so maybe there is a use-case for it. If you’re sure there isn’t, go ahead and delete it

**Comment by nicolevasilevsky** [comment]
There is a pending PR where I deleted it. @pnrobinson do you want to make the final decision? :)

**Comment by pnrobinson** [comment]
@drseb  I think I probably added this synonym from the OMIM CS a long time ago before I knew better!
@nicolevasilevsky please accept the PR!
