### ISSUE TITLE
Add definition to HP:0002140 Ischemic stroke

### ISSUE THREAD

**Issue by mshadbolt** [obophenotype/human-phenotype-ontology#6558]
**HPO term**
HP:0002140 Ischemic stroke

**Suggested revision of textual definition**
There is currently no definition, suggested definition:

A stroke where blood supply to the brain is reduced or ceased.

synonyms: ischaemic stroke

**Comment by pnrobinson** [comment]
Thanks for pointing this out! We generally like to provide PMIDs with links for users; I found this slightly expanded definition with link, what do you think?
def: Acute ischemic stroke (AIS) is defined by the sudden loss of blood flow to an area of the brain with the resulting loss of neurologic function. It is caused by thrombosis or embolism that occludes a cerebral vessel supplying a specific area of the brain. During a vessel occlusion, there is a core area where damage to the brain is irreversible and an area of penumbra where the brain has lost function owing to decreased blood flow but is not irreversibly injured. 
https://pubmed.ncbi.nlm.nih.gov/32054610/

**Comment by pnrobinson** [comment]
thanks, again, adding -- please reopen if further attention is needed.
