### ISSUE TITLE
blue irides

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#672]
Is there a better primary term name that will indicate this is an abnormal phenotype?

**Comment by pnrobinson** [comment]
After review, I think we should leave the term name as is. Even though there are some genetic disorders characterized by "unexpectedly" blue irides, the phenotype is not abnormal in itself, and to encode the "bundled" situation when one might use this term into the term name would not really be any clearer to users of the HPO not familiar with these diseases.

**Comment by cmungall** [comment]
I'm not following

"the phenotype is not abnormal in itself"

clearly "blue irises" when used in a general context is not abnormal, but clearly the HPO class is abnormal:

```
 is_a HP:0000118 ! Phenotypic abnormality
   is_a HP:0000478 ! Abnormality of the eye
    is_a HP:0012372 ! Abnormal eye morphology
     is_a HP:0012374 ! Abnormality of the globe
      is_a HP:0000553 ! Abnormality of the uvea
       is_a HP:0000525 ! Abnormality of the iris
        is_a HP:0008034 ! Abnormal iris pigmentation
         is_a HP:0000635 ! Blue irides *** 
 ```

> nd to encode the "bundled" situation when one might use this term into the term name

no idea what you mean here

**Comment by pnrobinson** [comment]
I mean that users need to infer we are talking about an „abnormally“ blue iris color from the context, and I cannot think of a way of saying this in the label!
-Peter

Von: Chris Mungall [mailto:notifications@github.com]
Gesendet: Donnerstag, 17. März 2016 17:47
An: obophenotype/human-phenotype-ontology <human-phenotype-ontology@noreply.github.com>
Cc: Robinson, Peter <peter.robinson@charite.de>
Betreff: Re: [human-phenotype-ontology] blue irides (#672)


I'm not following

"the phenotype is not abnormal in itself"

clearly "blue irises" when used in a general context is not abnormal, but clearly the HPO class is abnormal:

 is_a HP:0000118 ! Phenotypic abnormality

   is_a HP:0000478 ! Abnormality of the eye

    is_a HP:0012372 ! Abnormal eye morphology

     is_a HP:0012374 ! Abnormality of the globe

      is_a HP:0000553 ! Abnormality of the uvea

       is_a HP:0000525 ! Abnormality of the iris

        is_a HP:0008034 ! Abnormal iris pigmentation

         is_a HP:0000635 ! Blue irides ***

nd to encode the "bundled" situation when one might use this term into the term name

no idea what you mean here

**Comment by mellybelly** [comment]
see also
http://monarch-initiative.blogspot.com/2015/01/how-to-annotate-patients-phenotypic.html


On Mar 17, 2016, at 9:51 AM, Peter Robinson <notifications@github.com> wrote:

I mean that users need to infer we are talking about an „abnormally“ blue iris color from the context, and I cannot think of a way of saying this in the label!
-Peter

Von: Chris Mungall [mailto:notifications@github.com]
Gesendet: Donnerstag, 17. März 2016 17:47
An: obophenotype/human-phenotype-ontology <human-phenotype-ontology@noreply.github.com>
Cc: Robinson, Peter <peter.robinson@charite.de>
Betreff: Re: [human-phenotype-ontology] blue irides (#672)


I'm not following

"the phenotype is not abnormal in itself"

clearly "blue irises" when used in a general context is not abnormal, but clearly the HPO class is abnormal:

is_a HP:0000118 ! Phenotypic abnormality

is_a HP:0000478 ! Abnormality of the eye

is_a HP:0012372 ! Abnormal eye morphology

is_a HP:0012374 ! Abnormality of the globe

is_a HP:0000553 ! Abnormality of the uvea

is_a HP:0000525 ! Abnormality of the iris

is_a HP:0008034 ! Abnormal iris pigmentation

is_a HP:0000635 ! Blue irides ***

nd to encode the "bundled" situation when one might use this term into the term name

no idea what you mean here

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub<https://github.com/obophenotype/human-phenotype-ontology/issues/672#issuecomment-197969464>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/obophenotype/human-phenotype-ontology/issues/672#issuecomment-197970918>

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu
skype: melissa.haendel
503-407-5970
Appointments: Shanez De Silva desilva@ohsu.edu

**Comment by cmungall** [comment]
But there is no option of talking about HP:0000635 in a non-abnormal 
context. The hierarchy places it into an abnormal context. Any attempt 
to use it in a normal context will yield either inconsistencies (on the 
OWL reasoning level) or confusion (at the human reasoning level: e.g. 
what are the patient curation guidelines for 'blue irides'? Can I use it 
for normally blue? Or does it have to be 'markedly' blue?)

**Comment by pnrobinson** [comment]
Yes, but blue iris etc is the community accepted label, and given there is no option of talking about this term in a non-abnormal context there should not be a problem….

Von: Chris Mungall [mailto:notifications@github.com]
Gesendet: Donnerstag, 17. März 2016 18:53
An: obophenotype/human-phenotype-ontology <human-phenotype-ontology@noreply.github.com>
Cc: Robinson, Peter <peter.robinson@charite.de>
Betreff: Re: [human-phenotype-ontology] blue irides (#672)


But there is no option of talking about HP:0000635 in a non-abnormal
context. The hierarchy places it into an abnormal context. Any attempt
to use it in a normal context will yield either inconsistencies (on the
OWL reasoning level) or confusion (at the human reasoning level: e.g.
what are the patient curation guidelines for 'blue irides'? Can I use it
for normally blue? Or does it have to be 'markedly' blue?)
