### ISSUE TITLE
Term request: brachysyndactyly

### ISSUE THREAD

**Issue by jmcmurry** [obophenotype/human-phenotype-ontology#675]
"Abnormal shortness of fingers or toes combined with a webbing between the adjacent digits."
Source: http://medical-dictionary.thefreedictionary.com/brachysyndactyly

Use case: PMC4498842

I do not know how related this is to 	
HP:0012725 Cutaneous syndactyly; a question for @pnrobinson

**Comment by pnrobinson** [comment]
This is a "bundled term", i.e., it is describing two different things. The patient should instead be annotated to
1. short digit
2. cutaneous syndactyly

Occasionally it is a judgment call as to whether a combination deserves its own term, but this should almost always be avoided since then users have two different ways of annotating the same finding (with the "combined term" or with two "simple" terms).
