### ISSUE TITLE
Kinesiophobia

### ISSUE THREAD

**Issue by e-lbtn** [obophenotype/human-phenotype-ontology#6802]
**Preferred term label:**
Kinesiophobia

**Synonyms**

**Definition (free text, please give PubMed ID)**
PMID: 26559820

**Parent term (use hpo.jax.org/app)**
No found because of the specificity of the disease 

**Diseases characterized by this term ? (e.g. Orphanet or OMIM number)**
ORPHA:210272

**Your nano-attribution (ORCID)**

**Comment by pnrobinson** [comment]
I do not think that individuals with this disease actually have kinesophobia as it is described in the literature, 

Kinesiophobia (also known as fear of movement) is defined as an excessive, irrational and debilitating fear to carry out a physical movement, due to a feeling of vulnerability to a painful injury or reinjury.

https://bjsm.bmj.com/content/53/9/554

I think that this is probably better described as Vertigo.
