### ISSUE TITLE
New term - hemifacial microsomia

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#704]
**Proposed definition:**a condition in which the lower half of one side of the face is underdeveloped and does not grow normally

**Synonyms:** craniofacial microsomia, Goldenhar anomaly, otomandibular dysostosis, first and second branchial arch syndrome; oculo-auriculo-vertebral sequence; lateral facial dysplasia

**Superclass:** craniofacial asymmetry (HP:0004484); branchial anomaly (HP:0009794)

http://www.seattlechildrens.org/medical-conditions/chromosomal-genetic-conditions/hemifacial-microsomia/

**Comment by pnrobinson** [comment]
There is a term, HP_0011332, called hemifacial hypoplasia, which is intended to refer to this. We did not use the term hemifacial microsomia because that seems to refer more to the disease. https://en.wikipedia.org/wiki/Hemifacial_microsomia
I have added hemifacial microsomia as a related synonym though.
