### ISSUE TITLE
Better definition for HP:0011016 Abnormality of urine glucose concentration

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7141]
**HPO term**
HP:0011016 Abnormality of urine glucose concentration 

**Suggested revision of textual definition**
I think that because normal level of glucose in urine is zero, instead of definition:
"An abnormality of the concentration of glucose in the urine."
It would be much better to have definition like this one:
"Presence of glucose in the urine."

**Comment by pnrobinson** [comment]
Thanks for pointing this out @turnovec  -- actually, there does not need to be a term "Abnormality of urine glucose concentration" because there is no "Abnormally reduced urine glucose concentration", and therefore, the term "Glycosuria" is sufficient. I am going to obsolete (merge) the "Abnormality of urine glucose concentration"  term.
