### ISSUE TITLE
New term - Pentalogy of Cantrell

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#719]
**Proposed definition:** Failure of ventromedial migration of paired mesodermal structions occuring between 14 and 18 days postconception and leading to midline supraumbilical abdominal wall defect, lower sternal defect, diaphragmatic pericardial defect, anterior diaphragmatic defect and various intracardiac malformations

**Superclass:** thoracoabdominal wall defects (HP:0100656

)http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=1335

**Comment by pnrobinson** [comment]
This seems to be a disease entity (e.g., http://www.omim.org/entry/313850). The HPO sometimes has items that can be both a phenotypic feature (i.e., can be seen as a component of another disease, such as diabetes mellitus) or can be conceptualised as a disease entity. In this case, it seems that this is probably best left as a disease entity alone rather than an HPO term. An exception could be indicated if there are other diseases that feature Pentalogy of Cantrell as a component.
