### ISSUE TITLE
Abnormal fetal long-bone echogenicity

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7209]
Abnormal fetal long-bone echogenicity
Any deviation from the normal degree of echogenicity, which refers to the return of sound waves generated by an ultrasonography transducer. The echogenicity of a bone is related to the amount of calcification of the bones.

Elevated fetal long-bone echogenicity
An abnormally increased degree of echogenicity as compared to gestational age-dependent norms. This feature can indicate increased mineralization of bones.

Reduced fetal long-bone echogenicity
An abnormally decreased degree of echogenicity as compared to gestational age-dependent norms. This feature can indicate reduced mineralization of bones.

**Parent term (use hpo.jax.org/app)**
Abnormal fetal morphology (New term)

**Diseases characterized by this term ? (e.g. Orphanet or OMIM number)**

**Your nano-attribution (ORCID)**

**Comment by patt1morgan** [comment]
Definition: 
A deviation from the normal appearing echogenicity of the fetal bone. Echogenicity refers to the ability of tissue to reflect ultrasound waves back toward the transducer and produce an echo.  Whenever there is an interface of structures with different echogenicities, a visible difference in contrast will be apparent on the screen.  The higher the echogenicity of tissues, the brighter they appear on ultrasound imaging. 

Hyperechoic structures are seen as _brighter_ on the US image relative to surrounding structures due to higher reflectivity of the US beam.

Isoechoic structures  are seen as _bright_ as surrounding structures on conventional US imaging due to similar reflectivity to the US beam.

Hypoechoic structures are seen as _darker_ relative to the surrounding structures on the US image due to the US beam being reflected to a lesser extent.

Anechoic structures that lack internal reflectors fail to reflect the US beam to the transducer and are seen as _homogeneously black_ on imaging.  PMID: 21472065
(https://www.practicalpainmanagement.com/resources/diagnostic-tests/musculoskeletal-ultrasound?page=0,2)

**Reduced  fetal long bone echogenicity** due to hypomineralization is seen in some disorders such as hypophosphatasia, osteogenesis imperfecta and achondrogenesis

**Increased fetal long bone echogenicity** due to hyper mineralization can be seen in Osteogenesis imperfecta Type 5  PMID: 28548288 and homozygous BMP1 mutation PMID: 24091809

**Comment by pnrobinson** [comment]
added terms, thanks @patt1morgan
