### ISSUE TITLE
HPO license?

### ISSUE THREAD

**Issue by PabloBotas** [obophenotype/human-phenotype-ontology#7252]
**HPO license:** As far as I know HPO does not have a standard open source license. We are currently acknowledging HPO according to https://hpo.jax.org/app/license, but we want to know whether you will adopt a license in the future that could force HPO users to revisit how this resource affects the components it is used in. It would be good to have peace of mind regarding this issue as HPO and HPO's resources are pivotal for many projects.

(Sorry, no proper template for this issue)

Thanks!
Pablo

**Comment by pnrobinson** [comment]
Open to suggestions.
What exactly is the problem though, can you be more specific? What in the current license is worrying you?

**Comment by PabloBotas** [comment]
Licenses, even open source ones, may force a code to abide by specific terms or even use a certain license if code/resources are reused. Mondo has CC-4.0, which is a well known legal document. HPO doesn't have one. If in the future one is applied it may force the community to evaluate how HPO is included in their projects.

**Comment by pnrobinson** [comment]
Hi Pablo, we wrote the license in 2008 and it is just as much a legal document as CC-4.0. Being "well-known" is not a requirement for legal documents. There are some specific points in the HPO license that are important to us (https://hpo.jax.org/app/license -- item 2 is the major difference to the CC licenses, but we think it is necessary because of the medical context. We have considered this question multiple times and in the end thought that the existing licenses just are not well adapted. If there is something in the current license that is preventing you from doing something please let us know. Our intention is to be as free and open as possible with the exception of the points in item 2.

**Comment by PabloBotas** [comment]
Hi! Glad to read that you put that much care to this point. I don't have a particular suggestion, I just thought that maybe it wasn't a finished *product*. If it is, I think the terms are ok, so thanks a lot.
