### ISSUE TITLE
Visual impairment HP:0000505 and Abnormality of vision HP:0000504 are descendants of Abnormal eye physiology HP:0012373

### ISSUE THREAD

**Issue by DLewisSmith** [obophenotype/human-phenotype-ontology#7291]
**HPO term**
Visual impairment HP:0000505 and Abnormality of vision HP:0000504 are descendants of Abnormal eye physiology HP:0012373

**Suggested revision and reasons**
Not all forms of VI and Abnormality of vision are abnormalities of the eye. Within the subontology of Abnormal eye physiology HP:0012373 we currently find terms such as Cerebral visual impairment HP:0100704, Homonymous hemianopia HP:0030516, Visual field defect HP:0001123, Color vision defect HP:0000551, and Visual loss HP:0000572. The first is explicitly a cerebral rather than ophthalmic abnormality, the second is usually cerebral but rarely ophthalmic, and the others can be cerebral (but are usually ophthalmic). Teasing these apart would presumably require changing the parentage of Abnormality of vision to something more generic (maybe even to Phenotypic abnormality), and then giving second parentage to the Abnormality of the eye vs Abnormality of the Central nervous system. Thoughts? I am surprised that I could not find a previous discussion of this among the closed issues (apologies if there has been, I have tried to search through them).

**Comment by pnrobinson** [comment]
This is a great example of why it is necessary to split terms into morphology and physiology, because physiology often encompasses multiple anatomic structures. There are multiple ways of addressing this. The first would be to say that eye physiology includes the connections of the eye in the brain (this would allow us to not change things much). The second would be to rearrange the hierarchy with Abnormality of vision being a superterm for cerebral vision issues and eye-related vision issues. 
@psergouniotis could we also touch bases about this -- what would be most natural for ophthalmologists?

**Comment by DLewisSmith** [comment]
Thanks @pnrobinson. I agree with the importance of separating function and anatomy. For me, the tension arises with the use of a single anatomical structure to describe a mutiorgan function.

If a sign of Abnormal brain physiology falls under Abnormality of the eye, should the latter not be called something such as ‘’Abnormality of the visual system’? It seems misleading clinically to infer that Homonymous hemianopia is an eye phenotype rather than brain phenotype. However, it seems reasonable to say that HH is an abnormality of the visual system and an abnormality of brain, where as Cataract is an abnormality of the visual system and an abnormality of the eye.

**Comment by pnrobinson** [comment]
This is a difficult one. Abnormal eye physiology could be renamed to abnormal vision physiology, but this would require that we redo the entire HPO hierarchy (because it is not always true that abnormal vision physiology is abnormal eye physiology, at least not in a narrow sense. Perhaps moving forward we should make the top of the hierarchy branch out into morphology and physiology (and maybe neoplasia as well), but I think we are probably reaching the limits of what can be modeled with a hierarchical ontology. @cmungall @mellybelly Thoughts?

**Comment by pnrobinson** [comment]
I am thinking that for now it is probably best to leave this because even if the defect is in the CNS the physiology is related to the eye in some way. I am going to add Abnormal vision physiology as a broad synonym. I am hopiing to start having some workshops in child neurology @DLewisSmith this year it would be great to touch bases if you are interested in joining live or virtually.
