### ISSUE TITLE
HP:0040124. Patent tuba eustachii

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7324]
Hi Peter,
This concept refers to the Eustachian tube being patent, but this is a normal state. The parent is "abnormality" so I assume it's not a statement of normality. Could you clarify the intention please ?
Thanks for your help again.
Graham Ponting

**Comment by pnrobinson** [comment]
@grahamponting thanks for pointing out this inconsistency. It seems to be an error because as you say this is a normal finding. I will leave this issue open for a bit to see if this term rings a bell with anybody, but probably we will merge/obsolete it. No diseases are annotated to it in our database.

**Comment by pnrobinson** [comment]
merged/obsoleted this term
