### ISSUE TITLE
Erythema subtypes

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7381]
See -- 
https://cms.galenos.com.tr/Uploads/Article_32235/jtad-1-0-En.pdf

**Comment by PaulNSchofield** [comment]
All the types of erythema are listed here: https://dermnetnz.org/search.html?q=erythema. Id use this for nomenclature rather than the paper you mention.  This web site a very high grade resource. We have permission to use the definitions for the Dermo ontology but did not complete the work so dermo is currently lacking some of these but if they should all be in HPO then Im sure with a quick email and an acknowledgement the definitions could be used as they are. There is a standard textbook as well 

ISBN Number | 9780702062759
Dermatology: 2018: 
Jean L. Bolognia, MD, Julie V. Schaffer, MD and Lorenzo Cerroni

**Comment by PaulNSchofield** [comment]
Erythema multiforme, erythema gyratum repens, erythema migrans, erythema marginatum, erythema nodosum, necrolytic migratory erythema, erythema elevatum diutinum, erythema ab igne, annular erythema ( some familial forms), necrotic acral erythema, hand-foot syndrome, are all basically post-natal. Most of these are in Dermo. exc. NME, NAE

Probably more relevant to pregnancy and development are palmar erythema, erythema annulare centrifugatum,  toxic erythema of the newborn, possibly erythema palmare hereditarium. Latter not in Dermo, rest are.  Most are DBXref'd

**Comment by pnrobinson** [comment]
closing for now, we will plan to address this issue in upcoming workshops.
