### ISSUE TITLE
Review of gastrointestinal ulcers 

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/human-phenotype-ontology#7391]
Hello, 

The MP is currently reviewing and trying to reconcile its organization of gastrointestinal ulcers with that in HPO. 

MP Organization (gastrointestinal ulcer is placed under **abnormal digestive system morphology**):

![image](https://user-images.githubusercontent.com/13942924/158898515-9ba0f25f-88f2-4d4a-967b-4b255179253b.png)

HPO Organization (Peptic ulcer is placed under A**bnormality of digestive system physiology**):

![image](https://user-images.githubusercontent.com/13942924/158898609-a3ee3ab7-2376-4cb3-9850-1b84e191f91a.png)

By definition, MP term peptic ulcer [MP:0003301](https://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MP_0003301) (no EQ, synonym: gastroduodenal ulcer | marginal ulcer) specifically refers to “any lesion on the mucosal surface of the portion of the alimentary tract that is exposed to gastric acid, usually in the stomach or the duodenum”.

HPO term Peptic ulcer [HP:0004398](https://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0004398) uses gastrointestinal tract synonymously (Comment: “A peptic ulcer is defined as an erosion of the mucosa of the gastrointestinal tract, and can occur as esophageal ulcer, gastric ulcer, duodenal ulcer, and Meckel's Diverticulum ulcer”).

Both gastrointestinal ulcer [MP:0003300](https://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MP_0003300) and Peptic ulcer [HP:0004398](https://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0004398) use the same EQ:

has part some (increased amount and (characteristic of some (ulcer and (part of some alimentary part of gastrointestinal system))) and (has modifier some abnormal))

Is the MP drawing a distinction that has no/some biological meaning (in terms of exposure to gastric acid)? Should we treat peptic and gastrointestinal ulcers synonymously?

Thanks again, 

Anna

**Comment by pnrobinson** [comment]
The MP definition is more precise (i.e., better) than HP. You can have a colonic ulcer related to NSAID use or a rectal ulcer related to ischemia, for instance, and so not all ulcers in the GI tract are related to gastric acid. Pepsin is of course the main digestive enzyme in the stomach and there is no logical reason to define peptic ulcers in areas exposed to gastric acid since this will be about the same as areas exposed to pepsin. It is of course not the simple exposure to pepsin or gastric acid that causes an ulcer (otherwise, the entire stomach would be one big ulcer all the time), it is the increased susceptibility to digestion by pepsin/gastric acid that contributes to the etiology. Still, I am not sure I find either of the current definitions to be optimal. I am going to suggest a new definition for HP below

**Comment by pnrobinson** [comment]
The term peptic ulcer refers to acid peptic injury of the digestive tract, resulting in mucosal break reaching the submucosa. Peptic ulcers are usually located in the stomach or proximal duodenum, but they can also be found in the oesophagus or Meckel's diverticulum. Infection with Helicobacter pylori and the use of non steroidal antiinflammatory drugs (NSAIDs) or aspirin are the main risk factors of both gastric and duodenal peptic ulcers.

Comment: Symptoms of peptic ulcer disease have limited predictive value because they are non-specific. Patients with duodenal ulcers typically feel hungry or have nocturnal abdominal pain. By contrast, patients with gastric ulcers have postprandial abdominal pain, nausea, vomiting, and weight loss. Patients with untreated peptic ulcer disease typically have relapsing symptoms because of spontaneous healing and relapse while the causal factor (eg, H pylori infection or NSAID use) persists.
Source -- PMID:28242110

Also, I am not sure why the HP term is under physiology, it should be under morphology as with MP.

Thanks for pointing this out @anna-anagnostop  !

However, only a few people with H pylori infection or taking NSAIDs or aspirin develop peptic ulcer disease, suggesting that individual susceptibility to bacterial virulence and drug toxicity is essential to the initiation of mucosal damage.

**Comment by anna-anagnostop** [comment]
Thank you so much for your input @pnrobinson !

I will modify the peptic ulcer [MP:0003301](https://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MP_0003301) textual definition accordingly (based on the definition you provided) and review the MP annotations to reorganize/break intestinal ulcer [MP:0000512](https://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MP_0000512) into more specific child terms in order to accommodate large intestine and small intestine ulcers, as needed. The MP may need to keep gastrointestinal ulcer [MP:0003300](https://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MP_0003300) as I am pretty sure we have annotations to just this high-level parent term.

I will also look into finding a more appropriate filler than ‘[ulcer](https://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MPATH_579)’ for the relevant EQs as we are currently trying to refrain from using MPATH terms. 

Possible PATO terms include:

Eroding [PATO:0002453](https://www.ontobee.org/ontology/PATO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002453) or lesioned [PATO:0040025](https://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0040025)

Thanks again, 

Anna

**Comment by pnrobinson** [comment]
Hi @anna-anagnostop I am also adding a bit of hierarchy that will be similar to MP here, since currently the HP did not group these ulcer classes. Thanks for this suggestion!
FYI here is the definition I am using
Label: Gastrointestinal ulcer
Def: A deep defect in the esophageal, gastric, duodenal or intestinal wall involving the entire mucosal thickness and penetrating through the muscularis mucosae.
Comment: Gastrointestinal ulcers result from the tissue necrosis triggered by mucosal ischemia, ree radical formation and cessation of nutrient delivery, all caused by vascular and microvascular injury such as thrombi, constriction, or other occlusion.
PMID: 16184417

I have also fixed the above issue.
