### ISSUE TITLE
Missing capitalization of one of the synonyms

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#7415]
**HPO term**
HP:0002209 | Sparse scalp hair

**Bug description**
I think if other synonyms are capitalized (first letter), this should be too: "sparse-absent scalp hair". 

By the way when I'm checking it on https://hpo.jax.org/app/browse/term/HP:0002209, if some of the synonyms are containing comma, it can be a bit confusing to distinguish what is a "boundary" between synonyms and when it's part of the synonym (like "Scalp hair, thinning"). Maybe it would be better to show semicolon between synonyms or some other separator (e. g. "|")?

**Comment by pnrobinson** [comment]
I have removed this synonym since sparse is not the same thing as absent and the synonym is imprecise. For the other synoynms, I put them in natural order so that we do not need a comma.
In the original file, the synonyms are clearly separated. Maybe we need to improve the way they are displayed on the website.
