### ISSUE TITLE
Parietal foramina concept: HP:0004423 and HP:0002697

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7471]
**HPO term**
Parietal foramina HP:0002697
X-refs from HPO point to SNOMED 29307005 , with PT 'craniolacuna' and a syn of 'Parietal foramina'; and also SNOMED 11240000, PT 'Structure of parietal foramen' 

I am trying to understand the distinction between the above HPO concept and
Cranium bifidum occultum HP:0004423 , which HPO x-refs to SNOMED 718099006 (PT is 'Enlarged parietal foramina') and MSH:C566826 (pref name on this MeSH concept is 'Parietal Foramina')

My question: Are these the same phenotype?

MedGen is having trouble mapping these concepts and the preferred names from OMIM and Mondo related to these concepts. UMLS puts the 'parietal foramina' HPO term on a CUI for a 'body part or junction' and the 'cranium bifidum occultum' concept on the CUI with the OMIM phenotype description and other X-refs from Mondo's term that they say is equivalent to this HPO entry. If I can be clear on what these concepts represent from HPO's perspective, I can reached out to UMLS if they have mis-mapped these concepts on their end.

**Comment by nicolevasilevsky** [comment]
Hi @kanems I can take a look at this asap, I am traveling this week, so I may not get to it right away.

@pnrobinson should also be able to help too when he has a chance.

**Comment by pnrobinson** [comment]
We have
[Cranium bifidum occultum HP:0004423](https://hpo.jax.org/app/browse/term/HP:0004423)
and
[Parietal foramina HP:0002697](https://hpo.jax.org/app/browse/term/HP:0002697)

**Comment by pnrobinson** [comment]
Cranium bifidum occultum, also known as Catlin mark, is a congenital midline skull defect presenting as an enlarged posterior fontanelle in the upper posterior angle of the parietal bone close to the intersection of the sagittal and lambdoid sutures.1, 2, 3 Cranium bifidum occultum occurs due to a defect in intramembranous ossification, a process through which skull bones (frontal, parietal, squamous temporal and occipital bones superior to the mendosal suture) ossify under a vascularized membrane toward the midline to cover the brain.1, 4, 5 Unlike cranium bifidum cysticum, cranium bifidum occultum does not have herniation of intracranial contents. As the skull grows, the midline cranium bifidum occultum defect is separated into bilateral enlarged parietal foramina (EPF) by a midline osseous bridge
https://pubmed.ncbi.nlm.nih.gov/28522383/

**Comment by pnrobinson** [comment]
Cranium bifidum tends to resolve into distinct enlarged parietal foramina over the first few years of life through the midline ossification of a central bridge of bone bisecting the defect
https://www.ncbi.nlm.nih.gov/books/NBK1128/
So the two terms are not synonyms but are very close in meaning. I will revise the definition of Cranium bifidum occultum

**Comment by pnrobinson** [comment]
See also https://github.com/obophenotype/human-phenotype-ontology/issues/7671 --

**Comment by pnrobinson** [comment]
added the comment/definition to Cranium bifidum occultum
