### ISSUE TITLE
Ear infection

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#750]
reported by @tudorgroza

middle ear infection (caused by eustachian tube blockage)

**Comment by drseb** [comment]
add eustachian tube blockage . should be related/equivalent to *Stenosis of the Eustachian tube*

**Comment by tudorgroza** [comment]
Ear infection = C0699744 [UMLS]
Middle ear infection = C0029882 [UMLS]
Obstruction of Eustachian tube = C0149508 [UMLS]
Blocked Eustachian tube = C0149508 [UMLS] (ambiguous semantic type)

And since we're here - can we please also add 'Cannot remember current prime minister' (UMLS: C0423933) or 'Preoccupation with specific bodily appearance' (UMLS: C0423992) :)

**Comment by pnrobinson** [comment]
Note that middle ear infection due to eustachian tube blockage should be conceptualised as a disease rather than a phenotype term. I think that 
Obstruction of Eustachian tube = C0149508 [UMLS]
Blocked Eustachian tube = C0149508 [UMLS] - ambiguous semantic type
should be synonyms.
Ear infection/Middle ear infection are probably also best conceptualised as diseases, although they are also phenotypic features of other diseases (in the HPO, we have terms for recurrent ear infection, I believe).

**Comment by drseb** [comment]
after discussion with peter, I think we do the following:

 - add *recurrent infection of middle ear* (under *abn. of middle ear* and *recurrent infections*)

 - add *Blocked Eustachian tube* with *Obstruction of Eustachian tube* as synonym as subclass of *Abnormality of the Eustachian tube*
