### ISSUE TITLE
Acidosis & Alkalosis logical definition causes lots of bad inference 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/human-phenotype-ontology#7534]
**HPO term**

acidosis: 'has part' some 
    ('increased amount'
     and ('characteristic of' some 
        ('chemical entity'
         and ('part of' some 'bodily fluid')
         and ('has role' some acid)))
     and ('has modifier' some abnormal))

Leads to classification of increased levels of substances in bodily fluids that recorded as acids by CHEBI e.g.- Hyperglutaminemia
is an inferred subclass due to it being glutamine being an amino acids (it's actually also inferred to be Akalosis as well due.
'has part' some 
    ('increased amount'
     and ('characteristic of' some 
        (glutamine
         and ('part of' some blood)))
     and ('has modifier' some abnormal))

**Suggested revision of logical definition**

The definition should not be based on the nature of chemicals but on abnormal pH of the bodily fluid => 

'has part' some ('increased acidity' and ('characteristic of' some 'body fluid') and (has_modifier some 'abnormal')

ditto Alkalosis.

**Comment by dosumis** [comment]
(CC @rays22 )

**Comment by pnrobinson** [comment]
One of the main difficulties is that what we actually observe is acidemia (this is a pH) but what is often recorded in medical literature is an inferrence (acidosis, which is sometimes used interchangably with acidemia).
There are then subclasses that reflect the specific process causing acidemia. While this is often pretty accurate, I think that it is confusing to have separate terms in the HPO code acidemia and acidosis and we should consider restructuring.

**Comment by LCCarmody** [comment]
I would only add the logical defs. I will leave the restructuring up to you.

**Comment by pnrobinson** [comment]
@matentzn 
I am not sure we should worry that much about these definitions, and maybe we can close this? I do not know what the open action item is?

**Comment by matentzn** [comment]
The "lazy" way out to satisfy the request is to delete the `acidosis` and `alkalosis` logical definitions. The right way would be to ask Leigh to discuss this with @rays22 in the next uPheno call and fix it. 

You could also to both:

1. Delete now
2. Close issue
3. Ask Leigh and Ray to add a corrected EQ if they think it is important

**Comment by pnrobinson** [comment]
Let's leave this open until @LCCarmody  and @rays22 can deal with it!

**Comment by pnrobinson** [comment]
Looking at the definitions now
```

'has part' some 
    ('increased amount'
     and ('characteristic of' some 
        ('chemical entity'
         and ('part of' some 'bodily fluid')
         and ('has role' some acid)))
     and ('has modifier' some abnormal)
```
this seems perfectly reasonable. I will close this for now.

**Comment by rays22** [comment]
> Looking at the definitions now
> 
> ```
> 
> 'has part' some 
>     ('increased amount'
>      and ('characteristic of' some 
>         ('chemical entity'
>          and ('part of' some 'bodily fluid')
>          and ('has role' some acid)))
>      and ('has modifier' some abnormal)
> ```
> 
> this seems perfectly reasonable. I will close this for now.

@pnrobinson 
I am afraid there are several problems with this definition.
First of all, the logical axiom does not agree with the text definition of [HP:0001941](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001941). The text defines [HP:0001941 Acidosis](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001941) as a physiological process quality, but the axiom defines it in terms of quantitative qualities related to chemical entities. Although the participants in the physiological process indeed include chemical entities, but the axiom is too broad in such a way that it encompasses irrelevant categories of [amphoteric chemical compounds](https://en.wikipedia.org/wiki/Amphoterism). The axiom above clearly violates widely accepted and experimentally proven [basic](https://en.wikipedia.org/wiki/Base_(chemistry)) chemistry concepts of [how acidity is defined](https://en.wikipedia.org/wiki/PH). Although amphoteric compounds can indeed exhibit roles as acids, but it is the balance of acids and bases the lead to acidosis and acidic pH. The problem is that it

> Leads to classification of increased levels of substances in bodily fluids that recorded as acids by CHEBI e.g.- Hyperglutaminemia is an inferred subclass due to it being glutamine being an amino acids (it's actually also inferred to be Akalosis as well due. 'has part' some ('increased amount' and ('characteristic of' some (glutamine and ('part of' some blood))) and ('has modifier' some abnormal))


Options:
1. Fix the logical definition based on the defining characteristic and outcome of the homeostatic physiological process (pH)  as suggested:

> **Suggested revision of logical definition**
> 
> The definition should not be based on the nature of chemicals but on abnormal pH of the bodily fluid =>
> 
> 'has part' some ('increased acidity' and ('characteristic of' some 'body fluid') and (has_modifier some 'abnormal')
> 
> ditto Alkalosis.

2. Use [GO:0006885 regulation of pH](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0006885?lang=en) in a process based logical definition of  [HP:0001941 Acidosis](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001941) and [HP:0001948 Alkalosis](https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001948)
3. If none of the above are acceptable for some valid reason, then delete the misleading and incorrect logical axioms.

**Comment by matentzn** [comment]
@rays22 can you make a PR to this end? It seems @pnrobinson is on an issue closing spree and he wants this dealt with yesterday :P 

Thank you!
