### ISSUE TITLE
HP:4000007 Bronchoconstriction and HP:0025428 Bronchospasm are potential synonyms

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7557]
HP:4000007 Bronchoconstriction and HP:0025428 Bronchospasm are potential synonyms.
These two terms are very similar and I would suggest are synonyms, or there is a difference I can't see.
Graham Ponting

**Comment by pnrobinson** [comment]
@eswietlik @mgriese
I agree with Graham that these are probably synonyms, but a quick look revealed a few sources that differentiate between them.
Is there an "official" pulmonological definition we can use and are these two terms in fact synonymous?

https://link.springer.com/chapter/10.1007/978-3-319-42866-6_7

**Comment by mgriese** [comment]
In everyday practice the terms are used as synonyms. Major textbooks use either bronchospasm (Taussig, Landau...) or bronchoconstriction (Kendig and chernicks...).

**Comment by pnrobinson** [comment]
This is a difficult one, as there does not seem to be any official definition.
One finds many sources that say things like this
However, doctors sometimes consider bronchospasm to be a more sudden narrowing in one area of the lungs, while bronchoconstriction is typically a more widespread, less sudden narrowing. (https://www.healthline.com/health/asthma/asthma-vs-bronchospasm).
However, there are more articles that use the terms as synonyms, e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6092370/. 
I agree that it is not useful to have two differnet terms because it is unlikely that our users will differentiate between them in a consistent way.

**Comment by pnrobinson** [comment]
I have merged the terms and retained HP:4000007 Bronchoconstriction  as the current term.
