### ISSUE TITLE
HP:0010459 True hermaphroditism and HP:0012861 Ovotestis, are synonyms ?

### ISSUE THREAD

**Issue by grahamponting** [obophenotype/human-phenotype-ontology#7601]
HP:0010459 True hermaphroditism and HP:0012861 Ovotestis, are synonyms ?
These two concepts are "siblings" and have identical mappings to MSH, SNOMED CT and UMLS, their definitions/comments are very similar, suggesting that they are synonyms, or at least very closely related.
see https://rarediseases.org/rare-diseases/ovotesticular-disorder-of-sex-development/

Graham Ponting

**Comment by pnrobinson** [comment]
These are closely related concepts:
True hermaphroditism occurs when an ovary and a testis with mixed histologic features, i.e., ovotestis  is present. 
They are not exactly synonymous, because the finding can be different for the left and right gonad (e.g., one can have an ovotestis on the right and an ovary on the left). 

I will work on revising the definitions to make the respective use cases clearer, thanks for pointing this out.

**Comment by pnrobinson** [comment]
I have added this comment to True hermaphroditism to explain the difference between the two terms

In true hermaphroditism, the testicular tissue must have well developed seminiferous tubules, and the ovarian tissue primordial follicles. The external genitalia are usually associated with variable degrees of sexual ambiguity, depending on the amount of functioning testicular tissue. Internally, a uterus is almost always present, but the development of Mullerian and Wolffian structures is variable and generally depends on the adjacent gonad. Usually there is a vas deferens on the side of the testis, and a Fallopian tube on the side of the ovary. Both types of ducts can occur next to an ovotestis. An ovotestis is the most common gonad found in true hermaphroditism and can be coded with HP:0012861.
