### ISSUE TITLE
Missing HPO ID in hp.owl 

### ISSUE THREAD

**Issue by gerthijs** [obophenotype/human-phenotype-ontology#7614]
I have observed that for a subset of the terms in the hp.owl data the actual HPO ID is not available.  

For instance, the term HP:0032443 'Past medical history' has the following data in the hp.owl :
```
    <!-- http://purl.obolibrary.org/obo/HP_0032443 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/HP_0032443">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/HP_0000001"/>
        <obo:IAO_0000115>In a medical encounter, the physician generally will interview the patient about his or her current problem, and may perform additional testing. The past medical history (PMH) in contrast records information about the patient&apos;s medical, personal and family history that might be relevant to the presenting illness or to provide optimal clinical management. The PMH generally includes (if relevant) other major illnesses, hospitalizations, surgeries, injuries, allergies, gynecologic and obstetric history, family history, personal history including occupational history, alcohol and drug use, etc.</obo:IAO_0000115>
        <dc:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2019-03-03T16:39:26Z</dc:date>
        <oboInOwl:created_by rdf:datatype="http://www.w3.org/2001/XMLSchema#string">peter</oboInOwl:created_by>
        <rdfs:comment>This subontology of the HPO is not intended to provide all needed terms to describe the past medical history, but rather to be combined with other ontologies such as MONDO in order to capture information that is often needed to properly assess phenotypic findings related to a presenting medical problem.</rdfs:comment>
        <rdfs:label>Past medical history</rdfs:label>
    </owl:Class>    
```

I would expect the following field with the actual HPO ID also to be present in the XML 

```
 <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">HP:0032443</oboInOwl:id>
```

When this owl data files is loaded in a graph database and one executes a query to look up terms based on the ID, these terms cannot be retrieved.

**Comment by pnrobinson** [comment]
In OWL XML format, it is not possible to use ids such as HP:0032443 because of reasons that are summarized here https://www.w3.org/2007/OWL/draft/ED-owl2-syntax-20081202/

Instead, one uses the form with underscore HP_0032443, which is equivalent.

Please adjust your query/code to use the latter form if you are parsing OWL. An alternative is to use the JSON format, and if you use the phenol library for this  (https://github.com/monarch-initiative/phenol), then the CURIE form with ":" is used.

**Comment by gerthijs** [comment]
Looking at the entries in the OWL format it seems that large part of the terms do have the <oboInOwl:id> tag which has the HPO identifier. Below I have added an example of such a record. 
I was wondering why this tag is not available in all records?


    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/HP_0000142">
        <owl:equivalentClass>...</owl:equivalentClass>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/HP_0000008"/>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Any structural abnormality of the vagina.</obo:IAO_0000115>
        <oboInOwl:hasAlternativeId rdf:datatype="http://www.w3.org/2001/XMLSchema#string">HP:0008650</oboInOwl:hasAlternativeId>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UMLS:C1856023</oboInOwl:hasDbXref>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Vaginal malformation</oboInOwl:hasExactSynonym>
        **<oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">HP:0000142</oboInOwl:id>**
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Abnormal vagina morphology</rdfs:label>
    </owl:Class>

**Comment by pnrobinson** [comment]
I see what you mean.
A long time ago we were using OBO Editor to work on the HPO. When we switched from OBO to OWL format, the existing id's were coded with the oboInOwl:id but we switched to using this way of coding the id: rdf:about="http://purl.obolibrary.org/obo/HP_0000142"
@matentzn  -- actually it is easier to work with the oboInOwl:id when available then with the rdf:about attributes (which by default are not even displayed in Protege). I don't suppose there is any easy way to get Protege to always create an oboInOwl:id field?

**Comment by matentzn** [comment]
It has been a very long time since we are not supporting the oboInOwl:id property anymore - in almost all OBO ontologies. My preference would be to delete the existing redundant property. @gerthijs which graph database are you using? If you are using neo4j with neosemantics, I would recommend using addPrefixesAsText() during preprocessing. Alternatively, you can simply run a SPARQL update query that translates an IRI into a CURIE.

@pnrobinson ultimately, your call. I can simply inject HP ids at release time into the ontology, but I am not sure why we should add 20K essentially redundant triples to the ontology. But maybe you think your users need it?

**Comment by pnrobinson** [comment]
Probably not but it would be nice to show the IDs in Protege (this does not happen without the oboInOwl:id) attribute. 
Probably let's leave be. Protege is not a good tool for this :-0

**Comment by matentzn** [comment]
Alternatively, I can _remove_ the existing id annotations which are at the moment inconsistent in HPO, reducing the size of HPO somewhat :)
