### ISSUE TITLE
Are HP:0003239 and HP:0410158 different?

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7619]
**HPO term**
HP:0003239 and HP:0410158

**Suggested revision and reasons**
https://www.genome.jp/dbget-bin/www_bget?cpd:C00346 seems to suggest that Phosphoethanolamine and O-Phosphoethanolamine, so it is not clear why there are 2 separate HPO entries arranged hierarchically.

**Comment by pnrobinson** [comment]
This reflects the hierarchy in ChEBI: 
[CHEBI:36711 - phosphoethanolamine](https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:36711)
[CHEBI:17553 - O-phosphoethanolamine](https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:17553&treeView=true#vizualisation)
however, I think the phosphoethanolamine might be just a grouping term rather than a truly different compound. 

the following are synonyms
O-Phosphoethanolamine
Phosphorylethanolamine
Phosphoethanolamine

So I agree, these terms should be merged.

**Comment by pnrobinson** [comment]
done

**Comment by MickeySegal** [comment]
Since your actions are not yet visible on the public HPO version, could you indicate which HPO code will survive?
