### ISSUE TITLE
Panic attack PNES superclass question

### ISSUE THREAD

**Issue by reality** [obophenotype/human-phenotype-ontology#7629]
**HPO term**
https://hpo.jax.org/app/browse/term/HP:0025269

**Bug description**

Is it correct that panic attack is a subclass of [psychogenic non-epileptic seizure](https://hpo.jax.org/app/browse/term/HP:0033052)? Some instances of panic attacks are labelled as a kind of PNES, particularly where they present similarly to seizures but no neural basis can be found, however I don't think that all panic attacks are considered to be PNES. One of the citations of the PubMed association for HP:0025269 describes an associative relationship[1], in particular that:

"Psychogenic Non-Epileptic Seizures (PNES) are events that appear epileptic but are instead thought to have a psychological origin. Increased rates of several psychiatric disorders have been reported in PNES, including anxiety and panic disorders. Some theories suggest panic and/or hyperventilation have aetiological roles in PNES, though these remain unproven."

My interpretation would be that a subclass of panic attack, i.e. one in which the presentation is similar to a seizure, would be a subclass of PNES, but not panic attack itself? 

[1] https://pubmed.ncbi.nlm.nih.gov/29787922/

**Comment by pnrobinson** [comment]
@DLewisSmith The above interpretation seems correct to me -- could you please comment?

**Comment by DLewisSmith** [comment]
Yes. Complex area (as we’ve previously discussed). Some PNES do intersect with panic attacks and vice versa but some types of each can be independent of the other. I’d suggest keeping it simple by avoiding having directed is_a relationships between them in either direction. I would not suggest a shared child such as ‘PNES due to panic attack’ or ‘PNES as part of panic attack’ as I doubt that this would be particularly helpful vs coding both if each explicitly present.

**Comment by pnrobinson** [comment]
Thanks, both, I have removed the subclass assertion!
