### ISSUE TITLE
Differences unclear between HP:0012427 and HP:0031068 and between HP:0008796 and HP:0031070

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#7631]
**HPO term**
HP:0012427 and HP:0031068
HP:0008796 and HP:0031070
**Suggested revision of textual definition**
The differences between each of these terms in each pair needs to be clarified, or if the differences are not important, the terms should be merged.  For example, HP:0031068 is "Increased femoral torsion" explained as "femoral version" and HP:0012427 is explained as "increased degree of femoral version".  

Our curator clinicians have felt most comfortable with the term "Hips internally rotated" in analogue to "Hips externally rotated", so it would be good to include that in an entry.

**Comment by pnrobinson** [comment]
[Excessive femoral anteversion HP:0012427](https://hpo.jax.org/app/browse/term/HP:0012427)
[Increased femoral torsion HP:0031068](https://hpo.jax.org/app/browse/term/HP:0031068)

and

[Externally rotated hips HP:0008796](https://hpo.jax.org/app/browse/term/HP:0008796)
[Decreased femoral torsion HP:0031070](https://hpo.jax.org/app/browse/term/HP:0031070)

**Comment by pnrobinson** [comment]
I think these are all describing the same thing, see Figure 1 here -- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7542196/
I will merge and adjust the hierarchy, thanks for pointing this out.

**Comment by pnrobinson** [comment]
Merged to
Femoral retroversion (HP:0008796)
synonym: External rotation of the hips
Def: An abnormal backward rotation of the hip relative to the knee such that the hips are externally rotated with the foot pointed outward instead of straight ahead (out-toeing).
Comment: Femoral torsion, also known as femoral rotation or femoral version, refers to the twist between the proximal and distal parts of the femur on the transverse plane. Femoral anteversion averages between 30-40 degress at birth, and between 8-14 degrees in adults. This term applies if the amount of femoral torsion is below this range.

**Comment by pnrobinson** [comment]
Also 
Increased femoral anteversion (HP:0012427)
synonym Internally rotated hips
