### ISSUE TITLE
Spastic diplegia under Cerebral Palsy

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#7652]
**HPO term** Spastic diplegia HP:0001264

**Suggested revision and reasons**
Could you please give this term another parent under Cerebral palsy HP:0100021. This way it can be found underneath CP with the other spastic CP types, similar to #7315 . A good point was made in #7519 about not all spasticity being CP but I assume the multiple parent terms and definition makes this clear.

A suggestion might be to make another class called Spastic cerebral palsy similar to the MONDO branch (the CP branch is quite good!). I thought it'd be better to first get all the different CP types recognised under the CP parent term first before adding other CP branches.

**Comment by peupeubangbang** [comment]
@pnrobinson could spastic diplegia have CP added as parent? this is a well recognised CP phenotype

**Comment by pnrobinson** [comment]
@peupeubangbang 
The HPO tries to avoid "bundled" definitions, and the term Cerebral palsy is definitely bundled (it can be used to describe a disease entity or a collection of symptoms). We currently retain it in the ontology because it is used as a phenotypic description in much original literature, but we may remove it and replace it with a "meta term" in the future.

We cannot make Spastic diplegia a child of Cerebral palsy, because then (by ontological reasoning) software would conclude that every patient with Spastic diplegia has all of the ancestor terms including Cerebral palsy, which is incorrect medically.

We will be introducing the concept of Metaterm in the next 1-2 years to address this problem (which also applies to a few other terms) and believe it will also improve computational algorithms, but we need to reduce the length of our todo list first :smile:

**Comment by peupeubangbang** [comment]
Thanks @pnrobinson makes sense. I always thought phenotypes like this would be better annotated to CP in MONDO anyway. Metaterm sounds like a cool feature particularly for those trying to find suitable HPO codes for their diseases that can't be found in HPOA.

We have a CP structure ready to go for the types of movement disorders seen in cerebral palsy that have been well classified by the CP Registers across Australia and Europe for many years now. 

Tudor Groza's CP annotation work also showed these terms proposed below were needed as they were routinely used in CP clinical letters to describe phenotype (I went through all the annotations not picked up by the HPO concept recognition and compared to existing HPO).

The CP genomics consortium are very keen for these phenotypes to be in HPO as they embark on a few projects including WGS. 

Based on the above, I wanted to check the structure was still possible? See below except obviously I will exclude CP as a parent to be removed. We can then map these codes for CP Registers in Aus and Europe

![99234078-b76a-4cd5-96e1-4e79cc3dacf1.png](https://github.com/obophenotype/human-phenotype-ontology/assets/86904969/6356d864-81bb-453f-bb9e-fb8c4ba76b1f)

**Comment by pnrobinson** [comment]
@peupeubangbang  We would be delighed to organize a mini-workshop to add these annotations to the proper place in Mondo and HPO -- could you please send me an email and I will help to organize @cmungall @mellybelly 
Terms such as Dyskinetic CP seem to live somewhere between Mondo and HPO and we will need to figure out how to model them.
