### ISSUE TITLE
NTR: Abnormal type of vocalizations (Associated motor)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#7776]
New term request Abnormal type of vocalizations (kalia_091117031725): Involuntary vocalizations, groaning, grunting, humming included

**Comment by pnrobinson** [comment]
@MickeySegal
This is a great review -- https://movementdisorders.onlinelibrary.wiley.com/doi/full/10.1002/mds.27855

Currently, the HPO seems to only have phonic tics.
[Phonic tics HP:0100035](https://hpo.jax.org/app/browse/term/HP:0100035)

I will add Involuntary vocalization as a superclass and add the categories as suggested in that article.

Question -- does this belong under 
[Involuntary movements HP:0004305](https://hpo.jax.org/app/browse/term/HP:0004305)?

**Comment by MickeySegal** [comment]
I'm not sure how this got on the list because we have Phonic tics HP:0100035 listed for our "Involuntary vocalizations" finding.

Vocal tics don't quite fit under "Involuntary movements" unless you widen the definition to include vocalization muscles.

Another good link that we use is http://www.lifesatwitch.com/museum.html

**Comment by pnrobinson** [comment]
@MickeySegal 
@bcoleman96 

I have rearranged the hierarchy under
HP:4000074 Involuntary vocalizations
to reflect the phenomena in the cited article.

**Comment by MickeySegal** [comment]
But https://hpo.jax.org/app/browse/term/HP:4000074 is "Idiosyncratic language".

**Comment by bcoleman96** [comment]
This should be addressed more thoroughly in the language workshops that we are currently planning.
