### ISSUE TITLE
Movement: logical defintions

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#791]
HP:postural instability and other subclasses of HP:abnormality of movement, should be
related to GO:multicellular organismal movement

This will facilitate similarity to EQ statements in Zfish made to this GO process as
well as to worm and fly phenotypes.

see https://github.com/obophenotype/upheno/issues/27

**Comment by cmungall** [comment]
breaking this down

## posture vs balance

In GO these are distinct

```
    is_a GO:0050877 ! neurological system process [DEF: "A organ system process carried out by any of the organs or tissues of neurological system."]
     is_a GO:0050905 ! neuromuscular process ***  [DEF: "Any process pertaining to the functions of the nervous and muscular systems of an organism."]
      is_a GO:0001964 ! startle response [DEF: "An action or movement due to the application of a sudden unexpected stimulus."]
      is_a GO:0050884 ! neuromuscular process controlling posture [DEF: "Any process in which an organism voluntarily modulates its posture, the alignment of its anatomical parts."]
      is_a GO:0050885 ! neuromuscular process controlling balance [DEF: "Any process that an organism uses to control its balance, the orientation of the organism (or the head of the organism) in relation to the source of gravity. In humans and animals, balance is perceived through visual cues, the labyrinth system of the inner ears and information from skin pressure receptors and muscle and joint receptors."]
```

This suggests adding posture to PATO as a sib to balance

```
   is_a PATO:0001995 ! organismal quality [DEF: "A quality that inheres in an entire organism or part of an organism."]
    is_a PATO:0000186 ! behavioral quality [DEF: "An organismal quality inhering in a bearer by virtue of the bearer's behavior aggregate of the responses or reactions or movements in a given situation."]
     is_a PATO:0000185 ! balance ***  [DEF: "A behavioral quality inhering in a bearer by virtue of having physical steadiness."]
```

the defs could be better aligned but seem essentially consistent

 * posture: alignment of anatomical parts (should really be trunk and appendages?)
 * balance: consistent orientation w.r.t. gravity, steadiness

## posture in HPO

```
     is_a HP:0100022 ! Abnormality of movement [DEF: "An abnormality of movement with a neurological basis characterized by changes in coordination and speed of voluntary movements."]
      is_a HP:0001337 ! Tremor [DEF: "An unintentional, oscillating to-and-fro muscle movement."]
       is_a HP:0002345 ! Action tremor [DEF: "A tremor present when the limbs are active, either when outstretched in a certain position or throughout a voluntary movement."]
        is_a HP:0002174 ! Postural tremor ***  [DEF: "A type of tremors that is triggered by holding a limb in a fixed position."]
      is_a HP:0002172 ! Postural instability *** 
```

Postural tremor is consistent with GO

However,  Postural instability has no NL def. It may not be as simple as the label suggests - otherwise it should go under Postural tremor (since tremors imply instability)

This source defines it in terms of balance:
http://parkinsons.about.com/od/glossary/g/postural_instability.htm

So we have to be careful about words. 

## GO axioms

The GO classes for `neuromuscular process controlling {balance, posture} are unaxiomatized

I propose [GO:0050884](http://purl.obolibrary.org/obo/GO_0050884) ! neuromuscular process controlling posture to be `EquivalentTo neuromuscular process and regulates some posture` (similar for sibling classes)

Currently these are not associated with movement. They should be, and probably via [GO:0050882](http://purl.obolibrary.org/obo/GO_0050882) ! voluntary musculoskeletal movement

That would connect these hierarchies:

![nm](https://cloud.githubusercontent.com/assets/50745/13864646/8f480d6e-ec60-11e5-91b1-2e71e389daca.png)

What should the link be? has-part is not quite correct (the GO NMPCX class encompasses purely neurological processes?). I'll file a ticket.

**Comment by pnrobinson** [comment]
@drseb   @cmungall  @mellybelly  How should we proceed with the definitions here? This is a bit tricky because a lot of the abnormalities are involuntary movements of skeletal muscles. The pathophysiology is complex, and thus I am not sure that it is good to use a GO term like "neuromuscular process controlling posture" etc., because we would be oversimplifying. I think we can agree that we are observing abnormalities of musculoskeletal movement -- would it be a good idea for now to define the HP and MP terms relatively high up in the hierarchy using this GO term? We also need to invite Cindy and Sue to this discussion!

**Comment by cmungall** [comment]
We need on ontology with normal terms for posture etc - NBO?

**Comment by pnrobinson** [comment]
I am moving this to the WIki
https://github.com/obophenotype/human-phenotype-ontology/wiki/Movement
