### ISSUE TITLE
HP:0001071 Angiokeratoma corporis diffusum

### ISSUE THREAD

**Issue by kanems** [obophenotype/human-phenotype-ontology#7948]
**HPO term**
HP:0001071 Angiokeratoma corporis diffusum
syn 'Fabry syndrome'

**Suggested revision of textual definition**

There is no definition right now; based on historic data in MeSH (https://www.ncbi.nlm.nih.gov/mesh/?term=D000795) this HPO term is matched to Fabry disease in UMLS,  but that seems too narrow of a mapping for this phenotype.
Based on this article
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7247653/
It seems like a definition _could_ be
"Variable sized hyperkeratotic vascular papules that are characterized histologically by superficial dilated capillaries in papillary dermis with epidermal proliferation, occurring in a generalized pattern. These papules are known to occur in a variety of lysosomal enzyme deficiencies."

**Comment by pnrobinson** [comment]
See -- https://jamanetwork.com/journals/jamadermatology/fullarticle/404961
For many years, this term was used synonymously for Fabry disease, a systemic X-linked disease caused by a deficiency of the lysosomal enzyme α-galactosidase A.[3](https://jamanetwork.com/journals/jamadermatology/fullarticle/404961#ref-dob50112-3)-[8](https://jamanetwork.com/journals/jamadermatology/fullarticle/404961#ref-dob50112-3) Angiokeratoma corporis diffusum is now known to occur in several other diseases related to deficiencies of enzymes that are involved in the metabolism of glycoproteins, including fucosidosis,[9](https://jamanetwork.com/journals/jamadermatology/fullarticle/404961#ref-dob50112-9) sialidosis, mannosidosis,[10](https://jamanetwork.com/journals/jamadermatology/fullarticle/404961#ref-dob50112-10) GM1 gangliosidosis, and Kanzaki disease.[11](https://jamanetwork.com/journals/jamadermatology/fullarticle/404961#ref-dob50112-11)-[1](https://jamanetwork.com/journals/jamadermatology/fullarticle/404961#ref-dob50112-11)

**Comment by pnrobinson** [comment]
I am adding this definition;
Angiokeratoma corporis diffusum (ACD) is typically characterized by innumerable small red to black papules which occur in clusters and are situated symmetrically in the bathing trunks area. The number of lesions and the extension of the body increase steadily with time so that generalization and mucosal involvement are common. The single lesion begins with a minute reddish papule which enlarges to up to 10 mm in diameter, becomes dark red to black with a discrete keratotic overgrowth. Histologically, the papules are characterized by superficial dilated capillaries in papillary dermis with epidermal proliferation.

Comment: Angiokeratoma corporis diffusum (ACD) commonly occurs in Fabry disease and the term ACD was previously used synonymously with Fabry disease (OMIM:301500). However, ACD can also occur with other diseases related to deficiencies of enzymes that are involved in the metabolism of glycoproteins, including fucosidosis, sialidosis, mannosidosis, GM1 gangliosidosis, and Kanzaki disease.

**Comment by pnrobinson** [comment]
please reopen if needed. I think that this term should no longer be a synonym of Fabry disease (but it was this historically).
