### ISSUE TITLE
new HPO for EP300 and CREBBP gene

### ISSUE THREAD

**Issue by ltrujillano** [obophenotype/human-phenotype-ontology#8152]
**Am J Med Genet B Neuropsychiatr Genet. 2018 Jun;177(4):406-415. doi: 10.1002/ajmg.b.32628. Epub 2018 Apr 10.
Rubinstein-Taybi syndrome: New neuroradiological and neuropsychiatric insights from a multidisciplinary approach.
PMID: 29637745 DOI: [10.1002/ajmg.b.32628](https://doi.org/10.1002/ajmg.b.32628)**

**Parent term (use hpo.jax.org/app)**
Aplasia/Hypoplasia of the cerebellar vermis HP:0006817

**Diseases characterized by this term ? (e.g. Orphanet or OMIM number)**
RUBINSTEIN-TAYBI SYNDROME 1 (OMIM 180849) Gen: CREBBP [600140]
RUBINSTEIN-TAYBI SYNDROME 2 (OMIM 613684) Gen: EP300 [602700]

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-3028-6156

**Comment by pnrobinson** [comment]
@ltrujillano  Sorry for the late response. It would be great to add all of he annotations from this paper to the HPO database. Do you happen to have data on a per gene basis since we like to add frequencies -- it seems there are many CREBBP and only one EP300 case. We would not include data from the unclear cases. Could you send this to peter robinson's email?

**Comment by pnrobinson** [comment]
@ltrujillano I am not able to use the data in the paper you sent because we curate on a precise per disease/gene level. I have noted some of the other papers for our curation pipeline and we will be adding to the RTS annotations in the next few months. Thanks, Peter
