### ISSUE TITLE
NTR: Lipase low in blood (Lab: blood chemistry)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8406]
New term request Lipase low in blood (elthat_171217024616):

**Comment by pnrobinson** [comment]
@MickeySegal
could this be 
Decreased circulating lipoprotein lipase concentration HP:0031209
or 
Reduced lysosomal acid lipase activity HP:0031205

**Comment by MickeySegal** [comment]
Our references are not being specific:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6087479/ "lipase level was below the normal age range"
https://academic.oup.com/tropej/article/52/6/445/1689385 lists both Lipase and P-lipaseA2 being low.
One specifies the lipase used for treatment:
https://jkms.org/pdf/10.3346/jkms.2008.23.1.142
powdered pancrelipase

For another condition:
https://www.ncbi.nlm.nih.gov/books/NBK570570/ "Laboratory values are normal except for elevated serum bilirubin in pancreaticobiliary reflux and serum amylase and lipase if it is caused due to pancreatitis"

We have several conditions listed for each of the 2 HPO codes that you list, but I don't know how our citations above fit.

**Comment by pnrobinson** [comment]
Sometimes the literature is maddeningly imprecise. I do not think we should make imprecise terms to accommodate this, probably the only thing to do is to not annotate these articles. I am pretty sure that the lipase activities are distinguishable.

**Comment by MickeySegal** [comment]
https://pubmed.ncbi.nlm.nih.gov/7075943/
"Pancreatic lipase secretion was less than 2% of normal mean secretion in the steatorrheic patients and ranged from 3.7% to 13.6% in the patients without steatorrhea."

This should be the opposite of https://hpo.jax.org/app/browse/term/HP:0032932

I've changed both our findings to refer to pancreatic lipase / Pancreatic triacylglycerol lipase
