### ISSUE TITLE
NTR: Cysteine present in urine (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8499]
New term request Cysteine present in urine (segal_030502142056):   UMLS: 0863155

**Comment by pnrobinson** [comment]
@MickeySegal
Not an expert here, but I thought that one observes cystine (rather than cysteine) in the urine, e.g., in cysteinuria (https://omim.org/entry/220100)?
Can you comment on the disease in which this is observed?

**Comment by MickeySegal** [comment]
For Hartnup disease https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6938934/ lists "other amino acids ... included arginine, lysine, aspartic acid, glutamic acid, glycine, **cysteine**, methionine, proline, ornithine, taurine and alpha-aminobutyric acid".  Also, in gamma-glutamyl transpeptidase deficiency, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC349620/ describes "Excretion of **cysteine** and gamma-glutamylcysteine moieties".

But since cystine is 2 cysteines joined by a disulfide bond, I can't promise you that in practice the distinction is important.  I'm also not an expert here.

**Comment by pnrobinson** [comment]
@ahamosh -- Ada, do you have a recommendation as to whether it would be sensible to have a separate term for increased urine cysteine? I am not an expert but I think that what one observes is cystine?

**Comment by ahamosh** [comment]
As far as I can tell what you detect in urine is cystine.  I don't think that cysteine is stable.  In theory, I am an expert (as I am a biochemical geneticist), but I am not sure.  I will ask the director of our biochemical lab.

**Comment by ahamosh** [comment]
Hi All, confirmed by my laboratory colleagues.  They only detect cystine.

**Comment by MickeySegal** [comment]
Great.  We will merge our urine cysteine term into urine cystine since that is what is observed.  So we don't need a new term.

**Comment by pnrobinson** [comment]
thanks @ahamosh we will close this
