### ISSUE TITLE
NTR: Glycine low in CSF (Lab: chemistry: amino compounds)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8534]
New term request Glycine low in CSF (segal_030507180904): Cerebrospinal fluid  UMLS: 2674427

**Comment by pnrobinson** [comment]
@MickeySegal this existed already, adding synonym

Decreased CSF glycine concentration HP:0034390

**Comment by MickeySegal** [comment]
I don't know why I missed this, but I see that MedGen missed it also.  It has the increase, https://www.ncbi.nlm.nih.gov/medgen/1691638 and the parent term, but not the decrease.  I don't know if this has to do with the date of creation of a term since I don't see that information.  

BTW, we list the decrease in Phosphoserine aminotransferase deficiency, as per De Koning TJ (2010) OMMBID Serine deficiency disorders but the link is now broken.

**Comment by kanems** [comment]
Noting that UMLS is also missing this HPO ID (HP:0034390) 
![image](https://user-images.githubusercontent.com/71083858/205664647-d4b7c030-1f27-47ce-b904-5fe4a6138296.png)

@pnrobinson where can I find a history/creation date of HPO terms? Is that something in the downloads? If UMLS is missing this and it was created and released before late September, then UMLS should have had it in 22AB release. I'd also like to poke around in MedGen's records to see if we're missing some HPO data from releases.

**Comment by MickeySegal** [comment]
MedGen only covers a small subset of UMLS terms useful clinically, based on a set of rules.  But here, since it has the increased glycine and not the decreased glycine, it is an omission and not a policy.

In the process of generating our HPO / UMLS listings for findings, I communicated many times with the MedGen and UMLS teams to point out omissions and discrepancies.  It didn't take them long to realize that this was important input, and they became very responsive and made many fixes.
