### ISSUE TITLE
concerning Biventricular hypertrophy / Amyolid cardiomyopathy

### ISSUE THREAD

**Issue by anno-du** [obophenotype/human-phenotype-ontology#861]
Confusion about the following symptoms:
1.
Ventricular hypertrophy
    Left ventricular hypertrophy
    Biventricular hypertrophy
    Congenital hypertrophy of left ventricle

Right ventricular hypertrophy
    Biventricular hypertrophy

Am I wrong that I would propose to arrange Biventricular hypertrophy once below the symptom Ventricular hypertrophy.

2.
Amyloidosis
    Amyolid cardiomyopathy

In the other cases you use the syntax amyloid or amyloidosis; is this syntax intended. It attracted my attention because I could not find the symptom in your ontology.

**Comment by drseb** [comment]
I assume you closed by accident.

1)
The current structure seems correct for me:
 - *Biventricular hypertrophy* subclassOf *Left ventricular hypertrophy*
 - *Biventricular hypertrophy* subclassOf *Right ventricular hypertrophy*

What exactly is the problem here?

**Comment by anno-du** [comment]
It seems to me that:
Biventricular hypertrophy is a subitem of Ventricular hypertrophy and not a subitem of Right -respectively Left ventricular hypertrophy

**Comment by drseb** [comment]
In the current version of HPO I see that:

- *Biventricular hypertrophy* subclassOf *Left ventricular hypertrophy*
- *Biventricular hypertrophy* subclassOf *Right ventricular hypertrophy*

Do you think this is wrong? (Why?)
Or don't you see this in your version of HPO? (Which version do you use?)

**Comment by anno-du** [comment]
I use the version from Bioportal from April 2016
Biventricular hypertrophy is equal to Left or Right and not a subitem.
In my opinion the hierarchy should be arranged as follows: 

Ventricular hypertrophy

- Biventricular hypertrophy

- Left ventricular hypertrophy

- Right ventricular hypertrophy

**Comment by drseb** [comment]
Sorry I don't get it: Why should a *Biventricular hypertrophy* not be a subclass of *Left ventricular hypertrophy* and *Right ventricular hypertrophy* ?

**Comment by drseb** [comment]
@pnrobinson can you help?

**Comment by balhoff** [comment]
I think it might be a feeling that e.g. _Left ventricular hypertrophy_ implies that **only** the left side is increased (and vice versa for _Right ventricular hypertrophy_). If it means that the left side is increased but you can't assume anything about the right, then I think subclass makes sense, since _Biventricular_ would imply both left and right.

**Comment by pnrobinson** [comment]
There is a Tension due to ontological purity (the  open world assumption of OWL). Thus, if we know a Patient has left ventricular hypertrophy (LVH) we cannot assume that this patient does not also have right ventricular hypertrophy (RVH). Therefore, any Patient with biventricular hypertrophy ALSO has LVH and ALSO has RVH.
Clinicians, on the other Hand, might think this is unnatural, because a typical echo examination would allow you to say whether a Patient has LVH, RVH, or both (BVH). Therefore, I am echoing what Jim Balhoff has said in the above comment :-0. 
On hindsight, I think clinicians would appreciate a structure where LVH, RVH, and BVH are siblings. This might give us a Logical error in Protege, and thus if we make this Change, we would have to think about how to write the Logical Definition. I am going to revise the text Definition first.

**Comment by cmungall** [comment]
there are various ways we can encode the logic, e.g. a unilateral qualifier, or an explicit negation (I favor the former for simplicity). We should also document the design pattern, and whether it applies on a case by case basis, or all lateral structures, all lateral symmetrical structures, ...

**Comment by pnrobinson** [comment]
I have made the change to the structure (biventricular hypertrophy) as suggested. 
The second item in this request was Amylold cardiomyopathy -- this is a disease (Amyloid Heart Disease), but I think the term cardiac amyloidosis (the main feature of said disease) is OK, am adding this.
