### ISSUE TITLE
NTR: Acryloyl-cysteamine high in urine (Lab: chemistry: organic acids)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8644]
New term request Acryloyl-cysteamine high in urine (elthat_190815154447):

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is coming from here https://pubmed.ncbi.nlm.nih.gov/26251176/
but I cannot find a Chebi or pubchem entry and wonder if"Acryloyl-cysteamine" is non-standard?

**Comment by MickeySegal** [comment]
We have it from https://www.ncbi.nlm.nih.gov/books/NBK542806/
"Elevations of urine acryloyl-cysteamine, acryloyl-l-cysteamine, N-acetyl-acryloyl-cysteine, methacryl-cysteamine, methacryl-cysteamine, or N-acetyl-methacryl-l-cysteamine"

**Comment by MickeySegal** [comment]
https://omim.org/entry/616277 "In 2 patients, analysis of urine metabolites showed elevated acryloyl cysteamine, N-acetyl-acryloyl-cysteine, methacryl-L-cysteine, and N-acetyl-methacryl-cysteine. "

**Comment by pnrobinson** [comment]
I cannot find this anywhere else and since there does not seem to be a modern, precise reference, I am guessing it is possible the above was an imprecise description or mistake that will be hard to reproduce with contemporary data. I will close for now, but if we can find a modern citation we can add the term!

**Comment by MickeySegal** [comment]
This looks like a terminology issue and choice of relevant metabolites.  
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8507190/
In conclusion, we presented that the urinary levels of SCPC, SCPCM, and SCECM can be used to diagnose ECHS1 deficiency. An early diagnosis of ECHS and protein restriction therapy may alleviate the symptoms of ECHS1 deficiency.

SCPC, S-(2-carboxypropyl) cysteine
SCPCM, S-(2-carboxypropyl) cysteamine
SCECM, S-(2-carboxyethyl) cysteamine

Acryloyl is also known as 2-propenoyl, which is similar but not identical to carboxypropyl (double bond instead of single bond for two of the carbons).

I will use these 3, for which we will need new terms, and delete the 5 closed terms discussed or referenced in this thread.  I will not include Acryloyl or methylacryl as synonyms because they seem like different compounds.
