### ISSUE TITLE
NTR: Laryngoscopy: laryngeal polyps or nodules (Lab: endoscopy and exploratory surgery)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8656]
New term request Laryngoscopy: laryngeal polyps or nodules (elthat_101213002043): Larynx; papillomas  UMLS: 0238232

**Comment by pnrobinson** [comment]
@MickeySegal
This is a nearly a synonym:
Vocal cord polyp HP:0032041
(note to me - add this pubmed citation: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6331298/)

Can you specify what would be different about the above term or if it is synonymous?

**Comment by MickeySegal** [comment]
We used a more general term because of https://www.ncbi.nlm.nih.gov/books/NBK562327/ "[Laryngeal papillomatosis] has a predilection to respiratory tract transition zones. The true vocal cords transition from pseudostratified epithelium to stratified squamous epithelium. Therefore, they are a common location for papilloma lesions to occur. Nevertheless, LP may be seen in other regions of the respiratory tract."

**Comment by MickeySegal** [comment]
Agree.
