### ISSUE TITLE
NTR: Prenatal ultrasound: colon intraluminal calcifications (Lab: ultrasound & echocardiogram)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8694]
New term request Prenatal ultrasound: colon intraluminal calcifications (elthat_160506033921):

**Comment by pnrobinson** [comment]
@MickeySegal -- does this refer to calcified meconium?
https://onlinelibrary.wiley.com/doi/abs/10.7863/jum.1990.9.7.411

**Comment by MickeySegal** [comment]
We only have this for one disease, VATER, based on the textbook Benacerraf (2008) Ultrasound of Fetal Syndromes referring to "Anal atresia (diagnosable if there is a rectovesicular fistula, identified by the characteristic appearance of intraluminal calcifications [urine and meconium] in the distended loop of colon)".

Although we of course list anal atresia for this disease, but if Benacerraf felt that was only observable by calcified meconium prenatally it seems worth having the finding.

As you may have heard, Benacerraf died recently.  Jerome Kagan (who died a few years ago) and I tried to talk her into a study of whether one could observe ADHD findings prenatally, but she was not as willing to tackle controversial questions as we were.

**Comment by pnrobinson** [comment]
@MickeySegal  -- perhaops it would be good to add this new term under [Abnormal fetal gastrointestinal system morphology](https://hpo.jax.org/app/browse/term/HP:0034207) as
Intraluminal meconium calcification
def:Deposition of calcium in meconium present in the internal cavity of the fetal bowel. This manifestation may be the result of any distal intestinal obstruction.
@sparkste is this a proper definition?

**Comment by MickeySegal** [comment]
Seems good to me.

**Comment by pnrobinson** [comment]
added as HP:0034547

**Comment by sparkste** [comment]
Sorry to be late to this! Agree - this is a reasonable definition. However, would acknowledge that intraluminal calcifications can seen with a breadth of genetic diseases or due to other unrelated causes ie abruption and fetal swallowing of blood.

Thanks!


Teresa Sparks, MD, MAS
Associate Professor
Maternal-Fetal Medicine and Clinical Genetics
Program Director, Maternal-Fetal Medicine Fellowship
Investigator, Chan Zuckerberg Biohub
University of California, San Francisco
________________________________
