### ISSUE TITLE
NTR: WRN protein absent in western blot analysis (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8728]
New term request WRN protein absent in western blot analysis (elthat_100718002622): Werner syndrome

**Comment by pnrobinson** [comment]
@MickeySegal
Western blot is not a clinical examination and so this does not seem to be in scope for HPO?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1514/
"In certain unusual instances, protein analysis may be useful when both pathogenic WRN alleles cannot be identified by sequence analysis. Because the majority of WRN pathogenic variants are null and do not produce WRN protein (or rarely, produce truncated WRN), variants that are not detected by sequencing may be detectable by western blot or immunoblot analysis."

**Comment by pnrobinson** [comment]
Well, yes, but "In certain unusual instances, protein analysis may be useful", I think the instance includes being in a research study. Doing a Western is something that could be useful in any number of diseases where the genetic findings are not quite clear, and this is something that university labs can do, but this is not a clinical test and adding findings like this to the HPO would not really add much for diagnostic utility.

**Comment by MickeySegal** [comment]
Since this option is mentioned in a GeneReviews article we will retain this as a finding but increase its cost so as not to recommend this unless other findings have not been helpful.
