### ISSUE TITLE
NTR: Flow cytometry: TCR alpha/beta T-cells low or absent (Lab: serology & immunological tests)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8753]
New term request Flow cytometry: TCR alpha/beta T-cells low or absent (elthat_140211172137): T-cell receptor  UMLS: 5563154

**Comment by pnrobinson** [comment]
@MickeySegal
I think this is probably a proportion rather than a count if this is a flow cytometry finding. 
Is this simialr to [Abnormal proportion of gamma-delta T cells HP:0500269](https://hpo.jax.org/app/browse/term/HP:0500269)?

**Comment by MickeySegal** [comment]
https://www.omim.org/entry/615387 "Flow cytometric analysis showed the presence of CD3+ T cells, but these cells uniformly expressed TCR-gamma/delta, with little or no TCR-alpha/beta expression."

So it is analogous, but the text doesn't make it clear whether this is due to different proportion of T-cell receptors being alpha/beta versus gamma-delta without changes in total number, or a change in numbers of one type or the other.  But I'm glad to use proportion if that is the best description.

**Comment by pnrobinson** [comment]
@MickeySegal 
This is very close to [Increased proportion of gamma-delta T cells HP:0500270](https://hpo.jax.org/browse/term/HP:0500270).
We are planning to have some immunology workshops to go over all of these "proportion" terms, and we may add more detail then.

**Comment by MickeySegal** [comment]
That works.  I will, however, use both UMLS:
https://www.ncbi.nlm.nih.gov/medgen/C5398019
https://www.ncbi.nlm.nih.gov/medgen/C5563154
