### ISSUE TITLE
foveal atrophy

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#893]
See http://www.ncbi.nlm.nih.gov/pubmed/26029869

**Comment by pnrobinson** [comment]
Actually, this disease is characterized by  foveal hypoplasia and well demarcated areas of macular atrophy (not age related). However, we need to add a term for "absent photopic (cone) responses on ERG"

**Comment by psergouniotis** [comment]
* Foveal atrophy is not foveal hypoplasia and technically it could be added as a new term.
* If necessary, "absent photopic (cone) responses on ERG" could be added as a synonym to "Undetectable light-adapted electroretinogram". However, there are well-defined standards for ERG and visual electrophysiology terminology (http://www.iscev.org/standards/) and it is best to adhere to the current recommendations (for example use light-adapted rather than photopic).

**Comment by pnrobinson** [comment]
Adding a term, foveal atrophy, with definition: Partial or complete loss of foveal tissue that was once present.
and comment: Loss of foveal tissue (atrophy) may be inferred by a medical history of loss of vision and the observation of a foveal lesion such as reduced foveal thickness on optical coherence tomography (OCT).
