### ISSUE TITLE
NTR: OCT: retinal nerve fiber layer thick (Lab: radiology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#8979]
New term request OCT: retinal nerve fiber layer thick (elthat_131020064340): Optical coherence tomography

**Comment by pnrobinson** [comment]
@MickeySegal
can you provide context? How is this distinguished from [Retinal nerve fiber edema HP:0020120](https://hpo.jax.org/app/browse/term/HP:0020120)?

**Comment by MickeySegal** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK1174/  "In the presymptomatic phase, fundal abnormalities including peripapillary telangiectatic vessels and variable degrees of retinal nerve fiber layer edema have been previously documented; these can vary with time [Nikoskelainen 1994]. Using optical coherence tomography imaging, thickening of the temporal retinal nerve fiber layer was confirmed in clinically unaffected individuals with a LHON-causing mtDNA pathogenic variant, providing further evidence that the papillomacular bundle is particularly vulnerable in LHON"

So it seems like the same thing, but we may keep separate findings because one is determined by ophthalmoscopy and one by OCT, but we can use the same HPO code.

**Comment by pnrobinson** [comment]
@MickeySegal 
We are starting to collaborate with a large ophthal. group in Europe and will be doing substantial work on this section. Therefore, I will close this issue for now, since there is a term that is close.

**Comment by MickeySegal** [comment]
How will I find out when that material is available?
