### ISSUE TITLE
NTR: EMG: fibrillations on electromyogram (Lab: neurophysiology: NCV/EMG)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9051]
New term request EMG: fibrillations on electromyogram (segal_080910195442): Inflammatory  UMLS: 1865397

**Comment by pnrobinson** [comment]
@MickeySegal
this would be [Muscle fibrillation HP:0010546](https://hpo.jax.org/app/browse/term/HP:0010546)
I am adding the above as a synonym

**Comment by MickeySegal** [comment]
Thanks.  It would be good if there were a way to consolidate the synonymous UMLS concepts, here:
https://www.ncbi.nlm.nih.gov/medgen/C0231531 and 
https://www.ncbi.nlm.nih.gov/medgen/C1865397

**Comment by kanems** [comment]
@MickeySegal anyone can write to the UMLS team via the NLM help desk and suggest a CUI merge. https://support.nlm.nih.gov/support/create-case/ Since these terms are both "C#######" formatted, they are both UMLS-based CUIs. If one is "CN######" and the other is "C#######" then that's a request to MedGen to improve CUI mapping. (You can either email MedGen directly our submit a request from same link above and it will eventually filter to us.)
We had a hiccup with the November UMLS release processing so we've had to trouble shoot some of the data issues. We should up caught up with the UMLS 22AB data by the end of the month, during which we will more thoroughly review HPO concept mapping and CUI assignment in MedGen. 
I'll note the two CUIs above on my monthly email to UMLS and request the CUIs be merged, as well as the two CUIs I noted on ticket #9156 9156.

**Comment by MickeySegal** [comment]
On further reflection, using https://hpo.jax.org/app/browse/term/HP:0010546 here is wrong.  It refers to observable twitching.  The current term request refers to electrical recording.  They are related, but the two UMLS terms convey a real distinction that should be retained.

The issue can be confusing since the terms fibrillation and fasciculation are sometimes used interchangeably because the electrical observation underlies the twitch observed.

**Comment by pnrobinson** [comment]
reopening,

**Comment by pnrobinson** [comment]
@kanems @MickeySegal 
It seems to me that both UMLS terms refer to fibrillations

Fasciculations are visible spontaneous contractions involving small groups of muscle fibers.
Muscle fibrillations are contractions that are not visible under the skin and are detectable through needle electromyography and ultrasound.

So it seems to me we need to create a new HPO term called Muscle fasciculation and add a comment to the existing term.
Thoughts?

**Comment by MickeySegal** [comment]
That is fine, with https://hpo.jax.org/app/browse/term/HP:0010546 being made clear to be an EMG finding, not a visual observation.

**Comment by pnrobinson** [comment]
@MickeySegal 
updated definition to
Fine, rapid twitching of individual muscle fibers with little or no movement of the muscle as a whole as ascertained by electromyography (EMG). If a motor neuron or its axon is destroyed, the muscle fibers it innervates undergo denervation atrophy. This leads to hypersensitivity of individual muscle fibers to acetyl choline so that they may contract spontaneously. Isolated activity of individual muscle fibers is generally so fine it cannot be seen through the intact skin, although it can be recorded as a short-duration spike in the EMG.
