### ISSUE TITLE
New term request: tracheal tug

### ISSUE THREAD

**Issue by CourtneyHum** [obophenotype/human-phenotype-ontology#908]
Also known as Oliver's sign

**Comment by pnrobinson** [comment]
This is one of those rarely mentioned signs (see http://rc.rcjournal.com/content/57/3/404.full). I am not able to find any good reference on Oliver's sign. If you have one, please send it to me. Do you agree with the following comment (from https://www.youtube.com/watch?v=xM92cP5pE_Q)?

A tracheal tug in COPD is downward movement of the trachea during inspiration due to downward traction on the tracheobronchial tree. Trachial tug in Aortic arch aneurysm is seen during systole due to the anatomic position of the aortic arch, which overrides the left main bronchus.﻿

**Comment by CourtneyHum** [comment]
I agree although I don't know much about tracheal tug. I am requesting the term because a pulmonologist who is collecting data on kids with Nemaline Myopathy wants to use it. Do you want me to ask on my end for clarification or I should I relay the message that this is not a term you want to add to the HPO.

**Comment by pnrobinson** [comment]
I think that the term is fine. I suspect that a really good clinician can differentiate between tracheal tug upon Inspiration and tracheal tug upon systole, and I wonder if we should avoid the use of the Phrase "Oliver's sign" which probably different People use in different ways. But by all means please ask the clinician for clarification! Thanks a lot, Peter

**Comment by CourtneyHum** [comment]
The clinician I am working with agrees with the first half of the definition. The second half is not part of her practice. I think leaving out the synonym "Oliver's sign" is fine

**Comment by pnrobinson** [comment]
Sorry for the delay here. We just moved to the US, I have relocated to the Jackson Lab for Genomic Medicine!

**Comment by CourtneyHum** [comment]
That's fantastic! Congratulations and all the best at Jackson Lab. 


-------- Original message --------
