### ISSUE TITLE
NTR: Bone marrow: multinucleated erythroblasts (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9156]
New term request Bone marrow: multinucleated erythroblasts (elthat_100622040623):   UMLS: 3806288

**Comment by pnrobinson** [comment]
@MickeySegal
See [Multinucleated erythroblast HP:0034278](https://hpo.jax.org/app/browse/term/HP:0034278)
I think it would be sufficient to add this as a synonym. I think this finding is bone-marrow specific.

**Comment by MickeySegal** [comment]
That is good enough.  

Oddly, UMLS assigns a CN code to the HPO finding: https://www.ncbi.nlm.nih.gov/medgen/?term=CN315546
even though UMLS has https://www.ncbi.nlm.nih.gov/medgen/C3806288

I filed a report to the MedGen folks.

**Comment by kanems** [comment]
Hi @MickeySegal and @pnrobinson 
While MedGen aims to use the UMLS provided CUIs for our concepts, we cannot 100% rely on UMLS since they release only 2x a year and other terms (from HPO, OMIM, Mondo or submissions to GTR) may be created or renamed in between UMLS releases. So the CN terms are generated and assigned by MedGen, not UMLS.
The CUI  C3806288 (Multinuclear erythroblasts) suggested above maps only one 'atom' (cross-reference) from UMLS, an OMIM "PTCS" (which I think stands for something like "phenotype from clinical synopsis"), not the HPO ID. 
UMLS instead has  C2749670 for the HPO term HP:0034278, so MedGen will use this CUI. If you think the Multinuclear and multinucleated CUIs are the same (seem to be describing the same phenomenon to me) then that's a specific ask to the UMLS Metathesaurus team. The MedGen CUI should be updated in the next ~24-48 hours.

**Comment by MickeySegal** [comment]
I heard back already from NLM Support: "Thank you, these two have been merged. The UMLS code retained is CUI C2749670. "

As kanems suggested, I will now ask whether C2749670 and C3806288 should be merged.

**Comment by pnrobinson** [comment]
adding synonym, thanks
