### ISSUE TITLE
NTR: Retinal biopsy: lipofuscin granule accumulation (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9183]
New term request Retinal biopsy: lipofuscin granule accumulation (elthat_100829112511):

**Comment by pnrobinson** [comment]
@sukram
@MickeySegal

Is this the same as
[Hyperautofluorescent retinal lesion HP:0025158](https://hpo.jax.org/app/browse/term/HP:0025158)

?

**Comment by MickeySegal** [comment]
We have https://www.omim.org/entry/606693 "Lipofuscin deposits were confirmed in the retina" and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4163923/ refers to "lipofuscin-like autofluorescence".  So it sounds like 2 descriptions of the same thing, and since looking for autofluorescence is less invasive than biopsy, your term may be preferable.

**Comment by pnrobinson** [comment]
Added Retinal lipofuscin accumulation as a related synonym. We will be having an ophthalmology workshop next year to go over all such terms.
