### ISSUE TITLE
NTR: Skin biopsy: keratohyaline granules in keratinocytes on EM (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9308]
New term request Skin biopsy: keratohyaline granules in keratinocytes on EM (elthat_130429040141): Electron microscopy  UMLS: 1866035

**Comment by pnrobinson** [comment]
@MickeySegal

This does not appear to be an abnormal finding, see
https://www.ncbi.nlm.nih.gov/books/NBK537049/

**Comment by MickeySegal** [comment]
You are right.  

The correct name should be large keratohyaline granules: https://www.omim.org/entry/601952 "Electron microscopy disclosed numerous large keratohyaline granules in superficial keratinocytes. [Vahlquist et al. (1997)] suggested that the condition is due to a genetic defect in the formation of keratohyaline granules."

The granules are also small in another disease; I'll file a new term request rather than lumping both into "abnormal".

**Comment by pnrobinson** [comment]
@MickeySegal 

adding as
HP:0034927
Large keratohyaline granules
def: Abnormally large keratohyalin granules (KHG). KHG are typically present in the stratum granulosum of the epidermal layer of the skin (and epithelium of the mucosae). KHG are protein structures found in the keratinocytes of the stratum granulosum.

**Comment by kanems** [comment]
Should this HPO term be linked to this OMIM entry as a disease association? https://www.omim.org/clinicalSynopsis/601952?highlight=granule,in,keratinocyte,keratohyaline,large,numerous,superficial
