### ISSUE TITLE
NTR: Skin biopsy: desmosomes reduced or small on EM (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9343]
New term request Skin biopsy: desmosomes reduced or small on EM (elthat_131029170721): Electron microscope  UMLS: 4013297

**Comment by pnrobinson** [comment]
@MickeySegal

this is [Hypoplastic dermoepidermal hemidesmosomes HP:0020117](https://hpo.jax.org/app/browse/term/HP:0020117)

**Comment by MickeySegal** [comment]
I think these are different.  Google AI summary:
"Desmosomes connect cells to other cells, acting like "spot welds" with symmetrical structures linking intermediate filaments, found in skin & heart; while hemidesmosomes connect a cell to the basement membrane (extracellular matrix), asymmetrical structures that anchor basal epithelial cells, crucial for skin integrity, using different proteins (integrins vs. cadherins) despite similar appearances under the microscope. "

Relevant UMLS:
https://www.ncbi.nlm.nih.gov/medgen/C5393536
https://www.ncbi.nlm.nih.gov/medgen/C3277158
https://www.ncbi.nlm.nih.gov/medgen/C4230717
https://www.ncbi.nlm.nih.gov/medgen/C4230716
https://www.ncbi.nlm.nih.gov/medgen/C4013296
https://www.ncbi.nlm.nih.gov/medgen/C4693070
https://www.ncbi.nlm.nih.gov/medgen/C4013297

UMLS blew off my request to consolidate the UMLS because we had included you assignment of [Hypoplastic dermoepidermal hemidesmosomes HP:0020117](https://hpo.jax.org/app/browse/term/HP:0020117), but I agree with them that these are different and instead we need an HPO term for desmosomes reduced or small.
