### ISSUE TITLE
NTR: Peripheral nerve biopsy: spheroids (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9344]
New term request Peripheral nerve biopsy: spheroids (segal_131210214942):   UMLS: 3148985

**Comment by pnrobinson** [comment]
@MickeySegal this seems to be the same as #9240 ?

**Comment by pnrobinson** [comment]
Also, not I will use the definition here: https://pubmed.ncbi.nlm.nih.gov/34678457/

**Comment by MickeySegal** [comment]
Presumably one gets much smaller nerve branches from a skin biopsy than a peripheral nerve biopsy, but the underlying pathology is likely the same.  We'd keep both our skin biopsy and our nerve biopsy findings because we like to guide diagnosis towards the less invasive and less expensive test, but we'd be glad to use the same HPO term for the underlying pathology.

**Comment by pnrobinson** [comment]
@MickeySegal 
adding as
Peripheral axon spheroid formation
HP:0034922
def: Axonal spheroids are bubble-like biological features that form on most degenerating axons.
comment: They often contain cytoskeletal elements and organelles, and, depending on the pathological insult, can colocalize with disease-related proteins such as amyloid precursor protein (APP), ubiquitin, and motor proteins. Initial formation of axonal spheroids depends on the disruption of axonal and membrane tension governed by cytoskeleton structure and calcium levels. Shortly after spheroid formation, the engulfment signal, phosphatidylserine (PS), is exposed on the outer leaflet of spheroid plasma membrane, suggesting an important role for axonal spheroids in phagocytosis and debris clearance during degeneration.
