### ISSUE TITLE
NTR: Microfilaria on blood smear, skin biopsy or PCR (Lab: pathology: biopsies & morphology)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9426]
New term request Microfilaria on blood smear, skin biopsy or PCR (nadea3_190502015230): Microfilariae; polymerase chain reaction; DNA  UMLS: 0552545

**Comment by pnrobinson** [comment]
@MickeySegal
The HPO would probably make 3 terms out of this (same comment applies to several other term requests). 
PCR also needs to specify the source (blood?)
It may be overkill to have this many terms?

**Comment by MickeySegal** [comment]
We've had this discussion previously with our roles reversed, with you saying that different ways of getting to the same description of reality should be one HPO term.  But I agree that here there is more justification for splitting since different locations is important information.  

We use this only for Filariasis and Onchocerciasis, and presumably one can detect the microfilaria is various ways in various locations.

**Comment by pnrobinson** [comment]
@MickeySegal 
Adding as 
HP:0034639
Bloodstream microfilaria
(Note -- mode of investigation not important in HPO context -- PCR or microscopy)

**Comment by pnrobinson** [comment]
@MickeySegal 
also adding
HP:0034641
Dermal microfilaria
