### ISSUE TITLE
NTR: Contact with nickel (Triggers or responses: non-drug)

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9555]
New term request Contact with nickel (segal_220419201333): Nickle  UMLS: 2107946

**Comment by pnrobinson** [comment]
@mickeysegal
The intended use case for terms such as this -- https://hpo.jax.org/app/browse/term/HP:0025228
is to described a symptom that is inferred to be triggered by the agent. These terms do not describe the fact that somebody was exposed to the agent (which would be past medical history). Before we enter these terms, I just wanted to ask if that is what you intended?

**Comment by MickeySegal** [comment]
This issue is somewhere between philosophical and semantic.  

If it is clear that a sudden movement triggers a seizure or a headache, that is clear that the trigger is the proximate cause.  In other situations, the causality is more muddled, and we often use the word "etiology" rather than "cause".  For example, if someone was a smoker and got brain cancer, there is a statistical association, but it is not really clear whether the smoking caused the brain cancer.

It is fine for you to list these all as triggers, as we do in many situations, and could probably do with nickel, because careful examination reveals a distribution in the body corresponding to areas of contact with the metal.  For ANCA-associated vasculitis, the connection is a little less clear, but probably also legitimately described as a trigger.  But there is a spectrum and some with have less clear trigger-like relationships.

So feel free to call them triggers, and we may change naming of some, but not all.

**Comment by pnrobinson** [comment]
added as HP_4000120
