### ISSUE TITLE
Bad spelling of name in "Abnormal Estermann grid perimetry test"

### ISSUE THREAD

**Issue by turnovec** [obophenotype/human-phenotype-ontology#9593]
**HPO term**
HP:0030599 | Abnormal Estermann grid perimetry test 

**Bug description**
I found that the name of the author of this grid was Esterman, not Estermann:
https://jamanetwork.com/journals/jamaophthalmology/article-abstract/629111

**Comment by pnrobinson** [comment]
Fixed this and also added the definition

The Esterman grid test assays scores visual acuity. The grid consists of 100 units whose unequal size and distribution reflect the unequal functional value of different parts of the field-in effect a weighted or relative-value scale. Because each unit equals 1 percent, a simple count of units yields the functional score in percent.
