### ISSUE TITLE
Hierarchy revision Pulmonary venoocclusive disease HP:0006518

### ISSUE THREAD

**Issue by lcdaugherty** [obophenotype/human-phenotype-ontology#964]
relates to #914 BRIDGE_PAH_HPO_terms_20160616.xlsx

hierarchy revisions : Suggest this is also child of Abnormality of the pulmonary veins; Pulmonary hypertension (to the already asserted Abnormality of the lung)

**Comment by pnrobinson** [comment]
This term is not optimal because it is also the name of a disease. The term originated from OMIM records for some genetic forms of Pulmonary veno-occlusive disease (PVOD). In the HPO, we are not making terms for diseases but for phenotypic features, and I think that this term was being used in OMIM to describe the histological changes seen in PVOD (these are the defining feature).

The following is from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3603636/.

PVOD is characterised by diffuse occlusion of the pulmonary veins by fibrous tissue, pulmonary venous congestion and associated complications including severe pulmonary hypertension (pHTN), non-cardiogenic pulmonary oedema, hypoxia and right-ventricular failure. Clinical presentation is typically non-specific, including dyspnoea, fatigue and cough. Diagnosis of PVOD is based on high clinical suspicion with a definitive diagnosis based on histological confirmation. Work-up routinely includes high-resolution thoracic CT scan, pulmonary function testing with diffusing capacity, V/Q scanning, echocardiogram and cardiac catheterisation.

**Comment by pnrobinson** [comment]
The histological picture in PVOD is complex:

From:  http://erj.ersjournals.com/content/33/1/189.full
However, lesions frequently involve veins, capillaries and arteries in lungs of PVOD patients. In PVOD, the observed post-capillary lesions of septal veins and pre-septal venules frequently consist of loose, fibrous remodelling of the intima that may totally occlude the lumen (fig. 1a⇓). The involvement of pre-septal venules should be considered necessary for the histological diagnosis of PVOD.

From: http://www.sciencedirect.com/science/article/pii/S0954611110001320
The walls of affected small pulmonary veins are generally thickened as a result of disorganized smooth muscle hypertrophy and collagen matrix deposition. As a result, the lumina of these vessels is significantly narrowed or occluded, frequently resulting in overt intraluminal thrombosis.

**Comment by pnrobinson** [comment]
I think that for now, the best option is to change the term name to Pulmonary venous occlusion with the definition: Substantial narrowing or blockage of small pulmonary veins as a result of disorganized smooth muscle hypertrophy and collagen matrix deposition. 
I will add the current name as a related synonym.
