### ISSUE TITLE
Thumb abduction and adduction contracture

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9686]
**Preferred term label:**
Thumb abduction and adduction contracture

Shahrzad and Noemi, please provide definitions

**Comment by shahrzadnema** [comment]
Thumb abduction contracture==> Please remove it the term since this is not pertinent to AMC.
Thumb adduction contracture==>Inability of metacarpal-phalangeal and/or interphalangeal joints of the thumb to bring from medial side to neutral position, where the neutral position for the thumb is when the distal and proximal segments of the thumb joint are in linear alignment.

**Comment by pnrobinson** [comment]
@shahrzadnema 

added as
Thumb adduction contracture
HP:0034992
def: A type of thumb contracture characterized by a chronic reduction in active and passive ability of the metacarpal-phalangeal and/or interphalangeal joints of the thumb to bring from medial side to neutral position, where the neutral position for the thumb is when the distal and proximal segments of the thumb joint are in linear alignment.
