### ISSUE TITLE
abnormal bone ossification is not morphology but should be physiology

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/human-phenotype-ontology#9761]
**HPO term**
HP_0011849 Abnormal bone ossification

**Suggested revision and reasons**
Abnormal bone ossification eq uses GO process term and describes the abnormal _process_ of ossification.  We propose moving it to be a child of 'Abnormal musculoskeletal physiology'. All ossification child terms would move with to, except 'Abnormality of bone mineral density.

Suggestion for new structure:
<google-sheets-html-origin><style type="text/css"></style>

Abnormality of the skeletal system |   |   |   |   |  
-- | -- | -- | -- | -- | --
  | Abnormal musculoskeletal physiology |   |   |   |  
  |   | Abnormal bone ossification |   |   |  
  |   |   | Abnormal enchondral ossification |   |  
  |   |   | Abnormal intramembranous ossification |   |  
  |   |   | Decreased skull ossification |   |  
  |   |   | Ectopic ossification |   |  
  | Abnormal skeletal morphology |   |   |   |  
  |   | Abnormal bone structure |   |   |  
  |   |   | Abnormality of bone mineral density |   |  

Also, suggestion to revise EQ statement from
'has part' some 
    (quality
     and ('characteristic of' some 
        (ossification
         and ('occurs in' some 'bone element')))
     and ('has modifier' some abnormal)) 
To
'has part' some 
    (quality
     and ('characteristic of' some 
        ossification)
     and ('has modifier' some abnormal))

BECAUSE 'Ectopic ossification' is a child term and ectopic ossification occurs in a part that is not a bone element.

If you are okay with this, I will make the changes.

Working with @sbello @rays22 et al., looking to harmonize HP and MP.

**Comment by pnrobinson** [comment]
Clinically these are items that are almost always inferred from a single observation, which we refer to be the result of a process but we are not actually measuring a process and I think this placement is not what clinicians would expect. You can measure the time course (process) of ossification experimentally pretty easily but this is not what the HPO is modeling.

**Comment by pnrobinson** [comment]
I think the best thing would be to the PATO term for ossified
https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001448

**Comment by sbello** [comment]
@pnrobinson @LCCarmody Do you also plan to revise the text definition to make it clear you are defining the outcome of the process rather than the process itself. I'm going back through the closeMatch mappings and came across these again. I'm planning to change the mappings to relatedMatch since the MP term is really about the process and if I understand correctly the HPO term is about the outcome of the process. 
I think it would be helpful to have that distinction in the text definitions as well as in the logical ones.
Thanks,
Sue

**Comment by pnrobinson** [comment]
In clinical medicine we are not observing the process but we are observing the outcome. I am guessing this is also true for at least some uses of MP terms. Our rule is essentially that processes are things that are measured over time (movies) rather than in one instant (pictures).
I agree it would be good to go over the definitions, but maybe we can try to do this is a systematic way with a workshop or some colleagues in skeletal medicine.

**Comment by pnrobinson** [comment]
OK, I think we can close this...please reopen if needed.
