### ISSUE TITLE
Small eyes

### ISSUE THREAD

**Issue by MickeySegal** [obophenotype/human-phenotype-ontology#9782]
**HPO term**
HP:0008056 seems to be redundant with HP:0000568 and HP:0000528 

**Reason for deprecation**
HP:0008056 seems redundant.

**Suggested replacement or term to consider**
Keep HP:0000568 and HP:0000528

**Comment by pnrobinson** [comment]
This
[Aplasia/Hypoplasia affecting the eye HP:0008056](https://hpo.jax.org/app/browse/term/HP:0008056)


is a grouping term for the following -- sometimes users might want to search for both together since they are probably pathophysiologically related in most diseases.

[Microphthalmia HP:0000568](https://hpo.jax.org/app/browse/term/HP:0000568)
[Anophthalmia HP:0000528](https://hpo.jax.org/app/browse/term/HP:0000528)

This is a relatively common pattern in the HPO, so I would prefer to keep it unless I am missing something else?
