### ISSUE TITLE
Missing "NOT" qualifier for Orphanet terms in phenotype.hpoa file

### ISSUE THREAD

**Issue by ehartley** [obophenotype/human-phenotype-ontology#9818]
While looking at the different phenotypes between OMIM and Orphanet in the `phenotype.hpoa` file (version: 2023-06-06), I noticed that the "NOT" qualifier isn't used for any of the Orphanet terms. However, I've found 3 instances where I think it should be and there are probably more. It seems like something went wrong with the ingest from Orphanet and the "exclusion criterion" qualifiers were lost.

Here are the 3 cases I've found where qualifier = "NOT" is missing in the `phenotype.hpoa` file:

#### Case 1
**Disease ID and Name**
ORPHA:307   _Juvenile myoclonic epilepsy_

**HPO ID and Name**
HP:0001249   _Intellectual disability_

**Further information (Frequency, Onset, Pubmed-references, Comments)**
HP:0001249 is listed under the "Exclusion criterion" section on the [Orphanet page for ORPHA:307](https://www.orpha.net/consor/cgi-bin/Disease_HPOTerms.php?lng=EN&data_id=102&Disease_Disease_HPOTerms_diseaseGroup=Juvenile-myoclonic-epilepsy&Disease_Disease_HPOTerms_diseaseType=Pat&Disease(s)/group%20of%20diseases=Juvenile-myoclonic-epilepsy&title=Juvenile%20myoclonic%20epilepsy&search=Disease_HPOTerms_Simple).

#### Case 2
**Disease ID and Name**
ORPHA:466794   _Acute infantile liver failure-cerebellar ataxia-peripheral sensory motor neuropathy syndrome_

**HPO ID and Name**
HP:0007663   _Reduced visual acuity_

**Further information (Frequency, Onset, Pubmed-references, Comments)**
HP:0007663 is listed under the "Exclusion criterion" section on the [Orphanet page for ORPHA:466794](https://www.orpha.net/consor/cgi-bin/Disease_HPOTerms.php?lng=EN&data_id=24170&Disease_Disease_HPOTerms_diseaseGroup=466794&Disease_Disease_HPOTerms_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Acute-infantile-liver-failure-cerebellar-ataxia-peripheral-sensory-motor-neuropathy-syndrome&title=Acute%20infantile%20liver%20failure-cerebellar%20ataxia-peripheral%20sensory%20motor%20neuropathy%20syndrome&search=Disease_HPOTerms_Simple).

#### Case 3
**Disease ID and Name**
ORPHA:101046   _Autosomal dominant epilepsy with auditory features_

**HPO ID and Name**
HP:0410263   _Brain imaging abnormality_
HP:0001249   _Intellectual disability_

**Further information (Frequency, Onset, Pubmed-references, Comments)**
HP:0410263 and HP:0001249 are listed under the "Exclusion criterion" section on the [Orphanet page for ORPHA:101046](https://www.orpha.net/consor/cgi-bin/Disease_HPOTerms.php?lng=EN&data_id=14757&Disease_Disease_HPOTerms_diseaseGroup=101046&Disease_Disease_HPOTerms_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Autosomal-dominant-epilepsy-with-auditory-features&title=Autosomal%20dominant%20epilepsy%20with%20auditory%20features&search=Disease_HPOTerms_Simple).

**Comment by ehartley** [comment]
Update: I just realized the "exclusion" information from Orphanet isn't missing, it is provided in the `frequency` column as "HP:0040285". So it is just reported differently from the OMIM terms, which instead just use the `qualifier` column to indicate the excluded phenotypes.  Would it be possible to make the way excluded phenotypes are represented in the `phenotype.hpoa` file the same between the OMIM and Ophanet terms? Either through adding `qualifier = NOT` for the Orphanet terms or `frequency = HP:0040285` for the OMIM terms?

**Comment by pnrobinson** [comment]
@ehartley We are moving away from the NOT qualifier for the following reason.
If we know a lot about a rare disease, then we can confidently say that a certain feature is not associated with the disease. For instance, we can say that Polydactyly is not associated with cystic fibrosis. However, the way that NOT is generally used in the literature is to differentiate two diseases (e.g., Loey Dietz syndrome is NOT characterised by ectopia lentis -- to differentiate from Marfan). However, this is not good as a computational model, because not all case of Marfan have ectopia lentis and rarely cases of EL have been reported with LDS.
Also, for diseases that have not been extensively reported, we may only know that zero of two individuals had some feature.

Therefore, in the HPO annotations that are directly produced by the HPO team (see the phenotype hpoa file), we are moving towards frequency annotations such as 5/13 if 5 of 13 individuals in the cited study had some feature. ORPHA does not currently report features with this granularity and so the closest we can do is to use the [Excluded HP:0040285](https://hpo.jax.org/app/browse/term/HP:0040285) term.

If you use Java  we have a library for working with this data: https://github.com/monarch-initiative/phenol
We are also developing a Python library that is not quite as mature, but you can contact me to get more info

**Comment by ehartley** [comment]
@pnrobinson Thank you for the explanation!
