### ISSUE TITLE
Spontaneous onset of labor

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#983]
Could I request a new term for 'Spontaneous onset of labour'. This is just as important as an abnormal delivery or induced delivery in pregnancy studies.

**Comment by pnrobinson** [comment]
This is difficult to express in the HPO, which is an ontology of abnormalities. It turns out that it is important not to try and put everything into a single ontology-- while that may solve some issues, it makes the ontology less useful in general by diluting the focus. Perhaps it is sufficient to have your database have a few additional check boxes to store information like this? 
We are planning on extending the reach of resources (HPO and other Monarch ontologies and new endeavours), but this will certainly not be ready this year.
