### ISSUE TITLE
Typically Mosaic

### ISSUE THREAD

**Issue by pnrobinson** [obophenotype/human-phenotype-ontology#9881]
Typically Mosaic: Description of conditions in which, for example, constitutive mutation is lethal and cases are exclusively or predominantly mosaic. A much lower variant allele fraction (VAF) cutoff would be needed in analysis pipelines.

**Comment by pnrobinson** [comment]
label:Typified by somatic mosaicism
id:HP:0001442
definition:Description of conditions in which affected individuals display somatic mosaicism, i.e., genetically distinct populations of somatic cells in a given organism caused by DNA mutations, epigenetic alterations of DNA, chromosomal abnormalities or the spontaneous reversion of inherited mutations.
comment: In many conditions typified by somatic mosaicism, constitutive mutation is lethal and cases are exclusively or predominantly mosaic. A much lower variant allele fraction (VAF) cutoff would be needed in genomic analysis pipelines.

**Comment by angharadroberts** [comment]
suggestion
definition:Description of conditions in which affected individuals typically display somatic mosaicism, i.e., genetically distinct populations of somatic cells in a given organism caused by DNA mutations, epigenetic alterations of DNA, chromosomal abnormalities or the spontaneous reversion of inherited mutations. In many conditions typified by somatic mosaicism, constitutive mutation is lethal and cases are exclusively or predominantly mosaic.
comment:  A much lower variant allele fraction (VAF) cutoff would be needed in genomic analysis pipelines.

**Comment by pnrobinson** [comment]
@angharadroberts 
I have updated the definition as suggested.
I also tweaked the comment
A much lower variant allele fraction (VAF) cutoff would be needed in genomic analysis pipelines as compared with the threshold required for consitutional variants.
