### ISSUE TITLE
Suggest obsoletion: septo-optic dysplasia

### ISSUE THREAD

**Issue by peupeubangbang** [obophenotype/human-phenotype-ontology#9883]
**HPO term**
Septo-optic dysplasia
HP:0100842

**Reason for deprecation**
This is a bundled term of 3 phenotypes that already exist elsewhere in HPO. The phenotype is also variable (most patients will not have all three) meaning the HPO term itself does not accurately describe the concept. 

This could be handled by the SOD diagnosis code in combination with distinct HPO codes that make up the variable phenotype. 

**Suggested replacement or term to consider**
N/A

**Comment by pnrobinson** [comment]
@peupeubangbang 
I agree that this is a bundled term. The issue is that in many data sources this is all that we have and so we have kept this term for convenience. There are many instances of things like this (e.g. renal insufficiency) that are reported at a certain granularity or at different granularities in different sources. I do not think we can address this in the near future, but hopefully with time as reporting of phenotypic data improves we will be able to revisit issues like this.
Thanks for the feedback!
