### ISSUE TITLE
Pruritis gravidarum

### ISSUE THREAD

**Issue by julievonz** [obophenotype/human-phenotype-ontology#991]
Request a new term for 'Pruritis gravidarum'

**Comment by pnrobinson** [comment]
Hi!
This item seems to be a disease (synonsmous with  "Intrahepatic cholestasis of pregnancy") rather than a phenotypic feature. I would suggest that the system you are using to record HPO terms should simultaneous record the fact that the patient is pregnant -- if you do not do things this way, then it will not be possible to make a diagnosis using the system.
If you are recording the fact that a patient has itching while she is pregnant, then just using the existing term "pruiritus" might be the most appropriate.

Here is an explanation from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3860924/

Although ICP is a pruritic condition in pregnancy that involves only secondary skin changes, it is included in the classification of dermatoses of pregnancy because identifying this disease early is important to minimize potential adverse fetal outcomes. Intrahepatic cholestasis of pregnancy is also called idiopathic jaundice of pregnancy, obstetric cholestasis, and pruritus gravidarum. It is caused by the disruption of hepatic bile flow during pregnancy. The prevalence of ICP in North America is 0.5% to 1%, but it is particularly common in Scandinavia and South America, with the highest rates in Chile (15% to 28%).6 It runs in families and tends to recur in subsequent pregnancies.7
